### ISSUE TITLE
Crash when using ub_ctx_resolvconf and libevent

### ISSUE THREAD

**Issue by WolverinDEV** [NLnetLabs/unbound#100]
Hey,
I've found out a quite unexpected and really odd crash.

### How to reproduce
Here is a little (simple) code snipped which will crash.
```cpp
#include <iostream>

#include <mutex>
#include <condition_variable>
#include <cassert>
#include <thread>
#include <event.h>
#include <unbound.h>
#include <unbound-event.h>

#define ITERATIONS (2000)

int main() {
	/* Setting up all libevent stuff */
	std::mutex ev_lock{};
	std::condition_variable ev_condition{};
	auto ev_base = event_base_new();

	std::thread ev_loop = std::thread([&]{
		/* Wait until we should start the event loop */
		{
			std::unique_lock lock{ev_lock};
			ev_condition.wait(lock);
		}

		/* executing the event loop until no events are registered */
		event_base_loop(ev_base, 0);
	});


	/* Setting up libunbound */
	auto ctx = ub_ctx_create_event(ev_base);
	assert(ctx);

	auto errc = ub_ctx_hosts(ctx, nullptr);
	assert(errc == 0);

	errc = ub_ctx_resolvconf(ctx, nullptr);
	assert(errc == 0);

	int callback_call_count{0};
	for(int i = 0; i < ITERATIONS; i++){
		auto host = std::to_string(i) + "ts.teaspeak.de";
		errc = ub_resolve_event(ctx, host.c_str(), 33, 1, (void*) &callback_call_count, [](void* _ccc, int, void*, int, int, char*) {
			*static_cast<int*>(_ccc) += 1;
		}, nullptr);
		assert(errc == 0);

		if(i == 0) {
			//CASE 1: CRASH
			//Start the event loop as soon the first resolve has been scheduled
			ev_condition.notify_one();
		}
	}

	//CASE 2: NO CRASH
	//Start the event loop after all resolves have been scheduled
	//ev_condition.notify_one();

	/* Hang up until no more events */
	ev_loop.join();
	assert(ITERATIONS == callback_call_count);

	ub_ctx_delete(ctx);
	event_base_free(ev_base);
}
```
You'll see there two comments, `CASE 1` and `CASE 2`.
Uncomment/comment the line bellow to enable/disable the specified case.

Another interesting note I got while experimenting around is that as soon I remove the call to 
`ub_ctx_resolvconf`, the snipped seem to run stable without any crashes. Both cases work then.

#### unbound
Self compiled from git (commit 21472c2393328723a8888f50aad6798e610d813b)
Command
```
../configure --with-libunbound-only --with-libevent=../../libevent/out/linux_amd64/ --with-pthreads --enable-pie --prefix=`pwd`  --enable-debug --enable-allsymbols
```

#### libevent
Self compiled from git (commit 0d7d85c2083f7a4c9efe01c061486f332b576d28)
Date: Tue Jul 2 10:47:47 2019 -0700
Command
```
cmake ../../ -DCMAKE_C_FLAGS="-fPIC  -I../../boringssl/include/" -DEVENT__DISABLE_BENCHMARK=ON -DEVENT__LIBRARY_TYPE=STATIC -DEVENT__MSVC_STATIC_RUNTIME=ON -DEVENT__DISABLE_TESTS=ON -DEVENT__DISABLE_SAMPLES=ON -DEVENT__DISABLE_OPENSSL=ON -DCMAKE_BUILD_TYPE="Release"
```  

Note: Even with the default unbound precomputed binary, shipped with ubuntu 18.04 (bionic), the crash occor. 

### Operating system
All tests have been made on Ubuntu 18.04 (Bionic) amd64
`uname -a`:
```
Linux WolverinDEV 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

----------
Side note: Please do not ask how the hell I discovered this... It took me several hours to debunk this crash

**Comment by wcawijngaards** [comment]
The issue looks to be that the event loop is running in a different thread.  You then try to interact with it via the ub_ctx variable, that contains a reference to that same event loop, from the first thread.  This does not work.  It does not allow concurrent access to the same event loop, and thus the same unbound from two threads at the same time.

What you could do is have an event fire in the event loop and there call the ub_.. functions on that context.  Libevent provides a mechanism by which you can send an event to a loop on a different thread, event_active, or event_base_once perhaps.  Then the ub_.. calls are from the same thread as where the event loop is running, and it should work.

So, this is why case 1 fails, because it accesses the loop from two threads at the same time.  But case 2 works, because only one thread is using the loop at a time.

**Comment by wcawijngaards** [comment]
The reason that it works when you remove the call to resolveconf is that when you do resolveconf, that DNS resolver (from /etc/resolv.conf) is apparantly very fast.  Usually close by.  And then the replies from that return causing the event loop to fire events while you are still adding more lookups.  Access at the same time, and it fails.  When you remove it the other DNS resolver, or authority servers on the internet are further away, and in those milliseconds (of ping) the for that adds new resolves finishes, after which there is no more access at the same time.  At least, I guess this could be the cause for the resolvconf change you observed.

**Comment by WolverinDEV** [comment]
Thanks for the quick reply.
What you said gives sense and I first thought about that as well, but you're writing within your documentation that using libunbound from threads is supposed to be easy due to the thread-safty of libunbound.
Qoute (https://nlnetlabs.nl/documentation/unbound/libunbound-tutorial-5/): 
> Using threads is easy because libunbound is threadsafe

You should may specify this statement more precisely or make another statement especially for the libevent stuff.

**Comment by wcawijngaards** [comment]
Yes that is right.  If you use an eventloop, that loop is used for threadsafety.  Now where to note it.

**Comment by wcawijngaards** [comment]
So you can see the diff of the fix I am about to commit.

```diff --git a/content/documentation/unbound/libunbound-tutorial-5.rst b/content/documentation/unbound/libunbound-tutorial-5.rst
index 0db3860..d49fad9 100644
--- a/content/documentation/unbound/libunbound-tutorial-5.rst
+++ b/content/documentation/unbound/libunbound-tutorial-5.rst
@@ -44,10 +44,14 @@ and freed and the thread exits with ``return NULL``.
 The second thread, ``thread_two``, does the same as the first thread,
 but looks up ``www.google.nl`` instead.
 
-Using threads is easy because libunbound is threadsafe. In this example, when
-both threads start resolving, they act as a 2-threaded resolver, and share
-results, validation outcomes and data. When one of the threads finishes its
-lookup, the other thread continues as a 1-threaded resolver.
+Using threads is easy when the context is created with ``ub_ctx_create``.
+In this example, when both threads start resolving, they act as
+a 2-threaded resolver, and share results, validation outcomes and
+data. When one of the threads finishes its lookup, the other thread
+continues as a 1-threaded resolver.  When the resolver is created with
+``ub_ctx_create_event`` or ``ub_ctx_create_ub_event``, with an event base,
+then it can only be accessed from one thread, usually the one that is
+running that event loop.
 
 This example uses blocking resolution for both threads. You can use
 asynchronous resolution in threaded programs too. The function
```

**Comment by WolverinDEV** [comment]
Yeah this helps other users immense so they don't encounter this issue.
Ofc, I bet only 30% ever read docs carefully, but at least its correct now.

Thanks for being so painstaking :)


Edit:
`accessed from one thread, usually the one that is running that event loop.`
May specify a bit more that the event loop must not be running when adding resolves.
