### ISSUE TITLE
Can't find protobuf-c package since #999

### ISSUE THREAD

**Issue by origamiofficial** [NLnetLabs/unbound#1006]
**Describe the bug**
Since the merge of #999 compiling failed. If you check my [Dockerfile's](https://github.com/origamiofficial/docker-pihole-unbound/blob/main/Dockerfile) 48 & 49 line, both `libprotobuf-c-dev` and `protobuf-c-compiler` is already installed but still it gives me below error while compiling:
```
#24 60.29 configure: error: The protobuf-c package was not found with pkg-config. Please install protobuf-c!
```
Full log available: https://github.com/origamiofficial/docker-pihole-unbound/actions/runs/7771303847/job/21192465275

**To reproduce**
```bash
RUN build_deps="curl gcc libc-dev libevent-dev libexpat1-dev libnghttp2-dev make flex bison" && \
    set -x && \
    DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y --no-install-recommends \
      $build_deps \
      bsdmainutils \
      ca-certificates \
      ldnsutils \
      libevent-2.1-7 \
      libexpat1 \
      libprotobuf-c-dev \
      protobuf-c-compiler && \
    git clone https://github.com/NLnetLabs/unbound.git && \
    cd unbound && \
    groupadd _unbound && \
    useradd -g _unbound -s /dev/null -d /etc _unbound && \
    ./configure \
        --disable-dependency-tracking \
        --prefix=/opt/unbound \
        --with-pthreads \
        --with-username=_unbound \
        --with-ssl=/opt/openssl \
        --with-libevent \
        --with-libnghttp2 \
        --enable-dnstap \
        --enable-tfo-server \
        --enable-tfo-client \
        --enable-event-api \
        --enable-subnet && \
    make install
```
**Expected behavior**
It should compile just like before the merge of #999 

**System:**
 - Unbound version: source clone
 - OS: bullseye-slim
 - `unbound -V` output: N/A

**Additional information**
```
origami@rlabinctestlab:~$ which protoc-c
/usr/bin/protoc-c
origami@rlabinctestlab:~$ pkg-config --cflags libprotobuf-c

origami@rlabinctestlab:~$ pkg-config --libs libprotobuf-c
-lprotobuf-c
```

**Comment by origamiofficial** [comment]
@wcawijngaards Hi, sorry to ping you but is there any workaround? If I reverse the last commit of `configure` or use https://github.com/NLnetLabs/unbound/commit/c550bc154f2959796fc709ad437eb683b34afd1f it compiles fine!!

**Comment by wcawijngaards** [comment]
You could --enable-systemd, that could accidentally work, or instead specify with a path, `--with-protobuf-c=/usr`. But my colleague has found the correct fix for this.

**Comment by gthess** [comment]
Current master should work now. I included --enable-dnstap to the options that require pkg-config. Previously it would work only if one of the other pkg-config options (e.g., --enable-systemd) were defined during configure.
