### ISSUE TITLE
Cannot communicate through outgoing-interface if default gateway is not on the same interface

### ISSUE THREAD

**Issue by augiem** [NLnetLabs/unbound#1007]
Description:
unbound cannot communicate through outgoing-interface IP if default gateway is not on the same interface.

I'm trying to route unbound through OpenVPN (client) without the tunnel being set as the default gateway on the system. I want traffic only selectively to pass through the VPN tunnel (tun0). To achieve this, I prevent the OpenVPN server from setting the default gateway by adding this line the OpenVPN client config file:
pull-filter ignore redirect-gateway.

This successfully stops OpenVPN from modifying the ip routing table to force all traffic through the VPN tunnel. Applications can selectively choose to use the tunnel or not. I've tested that this works with both ping and curl with the current settings.

I can get the public IP of the VPN server like so:
curl 193.122.130.0 --interface tun0

And to get the public IP of my ISP:
curl 193.122.130.0

(193.122.130.0 is checkip.dyndns.org. I'm using the server's IP address instead of the domain because during this test the DNS, unbound, is not working.)

Ping also communicates through the tunnel or not by specifying -I tun0 or -I enp0s3.

With unbound running:

dig google.com
;; communications error to 127.0.0.1#53: timed out
;; communications error to 127.0.0.1#53: timed out
;; communications error to 127.0.0.1#53: timed out
; <<>> DiG 9.18.18-0ubuntu0.22.04.1-Ubuntu <<>> google.com
;; global options: +cmd
;; no servers could be reached

Unbound conf file:

server:
    interface: 127.0.0.1
    interface: 192.168.1.222
    # This is the IP of tun0
    outgoing-interface: 10.0.0.173
    port: 53
    access-control: 10.0.0.0/8 allow
    access-control: 127.0.0.0/8 allow
    access-control: 192.168.0.0/16 allow
    do-ip4: yes
    do-udp: yes
    do-tcp: yes
    do-ip6: no
    prefer-ip6: no
    hide-identity: yes
    hide-version: yes
    harden-glue: yes
    harden-dnssec-stripped: yes
    use-caps-for-id: no
    edns-buffer-size: 1232
    prefetch: yes
    num-threads: 1
    so-rcvbuf: 1m
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10

If I remove the outgoing-interface line, unbound successfully communicates over enp0s3 through the default gateway (no VPN) and returns DNS results.

Also, if I allow the OpenVPN connection to modify the default gateway, unbound successfully communicates through the tunnel if outgoing-interface is set to the tunnel IP, or even if the outgoing-interface line is removed entirely. I have confirmed with DNS leak tests that in this configuration, the IP of the DNS server matches the VPN IP. When the default gateway is not modified by OpenVPN, even if outgoing-interface is set to the VPN tunnel IP, it fails.

I have tried various other suggestions I've found such as tcp-upstream: yes, but nothing makes any difference. I have also disabled ufw for this test.

System:
Ubuntu 22.04

Unbound setup:
Recursive DNS
No forwarders
Installed via apt.

unbound -V:
Version 1.13.1

Configure line: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --disable-rpath --with-pidfile=/run/unbound.pid --with-rootkey-file=/var/lib/unbound/root.key --with-libevent --with-libnghttp2 --with-pythonmodule --enable-subnet --enable-dnstap --enable-systemd --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --libdir=/usr/lib
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 3.0.2 15 Mar 2022
Linked modules: dns64 python subnetcache respip validator iterator

**Comment by wcawijngaards** [comment]
It is possible to set verbosity: 5 on unbound, and then look into the logs, the logfile can be set with logfile: /root/unbound.log for example, and that gives details as to what unbound does. It attempts to bind to the interface address and then send to the destination IP. The logs could show if there are errors printed out. Or if the traffic just disappears.

**Comment by augiem** [comment]
> It is possible to set verbosity: 5 on unbound, and then look into the logs, the logfile can be set with logfile: /root/unbound.log for example, and that gives details as to what unbound does. It attempts to bind to the interface address and then send to the destination IP. The logs could show if there are errors printed out. Or if the traffic just disappears.

Thanks for the reply! I had done this before, but I was unable to determine anything useful from the log except that it is never getting a reply. I can't tell from the log, even at log level 5, what interface it is trying to use to send/listen. I don't see this information anywhere in the log.

I logged both with allowing OpenVPN to change the default gateway and without. There are no errors logged. In both cases, outgoing-interface is set to the VPN tun0 inet IP. In case 1 (default gateway changed to VPN IP address) it works and the log shows a response. In case 2 (default gateway left as-is), the log shows a timeout waiting for the response. I also cannot tell whether the traffic is reaching the destination. Neither log contains any references to the tun0 IP address, the default gateway IP address, my ethernet interface IP address, or any of the interface names (tun0, enp0s3). I also don't see anything in either log about attempting to bind to any IP addresses or interfaces. The only IP address in the log other than the target servers is 127.0.0.1/8, which appears in both logs:
debug: donotq: 127.0.0.0/8

Case 1 (default gateway changed to VPN IP address):
Feb 07 08:37:52 unbound[35006:0] info: sending query: . NS IN
Feb 07 08:37:52 unbound[35006:0] debug: sending to target: <.> 193.0.14.129#53
Feb 07 08:37:52 unbound[35006:0] debug: dnssec status: expected
Feb 07 08:37:52 unbound[35006:0] debug: EDNS lookup known=0 vs=0
Feb 07 08:37:52 unbound[35006:0] debug: serviced query UDP timeout=376 msec
Feb 07 08:37:52 unbound[35006:0] debug: inserted new pending reply id=e05b
Feb 07 08:37:52 unbound[35006:0] debug: opened UDP if=0 port=48974
Feb 07 08:37:52 unbound[35006:0] debug: comm point start listening 14 (-1 msec)
Feb 07 08:37:52 unbound[35006:0] debug: mesh_run: iterator module exit state is module_wait_reply
Feb 07 08:37:52 unbound[35006:0] info: mesh_run: end 2 recursion states (1 with reply, 0 detached), 1 waiting replies, >
Feb 07 08:37:52 unbound[35006:0] info: 0pvCD mod2  . NS IN
Feb 07 08:37:52 unbound[35006:0] info: 1RDdc mod2 rep google.com. A IN
Feb 07 08:37:52 unbound[35006:0] debug: cache memory msg=66072 rrset=66072 infra=8105 val=66352 subnet=74504
Feb 07 08:37:52 unbound[35006:0] debug: answer cb
Feb 07 08:37:52 unbound[35006:0] debug: Incoming reply id = e05b
Feb 07 08:37:52 unbound[35006:0] debug: Incoming reply addr = ip4 193.0.14.129 port 53 (len 16)
Feb 07 08:37:52 unbound[35006:0] debug: lookup size is 1 entries
Feb 07 08:37:52 unbound[35006:0] debug: received udp reply.

Case 2 (default gateway left as-is):
Feb 07 08:29:09 unbound[18597:0] info: sending query: . NS IN
Feb 07 08:29:09 unbound[18597:0] debug: sending to target: <.> 199.9.14.201#53
Feb 07 08:29:09 unbound[18597:0] debug: dnssec status: expected
Feb 07 08:29:09 unbound[18597:0] debug: EDNS lookup known=0 vs=0
Feb 07 08:29:09 unbound[18597:0] debug: serviced query UDP timeout=376 msec
Feb 07 08:29:09 unbound[18597:0] debug: inserted new pending reply id=f0bc
Feb 07 08:29:09 unbound[18597:0] debug: opened UDP if=0 port=53890
Feb 07 08:29:09 unbound[18597:0] debug: comm point start listening 14 (-1 msec)
Feb 07 08:29:09 unbound[18597:0] debug: mesh_run: iterator module exit state is module_wait_reply
Feb 07 08:29:09 unbound[18597:0] info: mesh_run: end 2 recursion states (1 with reply, 0 detached), 1 waiting replies, >
Feb 07 08:29:09 unbound[18597:0] info: 0pvCD mod2  . NS IN
Feb 07 08:29:09 unbound[18597:0] info: 1RDdc mod2 rep dns.msftncsi.com. A IN
Feb 07 08:29:09 unbound[18597:0] debug: cache memory msg=66072 rrset=66072 infra=8105 val=66352 subnet=74504
Feb 07 08:29:10 unbound[18597:0] debug: timeout udp
Feb 07 08:29:10 unbound[18597:0] debug: try edns1xx0 <.> 199.9.14.201#53
Feb 07 08:29:10 unbound[18597:0] debug: EDNS lookup known=0 vs=0
Feb 07 08:29:10 unbound[18597:0] debug: serviced query UDP timeout=376 msec
Feb 07 08:29:10 unbound[18597:0] debug: inserted new pending reply id=113b
Feb 07 08:29:10 unbound[18597:0] debug: opened UDP if=0 port=23013
Feb 07 08:29:10 unbound[18597:0] debug: comm point start listening 15 (-1 msec)
Feb 07 08:29:10 unbound[18597:0] debug: close of port 53890
Feb 07 08:29:10 unbound[18597:0] debug: comm_point_close of 14: event_del
Feb 07 08:29:10 unbound[18597:0] debug: close fd 14
Feb 07 08:29:10 unbound[18597:0] debug: timeout udp
Feb 07 08:29:10 unbound[18597:0] debug: svcd callbacks start
Feb 07 08:29:10 unbound[18597:0] debug: worker svcd callback for qstate 0x559de2145750
Feb 07 08:29:10 unbound[18597:0] debug: mesh_run: start
Feb 07 08:29:10 unbound[18597:0] debug: iterator[module 2] operate: extstate:module_wait_reply event:module_event_norep>
Feb 07 08:29:10 unbound[18597:0] info: iterator operate: query . NS IN
Feb 07 08:29:10 unbound[18597:0] debug: process_response: new external response event
Feb 07 08:29:10 unbound[18597:0] debug: iter_handle processing q with state QUERY RESPONSE STATE
Feb 07 08:29:10 unbound[18597:0] debug: query response was timeout

**Comment by wcawijngaards** [comment]
The message `opened UDP if=0 port=23013` relates to the outgoing interface, it picked if=0. That is the only one that is configured, the IP address of the outgoing-interface configuration. It logs the index in the interface table, inside unbound.

From the logs, the first works and the second has timeouts. Since unbound just binds to the IP that you specify, and then sends a UDP packet to the destination, there is little to see or fix, all unbound does is bind a the IP and send to the destination. Since there is a timeout, no reply returns. The system allows the send call to succeed, it does not give an error, and the system also allows to bind to the outgoing interface address. That does not mean the packet is actually sent, but to the unbound source code, or in its logs, it looks fine. And no reply returns. So that means the tunnel setup does not allow return packets in some way? If the tunnel setup would not send packets I guess there would be errors in the send call. With tcpdump on the tunnel it may be possible to see if packets leave or return? Or perhaps other stuff like the route table or firewall is blocking access to the tunnel. The default gateway setting is a route table setting, so I guess that something is wrong with the route table, perhaps there is some other gateway there that drops all traffic, that would otherwise be replaced by the vpn gateway?

**Comment by augiem** [comment]
Thanks for the insight! I've decided to solve the issue a different way using multiple VMs.

**Comment by wcawijngaards** [comment]
I guess the issue can be closed, then. There was something wrong with sending packets over the tunnel, but what is not sure.
