### ISSUE TITLE
TCP_BACKLOG

### ISSUE THREAD

**Issue by mibere** [NLnetLabs/unbound#101]
After installing [Redis](https://redis.io/) on Debian 10 (Kernel 4.19) there was the following entry in its log:

> WARNING: The TCP backlog setting of 511 cannot be enforced because
/proc/sys/net/core/somaxconn is set to the lower value of 128.

It's because the system default value of _net.core.somaxconn_ is _128_.

In default _redis.conf_ there is

```
# TCP listen() backlog.
#
# In high requests-per-second environments you need an high backlog in order
# to avoid slow clients connections issues. Note that the Linux kernel
# will silently truncate it to the value of /proc/sys/net/core/somaxconn so
# make sure to raise both the value of somaxconn and tcp_max_syn_backlog
# in order to get the desired effect.
tcp-backlog 511
```

It seems also Unbound uses a value higher than the default of 128 in [listen_dnsport.c](https://github.com/NLnetLabs/unbound/blob/master/services/listen_dnsport.c#L74)

> #define TCP_BACKLOG 256 

There should be a warning in Unbound log too (even on _verbosity:1_)

**Comment by wcawijngaards** [comment]
So we would like warning statements like this, but it is not configurable.  So the user has no way to remove the warning if they do not want to (or cannot) edit the kernel parameters.  The kernel is also silent about it as a failure.

So it would be nice to have, but only if the user can control it somehow.  Maybe better in a blog or how-to, or in the documentation somewhere?  Where would you look for it?  Or as a diagnostic, somewhere.  But not as a constant reminder, that only teaches people to ignore warnings.

**Comment by spirillen** [comment]
> So it would be nice to have, but only if the user can control it somehow. Maybe better in a blog or how-to, or in the documentation somewhere? Where would you look for it? Or as a diagnostic, somewhere. But not as a constant reminder, that only teaches people to ignore warnings.

I would look in the `man`and the [documentation](https://nlnetlabs.nl/documentation/unbound/) as blogs usually is full of anything but usefully information for "howto"

Just a 1cent

**Comment by mibere** [comment]
Good point.

> Maybe better in a blog or how-to, or in the documentation somewhere? Where would you look for it?

Not in a blog. My first recommendation for a hint with something like

```
net.core.somaxconn = 256
net.ipv4.tcp_max_syn_backlog = 256
```
would be in [Howto Optimise](https://nlnetlabs.nl/documentation/unbound/howto-optimise/), secondly [Howto Setup and Install](https://nlnetlabs.nl/documentation/unbound/howto-setup/).

> Or as a diagnostic, somewhere.

Maybe in _unbound-checkconf_ ?

**Comment by wcawijngaards** [comment]
Documented on the optimise page.  Not sure how to add it to _unbound-checkconf_ without the same issues as a warning to log, because some people output that to startup logs.
