### ISSUE TITLE
[FR] ECH support

### ISSUE THREAD

**Issue by cochcoder** [NLnetLabs/unbound#1012]
**Current behavior**
Does not support ECH (Encrypted Client Hello). 
**Describe the desired feature**
ECH is considered to be "the last puzzle piece to privacy" on the world wide web, supporting ECH on unbound would increase a user's privacy and security. 
**Potential use-case**
This feature would be useful to unbound users as it would give them the same, base, level of security and privacy compared to other DNS resolvers that will support this functionality. With unbound being able to self-hosted, this would make unbound almost perfect.

**Comment by mjamil85** [comment]
Agree. I also hope unbound will support for ECH.

**Comment by mjamil85** [comment]
> **Current behavior** Does not support ECH (Encrypted Client Hello). **Describe the desired feature** ECH is considered to be "the last puzzle piece to privacy" on the world wide web, supporting ECH on unbound would increase a user's privacy and security. **Potential use-case** This feature would be useful to unbound users as it would give them the same, base, level of security and privacy compared to other DNS resolvers that will support this functionality. With unbound being able to self-hosted, this would make unbound almost perfect.

I just found that you can enable ECH in unbound by added this "tls-use-sni: yes" & add DNS-over-TLS under "server:" in unbound config. In PiHole, make sure "Use DNSSEC" is disable. Using [Clouflare Security Test](https://www.cloudflare.com/ssl/encrypted-sni/), SNI pass.

![image](https://github.com/NLnetLabs/unbound/assets/155965177/1e74d986-1166-4033-ac4e-0df476937a7f)

PS: Encrypted Client Hello (ECH) is a successor to ESNI and masks the Server Name Indication (SNI) that is used to negotiate a TLS handshake
