### ISSUE TITLE
TLS attempted over port 53 when enabling tls-upstream 

### ISSUE THREAD

**Issue by philippelatulippe** [NLnetLabs/unbound#1014]
Hello Unbound folks! I'm experimenting with DNS resolvers for the first time and came across an issue with DNS over TLS.

#### Describe the bug
Certain configurations cause unbound to try to connect to upstreams and/or authoritative nameservers with TLS over port 53, which is not supported by servers [nor the RFC](https://www.rfc-editor.org/rfc/rfc7858.html#section-3.1). Here's an [example on the mailing list](https://lists.nlnetlabs.nl/pipermail/unbound-users/2024-February/008240.html) of someone else seeing this behaviour. It should probably be connecting over port 853 by default, and never over 53 if using TLS as a transport.

I ran into this issue while trying to make unbound use DoT to connect to authoritative nameservers while recursing, which I now realize is probably not yet supported. I configured my server to operate as a recursive resolver, and then set `tls-upstream` hoping it might also cause recursive lookups to go over DoT if available. To my delight it did attempt to use DoT! But on the wrong port, and with no fallback to plaintext DNS. I'm guessing it's not supported and that my configuration is wrong, but it would be nice if the server didn't fail in such a strange way.

#### To reproduce
1. Follow the [Getting Started guide](https://unbound.docs.nlnetlabs.nl/en/latest/getting-started/configuration.html?highlight=upstream#configuration).
2. In the configuration file, set `tls-upstream: yes`.
3. Don't configure any upstreams or forwarding.
4. Run unbound and make a query.

#### Expected behavior
Unbound could either:
* connect to the upstream or authoritative nameservers using TLS on port 853
* Ignore `upstream-tls` when recursing
* Maybe throw an error about the config

#### System
 - Unbound version: 1.19.0 from Homebrew
 - OS: Mac OS 14
 - `unbound -V` output: onfigure line: --prefix=/opt/homebrew/Cellar/unbound/1.19.0 --sysconfdir=/opt/homebrew/etc --enable-event-api --enable-tfo-client --enable-tfo-server --with-libevent=/opt/homebrew/opt/libevent --with-libnghttp2=/opt/homebrew/opt/libnghttp2 --with-ssl=/opt/homebrew/opt/openssl@3 --with-libexpat=/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr
Linked libs: libevent 2.1.12-stable (it uses kqueue), OpenSSL 3.2.1 30 Jan 2024
Linked modules: dns64 respip validator iterator
TCP Fastopen feature available

#### Additional information
<details>
<summary>unbound.conf</summary>
<pre>
server:
	username: "_unbound"
	root-hints: ""
	hide-identity: no
	hide-version: no
	hide-trustanchor: no
	qname-minimisation: yes
	auto-trust-anchor-file: "/opt/homebrew/etc/unbound/root.key"
	tls-upstream: yes
	tls-system-cert: yes
	http-notls-downstream: yes
</pre>
</details>

**Comment by gthess** [comment]
Hi Philippe,

You are right that DoT is not common to authoritatives yet.
The manpage in Unbound does warn that this option is global for all upstreams and useful in tunneling scenarios. If you know of specific upstreams that do support DoT you can explicitly configure them in forward and/or stub configuration sections as described in the manpage.

So I see this as not an issue for Unbound.

I believe what you would like to see is support for [unilater probing](https://datatracker.ietf.org/doc/draft-ietf-dprive-unilateral-probing/); a draft that describes a mechanism for a resolver to actively check for upstream DoT/DoQ support. This is not yet in Unbound but there are plans (not concrete) to include it in a future version.

**Comment by philippelatulippe** [comment]
I see now, I had misunderstood that paragraph to mean that it would contact all nameservers with tls over port 853, and you are correct that a probing mechanism like the one in that draft is what I had in mind. I will close this issue and wait for a future version. Thanks for the reply!
