### ISSUE TITLE
 How to forward DNS requests to tun interface?

### ISSUE THREAD

**Issue by noahge0923** [NLnetLabs/unbound#1018]
I use Sing-Box to proxy my local area network environment. Sing-Box creates a tun interface to intercept all traffic and intercepts DNS requests through sniffing. My Unbound is already configured, and computers both locally and in the LAN can resolve DNS queries normally. However, now I want to forward all DNS requests obtained by Unbound to Sing-Box for processing. What should I do now?

**Network**
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:83:33:b9 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.230/24 brd 192.168.1.255 scope global enp1s0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe83:33b9/64 scope link
       valid_lft forever preferred_lft forever
3: ztr4nvqcky: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 2800 qdisc fq_codel state UNKNOWN group default qlen 1000
    link/ether 7e:0e:fa:87:99:37 brd ff:ff:ff:ff:ff:ff
    inet 172.30.111.225/16 brd 172.30.255.255 scope global ztr4nvqcky
       valid_lft forever preferred_lft forever
    inet6 fe80::580a:acff:fec9:7ca7/64 scope link
       valid_lft forever preferred_lft forever
16: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 9000 qdisc fq_codel state UNKNOWN group default qlen 500
    link/none
    inet 172.19.0.1/30 brd 172.19.0.3 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::9142:3842:4a64:50c1/64 scope link stable-privacy
       valid_lft forever preferred_lft forever

**Resolvect Status**
Global
         Protocols: -LLMNR -mDNS -DNSOverTLS DNSSEC=yes/supported
  resolv.conf mode: uplink
Current DNS Server: 127.0.0.1
       DNS Servers: 127.0.0.1

Link 2 (enp1s0)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=yes/supported

Link 3 (ztr4nvqcky)
Current Scopes: none
     Protocols: -DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=yes/supported

Link 16 (tun0)
    Current Scopes: DNS
         Protocols: +DefaultRoute +LLMNR -mDNS -DNSOverTLS DNSSEC=yes/supported
Current DNS Server: 172.19.0.2
       DNS Servers: 172.19.0.2
        DNS Domain: ~.

**Unbound Config**
include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"

server:
    qname-minimisation: yes
    interface: enp1s0
    interface: 127.0.0.1
    prefer-ip4: yes
    access-control: 127.0.0.0/8 allow
    access-control: 192.168.0.0/16 allow

**Comment by noahge0923** [comment]
I can successfully retrieve DNS resolution records by using dig @172.19.0.2 google.com. However, after configuring a forward-zone and setting forward-addr in Unbound, all domain names cannot be resolved.

**Comment by noahge0923** [comment]
I need Sing-Box to intercept and use a proxy to resolve certain specific domain names, so I need to forward Unbound's DNS requests to Sing-Box.

**Comment by gthess** [comment]
You can specify the outgoing interface in unbound with `outgoing-interface:` in the `server:` section. In your example that would be:
```
server:
    ...
    outgoing-interface: 172.19.0.1
    ...
```
Maybe that solves your issue?

**Comment by noahge0923** [comment]
This option does not solve my problem. After disabling DNSSEC, I used a forward-zone to forward all DNS requests to 172.19.0.2, and now it works.

**Comment by gthess** [comment]
Glad that it works now for you, closing.
