### ISSUE TITLE
unbound-resolvconf.service: Failed with result 'exit-code'.

### ISSUE THREAD

**Issue by differentieel** [NLnetLabs/unbound#1020]
### on my Helios64 i upgraded to unbound 1.19.1 
some specs: Armbian_community 24.5.0-trunk.81 Bookworm with Linux 6.6.18-current-rockchip64

this error i do not know how to repair:

path: /lib/systemd/system/unbound-resolvconf.service

**unbound-resolvconf.service: Failed with result 'exit-code'.**

CODE_FILE    src/core/unit.c
CODE_FUNC    unit_log_failure
CODE_LINE    5627
INVOCATION_ID    8ab34e0c6e4c419b8d0e3bfb3af3b419
MESSAGE_ID    d9b373ed55a64feb8242e02dbe79a49c
PRIORITY    4
SYSLOG_FACILITY    3
SYSLOG_IDENTIFIER    systemd
TID    1
UNIT    unbound-resolvconf.service
UNIT_RESULT    exit-code

there is more to tell about this situation - please ask what you need to know to help me solve this 'resolfconf' problem

**Comment by differentieel** [comment]
errors disappeared - there where 2 versions installed - 1.17.1-2 and 1.19.1 - sorry for this - it may marked as solved

**Comment by wcawijngaards** [comment]
Happy to hear the problem is gone, so I guess the issue is marked as closed. The file src/core/unit.c is not part of Unbound, so the failure file must refer to some other code base, also the unit_log_failure function. I guess more details could have been in the system log.
