### ISSUE TITLE
refuse_non_local crashes unbound Windows service

### ISSUE THREAD

**Issue by RBetting77** [NLnetLabs/unbound#1022]
**Describe the bug**
Using refuse_non_local crashes the unbound Windows service when the first query is refused.

**To reproduce**
1. In service.conf, under "server:" use the next line: "access-control: 0.0.0.0/0 refuse_non_local"
2. Local queries get answered with no problem
3. The first recursive query which should be refused crashes the unbound service.

**Expected behavior**
The refusal of the non-local query.

**System:**
 - Unbound version: Version 1.19.1
 - OS: Windows 10, 22H2 19045.3930
 - `unbound -V` output:
 ```
 Version 1.19.1

Configure line: --host=x86_64-w64-mingw32 --build=x86_64-redhat-linux-gnu --target=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --exec-prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --bindir=/usr/x86_64-w64-mingw32/sys-root/mingw/bin --sbindir=/usr/x86_64-w64-mingw32/sys-root/mingw/sbin --sysconfdir=/usr/x86_64-w64-mingw32/sys-root/mingw/etc --datadir=/usr/x86_64-w64-mingw32/sys-root/mingw/share --includedir=/usr/x86_64-w64-mingw32/sys-root/mingw/include --libdir=/usr/x86_64-w64-mingw32/sys-root/mingw/lib --libexecdir=/usr/x86_64-w64-mingw32/sys-root/mingw/libexec --localstatedir=/usr/x86_64-w64-mingw32/sys-root/mingw/var --sharedstatedir=/usr/x86_64-w64-mingw32/sys-root/mingw/com --mandir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/man --infodir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/info --enable-debug --enable-static-exe --disable-flto --disable-gost --with-ssl=/home/wouter/src/unbound/unbound-dist-giKu5n/sslinstall --with-libexpat=/home/wouter/src/unbound/unbound-dist-giKu5n/wxpinstall
Linked libs: event winsock (it uses WSAWaitForMultipleEvents), OpenSSL 1.1.1l  24 Aug 2021
```

**Additional information**
service.conf:
 ```
server:
        interface: 0.0.0.0
        access-control: 0.0.0.0/0 refuse_non_local
 ```

**Comment by gthess** [comment]
I verify that the above commit ec0b510f1c140c11f2125f39cfadc95332e42b17 solves this problem.
Without the fix it was stopping with assertion failure.
The issue was with the refuse code path.
@RBetting77, you can either wait for a new version that includes the fix or use `deny_non_local` instead with 1.19.1.

**Comment by RBetting77** [comment]
Thank you very much for the fast actions!
Much appreciated.

**Comment by RBetting77** [comment]
Tested with version 1.19.2, works like a charm.

**Comment by gthess** [comment]
Nice that it works but the bug is still there in 1.19.2 :)
Probably it is not triggered (same way as we couldn't trigger it on Linux).
1.19.3 released in roughly a week from now will contain the fix.
Keeping open until then.

**Comment by RBetting77** [comment]
1.19.3 tested, no crash.
REFUSED is returned as expected.

**Comment by gthess** [comment]
Thanks for the confirmation! Closing.
