### ISSUE TITLE
DoT forward-zone via unbound-control

### ISSUE THREAD

**Issue by jdelker** [NLnetLabs/unbound#1034]
First off: I can't tell whether the problem described below is a bug, simply not implemented or me being to stupid to do.

My use case: **Setting a DoT DNS forwarder via unbound-control.**

Defining such forward in the config is fine and works correct as far as I can tell:
```
forward-zone:
	name: "."
	forward-tls-upstream: yes
	forward-addr: 1.1.1.1@853
```

Unfortunately, that static config does not suit my particular environment, because I'm operating in changing locations. I need to switch the "." forward zone to different upstream DNS servers (with and without DoT), basically on-the-fly.
Embedded in some "external detection logic", I'm already able to adjust the DNS setup via `unbound-control` accordingly, but unfortunately not for any DoT forwards. Simply because there seems to be no way to set the `forward-tls-upstream` option with the `forward_add` command.

If there is any way to accomplish this with `unbound-control` please let me know. Otherwise I would kindly request this as a feature.

**Comment by wcawijngaards** [comment]
There is a new option for unbound-control, for `unbound-control forward_add +t example.com 192.0.2.1@853`. That sets it to use tls for the upstream queries. The option is also added for `unbound-control stub_add +t example.com 192.0.2.1@853` to set it to use tls for the upstream queries.

**Comment by Playgirlkaybraz11** [comment]
> First off: I can't tell whether the problem described below is a bug, simply not implemented or me being to stupid to do.
> 
> My use case: **Setting a DoT DNS forwarder via unbound-control.**
> 
> Defining such forward in the config is fine and works correct as far as I can tell:
> 
> ```
>   $forward-zone:
> 	name: "."
> 	forward-tls-upstream: yes
> 	forward-addr: 1.1.1.1@853
> ```
> 
> Unfortunately, that static config does not suit my particular environment, because I'm operating in changing locations. I need to switch the "." forward zone to different upstream DNS servers (with and without DoT), basically on-the-fly. Embedded in some "external detection logic", I'm already able to adjust the DNS setup via `unbound-control` accordingly, but unfortunately not for any DoT forwards. Simply because there seems to be no way to set the `forward-tls-upstream` option with the `forward_add` command.
> 
> If there is any way to accomplish this with `unbound-control` please let me know. Otherwise I would kindly request this as a feature.



> First off: I can't tell whether the problem described below is a bug, simply not implemented or me being to stupid to do.
> 
> My use case: **Setting a DoT DNS forwarder via unbound-control.**
> 
> Defining such forward in the config is fine and works correct as far as I can tell:
> 
> ```
> forward-zone:
> 	name: "."
> 	forward-tls-upstream: yes
> 	forward-addr: 1.1.1.1@853
> ```
> 
> Unfortunately, that static config does not suit my particular environment, because I'm operating in changing locations. I need to switch the "." forward zone to different upstream DNS servers (with and without DoT), basically on-the-fly. Embedded in some "external detection logic", I'm already able to adjust the DNS setup via `unbound-control` accordingly, but unfortunately not for any DoT forwards. Simply because there seems to be no way to set the `forward-tls-upstream` option with the `forward_add` command.
> 
> If there is any way to accomplish this with `unbound-control` please let me know. Otherwise I would kindly request this as a feature.

**Comment by Playgirlkaybraz11** [comment]
test/serialization.test.ts #1090 #1090 #1115 #871 #994
