### ISSUE TITLE
unbound compiling question

### ISSUE THREAD

**Issue by Aura67** [NLnetLabs/unbound#1046]
Hello, I got unbound 1.19.3 running with pihole. I can now install and of course uninstall any version without my apt. Now the question arises for me when I specify when compiling: ./configure && make && make install without --with what is the difference between: ./configure && make && make install and ./configure --with && make && make Install ? 

Note: on Unbound compiling, it runs better as if you were installing it from apt, thanks again for all the work you do.

Best regards
aura

**Comment by wcawijngaards** [comment]
The syntax `--with` is not really an option, but `./configure` has a bunch of options for it. `./configure --help` shows the list of options. The defaults are pretty sensible and should result in a working resolver. Mostly people use it to enable features and specify that as the flags, and with some of them it is also possible to specify where the includes and libraries can be found. This is useful if the libraries are in a different location.

For the install after the compile, the `--prefix=/usr/local` is an important option. The `make install` puts the files in subdirectories of that install path. So in `/usr/local/bin` and `/usr/local/etc`, ... It is possible to configure the install locations in more detail.

**Comment by Aura67** [comment]
Ok, thank you, but I still have one question. I added the option to my update settings. These are:
# Aggressive NSEC uses the DNSSEC NSEC chain to synthesize NXDOMAIN
# and other denials, using information from previous NXDOMAINs answers.
aggressive-nsec: yes
 
Are these correctly indicating that, for example, my Pihole uses this option in addition to DNSSEC?

**Comment by wcawijngaards** [comment]
If the option is set then Unbound would use it, if DNSSEC is enabled. There is more documentation on the man page. It can also be found in the documentation https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-aggressive-nsec , there is also documentation about the other options.

**Comment by Aura67** [comment]
Hello, I have discovered another problem: it cannot find the root.hints, which are located under /etc/unbound/root.hints
I've tried everything but I always get the message: no config, using builtin root hints,It finds my root key without any problems.
My server settings:
server:
    # If no logfile is specified, syslog is used
    # logfile: "/var/log/unbound/unbound.log"
    verbosity: 0

    interface: 127.0.0.1
    port: 5335
    do-ip4: yes
    do-udp: yes
    do-tcp: yes

    # May be set to yes if you have IPv6 connectivity
    do-ip6: no

    # You want to leave this to no unless you have *native* IPv6. With 6to4 and
    # Terredo tunnels your web browser should favor IPv4 for the same reasons
    prefer-ip6: no

    # enable DNSSEC
    auto-trust-anchor-file: "/etc/unbound/root.key"

    # file to read root hints from.
    # get one from https://www.internic.net/domain/named.root
    # root-hints: “/etc/unbound/root.hints”

    # file to read root hints from.
    # get one from https://www.internic.net/domain/root.zone
    # root-zone: “/etc/unbound/root.zone”

    # DNS64 ignore AAAA records for these domains and use A instead.
    # dns64-ignore-aaaa: "example.com"

    # the time to live (TTL) value lower bound, in seconds. Default 0.
    # If more than an hour could easily give trouble due to stale data.
    cache-min-ttl: 0

    # the time to live (TTL) value cap for negative responses in the cache
    cache-max-negative-ttl: 3600

    # the time to live (TTL) value cap for RRsets and messages in the
    # cache. Items are not cached for longer. In seconds.
    cache-max-ttl: 86400

    # Privacy | Default: no, no
    hide-identity: yes
    hide-version: yes

    # send minimal amount of information to upstream servers to enhance privacy
    qname-minimisation: yes

    # Trust glue only if it is within the server's authority
    harden-glue: yes

    # Require DNSSEC data for trust-anchored zones, if such data is absent, the zone becomes BOGUS
    harden-dnssec-stripped: yes

    # Harden against queries that fall under dnssec-signed nxdomain names
    harden-below-nxdomain: yes

    # trust anchor signaling sends a RFC8145 key tag query after priming.
    trust-anchor-signaling: yes

    # Don't use Capitalization randomization as it known to cause DNSSEC issues sometimes
    # see https://discourse.pi-hole.net/t/unbound-stubby-or-dnscrypt-proxy/9378 for further details
    use-caps-for-id: no

    # Reduce EDNS reassembly buffer size.
    # IP fragmentation is unreliable on the Internet today, and can cause
    # transmission failures when large DNS messages are sent via UDP. Even
    # when fragmentation does work, it may not be secure; it is theoretically
    # possible to spoof parts of a fragmented DNS message, without easy
    # detection at the receiving end. Recently, there was an excellent study
    # >>> Defragmenting DNS - Determining the optimal maximum UDP response size for DNS <<<
    # by Axel Koolhaas, and Tjeerd Slokker (https://indico.dns-oarc.net/event/36/contributions/776/)
    # in collaboration with NLnet Labs explored DNS using real world data from the
    # the RIPE Atlas probes and the researchers suggested different values for
    # IPv4 and IPv6 and in different scenarios. They advise that servers should
    # be configured to limit DNS messages sent over UDP to a size that will not
    # trigger fragmentation on typical network links. DNS servers can switch
    # from UDP to TCP when a DNS response is too big to fit in this limited
    # buffer size. This value has also been suggested in DNS Flag Day 2020.
    edns-buffer-size: 1232

    # Perform prefetching of close to expired message cache entries
    # This only applies to domains that have been frequently queried
    prefetch: yes

    # One thread should be sufficient, can be increased on beefy machines. In reality for most users running on small networks or on a single machine, it should be unnecessary to seek performance enhancement by increasing num-threads above 1.
    num-threads: 1

    # Ensure kernel buffer is large enough to not lose messages in traffic spikes
    so-rcvbuf: 1m

    # Ensure privacy of local IP ranges
    private-address: 192.168.0.0/16
    private-address: 169.254.0.0/16
    private-address: 172.16.0.0/12
    private-address: 10.0.0.0/8
    private-address: fd00::/8
    private-address: fe80::/10

**Comment by bjovereinder** [comment]
Hi Aura,

Thanks for choosing Unbound with Pi-hole!  It’s great to hear that it is serving you well, and that you are installing the latest version of Unbound.

I would like to share here that for any support or discussions about bugs and new features of Unbound, we use GitHub to engage with the community.  However, for questions about using and configuring Unbound, we have a dedicated unbound-users mailing list. This is the perfect place to ask and answer questions about setting up and using Unbound.  You can join the conversation here: [Unbound Users Mailing List](https://lists.nlnetlabs.nl/mailman/listinfo/unbound-users).

Additionally, for guidance on installation and configuration, you can check out the official Unbound documentation:
- [Installation Guide](https://unbound.docs.nlnetlabs.nl/en/latest/getting-started/installation.html)
- [Configuration Guide](https://unbound.docs.nlnetlabs.nl/en/latest/getting-started/configuration.html)

Looking forward to seeing you on the mailing list!
