### ISSUE TITLE
There are memory leaks with SIGHUP

### ISSUE THREAD

**Issue by eaglegai** [NLnetLabs/unbound#1051]
**Describe the bug**
May be there are memory leaks, when I send SIGHUP to unbound service again and again, Memory grows slowly.

**To reproduce**
test.sh:
```
#~/bin/bash
service_name="unbound.service"

i=0
while (($i < 2700));
do
        echo $i
        systemctl status $service_name | grep "Memory" >> memleak.log
        #systemctl reload $service_name
        kill -SIGHUP 83578
        (( i ++ ))
        sleep 0.5
done
```
83578 is the main_pid of unbound.

**Expected behavior**
memory is stable, instead of growing slowly

**System:**
 - Unbound version:  1.17.1 and 1.19.3 have the same problem
 
**Additional information**

after test.sh, memory grows from 19.7M  to 48.2M

**Comment by eaglegai** [comment]
I have read run_daemon\daemon_cleanup\daemon_fork\daemon_create_workers\worker_delete  functions, but have no idea what's wrong, could you  help me?@wcawijngaards @gthess

**Comment by wcawijngaards** [comment]
A quick check with valgrind, shows that unbound has no memory leaks after a couple kill -HUP on it. I can see that the rss increases as well, with some size after the reloads, but valgrind reports no memory leaks. Perhaps it is something like memory fragmentation.

**Comment by yvoinov** [comment]
Sure. Looks like memory fragmentation. Unbound is significantly fragments RAM quite strongly (About 40%).

I can confirm that there are no significant memory leaks.

**Comment by eaglegai** [comment]
If we have good solutions about fragmentation, after several million times sending SIGHUP, memory increase to 400M, top command show unbound use more than 10% memory.
In extreme situations, cound unbound cause oom?

**Comment by Forza-tng** [comment]
Would THP be helpful here? There is `madvise` that a process could use, unless the sysadmin forces THP.

**Comment by eaglegai** [comment]
@wcawijngaards @yvoinov if you don't mind, I want to close the issue， thanks for your reply~

**Comment by wcawijngaards** [comment]
For THP, transparent huge pages in madvise, I do not easily see how it could help since Unbound does not really have unused mapped memory sitting around.

I also think the issue can be closed. Thank you for the participation.
