### ISSUE TITLE
Chroot location question

### ISSUE THREAD

**Issue by Aura67** [NLnetLabs/unbound#1067]
Under which directory would I have to add with: --with-chroot-dir= if the configurations are under /etc/unbound/unbound.conf.d? I haven't figured that out yet, otherwise everything works as it should. Thanks for answering if anyone knows.

**Comment by wcawijngaards** [comment]
For questions directed at the other unbound users, actually we have an email discussion list, unbound-users.

If unbound wants to reload configuration the config files need to be accessible from the chroot directory. For other files, chroot users use commands like `mount --bind -n /dev/log /etc/unbound/dev/log` to make files accessible from inside a '/etc/unbound' chroot directory.
