### ISSUE TITLE
Unbound anwsers SERVAIL instead of NOERROR

### ISSUE THREAD

**Issue by pywy18** [NLnetLabs/unbound#1077]
**Describe the bug**
When i try to resolve ipv6 address for domain ns1-proddns.glbdns.o365filtering.com, I have a SERVFAIL error but all other resolvers return NOERROR.

> $ unbound-host -vd -t AAAA ns1-proddns.glbdns.o365filtering.com
> [1716563931] libunbound[83465:0] notice: init module 0: validator
> [1716563931] libunbound[83465:0] notice: init module 1: iterator
> [1716563931] libunbound[83465:0] info: resolving ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563931] libunbound[83465:0] info: priming . IN NS
> [1716563931] libunbound[83465:0] info: response for . NS IN
> [1716563931] libunbound[83465:0] info: reply from <.> 198.97.190.53#53
> [1716563931] libunbound[83465:0] info: query response was ANSWER
> [1716563931] libunbound[83465:0] info: priming successful for . NS IN
> [1716563931] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563931] libunbound[83465:0] info: reply from <.> 170.247.170.2#53
> [1716563931] libunbound[83465:0] info: query response was REFERRAL
> [1716563931] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563931] libunbound[83465:0] info: reply from <com.> 2001:500:d937::30#53
> [1716563931] libunbound[83465:0] info: query response was REFERRAL
> [1716563931] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563931] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.38.8#53
> [1716563931] libunbound[83465:0] info: query response was nodata ANSWER
> [1716563931] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563931] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.4.8#53
> [1716563931] libunbound[83465:0] info: query response was ANSWER
> [1716563931] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563931] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.2.8#53
> [1716563931] libunbound[83465:0] info: query response was THROWAWAY
> [1716563932] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563932] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.44.8#53
> [1716563932] libunbound[83465:0] info: query response was THROWAWAY
> [1716563932] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563932] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.38.8#53
> [1716563932] libunbound[83465:0] info: query response was THROWAWAY
> [1716563932] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563932] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.4.8#53
> [1716563932] libunbound[83465:0] info: query response was THROWAWAY
> [1716563932] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563932] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.40.8#53
> [1716563932] libunbound[83465:0] info: query response was THROWAWAY
> [1716563933] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563933] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.40.8#53
> [1716563933] libunbound[83465:0] info: query response was THROWAWAY
> [1716563933] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563933] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.44.8#53
> [1716563933] libunbound[83465:0] info: query response was THROWAWAY
> [1716563933] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563933] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.44.8#53
> [1716563933] libunbound[83465:0] info: query response was THROWAWAY
> [1716563933] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563933] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.44.8#53
> [1716563933] libunbound[83465:0] info: query response was THROWAWAY
> [1716563933] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563933] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.38.8#53
> [1716563933] libunbound[83465:0] info: query response was THROWAWAY
> [1716563933] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563933] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.44.8#53
> [1716563933] libunbound[83465:0] info: query response was THROWAWAY
> [1716563933] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563933] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.38.8#53
> [1716563933] libunbound[83465:0] info: query response was THROWAWAY
> [1716563933] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563933] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.4.8#53
> [1716563933] libunbound[83465:0] info: query response was THROWAWAY
> [1716563933] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563933] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.2.8#53
> [1716563933] libunbound[83465:0] info: query response was THROWAWAY
> [1716563934] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563934] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.38.8#53
> [1716563934] libunbound[83465:0] info: query response was THROWAWAY
> [1716563934] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563934] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.40.8#53
> [1716563934] libunbound[83465:0] info: query response was THROWAWAY
> [1716563934] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563934] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.2.8#53
> [1716563934] libunbound[83465:0] info: query response was THROWAWAY
> [1716563934] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563934] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.124.8#53
> [1716563934] libunbound[83465:0] info: query response was THROWAWAY
> [1716563934] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563934] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.124.8#53
> [1716563934] libunbound[83465:0] info: query response was THROWAWAY
> [1716563934] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563934] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.40.8#53
> [1716563934] libunbound[83465:0] info: query response was THROWAWAY
> [1716563934] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563934] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.40.8#53
> [1716563934] libunbound[83465:0] info: query response was THROWAWAY
> [1716563935] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563935] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.124.8#53
> [1716563935] libunbound[83465:0] info: query response was THROWAWAY
> [1716563935] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563935] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.2.8#53
> [1716563935] libunbound[83465:0] info: query response was THROWAWAY
> [1716563935] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563935] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.38.8#53
> [1716563935] libunbound[83465:0] info: query response was THROWAWAY
> [1716563935] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563935] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.2.8#53
> [1716563935] libunbound[83465:0] info: query response was THROWAWAY
> [1716563935] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563935] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.4.8#53
> [1716563935] libunbound[83465:0] info: query response was THROWAWAY
> [1716563935] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563935] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.4.8#53
> [1716563935] libunbound[83465:0] info: query response was THROWAWAY
> [1716563935] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563935] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.4.8#53
> [1716563935] libunbound[83465:0] info: query response was THROWAWAY
> [1716563935] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563935] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.124.8#53
> [1716563935] libunbound[83465:0] info: query response was THROWAWAY
> [1716563935] libunbound[83465:0] info: response for ns1-proddns.glbdns.o365filtering.com. AAAA IN
> [1716563935] libunbound[83465:0] info: reply from <o365filtering.com.> 104.47.124.8#53
> [1716563935] libunbound[83465:0] info: query response was THROWAWAY
> Host ns1-proddns.glbdns.o365filtering.com not found: 2(SERVFAIL). (error)

With any other resolver, NOERROR is returned: 

> dig -t AAAA ns1-proddns.glbdns.o365filtering.com @9.9.9.9
> 
> ; <<>> dig 9.10.8-P1 <<>> -t AAAA ns1-proddns.glbdns.o365filtering.com @9.9.9.9
> ;; global options: +cmd
> ;; Got answer:
> ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21487
> ;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
> 
> ;; OPT PSEUDOSECTION:
> ; EDNS: version: 0, flags:; udp: 1232
> ;; QUESTION SECTION:
> ;ns1-proddns.glbdns.o365filtering.com. IN AAAA
> 
> ;; Query time: 455 msec
> ;; SERVER: 9.9.9.9#53(9.9.9.9)
> ;; WHEN: Fri May 24 17:21:37 CEST 2024
> ;; MSG SIZE  rcvd: 65

with log-servfail enabled I got this line: 

> May 24 17:00:15 192.168.18.101 unbound: [88968:2] error: SERVFAIL <ns1-proddns.glbdns.o365filtering.com. AAAA IN>: all servers for this domain failed, at zone o365filtering.com. from 104.47.40.8 nodata answer

**Expected behavior**
Return a NOERROR instead of SERVFAIL

**System:**
 - Unbound version: 1.18.0
 - OS:OpenBSD 7.5 stable
 - `unbound -V` output:
 $ unbound -V
Version 1.18.0

Configure line: --enable-allsymbols --with-ssl=/usr --with-libevent=/usr --with-libexpat=/usr --without-pythonmodule --with-chroot-dir=/var/unbound --with-pidfile= --with-rootkey-file=/var/unbound/db/root.key --with-conf-file=/var/unbound/etc/unbound.conf --with-username=_unbound --disable-shared --disable-explicit-port-randomisation --without-pthreads
Linked libs: pluggable-libevent 1.4.15-stable (it uses kqueue), LibreSSL 3.9.0
Linked modules: dns64 respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

**Additional information**
Add any other information that you may have gathered about the issue here.

**Comment by gthess** [comment]
This looks like an issue that was fixed in version 1.19.0 (https://github.com/NLnetLabs/unbound/issues/946).
Could you try with a newer version?

**Comment by pywy18** [comment]
You are absolutely right @gthess 
I've just tested with a snapshot of OpenBSD, which embeds unbound version 1.19.3, and it works as expected.
Sorry for the noise.
