### ISSUE TITLE
example.conf missing from distribution

### ISSUE THREAD

**Issue by rwfranks** [NLnetLabs/unbound#1089]
unbound.conf(5) makes the following claim:

'''
Below is a minimal config file. The source distribution contains an extensive example.conf file with all the options.
'''

Either this is a wicked lie, or it is called something else!
Certainly, I failed to find it.

**System:**
 - Unbound version: 1.20.0

**Comment by wtoorop** [comment]
> unbound.conf(5) makes the following claim:
> 
> ''' Below is a minimal config file. The source distribution contains an extensive example.conf file with all the options. '''
> 
> Either this is a wicked lie, or it is called something else! Certainly, I failed to find it.

Hi Dick :), before configure it is called example.conf.in and located in the doc directory. 
See: https://github.com/NLnetLabs/unbound/blob/master/doc/example.conf.in

Cheers,
-- Willem

**Comment by rwfranks** [comment]
Thanks
