### ISSUE TITLE
[Help] unbound-control  local_zone <name> <type>

### ISSUE THREAD

**Issue by spirillen** [NLnetLabs/unbound#109]
Hi guys, I would like a little help to figure out the right way to set this command with unbound-control

I'm trying to add a local-zone as
```
unbound-control local_zones "2mdn.net" always_nxdomain
unbound-control local_zones 2mdn.net always_nxdomain
unbound-control "local_zones 2mdn.net always_nxdomain"
```

According to the `unbound-control -h` this seems like the right syntax, but when I hit the enter, the console leaves me hanging, and nothing seems to happens before i hit `CTRL + C`

I'm running on Ubuntu 19.04 with Unbound 1.9.4
Compiled with as written here https://gitlab.com/rpz-zones/toolbox/issues/18#configure-options

Could someone please explain whats wrong with the syntax or ? and maybe give me an example of the right syntax for this example.

PS: This could also be a good example to add to the documentation :smiley:

**Comment by bjovereinder** [comment]
Hi,

For these kind of questions, we have an excellent mailing list for and from the Unbound users community.  The registration and archive of the unbound-user mailing list can be found here: https://nlnetlabs.nl/mailman/listinfo/unbound-users

Thanks for your suggestion to include this in the Unbound documentation. :-)

Best,

-- Benno

**Comment by spirillen** [comment]
And for those who actually don't use mails?
