### ISSUE TITLE
Build fails with OpenSSL >= 3.0 built with OPENSSL_NO_DEPRECATED

### ISSUE THREAD

**Issue by hardfalcon** [NLnetLabs/unbound#1091]
Building unbound 1.20.0 fails at the `./configure` stage on systems where OpenSSL >= 3.0 has been built with `OPENSSL_NO_DEPRECATED` enabled. This is caused by `configure.ac` [checking](https://github.com/NLnetLabs/unbound/blob/release-1.20.0/configure.ac#L1183) for the existence of the `ECDSA_sign` and `SHA384_Init` functions, which have been deprecated in OpenSSL 3.0 and newer:

* https://www.openssl.org/docs/man3.0/man3/ECDSA_sign.html
* https://www.openssl.org/docs/man3.0/man3/SHA384_Init.html

On most distros, this bug doesn't occur even with OpenSSL >= 3.0 installed because OpenSSL distro packages are usually not built with `OPENSSL_NO_DEPRECATED` enabled.

**Comment by wcawijngaards** [comment]
Fixed the detection, that was attempting to detect EC support, to use the newer OPENSSL_NO_EC define that can detect EC support. That is used if another newer EVP_PKEY_fromdata function exists. So now it can detect the old support calls, or the newer support setting. Also fixes are a number of deprecated function uses. Thanks for the report!
