### ISSUE TITLE
Ubuntu 22.04 Jammy fails to compile unbound 1.20.0

### ISSUE THREAD

**Issue by spirillen** [NLnetLabs/unbound#1092]
**Describe the bug**

**To reproduce**
1. Download unbound 1.20.0 source code
2. Copy the config line from 1.17 (see below)
3. Getting a complain `configure: error: systemd enabled but libsystemd not found`
4. Installing `libsystemd0` + `libsystemd-dev`
5. Getting same complain, even tried a reboot.
6. removing `--enable-systemd` from the config line, and gets a new error. `configure: error: Cannot find python in your system path`
7. Installing `libpython3.11-dev` + `python3.11-dev`
8. Same error

```cpp
./configure --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --disable-rpath --with-pidfile=/run/unbound.pid --with-rootkey-file=/var/lib/unbound/root.key --with-libevent --with-libnghttp2 --with-pythonmodule --enable-subnet --enable-dnstap --enable-systemd --enable-dnscrypt --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --libdir=/usr/lib
```

**Expected behavior**
Uncertain....

**System:**
 - Unbound version: 1.20.0
 - OS: Ubuntu 22.04
 - `unbound -V` output: N/A

**Additional information**

**Comment by gthess** [comment]
To configure for systemd you would need to install `pkg-config`.
For the Python error you would need to use `PYTHON_VERSION=3.11 ./configure ....` to point to a specific Python interpreter if your system does not have a default one (i.e., /usr/bin/python).

I'll leave this open to see what can be done better in config; I see there should already be a suggestion for pkg-config when enabling systemd but maybe there is a bug somewhere.

**Comment by gthess** [comment]
Fixed the configure script to print more helpful information for both issues.
For Python it would suggest the use of the PYTHON_VERSION environment value.
For systemd it will complain about the absence of pkg-config.

**Comment by spirillen** [comment]
Hi @gthess 
Thanks for your feedback, regarding the comments for how to do this, nay I suggest you to add this to your documentation (compiling). Maybe even ensure that each components requirements? this could make it easier to prepare properly before running the `./configure -arg1 -arg2`

**Comment by gthess** [comment]
Noone is properly prepared for the configure script! :)
I mean that is what the configure script is about; based on the arguments it would tell you if something is missing.
In https://github.com/NLnetLabs/unbound/commit/b67fbb69e75d80e24ec46a5ab9ab9cefb748f122 I added the missing hints for `--enable-systemd` in `./configure --help`.
