### ISSUE TITLE
Problem with unbound config and Microsoft Virtual Adapter

### ISSUE THREAD

**Issue by alejandrogiubel** [NLnetLabs/unbound#110]
I need a light DNS and i found Unboun. It work fine with ethernet adapter, but i need that it work with WiFi adapter (resolve queries from wireless devices). I use a program to create a hotspot to share the connection and Unbound work good when the computer whit Unbound is connected to another computer. If i disconnect the ethernet from the computer whit Unbound, Unbound can't resolve the queries from wireless devices. It only resolve the queries from wireless devices when ethernet is connected and i share the connection on hotspot way. How i can resolve this problem? I want that Unboun resolve queries from Microsoft Virtual Adapter (it is created when i create a hotspot). Thank

**Comment by bjovereinder** [comment]
Hi Alejandro,

Thank you for selecting and using Unbound.  We offer community support for our software via our mailing lists, see https://nlnetlabs.nl/mailman/listinfo/unbound-users.  Other enthusiastic Unbound users are also subscribed to this mailing list and can also provide useful input and answers to your questions.

We use GitHub Issues for bug reports and feature requests.

Best regards,

-- Benno
