### ISSUE TITLE
No Config Files in Current apt Unbound . . . 

### ISSUE THREAD

**Issue by corinthian13** [NLnetLabs/unbound#1100]
Just tried [this tutorial](https://www.linuxbabe.com/ubuntu/set-up-unbound-dns-resolver-on-ubuntu-20-04-server#comment-1041083) on installing Unbound.

Well, the current version from **apt** is 1.13.1 . . . 

**And this version has NO config files or key files in it**.

So **unbound-checkconf** naturally sees this during its config check.

And that is a show-stopper.

Maybe someone out there at NLNetLabs might be interested in this. 

After all, **Unbound** is an NLNetLabs baby . . .

**Comment by bjovereinder** [comment]
After a quick inspection, I see that the Ubuntu Noble distribution (24.04) currently has Unbound package 1.19.2 with the following files in /etc:
/etc/unbound/unbound.conf
/etc/unbound/unbound.conf.d/remote-control.conf
/etc/unbound/unbound.conf.d/root-auto-trust-anchor-file.conf

See https://packages.ubuntu.com/noble/amd64/unbound/filelist

**Comment by corinthian13** [comment]
Ubuntu 24.04 has Unbound bundled in it ?

Well, maybe so. But I'm staying on Ubuntu 22.04 LTS for the immediate future and so is my server. I think I'm taking enough risks at that. 

People used to say that Microsoft released software with limited testing so users would sort out all its bugs.

By NLNetLabs standards, Microsoft is a very well-managed outfit.

**Comment by bjovereinder** [comment]
Of course! Here's the revised text in a friendly tone:

Just to clarify, NLnet Labs is the developer of Unbound, while the Ubuntu packages are maintained and distributed by Ubuntu/Canonical.  We don't have a role in that process.

If you have any questions about the Ubuntu packaging, please feel free to refer to the relevant Ubuntu forums for assistance.

**Comment by bjovereinder** [comment]
Just to clarify, NLnet Labs is the developer of Unbound, while the Ubuntu packages are maintained and distributed by Ubuntu/Canonical. We don't have a role in that process.

If you have any questions about the Ubuntu packaging, please feel free to refer to the relevant Ubuntu forums for assistance.

**Comment by corinthian13** [comment]
_Just to clarify, NLnet Labs is the developer of **Unbound**, while the Ubuntu packages are maintained and distributed by Ubuntu/Canonical. We don't have a role in that process._

That is true.

Of course it's also true that the integrity of repositaries for **Unbound** on common package managers (including apt) _should_ be of more than a passing interest to NLNet. 

After all, evaluation and adoption of network-streamlining packages like Unbound by PC users across the globe is what the NLNet organization says it strives to do . . .

**Comment by bjovereinder** [comment]
We have very good relationships with the people who package software for Debian/Ubuntu/Redhat/Fedora/... and they do a fantastic job.  So no worries.  

The Unbound package for 22.04 LTS also includes the following files, which you can check for yourself at https://packages.ubuntu.com/jammy/amd64/unbound/filelist:
/etc/unbound/unbound.conf
/etc/unbound/unbound.conf.d/root-auto-trust-anchor-file.conf

**Comment by corinthian13** [comment]
I have just tried a reinstall via

`~ $ sudo apt install unbound`


Going to /etc/unbound I find this listing:

```
/etc/unbound $ ls -la
total 36
drwxr-xr-x   3 root root  4096 Jul  9 14:37 .
drwxr-xr-x 124 root root 12288 Jul  9 14:37 ..
drwxr-xr-x   2 root root  4096 Jul  9 14:37 unbound.conf.d
-rw-------   1 root root  2484 Jul  9 14:37 unbound_control.key
-rw-r-----   1 root root  1501 Jul  9 14:37 unbound_control.pem
-rw-------   1 root root  2484 Jul  9 14:37 unbound_server.key
-rw-r-----   1 root root  1549 Jul  9 14:37 unbound_server.pem
```

Going into /etc/unbound/unbound.conf.d directory we list all its contents:

```
/etc/unbound/unbound.conf.d$ ls -la
total 8
drwxr-xr-x 2 root root 4096 Jul  9 14:37 .
drwxr-xr-x 3 root root 4096 Jul  9 14:37 ..
```

In other words - while we have improved insofar as we have some key files we didn't have yesterday - we still do not have a .conf file anywhere in the Unbound apt repository.

Please check this for yourself, Mr Overeinder.

The present apt Unbound version is 1.13.1. Maybe NLNet no longer maintains it.

Since the [current Unbound version](https://www.nlnetlabs.nl/projects/unbound/about/) is 1.20.0, it might be time to request a newer version of Unbound on apt . . . I think that this new version should be carefully checked first of course.

You say that your organization has excellent relationships with staff at the main package manager organizations, i.e. RPM, apt, flatpak, snap, etc. That could be  reality. But even if it is so, it doesn't mean that people at NLNet or at apt are doing their maintenance work properly.

**Comment by bjovereinder** [comment]
Again, you seem to be confusing our role as software developers with that of Linux distribution packagers.  If you have an issue with your Ubuntu installation, please consult the Ubuntu forums for support, etc., etc.

I installed Unbound on Ubuntu 22.04 LTS and found the following files in /etc/unbound:

```
ls -l /etc/unbound/
total 24
-rw-r--r-- 1 root root  341 Sep  7  2022 unbound.conf
drwxr-xr-x 2 root root 4096 Jul  9 16:41 unbound.conf.d
-rw------- 1 root root 2484 Jul  9 16:41 unbound_control.key
-rw-r----- 1 root root 1501 Jul  9 16:41 unbound_control.pem
-rw------- 1 root root 2484 Jul  9 16:41 unbound_server.key
-rw-r----- 1 root root 1549 Jul  9 16:41 unbound_server.pem
```
The package appears to be correctly installed.

Your assertions that we or Ubuntu are not doing our job properly are unfounded.  Additionally, I ask that you review our Code of Conduct and use a more respectful tone in your communications: https://www.nlnetlabs.nl/conduct/.
