### ISSUE TITLE
Can I have two forward addresses?

### ISSUE THREAD

**Issue by Aura67** [NLnetLabs/unbound#1117]
Hello, I'm wondering if you can add two forward addresses. I've found two servers that only support donations and don't save requests or collect any data. I think it works because I haven't had any errors in Unbound so far, but I wanted to ask again.

I imagined it like this: 

forward-zone:
    name: "."
    forward-tls-upstream: yes
    forward-first: no
    forward-no-cache: no
    forward-addr: 9.9.9.11@853#dns11.quad9.net
    forward-addr: 149.112.112.11@853#dns11.quad9.net
    forward-addr: 9.9.9.9@853#dns.quad9.net
    forward-addr: 149.112.112.112@853#dns.quad9.net
    forward-addr: 185.95.218.42@853#dns.digitale-gesellschaft.ch
    forward-addr: 185.95.218.43@853#dns.digitale-gesellschaft.ch

**Comment by wcawijngaards** [comment]
Yes, it is possible to list a number of addresses for forward-addr, also stub-addr, forward-host and stub-host. They are attempted with randomisation, and fallback to the other servers if there is trouble.
