### ISSUE TITLE
Unbound returns "error: memory exhausted" with include directive on large file with version 1.21.0

### ISSUE THREAD

**Issue by simonpie** [NLnetLabs/unbound#1129]
**Describe the bug**
Starting with version 1.21.0, when loading unbound and using include directive to load a large file with lots of NXDOMAIN (244 859 entries), unbound gives a memory exhausted error and does not load on freebsd 13.3-p5.

**To reproduce**
1. add include directive to file with lots (over 244000) of entries like this  "local-zone: "vip.xvpn.io" always_nxdomain"
2. try to start unbound with service start unbound

**Expected behavior**
Unbound should start ( as it did before with version 1.20.0_1 )

**System:**
 - Unbound version: 1.21.0
 - OS: freebsd 13.3-p5
 - unbound -V` output:  

 ```
> unbound -V
Version 1.21.0

Configure line: --with-libexpat=/usr/local --with-ssl=/usr --enable-dnscrypt --disable-dnstap --with-libnghttp2 --with-dynlibmodule --enable-ecdsa --disable-event-api --enable-gost --with-libevent --disable-subnet --disable-tfo-client --disable-tfo-server --with-pthreads --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/share/man --infodir=/usr/local/share/info/ --build=amd64-portbld-freebsd13.3
Linked libs: libevent 2.1.12-stable (it uses kqueue), OpenSSL 1.1.1w-freebsd  11 Sep 2023
Linked modules: dns64 dynlib respip validator iterator
DNSCrypt feature available

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Additional information**
The behaviour appeared right after updating package from 1.20..0_1 ( still on 13.3-p5 ).  
Here is the output when restarting package and including file :

```
> sudo service unbound start     
/usr/local/etc/unbound/monblocker.conf:12163: error: memory exhausted
read /usr/local/etc/unbound/unbound.conf failed: 1 errors in configuration file
Obtaining a trust anchor...
/usr/local/etc/unbound/monblocker.conf:12163: error: memory exhausted
read /usr/local/etc/unbound/unbound.conf failed: 1 errors in configuration file
/usr/local/etc/rc.d/unbound: WARNING: failed precmd routine for unbound
```

And of course monblocker.conf is the included large file.
If I use a sharp sign (#) to comment out the include directive, unbound starts just fine. 

If I use just a couple of lines out of the 24000, the include directive works just fine and  unbound loads and returns NXDOMAIN for the few remaining domains.

**Comment by wcawijngaards** [comment]
Is this the same issue as #1127 ? It sounds like it could be. Perhaps the bug fix for that issue also fixed this issue here?

**Comment by simonpie** [comment]
Yes exactly. Sorry, I though I search for "memory exhausted" before posting.  What is the optimal way of closing this issue now ?

**Comment by wcawijngaards** [comment]
Okay, nice that it fixes this problem too.

**Comment by simonpie** [comment]
Well, I can't vouch for that yet.  But bug reports seems  to refer to the same issue.

**Comment by wcawijngaards** [comment]
If it does not fix the issue, this can be reopened. It would be nice to have the config that fails then; like a short version of the main config file and the include described with a sample line, because that would apparently then be a different config bug.

**Comment by simonpie** [comment]
Here are the three files needed to load my config.  Hopefully, `unbound.conf` is cleaned up correctly.



[Archive.zip](https://github.com/user-attachments/files/16751703/Archive.zip)

**Comment by wcawijngaards** [comment]
With the archive, I have verified that the fix works. Without the fix, with version 1.21.0, it gives the error like in the issue post, `monblocker.conf:12163: error: memory exhausted`. With the fix, there is no error. So the issue is already fixed by the other bug fix.

**Comment by simonpie** [comment]
Thank you very much.

**Comment by simonpie** [comment]
I am sorry to bring this back, but when can we expect the fix to be released ?
