### ISSUE TITLE
ubuntu 18.04 can only get version 1.6.7 from PPA

### ISSUE THREAD

**Issue by bruvv** [NLnetLabs/unbound#114]
How come that The Focal Fossa build from Ubuntu (20.04!) only has v1.9.4?
Source:
https://launchpad.net/ubuntu/+source/unbound

**Comment by gthess** [comment]
You could ask there. I suspect because 1.9.4 has a security fix and earlier versions are vulnerable. 1.9.5 also has a security fix but it is unlikely that the compiled version that comes with ubuntu is shipped with support for the ipsec module that enables that vulnerability.
