### ISSUE TITLE
:) forgive me

### ISSUE THREAD

**Issue by isnotevilikeu** [NLnetLabs/unbound#115]
I need help i havent done this before and i dont want to mess it up. Ive been plagued by this for over three years. Ty!

**Comment by gthess** [comment]
Hello,

Thank you for selecting and using Unbound. We offer community support for our software via our mailing lists, see https://nlnetlabs.nl/mailman/listinfo/unbound-users. Other enthusiastic Unbound users are also subscribed to this mailing list and can also provide useful input and answers to your questions.

We use GitHub Issues for bug reports and feature requests.

Best regards,

-- George
