### ISSUE TITLE
No libssp-0.dll in 1.21.1 Win x64 binaries archive

### ISSUE THREAD

**Issue by SilmorSenedlen** [NLnetLabs/unbound#1150]
Good day
I found that there is no libssp-0.dll in [Win x64 binaries archive](https://www.nlnetlabs.nl/downloads/unbound/unbound-1.21.1.zip) in latest version (1.21.1).
In [32-bit variant](https://www.nlnetlabs.nl/downloads/unbound/unbound-1.21.1-w32.zip) -  libssp-0.dll  exist.

I suppose it's a mistake?

**Comment by gthess** [comment]
Hi,
Thanks for contacting us.
Including libssp-0.dll in the windows builds is part of the script. Not sure why it wasn't included. I see that a new x64 build does include it:
- https://nlnetlabs.nl/~yorgos/unbound-1.21.1_20241004.zip
- https://nlnetlabs.nl/~yorgos/unbound-1.21.1_20241004.zip.asc
- https://nlnetlabs.nl/~yorgos/unbound-1.21.1_20241004.zip.sha1
- https://nlnetlabs.nl/~yorgos/unbound-1.21.1_20241004.zip.sha256
- https://nlnetlabs.nl/~yorgos/unbound_setup_1.21.1_20241004.exe
- https://nlnetlabs.nl/~yorgos/unbound_setup_1.21.1_20241004.exe.asc
- https://nlnetlabs.nl/~yorgos/unbound_setup_1.21.1_20241004.exe.sha1
- https://nlnetlabs.nl/~yorgos/unbound_setup_1.21.1_20241004.exe.sha256

Can you verify?

**Comment by SilmorSenedlen** [comment]
Good day
Yeah, now all right.
Thx!
