### ISSUE TITLE
Docs: Improve manpage about "default" chroot

### ISSUE THREAD

**Issue by melroy89** [NLnetLabs/unbound#1164]
**Current behavior**

Man page is saying: `By default chroot is enabled and the default is "".`

See my comment here: https://github.com/NLnetLabs/unbound/commit/1d315e11cf267241cbd8a9eb530fd98432ab171d#r148392042

**Describe the desired feature**

We most likely need to rephrase this sentence, since under some distributions like Ubuntu and Fedora, chroot is actually disabled by default. Making this sentence a contradictory.

**Comment by sunbearc22** [comment]
The meaning of this sentence `By default chroot is enabled and the default is "".`  seems vague as it does not explain what does the symbol "" means or do? This sentence could continue by stating: "For example, Ubuntu and Fedora would ..... while xxx, yyy, zzz would ....."

**Comment by melroy89** [comment]
Well, the full sentence is: "If given a chroot is done to the given directory. By default chroot is
enabled and the default is "@UNBOUND_CHROOT_DIR@". If you give "" no
chroot is performed." See again: https://github.com/NLnetLabs/unbound/blob/f5580f0a6390a0acc545191fce6f147171b6e76b/doc/unbound.conf.5.in#L905

Since on some distributions `@UNBOUND_CHROOT_DIR@`, is a variable, that is set to: `""` under several distributions like Ubuntu and Fedora, chroot will be disabled by default. 

So yes, this sentence needs to be rephrased.

**Comment by melroy89** [comment]
Anyhow, I created a PR: https://github.com/NLnetLabs/unbound/pull/1170
