### ISSUE TITLE
2 ip for 1 name

### ISSUE THREAD

**Issue by Eremiteb** [NLnetLabs/unbound#117]
Hello! I am create local zone and I want 2 ip addresses to be returned for requests.
here is an example of my zone

local-zone: "korem.kz." static
local-data: "korem.kz. 86400 IN NS ns1.korem.kz."
local-data: "korem.kz. 86400 IN SOA korem.kz. ns1.korem.kz. 3 3600 1200 604800 86400"
local-data: "korem.kz. 86400 IN A 95.59.143.254"
local-data: "korem.kz. 86400 IN A 95.141.137.37"
local-data: "vie.korem.kz. 86400 IN A 95.59.143.254"
local-data: "vie.korem.kz. 86400 IN A 95.141.137.37"
local-data: "vie-trade.korem.kz. 86400 IN A 95.59.143.254"
local-data: "vie-trade.korem.kz. 86400 IN A 95.141.137.37"
local-data: "trade.korem.kz. 86400 IN A 95.59.143.254"
local-data: "trade.korem.kz. 86400 IN A 95.141.137.37"

But for an nslookup  request, 2 IP addresses are returned only for the name trade.korem.kz.

C:\Windows\System32>nslookup trade.korem.kz 95.56.242.108
╤хЁтхЁ:  UnKnown
Address:  95.56.242.108

Не заслуживающий доверия ответ:
╚ь :     trade.korem.kz
Addresses:  95.141.137.37
          95.59.143.254

and at the request of other names returns only one ip-address

C:\Windows\System32>nslookup vie-trade.korem.kz 95.56.242.108
╤хЁтхЁ:  UnKnown
Address:  95.56.242.108

Не заслуживающий доверия ответ:
╚ь :     vie-trade.korem.kz
Address:  95.59.143.254

What's my mistake?

**Comment by gthess** [comment]
I don't see a mistake and your local-* configuration above seems to work fine here:
```
$ dig @localhost trade.korem.kz

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @localhost trade.korem.kz
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 26823
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;trade.korem.kz.			IN	A

;; ANSWER SECTION:
trade.korem.kz.		86400	IN	A	95.59.143.254
trade.korem.kz.		86400	IN	A	95.141.137.37

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Nov 25 12:13:57 CET 2019
;; MSG SIZE  rcvd: 75
```
```
$ dig @localhost vie-trade.korem.kz

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @localhost vie-trade.korem.kz
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 55725
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;vie-trade.korem.kz.		IN	A

;; ANSWER SECTION:
vie-trade.korem.kz.	86400	IN	A	95.59.143.254
vie-trade.korem.kz.	86400	IN	A	95.141.137.37

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Mon Nov 25 12:14:05 CET 2019
;; MSG SIZE  rcvd: 79
```

These are on a linux machine however.
Can you provide the unbound version you are using? Also is unbound running on the same windows machine I see above?

**Comment by Eremiteb** [comment]
Нou are right, now everything worked. I close the issue, thanks
