### ISSUE TITLE
the data being used is released in method nsec3_hash_test_entry

### ISSUE THREAD

**Issue by wenxuan70** [NLnetLabs/unbound#1183]
**Describe the bug**
In nsec3_hash_test_entry, the nsec3 variable is allocated through alloc and released through reply_info_parsedelete before the method returns. However, it will be inserted into the rbtree in the nsec3_hash_name method, causing the freed memory to be used in nsec3_hash_cmp later.

https://github.com/NLnetLabs/unbound/blob/733d5f7161c5675e66e39974b912a08eeb48140c/testcode/unitverify.c#L421-L461

**To reproduce**
1. Execute unittest command

**Expected behavior**

**System:**
 - Unbound version: 1.17.1
 - OS:
 - `unbound -V` 
```shell
output: Version 1.17.1
Configure line: LIBS=-ljemalloc --enable-subnet --with-libevent --with-pthreads --with-ssl
Linked libs: libevent 2.1.8-stable (it uses epoll), OpenSSL 1.1.1k  FIPS 25 Mar 2021
Linked modules: dns64 subnetcache respip validator iterator
```

**Additional information**
Add any other information that you may have gathered about the issue here.

**Comment by wcawijngaards** [comment]
The fix should keep the hash tree for the test file, and release the data when the test file is finished with the test. That should fix the deleted memory referenced by the tree. Thank you for reporting the release of data that is still in use.
