### ISSUE TITLE
Unbound - Ubuntu 24.04.1 LTS - unbound-checkconf - error: trust anchor presented twice

### ISSUE THREAD

**Issue by afroissard** [NLnetLabs/unbound#1184]
Hi there, I'm quite new to Unbound and I want to make sure I'm doing things right.
I followed the official documentation for Resolver for Home Networks.
Everything is well explained and pretty much straight forward.

When it was time to setting up for the rest of the network, I added the "minimal usable configuration" in /etc/unbound/unbound.conf.
It looked like this :

include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"
server:
    # location of the trust anchor file that enables DNSSEC
    auto-trust-anchor-file: "/var/lib/unbound/root.key"
    # send minimal amount of information to upstream servers to enhance privacy
    qname-minimisation: yes
    # the interface that is used to connect to the network (this will listen to all interfaces)
    interface: 0.0.0.0
    # interface: ::0
    # addresses from the IP range that are allowed to connect to the resolver
    access-control: 192.168.1.0/24 allow
    # access-control: 2001:DB8/64 allow

remote-control:
    # allows controling unbound using "unbound-control"
    control-enable: yes

Then I ran unbound-checkconf unbound.conf and I got this :

afroissard@ubuntu-server:/etc/unbound$ unbound-checkconf unbound.conf
[1731665412] unbound-checkconf[1256:0] error: trust anchor presented twice
[1731665412] unbound-checkconf[1256:0] error: could not parse auto-trust-anchor-file /var/lib/unbound/root.key line 2
[1731665412] unbound-checkconf[1256:0] error: error reading auto-trust-anchor-file: /var/lib/unbound/root.key
[1731665412] unbound-checkconf[1256:0] error: validator: error in trustanchors config
[1731665412] unbound-checkconf[1256:0] error: validator: could not apply configuration settings.
[1731665412] unbound-checkconf[1256:0] fatal error: bad config for validator module
afroissard@ubuntu-server:/etc/unbound$

The error message was related to the trust anchor so I decided to edit the unbound.conf file and replace its content with the default values :

afroissard@ubuntu-server:/etc/unbound$ more unbound.conf
Unbound configuration file for Debian.
See the unbound.conf(5) man page.
See /usr/share/doc/unbound/examples/unbound.conf for a commented reference config file.
The following line includes additional configuration files from the
/etc/unbound/unbound.conf.d directory.
include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"
afroissard@ubuntu-server:/etc/unbound$

In the unbound.conf.d directory there's a root-auto-trust-anchor-file.conf file and I guess that's why I had the "error: trust anchor presented twice" when I ran the unbound-checkconf unbound.conf.
Is that correct ?

From my understanding, what happens when the unbound.conf is read (include-toplevel: "/etc/unbound/unbound.conf.d/*.conf"), it will take into consideration ALL the .conf files located in /etc/unbound/unbound.conf.d to build the global configuration.
Is that correct ?

Following my assumptions I created a new CONF files ("my-custom-unbound.conf") in the /etc/unbound/unbound.conf.d directory.
As this directory already contains something related to the trust anchor, I removed the lines mentioning it in my new config file.
It looks like this :

afroissard@ubuntu-server:/etc/unbound/unbound.conf.d$ more my-custom-unbound.conf
server:
    # send minimal amount of information to upstream servers to enhance privacy
    qname-minimisation: yes
    # the interface that is used to connect to the network (this will listen to all interfaces)
    interface: 0.0.0.0
    # interface: ::0
    # addresses from the IP range that are allowed to connect to the resolver
    access-control: 192.168.1.0/24 allow
    # access-control: 2001:DB8/64 allow

remote-control:
    # allows controling unbound using "unbound-control"
    control-enable: yes
afroissard@ubuntu-server:/etc/unbound/unbound.conf.d$

Everything works like a charm I just want to make sure I've done things right ?

Thank you in advance for confirming everything's ok or to put me in the right direction if something I've done is wrong.

Thank you !

**Comment by gthess** [comment]
Hi, you nailed it!
One last tip is that if you include files based on patterns (as is the case with the default ubuntu configuration where you include all the files in a given directory) and you care about the order of configuration (e.g., when you configure RPZ zones that are order sensitive), you would need to name your files accordingly so that they are included in the desired order. This is usually done by prepending numbers to the filenames.

**Comment by afroissard** [comment]
Thank you very much for coming back to me.
For the moment I will keep it simple without any RPZ zones.
I just wanted to configure a DNS server in a simple way to protect my privacy - my ISP or Google or Cloudflare or Quad9 don't need to know what I browse on the web.
