### ISSUE TITLE
When the domain name length is 255, the dname_str method will cause the last label in the converted string to be lost.

### ISSUE THREAD

**Issue by wenxuan70** [NLnetLabs/unbound#1188]
**Describe the bug**
When the length of the domain name in wire format is 255, the `dname_str` method will cause the last label to be missing in the converted string.
For example, I use the dig command to initiate a request for `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ012345678` domain name to the unbound process, but the unbound.log log file records the string `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.&`.
However, the length of a domain name of 255 is in compliance with the RFC specification. Even the length of the converted string is 254 (excluding the last '\0' character)

https://github.com/NLnetLabs/unbound/blob/9e3c50ec9e0f6a84d2d62e9ff9f2a7c4308a752f/util/data/dname.c#L657-L661

**To reproduce**
1. Execute dig command
<img width="1480" alt="image" src="https://github.com/user-attachments/assets/a12ba4b7-847f-4629-b1c3-598a11c7ad61">

**Expected behavior**
When I want the unbound process to initiate a request for `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ012345678` domain name, the unbound.log log file should completely record the domain name `abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ01234567890.abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ012345678`.

**System:**
 - Unbound version: 1.17.1
 - OS:
 - `unbound -V` output:
 ```
 output: Version 1.17.1
Configure line: LIBS=-ljemalloc --enable-subnet --with-libevent --with-pthreads --with-ssl
Linked libs: libevent 2.1.8-stable (it uses epoll), OpenSSL 1.1.1k  FIPS 25 Mar 2021
Linked modules: dns64 subnetcache respip validator iterator
```

**Additional information**
Add any other information that you may have gathered about the issue here.

**Comment by gthess** [comment]
This was indeed a bug that would not allow a 255-length domain to be printed in logs. Thanks for also providing a fix!
