### ISSUE TITLE
Failing DNS queries when using unbound after it has been just started?

### ISSUE THREAD

**Issue by johanneskastl** [NLnetLabs/unbound#1194]
**Describe the bug**

First off, I am not sure if this is a bug or if I am missing something here. But I found no other issues that sounded similar (but the search terms are too generic, I fear).

I am currently using a vagrant setup that spins up a VM, installs and starts unbound and then tries to install further packages.

https://github.com/johanneskastl/unbound_vagrant_libvirt_ansible/tree/20241128_debugging

**To reproduce**

This is what a `vagrant up` will do, using vagrant and Ansible:

1. Start the VM
2. Install and start unbound
3. Use 127.0.0.1 in `resolv.conf`
4. Try to install packages
5. Error due to `host download.opensuse.org cannot be resolved`

All of that is handled "in one go" using Ansible, so the playbooks for the unbound installation and the package installation are run directly after one another.

Using 127.0.0.1 in `resolv.conf` leads to errors during the package installation, which seem to vanish after some time or some more requests.

I added a 1 minute pause after starting unbound, but the error persists. Seems like something is happening once the first queries are being received.

I also tried the workaround from #509, i.e. disabling the anchor-update as part of the service start.
As you can see from the [playbook](https://github.com/johanneskastl/unbound_vagrant_libvirt_ansible/blob/20241128_debugging/ansible/playbook-all_nodes-configure_and_start_unbound.yml#L23) I also added tasks that does the anchor update manually.

Is there something that I can do to make sure unbound is fully up and running, other than checking that the systemd service is running? Apparently this is not enough of an indicator to make sure DNS queries are working...

Or there is some other interference that I am not aware of?

This is the systemd unit file used by openSUSE (I also use one without the `ExecStartPre` for the anchor update):

```
[Unit]
Description=Unbound recursive Domain Name Server
After=syslog.target network.target
After=unbound-keygen.service
Wants=unbound-keygen.service
Wants=unbound-anchor.timer
Before=nss-lookup.target
Wants=nss-lookup.target

[Service]
Type=simple
User=unbound
Group=unbound
EnvironmentFile=-/etc/sysconfig/unbound
#ExecStartPre=/sbin/runuser --shell /bin/sh -c "/usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -c /etc/unbound/icannbundle.pem" unbound
ExecStartPre=/usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -c /etc/unbound/icannbundle.pem
ExecStartPre=/usr/sbin/unbound-checkconf
ExecStart=!/usr/sbin/unbound -d $UNBOUND_OPTIONS

[Install]
WantedBy=multi-user.target

```

**Expected behavior**
DNS queries should be working.

**System:**
 - Unbound version: unbound-1.22.0-1.1.x86_64
 - OS: openSUSE Tumbleweed
 - `unbound -V` output:
 
```
Version 1.22.0

Configure line: --host=x86_64-suse-linux --build=x86_64-suse-linux --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib/ --mandir=/usr/share/man --infodir=/usr/share/info --disable-rpath --with-libevent --with-pthreads --disable-static --with-ldns=/usr --with-libnghttp2 --enable-sha2 --enable-gost --enable-ecdsa --enable-event-api --enable-pie --enable-relro-now --enable-dnscrypt --enable-dnstap --with-conf-file=/etc/unbound/unbound.conf --with-pidfile=/run/unbound/unbound.pid --with-pythonmodule --with-pyunbound PYTHON=/usr/bin/python3 --with-rootkey-file=/var/lib//unbound/root.key --disable-explicit-port-randomisation
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 3.2.3 3 Sep 2024
Linked modules: dns64 python respip validator iterator
DNSCrypt feature available

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

```

Thanks in advance!

Kind Regards,
Johannes

**Comment by johanneskastl** [comment]
Forgot to add, that the journal for unbound does not contain anything useful.

```
Nov 28 10:32:00 unbound systemd[1]: Starting Unbound recursive Domain Name Server...
Nov 28 10:32:00 unbound unbound-checkconf[6655]: unbound-checkconf: no errors in /etc/unbound/unbound.conf
Nov 28 10:32:00 unbound systemd[1]: Started Unbound recursive Domain Name Server.
Nov 28 10:32:00 unbound unbound[6657]: [6657:0] notice: init module 0: validator
Nov 28 10:32:00 unbound unbound[6657]: [6657:0] notice: init module 1: iterator
Nov 28 10:32:00 unbound unbound[6657]: [6657:0] info: start of service (unbound 1.22.0).
```

**Comment by gthess** [comment]
From a quick look I see that this is the system packaged Unbound, so no fancy custom compilation/installation steps.
I would start by increasing the verbosity and trying to ask Unbound directly using `dig` for example. If Unbound receives the query and something is wrong you will see it in the log.
Otherwise maybe you need to configure something more in your openSUSE system to make it use Unbound for system resolution. I have no experience with openSUSE though :(

**Comment by johanneskastl** [comment]
Thanks for the fast reply. I'll try to debug further.

> Otherwise maybe you need to configure something more in your openSUSE system to make it use Unbound for system resolution. I have no experience with openSUSE though :(

As it seems to work fine after 20s, I doubt there is anything to configure apart from resolv.conf.

**Comment by johanneskastl** [comment]
Using dig you can see at which point the server is reachable and at which point it does no longer spit out `SERVFAIL`.

I was running the command below in one terminal and then started the unbound service in another one.

```
$ while true;do dig @127.0.0.1 suse.com;sleep 1;done
[...]
; <<>> DiG 9.20.3 <<>> @127.0.0.1 suse.com                                                                                                                                                                                                                   
; (1 server found)                                                                                                                                                                                                                                           
;; global options: +cmd                                                                                                                                                                                                                                      
;; no servers could be reached                                                                                                                                                                                                                               
;; communications error to 127.0.0.1#53: connection refused                                                                                                                                                                                                  
;; communications error to 127.0.0.1#53: connection refused                                                                                                                                                                                                  
;; communications error to 127.0.0.1#53: connection refused                                                                                                                                                                                                  
                                                                                                                                                                                                                                                             
; <<>> DiG 9.20.3 <<>> @127.0.0.1 suse.com                                                                                                                                                                                                                   
; (1 server found)                                                                                                                                                                                                                                           
;; global options: +cmd                                                                                                                                                                                                                                      
;; no servers could be reached                                                                                                                                                                                                                               
;; communications error to 127.0.0.1#53: connection refused
;; communications error to 127.0.0.1#53: connection refused                                                                   
;; communications error to 127.0.0.1#53: connection refused    
                                                                                                                              
; <<>> DiG 9.20.3 <<>> @127.0.0.1 suse.com                     
; (1 server found)                                         
;; global options: +cmd                                        
;; no servers could be reached                                                                                                
                                                               
; <<>> DiG 9.20.3 <<>> @127.0.0.1 suse.com                     
; (1 server found)                                             
;; global options: +cmd                                        
;; Got answer:                                             
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 20478 
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1
                                                               
;; OPT PSEUDOSECTION:                                      
; EDNS: version: 0, flags:; udp: 1232                      
;; QUESTION SECTION:                                           
;suse.com.                      IN      A                      
                                                               
;; Query time: 166 msec                                                                                                       
;; SERVER: 127.0.0.1#53(127.0.0.1) (UDP)                       
;; WHEN: Fri Nov 29 17:05:38 CET 2024                          
;; MSG SIZE  rcvd: 37                                      
                                                                       
```

All in all, I got 6 SERVFAIL answers before the proper result was returned.

The debug log is rather lengthy, but would I noticed is that there are multiple instances of this:

```
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] info: sending query: gtld-servers.net. A IN
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] debug: sending to target: <net.> 192.12.94.30#53
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] debug: iterator[module 1] operate: extstate:module_state_initial event:module_event_pass
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] info: iterator operate: query e.gtld-servers.net. A IN
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] info: resolving e.gtld-servers.net. A IN
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] info: resolving (init part 2):  e.gtld-servers.net. A IN
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] info: resolving (init part 3):  e.gtld-servers.net. A IN
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] info: processQueryTargets: e.gtld-servers.net. A IN
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] debug: removing 1 labels
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] debug: request e.gtld-servers.net. has exceeded the maximum global quota on number of upstream queries 129
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] debug: return error response SERVFAIL
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] debug: validator[module 0] operate: extstate:module_state_initial event:module_event_moddone
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] info: validator operate: query e.gtld-servers.net. A IN
Nov 29 17:05:38 unbound unbound[6754]: [6754:1] debug: iterator[module 1] operate: extstate:module_state_initial event:module_event_pass
```

This mentions a `SERVFAIL`. And says `request e.gtld-servers.net. has exceeded the maximum global quota on number of upstream queries 129`

The `129` is the first number, after that is goes on with requests for `f.gtkd.servers.net.` etc. and counts up to 162.
(The first mention of `suse.com`, which I queried, is at 154).

I can send the full log, if desired?

**Comment by gthess** [comment]
Please send it over email. You can find my email address at https://nlnetlabs.nl/people.

From the maximum quota limit I assume that something hinders Unbound outbound communication, keeps retrying and  hits the limit. Unbound will eventually record upstream information and fill the cache and would be able to reply to further queries.

If IPv4 or IPv6 has issues in your location you can use the [prefer-ip4](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-prefer-ip4) and [prefer-ip6](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-prefer-ip6). Or turn them off altogether with [do-ip4](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-do-ip4) and [do-ip6](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-do-ip6).

**Comment by johanneskastl** [comment]
Aaaah, that was the missing piece. Turning off IPv6 and enabling IPv4 solves the issue. Now as soon as unbound is reachable, the answers are given and DNS queries are working.

Thanks for your help!

(I am not sure if it is possible to make unbound "smarter" in such an environment, and if it is worth the effort for 15s of non-working queries. If it is possible, I would welcome such an improvement. Please feel free to close this issue)

**Comment by gthess** [comment]
Glad it helped, so closing the issue.

---

Not sure if that could be made reliable with live changing network environments, so better to be explicit in your configuration.
In your case, what was the original configuration and what did you change it into?
Do you experience IPv6 networking errors frequently or do you not have support for it altogether?
