### ISSUE TITLE
Multiple unbound processes spawned when one unbound process is expected.

### ISSUE THREAD

**Issue by sunbearc22** [NLnetLabs/unbound#1200]
Why are multiple `unbound` processes spawned when I run the command:

    $ sudo unbound -vvv -c /usr/local/etc/unbound/unbound.conf
    [1733378263] unbound[8060:0] notice: Start of unbound 1.22.0.
    Dec 05 13:57:43 unbound[8060:0] debug: creating udp4 socket 0.0.0.0 3000
    Dec 05 13:57:43 unbound[8060:0] debug: creating tcp4 socket 0.0.0.0 3000
    Dec 05 13:57:43 unbound[8060:0] debug: creating udp4 socket 0.0.0.0 3000
    Dec 05 13:57:43 unbound[8060:0] debug: creating tcp4 socket 0.0.0.0 3000
    Dec 05 13:57:43 unbound[8060:0] debug: creating udp4 socket 0.0.0.0 3000
    Dec 05 13:57:43 unbound[8060:0] debug: creating tcp4 socket 0.0.0.0 3000
    Dec 05 13:57:43 unbound[8060:0] debug: creating udp4 socket 0.0.0.0 3000
    Dec 05 13:57:43 unbound[8060:0] debug: creating tcp4 socket 0.0.0.0 3000
    Dec 05 13:57:43 unbound[8060:0] debug: creating tcp4 socket 0.0.0.0 8953 unbound-control
    Dec 05 13:57:43 unbound[8060:0] debug: module config: "validator iterator"
    Dec 05 13:57:44 unbound[8060:0] debug: chdir to /usr/local/etc/unbound
    Dec 05 13:57:44 unbound[8060:0] debug: chroot to /usr/local/etc/unbound
    Dec 05 13:57:44 unbound[8060:0] debug: drop user privileges, run as unbound
    Dec 05 13:57:44 unbound[8060:0] debug: switching log to unbound.log
    ^Z
    [1]+  Stopped                 sudo unbound -vvv -c /usr/local/etc/unbound/unbound.conf
    $ bg
    [1]+ sudo unbound -vvv -c /usr/local/etc/unbound/unbound.conf &
    $ ps -ef | grep unbound
    admin     7973  1787  0 13:01 pts/1    00:00:00 tail -f /usr/local/etc/unbound/unbound.log
    root      8058  1219  0 13:57 pts/0    00:00:00 sudo unbound -vvv -c /usr/local/etc/unbound/unbound.conf
    root      8059  8058  0 13:57 pts/2    00:00:00 sudo unbound -vvv -c /usr/local/etc/unbound/unbound.conf
    unbound   8060  8059  3 13:57 pts/2    00:00:00 unbound -vvv -c /usr/local/etc/unbound/unbound.conf
    admin     8065  1219 33 13:58 pts/0    00:00:00 grep unbound
    root     31522     2  0 02:09 ?        00:00:01 [kworker/u8:1-events_unbound]
    $ sudo unbound -V
    Version 1.22.0
    
    Configure line:
    Linked libs: mini-event internal (it uses select), OpenSSL 3.0.15 3 Sep 2024
    Linked modules: dns64 respip validator iterator

I was only expecting one `unbound` process to be started. Is something wrong here? How to fix this issue.

Also, I noticed that two of the three `unbound` processes are spawned by `root` while one of them is by `unbound`. The `unbound.conf` file did not declare the `chroot:`, `username:`, `directory:` and `pidfile:` server options, i.e. `unbound` default values for these options are used. I have experimented declaring

    username:  "" 

and that resulted in `root` spawning the three `unbound` processes. Still why 3 processes and not four processes since the CPU has four cores? Pls help me understand what is happening. Thank you.

The CPU:

    $ lscpu
    Architecture:             armv7l
      Byte Order:             Little Endian
    CPU(s):                   4
      On-line CPU(s) list:    0-3
    Vendor ID:                ARM
      Model name:             Cortex-A7
        Model:                5
        Thread(s) per core:   1
        Core(s) per socket:   4
        Socket(s):            1
        Stepping:             r0p5
        CPU(s) scaling MHz:   37%
        CPU max MHz:          1296.0000
        CPU min MHz:          480.0000
        BogoMIPS:             48.00
        Flags:                half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm

The latest version of Unbound was downloaded and I did `./configure`, `make` and `sudo make install` to install `unbound`.

**Comment by gthess** [comment]
This is how sudo(8) works. It needs to fork(2) and execve(2). You can read about it in the sudo(8) manpage in the "Process model" section. Online link: https://www.man7.org/linux/man-pages/man8/sudo.8.html#COMMAND_EXECUTION.
This has nothing to do with your available cores or how Unbound is configured.
