### ISSUE TITLE
tcp-idle-timeout effectively disabled after initial query/response

### ISSUE THREAD

**Issue by he32** [NLnetLabs/unbound#125]
Hi,

as observed in 

https://nlnetlabs.nl/pipermail/unbound-users/2019-August/011748.html
and
https://nlnetlabs.nl/pipermail/unbound-users/2019-November/011904.html

unbound appears to have issues with the `tcp-idle-timeout` handling; it does
not appear to work the way one would reasonably expect.

I *think* this may be due to the `tcp-idle-timeout` effectively being disabled
after an initial DNS message exchange on a TCP socket, and I have tried to
fix the bug with the code in pull request #122

Review would be most appreciated.

**Comment by wcawijngaards** [comment]
Yes, I think you are right and I merged the pull request.  Thanks!

I'll close the ticket, then, if things appear to be working.  (It can be hard to test TCP, TLS, because a quick test does not elicit the same behaviour as you can get in other environments, by the way).
