### ISSUE TITLE
rewrite rDNS/PTR lookup?

### ISSUE THREAD

**Issue by Zohman** [NLnetLabs/unbound#127]
Hi,

Can you tell if possible to make rewrite condition for rDNS lookups?
for example, if querying for the PTR record of 10.1.0.1
unbound rewrite the IP and make a query for 10.2.0.1 instead?

conditions:
- if PTR lookup
- if 10.1.x.x unbound overwrite and make 10.2.x.x lookup

Thanks in advance,
Zohman.

**Comment by bjovereinder** [comment]
Thank you for using Unbound.

For general questions about Unbound, its operations and how you can achieve something, we have the Unbound community support mailing list, see https://nlnetlabs.nl/mailman/listinfo/unbound-users.

GitHub Issues for Unbound are only for bug reports or feature requests.

Best regards,

-- Benno
