### ISSUE TITLE
Congrats on the latest audit!

### ISSUE THREAD

**Issue by CHEF-KOCH** [NLnetLabs/unbound#130]
Hey, 
sorry this isn't an issue nor a feature request but I quickly wanted to say, congrats on the latest audit, it looks [good](https://ostif.org/our-audit-of-unbound-dns-by-x41-d-sec-full-results/). 

1 Crit, 5 High, 5 Medium, 50 total changes were found but from what I can see there are already patched.

Maybe you guys could mention such important stuff in the readme.md?!

Greetings, 
CK

**Comment by wcawijngaards** [comment]
Hi, Thanks!

The code review is mentioned on the news post, here, https://nlnetlabs.nl/news/2019/Dec/12/unbound-1.9.6-released/ , and it links to the new items from the auditor and the sponsor.

There did not really look like a good spot for readme.md note for it, but the news items are nicer for it, I think.

Best regards, Wouter
