### ISSUE TITLE
Add support for GNU/Hurd

### ISSUE THREAD

**Issue by gnu-srs** [NLnetLabs/unbound#131]
Hello,

Currently unbound fails to build on GNU/Hurd due to a missing file for entropy. The attached patch fixes this problem by adding compat/getentropy_gnu.c. Additionally, instead of using a fixed size for oldcwd in smallapp/unbound-checkconf.c  dynamic allocation is used, appended to the patch.

This bug has been reported to Debian as bug number #905963. It build fine with their latest version: 1.9.4-2.

Thanks!
[hurd.diff.gz](https://github.com/NLnetLabs/unbound/files/3961789/hurd.diff.gz)

**Comment by gnu-srs** [comment]
ping!

**Comment by gnu-srs** [comment]
PING!

**Comment by bjovereinder** [comment]
Thank you for reporting the issue.  My colleagues are on a well-deserved vacation.

Your patch will be included with a next release.

Best regards,

-- Benno

**Comment by gnu-srs** [comment]
On Mon, 2019-12-30 at 02:07 -0800, Benno Overeinder wrote:
> Thank you for reporting the issue. My colleagues are on a well-deserved
> vacation.
> Your patch will be included with a next release.
> Best regards,
> -- Benno

Thanks in advance.

Happy holidays!

**Comment by gthess** [comment]
Hi,

First thanks for the interest and the time!

I've been going through the diff and I have a couple remarks questions:
- I will leave out the dynamic allocation on `getcwd()` because that behavior is not POSIX specified and may cause problems on other platforms;
- I am reluctant to change the check in `configure.ac` from `host` to `host_os` as it may break configuration on other systems. Is it not possible to keep using `host` there?
- Is there a specific reason you chose to copy the getentropy_solaris and not another getentropy file? In the solaris case we could also try using a more recent version from openbsd (the file's originator).
- I have been trying to check all the above in an emulated gnu/hurd environment. I used the debian preinstalled gnu/hard image from [here](https://www.debian.org/ports/hurd/hurd-install) but I have trouble compiling mainly because of missing dependencies and packages not available on the official repository(eg libexpat1-dev). Have you compiled unbound with this diff on hurd? If so, should I be checking something else than the debian gnu/hurd preinstalled image?

**Comment by gnu-srs** [comment]
Hi,

On Thu, 2020-01-09 at 05:44 -0800, gthess wrote:
> Hi,
> First thanks for the interest and the time!
> I've been going through the diff and I have a couple remarks questions:
> I will leave out the dynamic allocation on getcwd() because that behavior is
> not POSIX specified and may cause problems on other platforms;

For glibc-based systems it is defined though, see getcwd(3).

> I am reluctant to change the check in configure.ac from host to host_os as it
> may break configuration on other systems. Is it not possible to keep using
> host there?

See below.

> Is there a specific reason you chose to copy the getentropy_solaris and not
> another getentropy file? In the solaris case we could also try using a more
> recent version from openbsd (the file's originator).

No, no specific reason. We might try with the openbsd version, but need to check
if it works for GNU/Hurd too.

> I have been trying to check all the above in an emulated gnu/hurd environment.
> I used the debian preinstalled gnu/hard image from here but I have trouble
> compiling mainly because of missing dependencies and packages not available on
> the official repository(eg libexpat1-dev).

See below!

> Have you compiled unbound with this diff on hurd?

Yes of course.

> If so, should I be checking something else than the debian gnu/hurd
> preinstalled image?

I haven't done the build on the pre-installed image, but on other Hurd images.
Trying that now.

download pre-installed image:
wget 
https://cdimage.debian.org/cdimage/ports/current-hurd-i386/debian-hurd.img.tar.gz
tar xzf debian-hurd.img.tar.gz
extracts to debian-hurd-20190705.img

run qemu-system-x96_64:
cat /usr/bin/kvm
#! /bin/sh
exec qemu-system-x86_64 -enable-kvm "$@"

kvm -m 1G -drive file=$(echo debian-hurd*.img),cache=writeback -net
nic,model=e1000 -net user,hostfwd=tcp::5580-:22

In qemu console:
login: root
passwd <set root password>
adduser <uername>
fill in required data; exit

In a terminal:
ssh -p 5580 -l <username> localhost
su
passwd: <root-passwd>
export PATH=/sbin:/usr/sbin:$PATH

nano/vi /etc/apt/sources.list
deb http://ftp.ports.debian.org/debian-ports sid main
deb-src http://ftp.se.debian.org/debian/ sid main contrib non-free
deb http://ftp.ports.debian.org/debian-ports unreleased main

<as root>:
FIXME: locale problems!
locale
LANG=en_GB.utf8
LANGUAGE=
...
apt-get install locales
dpkg-reconfigure locales

apt-get update
apt-get upgrade
apt-get dist-upgrade
apt-get autoremove
<reboot>

<as root>:
apt-get build-dep unbound
apt-get install quilt

<as non-root>:
apt-get source unbound
cd unbound 1.9.4
scp -p 10.0.2.2:<path-to-unbound-patches>/hurd.diff debian/patches
cat >> debian/patches/series
hurd.diff
<C-d>

<apply patches/hack>
dpkg-buildpackage -b 2>&1 | tee ../buildpackage-1.9.4-2.1.log
<builds fine>

Will change the host test in configure.ac and rebuild later on.

**Comment by jrtc27** [comment]
GNU/Hurd has getentropy these days, you shouldn't need to bother with the compat fallback.

**Comment by gnu-srs** [comment]
On Thu, 2020-01-09 at 13:19 -0800, James Clarke wrote:
> GNU/Hurd has getentropy these days, you shouldn't need to bother with the
> compat fallback.

Yes, I knew that was happening but was asked to submit the patches for #905963
upstream. In the meanwhile getrandom/getentropy was implemented by Andrew. I
wonder why youpi did not build unbound without that patch, unbound-1.9.4-2
builds fine without it.

We might close this bug and #905963 when the build has been confirmed.


Thanks!
