### ISSUE TITLE
what do the errors mean?

### ISSUE THREAD

**Issue by luckypoem** [NLnetLabs/unbound#141]
hi.

root@rd:/etc/unbound# cat unbound-by-me.conf
server:
directory: "/etc/unbound"
        username: unbound
        chroot: "/etc/unbound"
        pidfile: "/etc/unbound/unbound.pid"
        interface: 0.0.0.0@853
        access-control: 0.0.0.0/0 allow 

        tls-service-key: "privkey.pem" 
        tls-service-pem: "fullchain.pem" 
        tls-port: 853 
        incoming-num-tcp: 1000
        udp-upstream-without-downstream: yes 
        qname-minimisation: yes 
    
forward-zone:
    name: .
    forward-tls-upstream: yes
    forward-addr: 8.8.8.8@853 
root@rd:/etc/unbound# 
root@rd:/etc/unbound# unbound -c unbound-by-me.conf
unbound-by-me.conf:12: error: unknown keyword 'tls-service-key'
unbound-by-me.conf:12: error: stray ':'
unbound-by-me.conf:12: error: stray '"'
unbound-by-me.conf:12: error: unknown keyword 'privkey.key'
unbound-by-me.conf:12: error: stray '"'
unbound-by-me.conf:13: error: unknown keyword 'tls-service-pem'
unbound-by-me.conf:13: error: stray ':'
unbound-by-me.conf:13: error: stray '"'
unbound-by-me.conf:13: error: unknown keyword 'fullchain.pem'
unbound-by-me.conf:13: error: stray '"'
unbound-by-me.conf:14: error: unknown keyword 'tls-port'
unbound-by-me.conf:14: error: stray ':'
unbound-by-me.conf:14: error: unknown keyword '853'
unbound-by-me.conf:21: error: unknown keyword 'forward-tls-upstream'
unbound-by-me.conf:21: error: stray ':'
unbound-by-me.conf:21: error: unknown keyword 'yes'
read unbound-by-me.conf failed: 16 errors in configuration file
[1578377003] unbound[23240:0] fatal error: Could not read config file: unbound-by-me.conf
root@rd:/etc/unbound#

what do the errors mean? how to fix them?

**Comment by luckypoem** [comment]
anybody can reply me?it's a headache for me

**Comment by gthess** [comment]
It seems you have an older version of unbound. I suspect <1.6.9. You can verify with `unbound -V`.

You can try using the ssl equivalents for those options. For example `ssl-service-key`.
The man page should list those (`man unbound.conf`).

If your version is lower than 1.6.0 then the option `forward-ssl-upstream` will not be available.

**Comment by luckypoem** [comment]
yes,u are right.the unbound's version is 1.6.7,i changed the following
tls-service-key: "privkey.pem"
tls-service-pem: "fullchain.pem"
tls-port: 853
forward-tls-upstream: yes

to:

ssl-service-key: "privkey.pem"
ssl-service-pem: "fullchain.pem"
ssl-port: 853
forward-ssl-upstream: yes

then the issue is fixed.

**Comment by gthess** [comment]
Good to hear, closing this one.
