### ISSUE TITLE
DNSSec doesnt work | auto-trust-anchor-file

### ISSUE THREAD

**Issue by useronegit** [NLnetLabs/unbound#160]
If I write **"sudo unbound-anchor -C unbound.conf"**
 then the **error** appears **"trust anchor presented twice"** **it cannot be read.** 
I have deleted and regenerated the root.key several times already and have followed the tutorial several times how to activate DNSSec, but nothing works.
I also uninstalled and reinstalled unbound several times.
I **cannot write "auto-trust-anchor-file"** into the **unbound config**, because otherwise **unbound won't work at all**. And there is also an error when I write "sudo unbound-checkcfg"
But **if auto trust** is in the **extra file** in the **"/unbound/unbound.conf.d/root../"** then I only get an error if I write "unbound -C unbound.conf" but **unbound works normally.**

When i try to see if DNSSec works, no AD flag appears, but the connection is working.

(Sorry for my english, most is from Translator)

**Comment by wcawijngaards** [comment]
Hi,
The first issue; sudo unbound-anchor; that is because you have the statement auto-trust-anchor-file twice in unbound.conf and files included in unbound.conf.  It is about the statement in the config file, not about the file itself, so deleting it or creating that does not make a difference for that error.

The second issue, if you write auto-trust-anchor-file in unbound.conf,  you add the file to the server: section.  Not somewhere else.  Or in an included file, that is included in unbound.conf, also in the server: section of the conf.

The third issue, sudo unbound-checkcfg, that is spelled sudo unbound-checkconf, that should print out errors in the configuration so you can fix that.

The fourth issue. The unbound command does not take the '-C' flag, it is spelled '-c'.

You seem to be looking for our community support. We offer community support for our software via our mailing lists, see https://nlnetlabs.nl/mailman/listinfo/unbound-users. Other enthusiastic Unbound users are also subscribed to this email list and can also provide useful input and answers to your questions.

Best regards, Wouter

**Comment by useronegit** [comment]
> The first issue; sudo unbound-anchor; that is because you have the statement auto-trust-anchor-file twice in unbound.conf and files included in unbound.conf. It is about the statement in the config file, not about the file itself, so deleting it or creating that does not make a difference for that error.

No, its not twice in unbound.conf. That's the problem.
The file "root-auto-trust-anchor-file.conf" was generated automatically and there is the "auto-trust" in it. Only once. Nowhere in the unbound config.
If I comment it out or remove it, I no longer have DNSSec turned on. According to the DNSSec test pages.

> The second issue, if you write auto-trust-anchor-file in unbound.conf, you add the file to the server: section. Not somewhere else. Or in an included file, that is included in unbound.conf, also in the server: section of the conf.

If I do that, then the error "unbound-checkcfg" occurs and unbound does not work at all. If I leave it switched on at "root-auto-trust-anchor-file.conf" then I only get the error if I use "unbound-anchor -C /etc/unbound/unbound.conf".

> The third issue, sudo unbound-checkcfg, that is spelled sudo unbound-checkconf, that should print out errors in the configuration so you can fix that.

I tried everything I could. Unbound reinstalled, rebuilt the Configs. Leave only DNSSec enabled. The error remains. The same error remains. 
I have also checked several times if "auto-trust-anchor-file" is written somewhere else. But no. In the Configs it is only in the "root-auto-trust-anchor-file.conf". Another colleague has the same problem. He has the default configs and only turned on DNSSec, the same thing happened.

> The fourth issue. The unbound command does not take the '-C' flag, it is spelled '-c'.

Sorry, I meant it wrong and C is right.
"sudo unbound-anchor -C /etc/unbound/unbound.conf"

**Comment by wcawijngaards** [comment]
So, it looks like something is wrong in your unbound.conf file.  This would print a failure when you run unbound-checkconf, unbound-anchor, or unbound.  It would also fail to start the server from the system script.  The unbound-checkconf command can be used to print an error what is wrong with the config.  What does it print?

There also seems to be some issue where you reinstall stuff and the system starts stuff and creates files for you.  I did not build that system, it is from the system distribution that you use.  It also seems to create files that are included into the /etc/unbound/unbound.conf file, these contain config snippets, a couple of lines of config just like it was part of the main unbound.conf file.

The filename of the trust anchor file does not really matter to unbound.  You can write whatever you want between the quotes, like `auto-trust-anchor-file: "/my_directory/my_filename"`

**Comment by useronegit** [comment]
> What does it print?

I have reinstalled unbound and deleted all config files. The unbound config was empty and I only wrote auto-trust-file into it. The exact same thing came out.
I didn't write it twice or anything.
I also have the Raspberry pi 3 model b+ running with debian stretch lite.
All is updated.
Unbound Version: 1.9.0-2+deb10u1

Here is the error that appears when I write the command: 
"sudo unbound-anchor -C /etc/unbound/unbound.conf"

[1581172029] libunbound [13010:0] error: trust anchor presented twice
1581172029] libunbound [13010:0] error: could not parse auto-trust-anchor-file /var/lib/unbound/root.key line 2
1581172029] libunbound [13010:0] error: error reading auto-trust-anchor-file: /var/lib/unbound/root.key
1581172029] libunbound [13010:0] error: validator: error in trustanchors config
1581172029] libunbound [13010:0] error: validator: could not apply configuration settings.
1581172029] libunbound[13010:0] error: module init for module validator failed


And when I write "sudo unbound-checkcfg,"
unbound-checkconf: no errors in /etc/unbound/unbound.conf

To download the root.key I wrote "sudo unbound-anchor" and even "sudo unbound-anchor -a /var/lib/unbound/root.key" or even referred to another folder. Also renamed the root key, no success.

It doesn't matter if I move the root key to a different folder, rename the root key re-download it or reinstall unbound, delete all configs or anything else.

Most websites say that I use DNSSec, but when I test it with command 
"dig com. SOA +dnssec"

then the "AD" flag will not appear.
Only "qr rd ra"

**Comment by wcawijngaards** [comment]
Thanks for the printouts.

It looks like the config file for unbound-anchor and for unbound and unbound-checkconf are different.  You have different config files installed, perhaps at multiple locations, like /etc or /usr/local/etc or /var/lib somewhere.  The locations depend on the packager (from where you installed it) choices.  The files are different, because otherwise the commands would have printed the exact same errors.

unbound-checkconf -h prints the location of what config file it will use.  (by default).  That is the one that uses.   Also unbound -h prints the location of the config file that it is compiled to use.

My guess is that the config files are different in what auto-trust-anchor-file statements they have.  Hence on the commandline what you see for trust anchor, is different when you test websites and with dig.  With dig, see what resolver it queries (the IP address).  Is that your unbound? Or another?  Otherwise also resolv.conf is not pointing at the server you want it.  This because sometimes people start unbound, or even several DNS servers, but then the resolv.conf determines where the lookups happen. (and also there is the ISP-provided or online DNS servers).

Best regards, Wouter

**Comment by edmonds** [comment]
Raspbian is a Debian-based distro, and version 1.9.0-2+deb10u1 of their unbound package is exactly the same as the Debian 1.9.0-2+deb10u1 unbound package.

In Debian, we ship a default configuration that enables `auto-trust-anchor-file: "/var/lib/unbound/root.key"` in a config file fragment:

```
$ head -999 /etc/unbound/unbound.conf /etc/unbound/unbound.conf.d/*.conf
==> /etc/unbound/unbound.conf <==
# Unbound configuration file for Debian.
#
# See the unbound.conf(5) man page.
#
# See /usr/share/doc/unbound/examples/unbound.conf for a commented
# reference config file.
#
# The following line includes additional configuration files from the
# /etc/unbound/unbound.conf.d directory.
include: "/etc/unbound/unbound.conf.d/*.conf"

==> /etc/unbound/unbound.conf.d/root-auto-trust-anchor-file.conf <==
server:
    # The following line will configure unbound to perform cryptographic
    # DNSSEC validation using the root trust anchor.
    auto-trust-anchor-file: "/var/lib/unbound/root.key"
$
```

There is no need to edit `/etc/unbound/unbound.conf` to add anything or run any further commands to enable DNSSEC validation. If you run `apt install unbound` you get an unbound that is already pre-configured for DNSSEC validation.

Furthermore, at package installation time, we do a one-time initialization of `/var/lib/unbound/root.key` with a copy of the 2017 IANA root trust anchor (aka KSK-2017, key tag 20326), copied from `/usr/share/dns/root.key` (from the standalone `dns-root-data` Debian package). This ensures that unbound / unbound-anchor start up with an up-to-date copy of the root trust anchor on disk.

```
$ cat /usr/share/dns/root.key
.	86400	IN	DNSKEY	257 3 8 AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU= ;{id = 20326 (ksk), size = 2048b} ;;state=2 [  VALID  ]
$ 
```

Again, if you run `apt install unbound` on a Debian or Debian-derived distro, it does DNSSEC validation out of the box. If DNSSEC validation doesn't work then it most likely indicates a problem with the network.

**Comment by useronegit** [comment]
>In Debian, we ship a default configuration that enables auto-trust-anchor-file: "/var/lib/unbound/root.key" in a config file fragment:

> Again, if you run `apt install unbound` on a Debian or Debian-derived distro, it does DNSSEC validation out of the box. If DNSSEC validation doesn't work then it most likely indicates a problem with the network.

I know that, that's what I meant.
The file is created automatically and auto-trust is activated automatically.
If I leave everything on default, the error still comes.
With "sudo unbound-anchor -C /etc/unbound/unbound.conf"

> unbound-checkconf -h

It only opens the help for the command unbound-anchor but there is nothing about the location of the config


> unbound -h

the same

> If DNSSEC validation doesn't work then it most likely indicates a problem with the network.

The problem is that there is no problem per se. 
Again, if I uninstall unbound and delete all configs and reinstall unbound.
I look into the configs ALL is default. Also the file with auto-trust was generated. 

Then the following happens:

"sudo unbound-checkconf" 
unbound-checkconf: no errors in /etc/unbound/unbound.conf

"sudo unbound-anchor -C /etc/unbound/unbound.conf" 
[1581172029] libunbound [13010:0] error: trust anchor presented twice
1581172029] libunbound [13010:0] error: could not parse auto-trust-anchor-file /var/lib/unbound/root.key line 2
1581172029] libunbound [13010:0] error: error reading auto-trust-anchor-file: /var/lib/unbound/root.key
1581172029] libunbound [13010:0] error: validator: error in trustanchors config
1581172029] libunbound [13010:0] error: validator: could not apply configuration settings.
1581172029] libunbound[13010:0] error: module init for module validator failed

I do not change anything !

https://dnssec.vs.uni-due.de/
This page tells me that I have activated DNSSec.

dig com. SOA +dnssec
This should show me the "AD" flag, but it does not.
The flags are "qr rd ra"

If I type this in.
"sudo unbound-control stats_noreset"
then the number of "SERVFAIL" is the most.
When DNSSec is turned on without changing anything in the config or even if I change anything No matter what I do, the error remains. 
No matter if I change the location of the file, change the file name or use "sudo unbound-anchor".
Nothing works. The one and only error remains.

**Comment by useronegit** [comment]
Any other solution?

**Comment by wcawijngaards** [comment]
I guess the error may not be caught by unbound-checkconf, but it is caught by the unbound-anchor.  It would be reasonable to assume that unbound itself should also fail like unbound-anchor does.  Because it uses the same code.  unbound-host -C /etc/unbound/unbound.conf should have the same trouble as unbound-anchor.

Robert should be right and things are setup right.  But not for you.  Maybe you selected alternates, like resolvconf or dns alternates.  Or resolv.conf points to a different server.  Does that dig use the local unbound or something else?  or another DNS server you have installed?  It prints the IP address.

The -h output contains the default config that it uses in the printout of the help summary, for the config option.

**Comment by useronegit** [comment]
> unbound-host -C /etc/unbound/unbound.conf
command not found

I'm not the only one who has the problem, I've talked to others who have displayed exactly the same thing, even though other configs have the default config.
Apparently it is due to the Raspberry Pi unbound and not the general unbound.

> Robert should be right and things are setup right. But not for you. Maybe you selected alternates, like resolvconf or dns alternates. Or resolv.conf points to a different server. Does that dig use the local unbound or something else? or another DNS server you have installed? It prints the IP address.

I have no other DNS installed and everything works as it should. Except DNSSEC.
I have tested it and unbound cached queries work as well.

**Comment by bjovereinder** [comment]
Hi,

[Thank you for contacting us, but as mentioned earlier, this discussion should take place on the unbound mailing list, <https://lists.nlnetlabs.nl/mailman/listinfo/unbound-users>.  GitHub issues are intended for software development: software errors and function requests.  The problems you encounter are software configuration related, and we and our user community are happy to help you on the Unbound mailing list.]

I have installed Unbound 1.9.0.2 version from the Raspbian repository, and with a fairly standard unbound.conf (only allow local/LAN access).  You don't need to do any additional `unbound-anchor` or `auto-trust-anchor-file` configuration.

This is the output of `dig` command:
```
$ dig com. SOA +dnssec

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> com. SOA +dnssec
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 19745
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags: do; udp: 4096
;; QUESTION SECTION:
;com.				IN	SOA

;; ANSWER SECTION:
com.			661	IN	SOA	a.gtld-servers.net. nstld.verisign-grs.com. 1582372987 1800 900 604800 86400
com.			661	IN	RRSIG	SOA 8 1 900 20200229120307 20200222105307 56311 com. JireliO+Fkf57VuH8X/vYLgQ7MHP2orV+eXf+nwKjdTTirUZivebvbXr xaQOjofHIyVwIpbe5PllKp9nTdVwoTfExeZviSPBDYCPkIvcSypq3UG3 HRtqkUmq/GbFkYKVoUv14Jxoze9PCiW461zMZAfSXWY2x8gWDq94ZLXj FX1TjAoRRuxzljvWe0DCSbRvyaGefYV2Bf4h1rfAMHy9tA==

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Sat Feb 22 13:07:27 CET 2020
;; MSG SIZE  rcvd: 300
```
As you can see, the AD flag is displayed with a standard Unbound Raspbian installation.

I recommend that you put the output of your `dig` command on the Unbound mailing list and ask for solutions.  It is difficult for us to figure out how your configuration differs from other Raspbian installations.  Is Unbound configured to forward queries to (non-validating) resolvers, are there middleboxes (firewalls, etc.) that strip replies, etc.? But again, continue the discussion on the [Unbound mailing list](https://lists.nlnetlabs.nl/mailman/listinfo/unbound-users).

Regards,

-- Benno

**Comment by useronegit** [comment]
>  It is difficult for us to figure out how your configuration differs from other Raspbian installations.

My Config is blank, only some comments.
And the "include".

in unbound.conf.d are files
qname-minimisation.conf  and root-auto-trust-anchor-file.conf
qname-minimisation is on yes in qname conf
auto-trust-anchor-file is on the default path /var/lib/unbound/root.key in trust conf

Both files were created automatically. 
I didn't change or create anything.

> You don't need to do any additional unbound-anchor or auto-trust-anchor-file configuration.

I know that, and that is the problem. I do not change anything in the config and still the error appears. When I reinstall, I delete all configs and let unbound recreate them.


> I recommend that you put the output of your dig command on the Unbound mailing list and ask for solutions.

Yeah, but the problem is, it's not a config fault. Because I didn't change anything in the config.
and I've already written it above with the flags. 
That's why I thought I was in the right place.

It's exactly the same as yours, but without the AD flag.
when I activate unbound-control and check the requests, most of them are at SERVFAIL

> then the "AD" flag will not appear.
> Only "qr rd ra"

-
> Is Unbound configured to forward queries to (non-validating) resolvers, are there middleboxes (firewalls, etc.) that strip replies, etc.?

No, there are no middle boxes

Tested with both.
Once forwarded to Dnscrypt-proxy
(what works without DNSSec)
And once without forwarding
(which also works without DNSSec)

As already said, the problem is not only with me but also with others I have asked.
They have unbound with the default config.

**Comment by restavr** [comment]
in the file "/etc/unbound/unbound. conf", comment out the line 
 `# include:" /etc/unbound/unbound.conf.d/*.conf`
 and enter the parameter 
`auto-trust-anchor-file:" /var/lib/unbound/root.key`
 after that, you can restart unbound and finally see 
 `flags: qr rd ra ad;`
I've been struggling with this myself for several hours :-)

**Comment by bjovereinder** [comment]
Thank you @restavr.  I will close the issue.
