### ISSUE TITLE
Config grammar plus "include:" directive behavior is not robust

### ISSUE THREAD

**Issue by edmonds** [NLnetLabs/unbound#161]
Hi,

The unbound config file parser is a little fragile due to a combination of two properties:

1) Clauses (like `server:`) don't appear to be ended by anything except the beginning of a new clause. Indentation is not actually meaningful.

2) The `include:` directive concatenates the included config file text. It is commonly combined with globbing to include multiple config file fragments from a directory.

So, for instance, imagine a scenario where a user starts with three config files:

```
# /etc/unbound/unbound.conf
include: "/etc/unbound/unbound.conf.d/*.conf"
```

```
# /etc/unbound/unbound.conf.d/trust-anchor-file.conf
server:
    trust-anchor-file: "/usr/share/dns/root.key"
```

```
# /etc/unbound/unbound.conf.d/verbosity.conf
verbosity: 5
```

The `verbosity.conf` config file fragment provides a `verbosity:` option, which must be specified inside the `server:` clause. Because config file fragments are simply concatenated together (and in a specific, sorted order), and because indentation is not meaningful, this set of config files will be accepted by the config file parser.

Now imagine the `trust-anchor-file.conf` config file fragment is removed. The `verbosity:` option is no longer part of the `server:` clause. This causes a parse error.

This makes it problematic for distros to ship a default `unbound.conf` with an include directive including config file fragments from a ".d" directory, and then add or remove distro defaults by installing or uninstalling config file fragments in the .d directory. (E.g., Debian has enabled the root trust anchor for a while by shipping the directive in a .d config file fragment rather than in the main config file. Recently we shipped a `qname-minimisation.conf` config file fragment that enabled qname minimisation but removed the fragment now that this feature is enabled by default.) Users can add their own .d config file fragments with filenames that sort after these distro-provided fragments and inadvertently rely on a previous config file fragment entering a particular clause.

My suggestion would be to change the config file parser so that the `include:` directive functions logically rather than textually and includes each matching glob'd file inside the clause where the `include:` directive appears (or at the top-level if the `include:` directive is not inside any clause). Or another way of putting it would be that after reading each `include:`'d file, the current clause should be reset to the one that the `include:` directive is embedded in.

This suggestion would still break some existing configs that use the `include:` directive but it would be more robust going forward and would prevent users from structuring configs that can be broken by removing or reordering individual config file fragments.

**Comment by gthess** [comment]
Hi Robert,

The way unbound is parsing the config file, you could repeat clauses as long as you like.
In your example I would use the following:
```
# /etc/unbound/unbound.conf.d/verbosity.conf
server:
    verbosity: 5
```
(indentation indeed doesn't matter but added for clarity).

If this wasn't clear I can add more text to the unbound.conf man page.

**Comment by gthess** [comment]
Updated the man page in https://github.com/NLnetLabs/unbound/commit/8e135d5f5947c439d6405110e85751dfaef2fa80.

**Comment by edmonds** [comment]
Sorry, updating the manpage doesn't really help at all. Yes, users can structure their included config file fragments to always enter a clause _**but this is not required by the config parser**_, and this allows users to create configurations that are not robust against individual config file fragments being edited, reordered, or removed.

> This makes it problematic for distros to ship a default unbound.conf with an include directive including config file fragments from a ".d" directory, and then add or remove distro defaults by installing or uninstalling config file fragments in the .d directory. (E.g., Debian has enabled the root trust anchor for a while by shipping the directive in a .d config file fragment rather than in the main config file. Recently we shipped a qname-minimisation.conf config file fragment that enabled qname minimisation but removed the fragment now that this feature is enabled by default.) Users can add their own .d config file fragments with filenames that sort after these distro-provided fragments and _**inadvertently rely on a previous config file fragment entering a particular clause.**_

The problem is that when a series of config file fragments are included into the config, a config file fragment can enter a clause, and this state is not reset when parsing subsequent config file fragments.

**Comment by gthess** [comment]
We would like to keep the `include:` behavior (textual inplace inclusion) as-is.
However we could introduce an extra include directive that would implicitly start a `server:` clause.
That would force the user to either include server options (without specifying a clause) or explicitly start a new clause.
Does that sound ok to you?

**Comment by edmonds** [comment]
If you're going to introduce a new include directive I would stick with my original suggestion:

> My suggestion would be to change the config file parser so that the include: directive functions logically rather than textually and includes each matching glob'd file inside the clause where the include: directive appears (or at the top-level if the include: directive is not inside any clause). Or another way of putting it would be that after reading each include:'d file, the current clause should be reset to the one that the include: directive is embedded in.

Maybe call the new include directive `include-logical:` or something. I don't think it makes sense to hardcode a particular clause like `server:`.

If you are going to stick with hardcoding the clause that a new include directive implicitly starts, I would prefer an `include-toplevel:` directive that implicitly adds the directives in each glob'd file to the top-level context. (Combined with making it a syntactical error for `include-toplevel:` to appear inside a clause so that its behavior is clear.) Then I could change the default `unbound.conf` shipped with the Debian package to use `include-toplevel:` rather than `include:` and it would protect users from the problem described in the first message in this issue.

I still think the textual in-place inclusion that `include:` does is fundamentally broken and I would prefer to see `include:` fixed rather than retaining the broken behavior.

Thanks!

**Comment by gthess** [comment]
Hi Robert,

I implemented kind of your `include-toplevel:` suggestion and you can find the feature at https://github.com/NLnetLabs/unbound/tree/include-toplevel.
As documented there, `include-toplevel:` will close any previous clause (if any) and require the included files to explicitly start a clause. A clause is also needed after the directive.

I didn't merge the feature on master and instead opted for a branch so that you can first test and see if it works with your use case. Any feedback is of course welcome.

**Comment by edmonds** [comment]
Hi, George:

Just got a chance to test the `include-toplevel` branch. This looks great, it would be highly appreciated to have this feature in a future Unbound release. Thanks!

**Comment by gthess** [comment]
Perfect, thanks for testing!
We plan on including this in the next release.
