### ISSUE TITLE
unbound-control reload cause 'log-identity' config lost

### ISSUE THREAD

**Issue by qyb** [NLnetLabs/unbound#163]
I define 'log-identity' as "unbound-dnsaas", then my log output as:
...
Feb  9 21:18:20 localhost unbound-dnsaas: [6222:0] info: 36.157.117.62 www.archlinux.org. AAAA IN NOERROR 0.000000 1 95
...

after I run `sudo unbound-control reload`, log output as:
...
Feb  9 21:14:01 localhost google.ws.: [5761:0] info: 172.16.0.10 translate.google.com. A unknown
...

**Comment by gthess** [comment]
Thanks for reporting! This is now fixed on master.
