### ISSUE TITLE
Add prefer-ip4 and require-ip4/require-ip6 options

### ISSUE THREAD

**Issue by nomis** [NLnetLabs/unbound#165]
There's a `prefer-ip6` option but no corresponding `prefer-ip4` option.

Many service providers are unable to consider the reputation of any source address smaller than a /64 but many VPS providers put all customers in the same /64.

This makes it impossible to reliably use IPv6 for outbound connections. For example, sending any email to Google over IPv6 will significantly reduce the likelihood of it being delivered.

When querying DNS blacklists/whitelists that impose a query limit based on source address, the only viable solution at this time is to prefer IPv4 whenever possible.

Ideally I'd like to be able to configure specific zones to be IPv4-only with a `require-ip4` option.

**Comment by wcawijngaards** [comment]
Thanks for the issue report, the `prefer-ip4` option is in the code base.  It is the mirror identical of `prefer-ip6`.  For the require options, not sure how that would work.

**Comment by dinguz** [comment]
It seems that the _prefer-ip4_ and _prefer-ip6_ options are not recognised in unbound-control. Is this done on purpose?

root@haanjdj:~ # unbound-control -c /var/unbound/unbound.conf get_option prefer-ip4
error unknown option

**Comment by wcawijngaards** [comment]
You need version 1.11.0 (or later) to have that option `prefer-ip4`.  I guess you are using an older version.

**Comment by dinguz** [comment]
I have 1.11.0, according to unbound-control -h 
I'm running OPNsense 20.7.2 BTW.

**Comment by wcawijngaards** [comment]
You are right, that is missing from the code.  I added the missing functionality in commit https://github.com/NLnetLabs/unbound/commit/2541ccbb1bc5d675aafce7f876db90ae8aa422b2 and this should appear in the next release.

**Comment by dinguz** [comment]
Thanks!
