### ISSUE TITLE
Unbound 1.10.0 fails to start

### ISSUE THREAD

**Issue by sam-lunt** [NLnetLabs/unbound#168]
I'm running unbound as my local DNS resolver on ArchLinux. After upgrading to 1.10.0, unbound fails to start with the error message below. Downgrading to 1.9.6 solves the problem. Also, `/var/run` is not a read-only file system and there was no file `/var/run/unbound.sock`.

```
unbound[12668]: [1582728262] unbound[12668:0] error: Cannot remove old local socket /var/run/unbound.sock (Read-only file system)
unbound[12668]: [1582728262] unbound[12668:0] error: cannot open control interface /var/run/unbound.sock 8953
unbound[12668]: [1582728262] unbound[12668:0] fatal error: could not open ports
```

**Comment by wcawijngaards** [comment]
Looks like this is an issue with the systemd.service file.  These have been changed in contrib/ in the 1.10.0 release, I guess this impacted you, but I do not know the specifics for the systemd stuff (hence it is user contributed files, that are examples).

This may better be an issue with the packaging system, as it looks something to solve there. Or in the systemd service files that are combined with the package.  (We do not do the distro packages, that is done by the distributions themselves).  But we ship user made examples in the source contrib/ dir.  Also for systemd.  And for 1.10.0 there were a number of contributions that changed it (back and forth).

Best regards, Wouter

**Comment by sam-lunt** [comment]
Thanks for the hint. After some digging, it seems the issue is the removal of `/run` from the `ReadWritePaths`. The diff between 1.9.6 and 1.10.0 for `ReadWritePaths`:

```
-ReadWritePaths=/run /etc/unbound /etc/unbound
+ReadWritePaths=/etc/unbound /etc/unbound
```

Commit [1464bed](https://github.com/NLnetLabs/unbound/commit/1464bedce25f270508a3c9d921448afedc9ec9a2#diff-392c7963111775f9b4048bf39331abce) split `ReadWritePaths` into its own entry, then commit [9aa4b5a](https://github.com/NLnetLabs/unbound/commit/9aa4b5a7a61f3fc03d49e904cca6d31523e8b073#diff-392c7963111775f9b4048bf39331abce) removed the separate entry.

The issue is going to be specific to my configuration, since I have this entry:

```
remote-control:
    control-enable: yes
    control-interface: /var/run/unbound.sock
```

I feel like `/var/run` (or `/run`) is the appropriate place for a socket like this, but I will reconsider my config and try placing it somewhere else.

Thanks for the quick response.

**Comment by wcawijngaards** [comment]
Thanks for the detailed response, because other people sometimes also look for these issues and this may help them a lot.

**Comment by Maryse47** [comment]
@sam-lunt the more appropriate place would be `/var/run/unbound/unbound.sock` which should work with shipped systemd service.

Also the `/var` prefix is redundant, `/run/unbound/unbound.sock` would work the same.

**Comment by sam-lunt** [comment]
@Maryse47 thanks for the suggestion, that location did work. And yes, `/var/run` is a symlink to `/run` on my machine. Apparently FHS 3.0 replaced `/var/run` with `/run`
