### ISSUE TITLE
dnstap does not build on macOS

### ISSUE THREAD

**Issue by jschlyter** [NLnetLabs/unbound#177]
Building dnstap fails with:

```
../dnstap/dtstream.c:1582:38: error: use of undeclared identifier 'usock'
        s.sun_len = (unsigned)sizeof(usock);
```

**Comment by wcawijngaards** [comment]
Fixed the issue in https://github.com/NLnetLabs/unbound/commit/4207b58700ccb41f1e7fb959120aef4da87c246d .  Thanks for the report.  Those system headers are just a bit different, and the compatibility code needs adjustment.
Best regards, Wouter
