### ISSUE TITLE
unbound-control.c:882:6: error: 'execlp' is unavailable: not available on tvOS

### ISSUE THREAD

**Issue by noloader** [NLnetLabs/unbound#188]
Hi Everyone, @wcawijngaards,

I'm testing Unbound Master on iOS. The testing below is on AppleTVOS. WatchOS and the simulators will produce a similar result.

```
libtool: compile:  clang -I. -I/Users/travis/AppleTVOS-arm64/include -I/Users/travis/AppleTVOS-arm64/include -DSRCDIR=.
-arch arm64 -mappletvos-version-min=6 --sysroot=/Applications/Xcode-10.0.app/Contents/Developer/Platforms/
AppleTVOS.platform/Developer/SDKs/AppleTVOS12.0.sdk -c smallapp/unbound-control.c -o unbound-control.o

smallapp/unbound-control.c:882:6: error: 'execlp' is unavailable: not available on tvOS
                if(execlp("unbound", "unbound", "-c", cfgfile, 
                   ^

/Applications/Xcode-10.0.app/Contents/Developer/Platforms/AppleTVOS.platform/Developer/SDKs/AppleTVOS12.0.sdk/
usr/include/unistd.h:442:6: note: 'execlp' has been explicitly marked unavailable here
int      execlp(const char * __file, const char * __arg0, ...) __WATCHOS_PROHIBITED __TVOS_PROHIBITED;
         ^
1 error generated.
```

We may need to add `ac_cv_func_execlp=no` to `configure`. Otherwise, I believe Autotools [incorrectly] guesses `execlp` is available. ([Commit 84864caeefb0](https://github.com/NLnetLabs/unbound/commit/84864caeefb0) tries the `ac_cv_func_execlp=no` fix).

This result depends upon [PR #187](https://github.com/NLnetLabs/unbound/pull/187). The 187 PR updates Android and iOS and adds iOS simulator testing to Travis.

Also see [Travis test 660761901](https://travis-ci.org/noloader/unbound/jobs/660761901).

**Comment by noloader** [comment]
Adding `ac_cv_func_execlp=no` to `configure` was not successful. Maybe you can add an Autootools test for the `<TargetConditionals.h>` header. Then you can add this to `unbound-control.c`:

```
#ifdef HAVE_TARGETCONDITIONALS_H
#include <TargetConditionals.h>
#endif
```

And then disable `execlp` if `TARGET_OS_TV` or `TARGET_OS_WATCH` is defined. Maybe something like:

```
	if(argc >= 1 && strcmp(argv[0], "start")==0) {
#if defined(TARGET_OS_TV) || defined(TARGET_OS_WATCH)
		fatal_exit("could not exec unbound: %s",
			strerror(ENOSYS));
#else
		if(execlp("unbound", "unbound", "-c", cfgfile, 
			(char*)NULL) < 0) {
			fatal_exit("could not exec unbound: %s",
				strerror(errno));
		}
#endif
	}
```

This has the benefit of being self sufficient. It does not require users to add `ac_cv_func_execlp=no` to `configure` to avoid a wrong guess by Autotools during cross-compiles.

**Comment by wcawijngaards** [comment]
The commit with the targetconditionals header was imported.  The other one with AC_FUNC configure tests is not imported (it looks unused).  I removed a whitespace in configure.ac, and remade the configure script.  This should import the fixes you had into the master branch on github.

If it does not really work, i.e. after you import it and travis runs, reopen or make a new issue.  Thanks for the test and code suggestions!
