### ISSUE TITLE
[unbound-checkconf] fatal error: module conf 'dns64 subnetcache respip validator iterator' is not known to work

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#192]
> Version 1.10.0
> 
> Configure line: --target=arm-openwrt-linux --host=arm-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix= --program-suffix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-dsa --disable-gost --enable-allsymbols --enable-subnet --with-libexpat=/home/beast/beast/workspace/turris-os-packages-dragons-omnia/build/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr --with-ssl=/home/beast/beast/workspace/turris-os-packages-dragons-omnia/build/staging_dir/target-arm_cortex-a9+vfpv3_musl_eabi/usr --without-pthreads --enable-tfo-server --enable-tfo-client
> Linked libs: pluggable-event internal (it uses select), OpenSSL 1.1.1d  10 Sep 2019
> Linked modules: dns64 subnetcache respip validator iterator
> TCP Fastopen feature available
___

`module-config: 'respip validator iterator'` -> no error printed

`module-config: 'dns64 subnetcache validator iterator'` -> no error printed

`module-config: 'dns64 subnetcache respip validator iterator'` -> prints

> unbound-checkconf[29761:0] fatal error: module conf 'dns64 subnetcache respip validator iterator' is not known to work

`module-config: 'subnetcache respip validator iterator'` -> prints

> unbound-checkconf[30313:0] fatal error: module conf 'subnetcache respip validator iterator' is not known to work

`module-config: 'dns64 respip validator iterator'` -> prints

> unbound-checkconf[31009:0] fatal error: module conf 'dns64 respip validator iterator' is not known to work

Despite the error the instance starts.

**Comment by wcawijngaards** [comment]
Hi N8v8r,
Yes it starts, and checkconf warns that we do not know if it works.  If you can verify that it in fact works, I mean also the parts where those modules perform special work for you and regular lookups work too, then I can mark then as working in checkconf.  In checkconf we currently have a list of working module combinations.  We simply have not checked all of them.  But if you can tell us that a module combination - the one you want to use - works, then I can change the source to indicate that the module combination is a working one.

The message gives the warning, unbound starts.  Apart from starting, does everything work?

Best regards, Wouter

**Comment by ghost** [comment]
currently having in place `module-config: 'dns64 subnetcache respip validator iterator'` I do not see any inclement impact.

Not sure if it is any indication (since it appears to to test the upstream resolver instances configured in unbound but not clear whether the test uses its own resolver or the local unbound instance) but the score on https://cmdns.dev.dns-oarc.net exhibits
![Annotation 2020-03-16 091817](https://user-images.githubusercontent.com/13611490/76736658-28a9eb80-675f-11ea-84a4-5c086a7e9a2d.png)

**Comment by wcawijngaards** [comment]
Ok thanks, I have listed the config as working, because thing seem to work for you.  Yes, I think the score is (mostly) the upstream server you are looking at.
