### ISSUE TITLE
Option for Redis in cachedb to store records with expiry information

### ISSUE THREAD

**Issue by gthess** [NLnetLabs/unbound#195]
Currently the records stored in Redis have no expiry information.
The DNS TTL is encoded in the record itself but the records keep on living in Redis unless removed by an eviction policy.
A configuration option could be available to add expiry on those records based on the DNS TTL.
Based on the usage scenario, a user could opt in for the feature.

Initial thinking is to use `SETEX` instead of `SET` when that option is enabled. `SETEX` provides atomicity which we want but is only supported in Redis >= 2.0.0. Maybe try to honor the option but give a warning and fallback to `SET` when Redis < 2.0.0.

Additional notes:
- Expiry information seems to require "[...] some additional memory used by the key [...]".
- Redis uses future absolute Unix timestamps for TTLs; clock needs to be stable and care taken if replicating to other machines with different clocks.

More info for expires in Redis: https://redis.io/commands/expire

**Comment by Talkabout** [comment]
Hi @gthess ,

I'd like to try this change myself. Can you give me a hint how to extract the "ttl" from the dns answer in the method "redis_store"? I have tried several things but am not able to get the required value. It seems to be "encoded" in the "data" variable but decoding it is causing me trouble.

Thanks!

Bye

**Comment by gthess** [comment]
Sure!
The data is prepared (`prep_data()`) in `cachedb.c`. There you can see that the ttl value you want is the relative one found on `qstate->return_msg->rep->ttl`.
You could follow part of the `parse_data()` to retrieve that value in `redis_store()` but I believe the better solution (avoiding unnecessary decoding) is to pass that value when `cachedb_extcache_store()` calls the backend. Then in `redis_store()` you could use that value to set expiry on redis records.
Have fun!

**Comment by Talkabout** [comment]
Thanks @gthess !

I have implemented the method now in the following way:

```
static void
redis_store(struct module_env* env, struct cachedb_env* cachedb_env,
        char* key, uint8_t* data, size_t data_len, uint64_t ttl)
{
        redisReply* rep;
        char cmdbuf[4+(CACHEDB_HASHSIZE/8)*2+3+4+sizeof(uint64_t)+1]; /* "SET " + key + " %b EX " + ttl */
        int n;

        verbose(VERB_ALGO, "redis_store %s (%d bytes)", key, (int)data_len);

        /* build command to set to a binary safe string */
        n = snprintf(cmdbuf, sizeof(cmdbuf), "SET %s %%b EX %d", key, ttl);
        if(n < 0 || n >= (int)sizeof(cmdbuf)) {
                log_err("redis_store: unexpected failure to build command");
                return;
        }

        rep = redis_command(env, cachedb_env, cmdbuf, data, data_len);
        if(rep) {
                verbose(VERB_ALGO, "redis_store set completed");
                if(rep->type != REDIS_REPLY_STATUS &&
                        rep->type != REDIS_REPLY_ERROR) {
                        log_err("redis_store: unexpected type of reply (%d)",
                                rep->type);
                }
                freeReplyObject(rep);
        }
}
```
It is surely not the best solution but it works for me. The ttl is now considered on redis and the entries get expired. Maybe this is a starting point for other people.

Here are the changed files to be extracted to the "cachedb" folder: [cachedb.zip](https://github.com/NLnetLabs/unbound/files/4397214/cachedb.zip)

Bye

**Comment by Talkabout** [comment]
Hi @gthess ,

I guess this issue can be closed now.

Bye

**Comment by gthess** [comment]
Fixed with https://github.com/NLnetLabs/unbound/pull/206
