### ISSUE TITLE
"rrset-roundrobin" option to 'Yes' by default

### ISSUE THREAD

**Issue by iz8mbw** [NLnetLabs/unbound#215]
Hi.
I propose for next release of unbound to set by default to "Yes" the option `rrset-roundrobin`.

Based on my test, when for an A record there are multiple IPs, unbound gives "the IP list" with always the same order for each query until the TTL expires.
For me this does not make much sense because the client that makes query will have always the same "IP list" and will not benefit of the possibility to use multiple IP for the connection that will go to establish (because for example will always goes to use the first one IP in the list).

Then, since I expect that the "upstream" DNS server supports round robin, if in unbound the default value for `rrset-roundrobin` is "No", the unbound clients will "lost" this feature.

And, also if the "upstream" DNS server does not support round robin but provide multiple IPs, with `rrset-roundrobin` set to "Yes" we will go to make this great feature come to life.  :-)

I cannot understand a reason to leave `rrset-roundrobin` set to "No" by default.

Thank you.

**Comment by gthess** [comment]
Hi,
I also brought this up for discussion on the mailing list and the consensus is to change the default to yes.

So closing this issue with https://github.com/NLnetLabs/unbound/commit/226d66ca9258c4e47b1e549ef9ab5e12c4925771.

**Comment by iz8mbw** [comment]
Thanks for you effort.
The right decision was taken.

**Comment by gthess** [comment]
@mibere I got the following github email notification relating to this issue:
>Seems that after the release of version 1.10.1 the documentation at https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/ is not up-to-date.

       rrset-roundrobin: <yes or no>
              If yes, Unbound rotates RRSet order in response (the random num-
              ber  is  taken  from the query ID, for speed and thread safety).
              Default is no.

but I can't seem to find that in github, so I am replying here.
1.10.1 is a security release addressing specific CVEs. For these releases we only include code that fixes those security issues. 1.10.1 is supposed to be 1.10.0 + the security fixes. Whatever code was currently in the master branch needs to wait for a later release. That is why the default rrset-roundrobin is not updated with 1.10.1.
I hope that clears things up.

**Comment by mibere** [comment]
@gthess Thanks for your response. Your explanation is the reason why you can't find my comment, I've deleted it.
