### ISSUE TITLE
Main PID: 5606 (code=exited, status=1/FAILURE)

### ISSUE THREAD

**Issue by raidoo9** [NLnetLabs/unbound#217]
Hi everyone,

Trying to set up Unbound on Raspbian and coming across the following errors on install. Hope someone can shed some light.

Thanks

> **Job for unbound.service failed because the control process exited with error code.
See "systemctl status unbound.service" and "journalctl -xe" for details.
Job for unbound.service failed because the control process exited with error code.
See "systemctl status unbound.service" and "journalctl -xe" for details.
invoke-rc.d: initscript unbound, action "start" failed.**
  **Process: 5606 ExecStart=/usr/sbin/unbound -d $DAEMON_OPTS (code=exited, status=1/FAILURE)
 Main PID: 5606 (code=exited, status=1/FAILURE)**

>  systemctl status unbound.service
? unbound.service - Unbound DNS server
   Loaded: loaded (/lib/systemd/system/unbound.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sat 2020-04-11 14:49:59 BST; 6min ago
     Docs: man:unbound(8)
  Process: 5916 ExecStartPre=/usr/lib/unbound/package-helper chroot_setup (code=exited, status=0/SUCCESS)
  Process: 5919 ExecStartPre=/usr/lib/unbound/package-helper root_trust_anchor_update (code=exited, status=0/SUCCESS)
  Process: 5924 ExecStart=/usr/sbin/unbound -d $DAEMON_OPTS (code=exited, status=1/FAILURE)
 Main PID: 5924 (code=exited, status=1/FAILURE)
Apr 11 14:49:59 pi systemd[1]: unbound.service: Main process exited, code=exited, status=1/FAILURE
Apr 11 14:49:59 pi systemd[1]: unbound.service: Failed with result 'exit-code'.
Apr 11 14:49:59 pi systemd[1]: Failed to start Unbound DNS server.
Apr 11 14:49:59 pi systemd[1]: unbound.service: Service RestartSec=100ms expired, scheduling restart.
Apr 11 14:49:59 pi systemd[1]: unbound.service: Scheduled restart job, restart counter is at 8.
Apr 11 14:49:59 pi systemd[1]: Stopped Unbound DNS server.
Apr 11 14:49:59 pi systemd[1]: unbound.service: Start request repeated too quickly.
Apr 11 14:49:59 pi systemd[1]: unbound.service: Failed with result 'exit-code'.
Apr 11 14:49:59 pi systemd[1]: Failed to start Unbound DNS server.

> journalctl -xe
-- Support: https://www.debian.org/support
--
-- A stop job for unit unbound-resolvconf.service has finished.
--
-- The job identifier is 1765 and the job result is done.
Apr 11 14:49:59 pi systemd[1]: Stopped Unbound DNS server.
-- Subject: A stop job for unit unbound.service has finished
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A stop job for unit unbound.service has finished.
--
-- The job identifier is 1705 and the job result is done.
Apr 11 14:49:59 pi systemd[1]: unbound.service: Start request repeated too quickly.
Apr 11 14:49:59 pi systemd[1]: unbound.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unbound.service has entered the 'failed' state with result 'exit-code'.
Apr 11 14:49:59 pi systemd[1]: Failed to start Unbound DNS server.
-- Subject: A start job for unit unbound.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unbound.service has finished with a failure.
--
-- The job identifier is 1705 and the job result is failed.
Apr 11 14:49:59 pi systemd[1]: unbound-resolvconf.service: Start request repeated too quickly.
Apr 11 14:49:59 pi systemd[1]: unbound-resolvconf.service: Failed with result 'start-limit-hit'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unbound-resolvconf.service has entered the 'failed' state with result 'start-limit-hit'.
Apr 11 14:49:59 pi systemd[1]: Failed to start Unbound DNS server via resolvconf.
-- Subject: A start job for unit unbound-resolvconf.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unbound-resolvconf.service has finished with a failure.
--
-- The job identifier is 1765 and the job result is failed.
Apr 11 14:50:02 pi CRON[5973]: pam_unix(cron:session): session opened for user root by (uid=0)
Apr 11 14:50:02 pi CRON[5977]: (root) CMD (   PATH="$PATH:/usr/local/bin/" pihole updatechecker local)
Apr 11 14:50:02 pi CRON[5973]: pam_unix(cron:session): session closed for user root
Apr 11 14:52:23 pi dhcpcd[600]: eth0: Router Advertisement from 
Apr 11 14:52:27 pi dhcpcd[600]: eth0: Router Advertisement from 
Apr 11 14:56:35 pi dhcpcd[600]: eth0: Router Advertisement from

**Comment by bjovereinder** [comment]
Dear raidoo9,

You can direct these questions to our Unbound community mailing list.  GitHub issues are ment for reporting bugs and for feature requests.  

General questions about Unbound, it’s configuration, behaviour, etc., can be posted on the Unbound community mailing list,  https://lists.nlnetlabs.nl/mailman/listinfo/unbound-users.

You will find excellent support and feedback from the Unbound community on your questions. 

Best regards,

— Benno
