### ISSUE TITLE
RPZ zones with .rpz-nsdname records not applied 

### ISSUE THREAD

**Issue by spirillen** [NLnetLabs/unbound#219]
Hey Guys, seems like I have found a bug in the RPZ system and my RPZ-zone files with `.rpz-nsdname` records

```
*.parkingcrew.net.rpz-nsdname.rpz.mypdns.cloud. 86400   IN      CNAME   .
```

Next step is to test this and reproduce the error.

First lets take a domain `kickasstorrent.ph` and verify it is located at `*.parkingcrew.net`

```
dig kickasstorrent.ph -t ns @9.9.9.9 +short
ns2.parkingcrew.net.
ns1.parkingcrew.net.
```

Next step is the reproducing the error

```
dig kickasstorrent.ph @127.0.0.1 -p 53 +short
185.53.178.54
```

according to the [RFC](https://datatracker.ietf.org/doc/html/draft-vixie-dns-rpz-04#section-4.4) this should had returned a NXDOMAIN and not a IP-addresses to the hijacked domain. I know the record is working on Bind and the [recursor](https://www.powerdns.com/recursor.html) but it fails on all my unbound setups :unamused: and that sucks as i have left out a lot of records do to the `*.example.org.rpz-nsdname.rpz.mypdns.cloud. CNAME .`

**Comment by ralphdolmans** [comment]
As documented in the man page, only the QNAME and Response IP Address triggers are **currently** supported.

You might also be able to find something like this in your log:
```RPZ: skipping unsupported trigger: nsdname```

**Comment by spirillen** [comment]
Hi @ralphdolmans thanks for your reply, I haven't noticed that part I'm afraid :unamused: 

Let me put it this way like a cartoon what I think right now `)(/%(/¤%&¤#%¤"¤#%&` I should have noticed that....

is there by any change you have an idea about when the full RPZ is implanted?

**Comment by Zjemm** [comment]
Two things

Is it needed the way domains are put in the zone file like:

$ORIGIN rpz.nlnetlabs.nl.
drop.example.com.rpz.nlnetlabs.nl. CNAME rpz-drop.

Why the trailing part after the actual domain?

In bind this isn’t the case
So when doing a zone transfer from bind to unbound for a rpz zone. Does it convert and add that trailing part?
Or does the zone that is going to be transferred have to apply to a certain standard?

In that case nsdname should be filtered out When doing a transfer

**Comment by spirillen** [comment]
Is this still an issue on unbound?? as I've come to understand, then you have finally incorporated the full RPZ rule set (https://datatracker.ietf.org/doc/html/draft-vixie-dns-rpz-04#section-4.4).

In that case you can close this issue, also I haven't been either using or testing unbound since this issue was opened as I come to stick with powerdns as they supported all of the RPZ, so please close if this is solved

**Comment by wcawijngaards** [comment]
Yes, unbound currently supports the RPZ rules. Also nsip and clientip triggers, and also the different actions.
