### ISSUE TITLE
Excessive logging of failed sends

### ISSUE THREAD

**Issue by dermoth** [NLnetLabs/unbound#224]
Yesterday during a strange network glitch unbound started streaming 30mbps of syslog messages from my tiny home OpenWRT-based router...

The logs comes from this block:

https://github.com/NLnetLabs/unbound/blob/226d66ca9258c4e47b1e549ef9ab5e12c4925771/util/netevent.c#L373-L384

You will see more details on the issue, including logged messages, in this bug report: https://github.com/openwrt/packages/issues/11904

Unless there is a better way to rate-limit these messages I think raising the verbosity level for these could be considered.

**Comment by tobiasmcnulty** [comment]
Posted on https://github.com/openwrt/packages/issues/11904 as well, but this might be related to #35?

**Comment by EricLuehrsen** [comment]
please see how openwrt/packages#12141 has resolved this

**Comment by EricLuehrsen** [comment]
@wcawijngaards and @ralphdolmans this is still an issue in Unbound 1.12.0

**Comment by gthess** [comment]
This should have been fix with https://github.com/NLnetLabs/unbound/commit/addd21f750b6042c40c2a92aef9b8919d8497532.
It squelches the permission denied errors on the lower verbosity levels.
Will be part of the upcoming 1.13.2 release.
