### ISSUE TITLE
Unbound not resolving certain domains

### ISSUE THREAD

**Issue by Spanishu** [NLnetLabs/unbound#238]
I am facing a strange problem. I have installed unbound on a raspberry pi 4 following the pi-hole instructions https://docs.pi-hole.net/guides/unbound/

It worked fine for years and without any further problem. Since approx 2 weeks I have troubles to resolve Facebook related domains (sometimes) as well as microsoft. 

here a dig example 
`dig www.instagram.com @127.0.0.1 -p 5335
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.11.5-P4-5.1-Raspbian <<>> www.instagram.com @127.0.0.1 -p 5335
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 31420
;; flags: qr rd ra; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;www.instagram.com.		IN	A

;; ANSWER SECTION:
www.instagram.com.	3600	IN	CNAME	z-p42-instagram.c10r.facebook.com.
z-p42-instagram.c10r.facebook.com. 27739 RESERVED0 A \# 4 1F0D53AE

;; Query time: 30 msec
;; SERVER: 127.0.0.1#5335(127.0.0.1)
;; WHEN: Thu May 21 10:20:15 CEST 2020
;; MSG SIZE  rcvd: 106
`

yesterday for example I was not able to access teams.microsoft.com when I then switched to google dns it resolved without any further problem.

**Comment by wcawijngaards** [comment]
The output of the dig shows that the A record is from an rrset class that is in the reserved range, this is wrong it should be IN.  Unbound likely echoes that from the upstream server message.  It is therefore likely that if you enable verbosity 4 and look at unbound's logs of the resolution, that unbound logs receiving that awkward record from the upstream server when it asks for that.

In any case if you switch on verbosity 4 you can see that happens, and also the individual, dig-style messages and output in the logs when answers are received.  Then you can skip through those logs and look at what unbound received when it asked that question.  This can help uncover what happened.

Best regards, Wouter

**Comment by Spanishu** [comment]
Hi, 

here are the results from Syslog Unfortunately the logging did not work well on the initial test. FYI the first lookup was successful it was the second one which had the problems. 

[Syslog.txt](https://github.com/NLnetLabs/unbound/files/4675674/Syslog.txt)

**Comment by wcawijngaards** [comment]
So from that syslog.txt, you receive, twice records with CLASS value 0 rrsets in them.  Also the root trust anchor fails to prime with signature verification failure.  That would make all queries SERVFAIL with DNSSEC failure.  Also there are timeouts, where no response is received.

From <whatsapp.com.> 66.111.49.12
May 25 08:45:46 pihole unbound[27513]: web.whatsapp.com.#01130736#011CLASS0#011C
NAME#011mmx-ds.cdn.whatsapp.net.

And later from <cdn.whatsapp.net.> 129.134.31.11
May 25 08:45:46 pihole unbound[27513]: mmx-ds.cdn.whatsapp.net.#01130780#011CLASS0#011A#01131.13.83.51

In that above `#011` is a tab, syslog puts that instead.

Unbound is asking for the CLASS IN records, but gets replies in with CLASS0 (a value of zero in the class field, which is not supposed to happen in ordinary query answer packets).

Additionally, I see May 25 08:45:45 pihole unbound[27513]: [1590389145] unbound[27513:0] info: failed to prime trust anchor -- DNSKEY rrset is not secure . DNSKEY IN
with before that the DNSSEC fail reason: verify: signature mismatch

And you have timeouts in response to queries.  So the upstream servers are not responding to you, or only intermittently.

Unbound fails to look up, but it looks like everything is wrong.  Not getting answers.  Answers with simply some sort of format error, class 0.  And wrong answers, in the DNSSEC sense, the data is not correct.

If I try to fetch data from whatsapp, I do not receive CLASS0 or timeouts from them.  You could try to perform a dig manually for the packets that seem to have responses that unbound cannot work with, it looks like that would then also give the wrong data to that dig output manually.  Unbound cannot really create the correct answer for you if it only gets answers with the wrong contents.

**Comment by Spanishu** [comment]
I just tried 
`dig web.whatsapp.com @8.8.8.8
;; Warning: Message parser reports malformed message packet.

; <<>> DiG 9.11.5-P4-5.1+deb10u1-Raspbian <<>> web.whatsapp.com @8.8.8.8
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 21405
;; flags: qr aa cd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
;; WARNING: Message has 4070 extra bytes at end

;; QUESTION SECTION:
;web.whatsapp.com.              IN      A

;; ANSWER SECTION:
web.whatsapp.com.       30736   RESERVED0 CNAME mmx-ds.cdn.whatsapp.net.

;; Query time: 1 msec
;; SERVER: 8.8.8.8#53(8.8.8.8)
;; WHEN: Mon May 25 09:47:53 CEST 2020
;; MSG SIZE  rcvd: 4157`

It is a bit bizarre to me. for your answer, what do you suggest I do ?

**Comment by wcawijngaards** [comment]
I guess it worked before for you because you enabled TLS for unbound upstream connection and that stops the DNS packets from getting changed, simply because it uses a different transport mechanism.

But I do not know what causes your answers to get mangled.  Does not really look like it is a wrong answer, I get the same CNAME answer, but not malformed, here.  If you are on a network where you need to sign up, sometimes they do this to stop people that have not paid from accessing the network, and the intent may be that 'everything works' after the sign up, but perhaps some buggy software is not so good, eg. does not send DNSSEC signatures is what I have seen before.  Not the malformed packets that you have.

**Comment by Spanishu** [comment]
Could you tell me how to enable TLS for upstream? I would like to try to see what happens if I enable.
I am working on my "normal" home network. I am wondering if there might be something wrong with my router?

**Comment by wcawijngaards** [comment]
TLS upstream with `tls-upstream: yes` (for all upstreams) or `forward-tls-upstream: yes` (for the servers in that forward statement).  There are more servers that support TLS if you search for that.

The packets are wrong, I do not know what device could have done it.

**Comment by Spanishu** [comment]
I tried to add the tls-upstream: yes or the alternative to unbound.conf however I get an error when starting
`May 25 11:53:31 pihole systemd[1]: unbound.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unbound.service has entered the 'failed' state with result 'exit-code'.
May 25 11:53:31 pihole systemd[1]: Failed to start Unbound DNS server.
-- Subject: A start job for unit unbound.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unbound.service has finished with a failure.
--
-- The job identifier is 3539 and the job result is failed.
May 25 11:53:31 pihole systemd[1]: unbound-resolvconf.service: Start request repeated too quickly.
May 25 11:53:31 pihole systemd[1]: unbound-resolvconf.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- The unit unbound-resolvconf.service has entered the 'failed' state with result 'exit-code'.
May 25 11:53:31 pihole systemd[1]: Failed to start Unbound DNS server via resolvconf.
-- Subject: A start job for unit unbound-resolvconf.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
--
-- A start job for unit unbound-resolvconf.service has finished with a failure.
--
-- The job identifier is 3600 and the job result is failed.
May 25 11:53:34 pihole kernel: Voltage normalised (0x00000000)
May 25 11:53:36 pihole sudo[1359]:      xxx : TTY=pts/0 ; PWD=/etc/unbound ; USER=root ; COMMAND=/bin/journalctl -xe
May 25 11:53:36 pihole sudo[1359]: pam_unix(sudo:session): session opened for user root by xxx(uid=0)`

**Comment by wcawijngaards** [comment]
Try unbound-checkconf for syntax errors.  Or look at the syslog to see if it printed the syntax errors in the config file.  If your unbound version is very old, the TLS upstream is not there, upgrade or use a package like getdns or stubby.

**Comment by Spanishu** [comment]
I tried to downgrade the firmware of my router. For the moment it seems like it is working. I will monitor and post back

Have run it now for 24hours and no faillure at all. The problem was the router firmware.
Router Movistar Fiber in Spain
Firmware downgrade to Version 43

All problems solved
