### ISSUE TITLE
About python support

### ISSUE THREAD

**Issue by vp1981** [NLnetLabs/unbound#242]
Hello,
there are two configure options related with python: `--with-pyunbound` and `--with-pythonmodule`. Due to lack of documentation it is unclear what these options are do. Correct me if I'm wrong but AFAIU, the `--with-pythonmodule` means that `unbound` will be build with python scripting support, i.e. one may call python script to "extend" unbound or change the output of running `unbound` application (that's how I understand the examples in `pythonmod/{,doc/}examples`). The `--with-pyunbound` option is opposite: it enables to build the python "library" which allows one to perform some task from (standalone) python script.

If I'm right could someone enlighten me why if I pass options `--without-pythonmodule --with-pyunbound` to build only a (standalone) python module the `libunbound.so*` becomes linked with `libpython`? Is it necessary and without linking `libunbound.so` with `libpython` the python module (files located in `/usr/lib/pythonX.Y/site-packages`, namely `_unbound.so` and `unbound.py`) won't work? Is it possible to build unbound with python module without linking `libunbound.so` with `libpython`?

P.S. I'm using Archlinux and considering to use "hash-slinger" but it requires unbound python modules. I asked to provide python module for unbound package but package maintainer don't like that in this case `libunbound.so` is linked with `libpython` ("... really too big a hard dependency for such as small package as unbound ...") and though I made a workaround for this I would like in first place to know why there are two options and what they are do.

**Comment by yan12125** [comment]
> Is it necessary

Apparently not. I created a patch to skip libpython for this case: https://github.com/NLnetLabs/unbound/pull/511
