### ISSUE TITLE
Unbound requires reload to answer queries

### ISSUE THREAD

**Issue by JLT032** [NLnetLabs/unbound#244]
Following a list of difficutties with Unbound responding investigation showed when any change to the up-down of the interface and/or an ACL on the gateway changes from _non-block to block to non-block_ this requires a `unbound-control reload`

I am unaware of any setting which may influence this so i report it as a possible issue to mitigate.

**Comment by aletheia7** [comment]
Maybe related to #248.

**Comment by gthess** [comment]
Hi,
which version of unbound is that? Do you see anything interesting in the logs during that time?

**Comment by gthess** [comment]
Closing this. Feel free to ping me here if you have more information and you want this reopened.
