### ISSUE TITLE
Remove DLV entirely from Unbound

### ISSUE THREAD

**Issue by vrisk** [NLnetLabs/unbound#246]
Hey, I could be mistaken, but it seems like you might still have the DLV option in Unbound. If you do, it is time to remove it.

1.5.4 changed the default settings and removed the ISC DLV key from the packages - which is great, but at this point, any resolver that is querying the DLV is going extra work for zero added value. At this point there is an empty zone at dlv.isc.org, just so that resolvers querying it won't get stuck in a loop re-querying it.  It would be better to remove the DLV from Unbound entirely.  We removed it from BIND as of BIND 9.16 (the 2020 stable version), which has the added benefit of simplifying our code.

**Comment by wcawijngaards** [comment]
Hi Vicky,
Yes that sounds like it is a good idea, we should really remove the obsolete DLV functionality from Unbound too.  At version 1.5.4 (in 2015) we put in advice, in manual pages, for people to stop using it.

**Comment by wcawijngaards** [comment]
There is code in progress on this branch: https://github.com/NLnetLabs/unbound/tree/dlv-removal  This aims to remove DLV, but makes the dlv option ignored and print a warning.

**Comment by wcawijngaards** [comment]
Thanks for the heads up and the code has been modified for upcoming releases to remove the leftover DLV functionality.  If people still have DLV options it prints a warning.  Since the DLV repository is empty, that is the same validation end result anyway.
