### ISSUE TITLE
ssl handshake failed crypto error

### ISSUE THREAD

**Issue by nfour14** [NLnetLabs/unbound#253]
Hi! 
I was using version 1.6.6 and moved to 1.10.1 - I am using the same unbound.conf file and get the following error:

unbound-checkconf[104679:0] fatal error: module_conf lists module 'ipsecmod' but that module is not available.

I have the resolver setup for DNS over TLS. Has that module been deprecated? 

Was this supposed to be compiled beforehand?

**Comment by nfour14** [comment]
Fixed. Had to add --enable-ipsecmon

I can start unbound - but I am getting:

ssl handshake failed crypto error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed

This happens on every lookup.

**Comment by gthess** [comment]
These are verification failures for the TLS part.

As you are building unbound from source you need to make sure that:
- `tls-cert-bundle:` is set to a CA bundle file (usually .crt) on unix/linux variants. You can find and use your system's one or download one you trust.
- `tls-win-cert: yes` if you are on windows and want to use the system installed certificates.
Both of these options are mentioned in the `forward-tls-upstream:` option in the `unbound.conf` manpage.

Also make sure that the name you are using for verifying the forwarders is the correct one. More info on available public DoT resolvers can be found at https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Public+Resolvers.

If you still can't solve the issue, pasting your configuration would help.

**Comment by nfour14** [comment]
Understood - I will recompile and try again.

**Comment by rtmgllc** [comment]
Well, for some reason its looking in /etc/unbound for the config files instead of /usr/local/etc/unbound - the former is where the older version that came with the CentOS package manager has its config files. How can I get unbound to look at /usr/local/etc/unbound? Did it have to be compiled for that?

**Comment by nfour14** [comment]
Looks like it wants /etc/unbound as the config file location, which is where yum puts the config files for the older version. I had the config files in /usr/local/etc/unbound for the 1.10.1 version. Looks like it uses the former. Working now.
