### ISSUE TITLE
Help wanted. Add dns servers

### ISSUE THREAD

**Issue by hissssst** [NLnetLabs/unbound#258]
Hello, I've recently started using `unbound` as my local dns server. I was wondering about how to add DNS servers to resolve special domains

For example, I want to resolve `*.ygg` domains (like `example.ygg` or `sub.website.ygg`) via external ipv6 DNS servers

I've added following lines to configuration but it doesn't seem to work
```
forward-zone:
	name: "ygg."
	forward-addr: 303:8b1a::53
	forward-addr: 301:2522::53
	forward-addr: 301:2923::53
	forward-addr: 300:4523::53
```

**Comment by ralphdolmans** [comment]
That configuration will forward all queries for ygg and all subdomains (including example.ygg and sub.website.ygg) to the configured addresses. Can you give us some more information on what does not work?

**Comment by hissssst** [comment]
It doesn't forward DNS queries to these addresses. The problem can be that these IPs are [Yggdrasil's](https://github.com/yggdrasil-network/yggdrasil-go) one's and are routed by `yggdrasil.service`. I've tried changing the service startup order but this didn't solve anything

My sniffer shows that only `1.1.1.1` and `8.8.8.8` are queried

My forward zone looks like
```
forward-zone:
	name: "."
	forward-addr: 1.1.1.1
	forward-addr: 8.8.8.8
	forward-addr: 200:8993:bb44:e1f3:bde7:6234:3f3e:fdd1
 	forward-addr: 303:8b1a::53
 	forward-addr: 301:2522::53
 	forward-addr: 301:2923::53
 	forward-addr: 300:4523::53
```

Could it be some missing configuration option?

**Comment by ralphdolmans** [comment]
Did you try to send queries to these addresses directly, to make sure they are reachable?

The unbound log might give you more information on why these addresses are not selected.

**Comment by hissssst** [comment]
Yes, I've tried them and they are working. How do I read the unbound log?

**Comment by hissssst** [comment]
@ralphdolmans 

```
# unbound -vvvvvvvv -d -c /etc/unbound/unbound.conf                                           ~
[1595236242] unbound[91255:0] notice: Start of unbound 1.10.1.
[1595236242] unbound[91255:0] debug: increased limit(open files) from 1024 to 4152
[1595236242] unbound[91255:0] debug: creating udp6 socket ::1 53
[1595236242] unbound[91255:0] debug: creating tcp6 socket ::1 53
[1595236242] unbound[91255:0] debug: creating udp4 socket 127.0.0.1 53
[1595236242] unbound[91255:0] debug: creating tcp4 socket 127.0.0.1 53
[1595236242] unbound[91255:0] debug: creating tcp4 socket 127.0.0.1 8953
[1595236242] unbound[91255:0] debug: setup SSL certificates
[1595236242] unbound[91255:0] debug: switching log to syslog
```

Starting unbound with logging gives no info on why these addresses are not queried

**Comment by ralphdolmans** [comment]
Hi, the last line indicates that Unbound will continue logging to syslog. Please check that log (or set `use-sylog` to no) for information on the used addresses.

**Comment by ralphdolmans** [comment]
Closing this one as this does not seem to be an Unbound bug. Feel free to use the unbound-users mailing list (https://lists.nlnetlabs.nl/mailman/listinfo/unbound-users) if you have questions about your Unbound configuration.
