### ISSUE TITLE
unbound-checkconf does not check view existence

### ISSUE THREAD

**Issue by Ridorix** [NLnetLabs/unbound#259]
`unbound-checkconf` does not check if the `view` exists when it defined by `access-control-view`.

So, when executing `unbound-control reload` this command reports `ok` and restarts the service.

But the service actually stops and can't start with the error:
`error: no view with name: test_zone_01`
`fatal error: Could not setup access control list`

Version: 1.10.1

**Comment by wcawijngaards** [comment]
Thanks for the report, added code to check that and a number of other statements for access control views and tags.
