### ISSUE TITLE
no work restart  or reload  (use dnstap)

### ISSUE THREAD

**Issue by glomazdov** [NLnetLabs/unbound#262]
Use 1.10.0
I am using socat to redirect from socket to TCP.
unbound conf:
dnstap-socket-path: "/var/run/unbound/dnstap.socket"
socat conf:
socat -d -d UNIX-LISTEN: /usr/local/var/run/unbound/dnstap.socket,reuseaddr,fork TCP: XX.XX.XX.XX: 6000
All work until I restart or reload unbound.
In the log I see: unbound [35876: 0] notice: closing dnstap socket.
and nothing happens until I manually restart socat
How to make it work.

**Comment by wcawijngaards** [comment]
The upcoming release fixes dnstap for making reconnections when the connection is lost.  This code is already available in the code repository, the master branch.  This likely fixes your issue.

**Comment by wcawijngaards** [comment]
The new version can also directly write to tcp, by the way, with the (new) config option `dnstap-ip: <IPaddress[@port]>`.  And also you can use TLS.

**Comment by glomazdov** [comment]
I saw new functionality. When can I wait for the release?
