### ISSUE TITLE
Unbound control reload failed

### ISSUE THREAD

**Issue by fivehundredmiless** [NLnetLabs/unbound#266]
After the first time unbound is reload the unbount-control port 8953 is gone,What causes this problem thanks.

**Unbound version 1.10.1**

**unbound.conf** 

cat etc/unbound/unbound.conf 
server:
	# verbosity number, 0 is least verbose. 1 is default.
	verbosity: 1
	# printed from unbound-control. default off, because of speed.
	# extended-statistics: no
	interface: 0.0.0.0
	port: 53
	# access-control: 127.0.0.0/8 allow
remote-control:
	control-enable: yes
	control-interface: 127.0.0.1
	control-port: 8953
	# control-use-cert: "yes"

The output is as below

./sbin/unbound-control -c etc/unbound/unbound.conf

netstat -lntup | egrep -w "53|8953"
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      30207/./sbin/unboun 
tcp        0      0 127.0.0.1:8953          0.0.0.0:*               LISTEN      30207/./sbin/unboun 
udp        0      0 0.0.0.0:53              0.0.0.0:*                           30207/./sbin/unboun

1. The first time to reload 
./sbin/unbound-control -c etc/unbound/unbound.conf reload
ok

netstat -lntup | egrep -w "53|8953"
tcp        0      0 0.0.0.0:53              0.0.0.0:*               LISTEN      30207/./sbin/unboun 
udp        0      0 0.0.0.0:53              0.0.0.0:*                           30207/./sbin/unboun

2. ./sbin/unbound-control -c etc/unbound/unbound.conf reload
[1594823183] unbound-control[30443:0] error: connect: Connection refused for 127.0.0.1 port 8953

After the reload command is execute and the port 8953 is gone，plz give me some help,thanks.

**Comment by ralphdolmans** [comment]
Looks like a chroot issue, as described in this issue: https://github.com/NLnetLabs/unbound/issues/46#issuecomment-510454567

Please check if the configuration file is available in the chroot directory.
