### ISSUE TITLE
ed25519 signed domains fail

### ISSUE THREAD

**Issue by Ferine2016** [NLnetLabs/unbound#271]
Tested on unbound 1.10.1 compiled against OpenSSL 1.0.2u-freebsd . (Freebsd 11.4)
The domains "europris.no" and "ed25519.nl" fail resolution since they are only ed25519 signed.
Unbound compiled against newer OpenSSL resolve as expected.

is this intended behaviour from unbound?

drill -DT www.europris.no A @127.0.0.1
;; Number of trusted keys: 1
;; Domain: .
[T] . 172800 IN DNSKEY 256 3 8 ;{id = 46594 (zsk), size = 2048b}
. 172800 IN DNSKEY 257 3 8 ;{id = 20326 (ksk), size = 2048b}
Checking if signing key is trusted:
New key: .      172800  IN      DNSKEY  256 3 8 AwEAAdauOGxLhfAKFTTZwGhBXbk793QKdWIQRjiSftWdusCwkPhNyJrIjwtNffCWXGLlZAbpcs414RE3oS1qVwV+AdXsO92SBu5haGlxMUk0NqZO7Xlf84/wrzGZVRRouPo5pNX/CKS8Mv9UOi0olKGCu31dNfh8qCszWZcloLDgeLzSnQSkvFoGe69vNCfh7feESKedkBC2qRz0BZv9+oJI0IY/3D7WEnV0NOlf8gSHozhfJFJ/ZAKtvw/Q3ogrVJFk0LyVaU/NVtVA5FM4pVMIRID7pfrPi78aAzG7b/Wh/Pce4jPAIpS3dApq25YkvMuPvfB91NMf9FemKwlp78PBVcM= ;{id = 46594 (zsk), size = 2048b}
        Trusted key: .  86400   IN      DNSKEY  257 3 8 AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU= ;{id = 20326 (ksk), size = 2048b}
        Trusted key: .  172800  IN      DNSKEY  256 3 8 AwEAAdauOGxLhfAKFTTZwGhBXbk793QKdWIQRjiSftWdusCwkPhNyJrIjwtNffCWXGLlZAbpcs414RE3oS1qVwV+AdXsO92SBu5haGlxMUk0NqZO7Xlf84/wrzGZVRRouPo5pNX/CKS8Mv9UOi0olKGCu31dNfh8qCszWZcloLDgeLzSnQSkvFoGe69vNCfh7feESKedkBC2qRz0BZv9+oJI0IY/3D7WEnV0NOlf8gSHozhfJFJ/ZAKtvw/Q3ogrVJFk0LyVaU/NVtVA5FM4pVMIRID7pfrPi78aAzG7b/Wh/Pce4jPAIpS3dApq25YkvMuPvfB91NMf9FemKwlp78PBVcM= ;{id = 46594 (zsk), size = 2048b}
Key is now trusted!
        Trusted key: .  172800  IN      DNSKEY  257 3 8 AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU= ;{id = 20326 (ksk), size = 2048b}
[T] no. 86400 IN DS 29471 8 2 915ede46ea5324ff86b11c9ed4e9c814ae8c462c165e5380a3999d90418841da
;; Domain: no.
[T] no. 3600 IN DNSKEY 256 3 8 ;{id = 35961 (zsk), size = 1024b}
no. 3600 IN DNSKEY 257 3 8 ;{id = 29471 (ksk), size = 2048b}
Checking if signing key is trusted:
New key: no.    3600    IN      DNSKEY  256 3 8 AwEAAeO4tN2O6OwWqW1Rhy5IjzWorLlZSa8Y/ldX9cv5u+kjaDPVrb9AMYBCzhSVdOKOADXtnqTXrrCtElvflcbdqLyAqBGT96HkndpJ1wOA+grkJTw4Wbe9DArc3FH584/84MzutvxwtidyEM9tgTbhyBMfyjTwGCeqsVJj7wLA/t2v ;{id = 35961 (zsk), size = 1024b}
        Trusted key: .  86400   IN      DNSKEY  257 3 8 AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU= ;{id = 20326 (ksk), size = 2048b}
        Trusted key: .  172800  IN      DNSKEY  256 3 8 AwEAAdauOGxLhfAKFTTZwGhBXbk793QKdWIQRjiSftWdusCwkPhNyJrIjwtNffCWXGLlZAbpcs414RE3oS1qVwV+AdXsO92SBu5haGlxMUk0NqZO7Xlf84/wrzGZVRRouPo5pNX/CKS8Mv9UOi0olKGCu31dNfh8qCszWZcloLDgeLzSnQSkvFoGe69vNCfh7feESKedkBC2qRz0BZv9+oJI0IY/3D7WEnV0NOlf8gSHozhfJFJ/ZAKtvw/Q3ogrVJFk0LyVaU/NVtVA5FM4pVMIRID7pfrPi78aAzG7b/Wh/Pce4jPAIpS3dApq25YkvMuPvfB91NMf9FemKwlp78PBVcM= ;{id = 46594 (zsk), size = 2048b}
        Trusted key: .  172800  IN      DNSKEY  257 3 8 AwEAAaz/tAm8yTn4Mfeh5eyI96WSVexTBAvkMgJzkKTOiW1vkIbzxeF3+/4RgWOq7HrxRixHlFlExOLAJr5emLvN7SWXgnLh4+B5xQlNVz8Og8kvArMtNROxVQuCaSnIDdD5LKyWbRd2n9WGe2R8PzgCmr3EgVLrjyBxWezF0jLHwVN8efS3rCj/EWgvIWgb9tarpVUDK/b58Da+sqqls3eNbuv7pr+eoZG+SrDK6nWeL3c6H5Apxz7LjVc1uTIdsIXxuOLYA4/ilBmSVIzuDWfdRUfhHdY6+cn8HFRm+2hM8AnXGXws9555KrUB5qihylGa8subX2Nn6UwNR1AkUTV74bU= ;{id = 20326 (ksk), size = 2048b}
        Trusted key: no.        3600    IN      DNSKEY  256 3 8 AwEAAeO4tN2O6OwWqW1Rhy5IjzWorLlZSa8Y/ldX9cv5u+kjaDPVrb9AMYBCzhSVdOKOADXtnqTXrrCtElvflcbdqLyAqBGT96HkndpJ1wOA+grkJTw4Wbe9DArc3FH584/84MzutvxwtidyEM9tgTbhyBMfyjTwGCeqsVJj7wLA/t2v ;{id = 35961 (zsk), size = 1024b}
Key is now trusted!
        Trusted key: no.        3600    IN      DNSKEY  257 3 8 AwEAAZ/4Gp4JK9sYmX+LXKB8VpudlotL7/534h85e2QXzrgfFTP+5odzXGo4BaIpu2FgH64o/TiDtyVoRxcMEQqj7DouY/as/0OMWd3wVIzGTNdX62WzTgVpZe9tjDPbBb6NO5dNUwMpHfM0g+RuM+v4KSH2Rj+kwCJoh34loFbE3+M8YmlTlrJiqJINE6XLw7PDIUpV+uM/qanoxBqHwRKfrRgQUH3v6zIliDZj7VuCTACU77Fu8+v8L1C7Epz5HDa+wHa8RMSvNQA9HJwFwZE3pzWIVDV34CWVyua63wtdof9e29gjhbkKqVMuQCdz49XmqhQQ0gYzYOGMZTnY/pskTVs= ;{id = 29471 (ksk), size = 2048b}
[T] europris.no. 7200 IN DS 25323 15 2 86b83842718f2ae110875d154b18a2e1150b231d0fb4b5d7d5e5051ddae72ae5
europris.no. 7200 IN DS 25323 15 4 f97845f1a6988d4ab8bcb1b1cbbc4cb1e95c17b197ae1354bc580a0a48a0d054b2100acb400fea0c6eb70c5ff3d7cf53
;; Domain: europris.no.
;; Signature ok but no chain to a trusted key or ds record
[S] europris.no. 3600 IN DNSKEY 257 3 15 ;{id = 25323 (ksk), size = 0b}
europris.no. 3600 IN DNSKEY 256 3 13 ;{id = 14997 (zsk), size = 256b}
europris.no. 3600 IN DNSKEY 256 3 15 ;{id = 39946 (zsk), size = 0b}
europris.no. 3600 IN DNSKEY 257 3 13 ;{id = 46820 (ksk), size = 256b}
;; No DS for www.europris.no.;; No ds record for delegation
;; Domain: www.europris.no.
;; No DNSKEY record found for www.europris.no.
[U] No data found for: www.europris.no. type A
;;[S] self sig OK; [B] bogus; [T] trusted

**Comment by Ferine2016** [comment]
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=248239

**Comment by gthess** [comment]
If unbound is compiled with a version of OpenSSL that does not support ed25519, then a domain that is only signed with ed25519 is treated as insecure.
So this is expected behavior.

The output you shared is from drill and that has its own rules and extra checks on top of unbound (especially with the -T option).

**Comment by vdukhovni** [comment]
The only thing that's perhaps unfortunate in the output reported by `drill(1)` is that when using *both* of the `-D` and `-T` options it does not report unvalidated answers.  For example, `drill -D -T www.google.com` does not show the A records, while `drill -D` and `drill -T` do.

**Comment by Ferine2016** [comment]
Thanks for the clarification.
I have been in contact with domeneshop.no (largest dns host in norway) and they are in the process of resigning all of domains with ed25519. Estimated complete in 3 months.

This will lead to breakage for all unbound installations compiled against old OpenSSL.

I would suggest adding more even more warnings when compiling/running Unbound with deprecated OpenSSL versions.

**Comment by vdukhovni** [comment]
> Thanks for the clarification.
> I have been in contact with domeneshop.no (largest dns host in norway) and they are in the process of resigning all of domains with ed25519. Estimated complete in 3 months.
> 
> This will lead to breakage for all unbound installations compiled against old OpenSSL.
> 
> I would suggest adding more even more warnings when compiling/running Unbound with deprecated OpenSSL versions.

Are you sure they'll be signing with *ONLY* ed25519?  That sounds exceedingly unwise at the moment.  There are still many validating resolvers that don't support it yet.

The result would not be "breakage", rather many domains would no longer appear to be signed. So it would be a significant degradation of security, but not "breakage" as such.

Is there somewhere a public statement from domeneshop that details their plans?

**Comment by vdukhovni** [comment]
All I've found [is](https://domene.shop/faq?id=274):
```
For de teknisk interesserte kan vi opplyse om at Domeneshop signerer alle DNSSEC-soner ved hjelp av
algoritme 13 (ECDSAP256SHA256) eller 15 (ED25519) med NSEC3. Signaturene har en levetid på
30 dager, og nøklene rulleres hver 3. måned (ZSK) og 12. måned (KSK). Det er ikke mulig å spesifisere
individuelle parametere eller algoritmer når man benytter DNSSEC på Domeneshops navnetjenere.
```
Which says "13 or 15", but it is rather unclear what they mean by that.

**Comment by Ferine2016** [comment]
Answer i got from domeneshop support:
--------------------------------------------
Vi har signert mange toppnivådomener med ED25519 siden i fjor høst, men det er ikke før i de siste par ukene at vi har begynt å signere .no-domener med denne algoritmen.

Vi rullerer nøkler hver tredje måned, så innen tre måneder vil alle .no-domener være resignert.

OpenSSL 1.0.2 LTS var forøvrig end-of-life 31. desember 2019. Dette, kombinert med at alle de store åpne resolverne (Cloudflare, Google, Quad9, osv) i løpet av de siste årene nå støtter ED25519 er grunnen til at vi har valgt å gå over til denne signeringsalgoritmen.
------------------------------------------

**Comment by vdukhovni** [comment]
If true, that's a pretty "aggressive" move on their part. I think it is somewhat premature, and would have waited a year or two more, unless they don't mean "only" algorithm 15, and will actually sign with *both* 13 and 15.

Looking at the underlying DANE/DNSSEC survey data, out of 12 million domains only 53.3 thousand have just algorithm 15 DS RRs. It is far from widely used.  Though perhaps the fact that 3 of those domains are:
```
domeneshop.nl
domeneshop.nu
domeneshop.se
```
suggests that they may indeed be moving in that direction faster than I'd have expected...

**Comment by ralphdolmans** [comment]
Some numbers that might be of interest: our dnsthought measurements show that algorithm 13 (66.7%) [0]  is roughly as well supported as algorithm 8 (67.5%) [1].  Algorithm 15 has not the same level of adoption yet with 51.9% [2].

[0] - https://dnsthought.nlnetlabs.nl/#ecdsa256
[1] - https://dnsthought.nlnetlabs.nl/#rsasha256
[2] - https://dnsthought.nlnetlabs.nl/#ed25519

**Comment by Ferine2016** [comment]
Ive sent this ticket to domeneshop and asked them to for their input, so hopefully they will clarify further what their plans are.

**Comment by vdukhovni** [comment]
> Some numbers that might be of interest: our dnsthought measurements show that algorithm 13 (66.7%) [0] is roughly as well supported as algorithm 8 (67.5%) [1]. Algorithm 15 has not the same level of adoption yet with 51.9% [2].
> 
> [0] - https://dnsthought.nlnetlabs.nl/#ecdsa256
> [1] - https://dnsthought.nlnetlabs.nl/#rsasha256
> [2] - https://dnsthought.nlnetlabs.nl/#ed25519

That's good data, thanks!  It sure looks like ~33% of resolvers don't validate at all, and then RSASHA256(8) and ECDSAP256(13) are pretty much universally supported by resolvers that do any  validation at all.  Which suggests that ED25519 is supported by ~52/67 or ~77% of validating resolvers. Not bad, but not quite enough yet in my book.

**Comment by wtoorop** [comment]
Op 28-07-2020 om 10:19 schreef Viktor Dukhovni:
>     Some numbers that might be of interest: our dnsthought measurements
>     show that algorithm 13 (66.7%) [0] is roughly as well supported as
>     algorithm 8 (67.5%) [1]. Algorithm 15 has not the same level of
>     adoption yet with 51.9% [2].
> 
>     [0] - https://dnsthought.nlnetlabs.nl/#ecdsa256
>     [1] - https://dnsthought.nlnetlabs.nl/#rsasha256
>     [2] - https://dnsthought.nlnetlabs.nl/#ed25519
> 
> That's good data, thanks! It sure looks like ~33% of resolvers don't
> validate at all, and then RSASHA256(8) and ECDSAP256(13) are pretty much
> universally supported by resolvers that do any validation at all. Which
> suggests that ED25518 is supported by ~52/67 or ~77% of validating
> resolvers. Not bad, but not quite enough yet in my book.

You can do this selection within the dnsthought pages too.
Here is the graph of ED25519 support for all resolvers that can validate
RSASHA256 (which must be supported, because the root is signed with it):

	https://dnsthought.nlnetlabs.nl/can_rsasha256/#ed25519

So 71.2%.

98% can validate EXDSA-P256-SHA256:

	https://dnsthought.nlnetlabs.nl/can_rsasha256/#ecdsa256

Results are based on measurements against the RIPE Atlas probes
configured resolvers.  Here is a page containing a list of measurements
used with dnsthought: https://dnsthought.nlnetlabs.nl/raw/

**Comment by Ferine2016** [comment]
Recieved followup from domeneshop:
------------

Hei,

Planen vår er å gå over til algoritme 15 (ed25519) etter hvert som vi rullerer de gamle nøklene slik at om et års tid så bruker vi bare ed25519. Vi er klar over at det fremdeles er en del validerende resolvere som ikke støtter denne algoritmen, men samtidig så er det også en stor andel resolvere som ikke gjør dnssec-validering overhodet. Prosenttallene for Norge er forøvrig en del høyere enn verdensgjennomsnittet, både når det gjelder andelen resolvere som validerer og andelen validerende resolvere som forstår algoritme 15.

Store leverandører som Google (8.8.8.8) og CloudFlare (1.1.1.1) har støttet ed25519 siden 2018, og OpenSSL 1.0.x hadde EOL i desember 2019, slik at det er mange rundt omkring nå som er nødt til å oppgradere til OpenSSL 1.1.x. Da vil de automatisk få støtte for ed25519.

**Comment by vdukhovni** [comment]
> ## Recieved followup from domeneshop: [...]

Which Google-translate renders quite well into English:
```
Our plan is to switch to algorithm 15 (ed25519) as we roll out the
old keys so that in a year's time we will only use ed25519. We are
aware that there are still a number of validating resolvers that
do not support this algorithm, but at the same time there are also
a large proportion of resolvers that do not do dnssec validation
at all. The percentages for Norway are otherwise somewhat higher
than the world average, both in terms of the proportion of resolvers
that validate and the proportion of validating resolvers that
understand algorithm 15.

Major vendors such as Google (8.8.8.8) and CloudFlare (1.1.1.1)
have supported ed25519 since 2018, and OpenSSL 1.0.x had EOL in
December 2019, so there are many around now who will have to upgrade
to OpenSSL 1.1 .x. Then they will automatically get support for
ed25519.
```
So I guess they're moving ahead. Cool. I hope it goes well. Anyway unbound handles this properly. If built with OpenSSL 1.1.1, it can validate such domains. If built with older releases, it'll be able to resolve them as unsigned (without validation).
