### ISSUE TITLE
Publishing the windows exe to chocolatey

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#274]
Hello, i really love this software (on linux), so when i had to use windows i have searched for it on chocolatey (repository for windows) but i don't have found it.

So i just want to know if its possible to publish it to chocolatey so we can also have update more easily
thanks !!

**Comment by wcawijngaards** [comment]
For Linux packages, we rely on maintainers that port the source code to the packages.  Also for BSD ports.  So for Windows that would be the same.  So, publishing it needs a package maintainer for the Windows binaries for the package repository.

The source code can be compiled to windows binary, the instructions are here.
https://github.com/NLnetLabs/unbound/blob/master/winrc/README.txt
Currently that supports 32 and 64 bit and maybe windows versions back to very long ago (95/98/XP, but also 7/8/10).  Unbound uses mingw to compile for Windows.  There are instructions how to compile with mingw on windows itself, and you could have a package that compiles from source if you want, similar to other distros that compile from source.

This mostly relies on some support to be present to run ./configure there, and the mingw compiler (and libexpat, libcrypto, libssl).  The binaries on our website (provided as a convenience, but without a lot of testing or support), are created with a cross compile with the mingw compiler packages from Linux.  And you can do this too, with `mingw64-configure` from the source directory.

The source code has the BSD license, and Unbound is free, open source software.
More information here, https://www.nlnetlabs.nl/projects/unbound/about/

**Comment by ghost** [comment]
Thanks for the answer i will see on the chocolatey community to find a maintainer for the binaries.
