### ISSUE TITLE
[rpz] check logic for RPZ records are subdomain of configured zone?

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#276]
>Version 1.11.0
Configure line: --target=arm-openwrt-linux --host=arm-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix= --program-suffix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls --disable-dsa --disable-gost --enable-allsymbols --enable-ecdsa --enable-tfo-client --enable-tfo-server --with-libexpat=/builder/shared-workdir/build/sdk/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr --with-ssl=/builder/shared-workdir/build/sdk/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr --with-user=unbound --with-run-dir=/var/lib/unbound --with-conf-file=/var/lib/unbound/unbound.conf --with-pidfile=/var/run/unbound.pid --enable-ipset --with-libmnl=/builder/shared-workdir/build/sdk/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr --enable-event-api --with-libevent=/builder/shared-workdir/build/sdk/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr --with-pthreads
Linked libs: pluggable-libevent 2.1.11-stable (it uses epoll), OpenSSL 1.1.1g  21 Apr 2020
Linked modules: dns64 ipset respip validator iterator
TCP Fastopen feature available

```
rpz:
	name: "urlhaus.abuse.ch"
        url: https://urlhaus.abuse.ch/downloads/rpz
	rpz-log: yes
	rpz-log-name: urlhaus
```
___

with the above setup the log prints

>error: RPZ: name of record to insert into RPZ is not a subdomain of the configured name of the RPZ zone

which seems to be invoked by the check implemented in https://github.com/NLnetLabs/unbound/commit/28e6c86e618985a9359da4af77370b9dad3295ae

Somehow it does not make sense (seem logic) that the records provided through a RPZ have to be subdomains of the configured zone origin, it kind of defeats the purpose of such RPZ.

**Comment by gthess** [comment]
That log message was because of an error in the downloaded rpz zonefile. I see that now it is already fixed.
The error was that one of the domains was not a relative subdomain to the rpz zone, but rather an absolute domain name from the root .i.e.:
```
example.com  CNAME .   ; correct record
example.com. CNAME .   ; wrong record
```
That was an invalid record and the whole zone parsing was cancelled.

In higher verbosity level you could see the parsing error.
However I will update the current error log message to also show the domains in question.

>Somehow it does not make sense (seem logic) that the records provided through a RPZ have to be subdomains of the configured zone origin, it kind of defeats the purpose of such RPZ.

The records provided through rpz are subdomains of the rpz zone (as you see in the downloaded rpz zone file).
There is logic to extract the correct domain based on the rpz domain and apply the rpz action.

**Comment by ghost** [comment]
Thank you for the feedback. How to view downloaded rpz zone files if `zonefile:` is not used, `unbound-cotrol` does not seem to offer a related command option?

**Comment by gthess** [comment]
There is no way to see the file if you don't use `zonefile:`.
However in your case (since it's a url) you can just get the file itself at https://urlhaus.abuse.ch/downloads/rpz/.
`unbound-control list_auth_zones` will also list the rpz zones (as they are technically treated as auth_zones).

**Comment by ghost** [comment]
In general I would preferably utilise `zonefile:` but on one of my nodes it is currently no possible (OpenWrt by default compiles the kernel without FSACL and the zone-files are to be stored outside *unbound*'s chroot).

Anyway, `unbound-control list_auth_zones` lists the RPZ indeed but just not their content - maybe something to consider implementing in the future
