### ISSUE TITLE
[feature suggestion | rpz] local source zone

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#281]
A look at the current RPZ ecosystem https://dnsrpz.info and search for free public RPZ feed provider is rather sobering. Ideally I would wish *unbound* for being capable to convert feeds from various sources into a RPZ  and automatically maintains/updates them, something like https://github.com/Homas/ioc2rpz does. 

Short of that it would be at least helpful if *unbound* could leverage local RPZ files that would not need to be served through either a http server or an authoritative zone server. `stub-zone:` or `local-zone` would not seem suitable for providing a local RPZ, or would either one?

Also it would likely be easier to convert sources feeds to an RPZ file rather than converting into `stub-zone:` or `local-zone` and to dynamically update such zones after each feed conversion.

**Comment by ralphdolmans** [comment]
> Ideally I would wish _unbound_ for being capable to convert feeds from various sources into a RPZ and automatically maintains/updates them, something like https://github.com/Homas/ioc2rpz does.

I don't think we should add this to Unbound. The de facto standard for loading filtering policies into DNS resolvers is RPZ. In case your policy provider does not provide the information in RPZ format it makes more sense to me to have the conversion done using an external tool, like the one you mentioned. In that case, not all different resolver implementations have to support the endless number of possible formats.

> Short of that it would be at least helpful if _unbound_ could leverage local RPZ files that would not need to be served through either a http server or an authoritative zone server. `stub-zone:` or `local-zone` would not seem suitable for providing a local RPZ, or would either one?

Unbound's RPZ implementation can already load the zones from a local file, using its `zonefile` configuration option.

**Comment by ghost** [comment]
>Unbound's RPZ implementation can already load the zones from a local file, using its `zonefile` configuration option.

I was not aware of that, apparently, reading from documentation

>If  the  file  does not exist or is empty, unbound will attempt to fetch zone data  (eg.  from  the  master servers).

been under the impression that only fetched zone data (`master` | `url`) could be leveraged.
