### ISSUE TITLE
[bug report | rpz] Domainname length overflow

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#285]
> Version 1.11.0
> 
> Configure line: --target=arm-openwrt-linux --host=arm-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix= --program-suffix= --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-dsa --disable-gost --enable-allsymbols --enable-subnet --with-libexpat=/home/beast/beast/workspace/turris-os-packages-lions-omnia/build/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr --with-ssl=/home/beast/beast/workspace/turris-os-packages-lions-omnia/build/staging_dir/target-arm_cortex-a9+vfpv3-d16_musl_eabi/usr --without-pthreads --enable-tfo-server --enable-tfo-client
> Linked libs: pluggable-event internal (it uses select), OpenSSL 1.1.1g  21 Apr 2020
> Linked modules: dns64 subnetcache respip validator iterator
> TCP Fastopen feature available
___
RPZ file https://block.energized.pro/ultimate/formats/rpz.txt

contains

`paypal.com.us.continue.myaccount.account.active.login.us.intl.internationa.transfer.now.login.myaccount.account.active.login.us.intl.internationa.transfer.now.myaccount.account.active.login.us.intl.internationa.transfer.now.newmanhope.duckdns.org CNAME .`

which appears to be a valid domain, according to https://dnschecker.org/#A/paypal.com.us.continue.myaccount.account.active.login.us.intl.internationa.transfer.now.login.myaccount.account.active.login.us.intl.internationa.transfer.now.myaccount.account.active.login.us.intl.internationa.transfer.now.newmanhope.duckdns.org
___
unbound log prints

>error: block.energized.pro/ultimate/formats/rpz.txt parse failure RR[256]: Domainname length overflow in 'paypal.com.us.continue.myaccount.account.active.login.us.intl.internationa.transfer.now.login.myaccount.account.active.login.us.intl.internationa.transfer.now.myaccount.account.active.login.us.intl.internationa.transfer.now.newmanhope.duckdns.org CNAME .'

As a consequence it seems that *unbound* seems not to be discarding the entire RPZ, least it is not saving the `zonefile` and entries from that RPZ are being resolved nonetheless despite *unbound* log printing

>info: RPZ applied

**Comment by gthess** [comment]
This is a limitation of RPZ.

DNS domain names have a maximum size (https://tools.ietf.org/html/rfc1034#section-3.1)
>To simplify implementations, the total number of octets that represent a
domain name (i.e., the sum of all label octets and label lengths) is
limited to 255.

In this case the domain name is valid (248 length) but in RPZ this needs to be a subdomain of the RPZ zone. If you use a smaller name for the RPZ zone it may fit i.e., `123456.` works.

The consequence you see is that unbound stops further parsing at this point. This means that records before the parsing error are available (blocked) while records at and after the parsing error are not available. Writing the zonefile is also skipped.

**Comment by ghost** [comment]
a bit of chicken and egg problem it seems, in two aspects:

* RPZ zone domain not being subtracted from the 255 count
* *unbound* not saving the zonefile (and thus not user editable) plus not blocking entries from the RPZ
____
>This means that records before the parsing error are available (blocked)

that is not my observation, whilst the log printing 

>info: RPZ applied

records listed prior to the one causing the parsing error are not being NX but getting their IPs resolved.

**Comment by ghost** [comment]
>If you use a smaller name for the RPZ zone it may fit i.e., `123456`. works.

That is fine until some (bad) actor, who else would go literally to such url length, comes up with a 255 url length and which would cause the issue all over again. 

I think *unbound* should discard/discount the RPZ zone label in order to avoid this case.

**Comment by gthess** [comment]
>RPZ zone domain not being subtracted from the count

This cannot happen. RPZ data is valid zone data with added logic for the actions. The domain name needs to adhere to DNS limitations.

>That is fine until some (bad) actor, who else would go literally to such url length, comes up with a 255 url length and which would cause the issue all over again.

This is a known limitation of RPZ. The RPZ producer can work around it by specifying a zone name and making sure that all RPZ records are within the limits by applying wildcards for example.

>I think unbound should discard/discount the RPZ zone label in order to avoid this case.

This is not how RPZ works.

>unbound not saving the zonefile (and thus not user editable) plus not blocking entries from the RPZ

Unbound thinks the zone contains garbage and stops processing. You can get the zonefile from the URL, edit it and then give it to unbound with `zonefile:` and without `url:` (or `master:`). But that defeats the purpose of auto updating RPZ data.

----
Could you verify the blocking behavior of the records before and after the parsing error? The behavior I get locally is the one I mentioned above:
records before the parsing error are available (blocked) while records at and after the parsing error are not available (and thus not blocked).

**Comment by ghost** [comment]
Sure, but the RPZ producer does not know the length of the RZP zone label set by the user - another chicken and egg place...
Anyway, I hope it will not come to that 255 case, or something exceeding this 248 case because I do not constantly monitor the *unbound* logs. 
___
>Could you verify the blocking behaviour of the records

Ouhm, have to backtrack from my previous statement since used a browser with some security add-ons that would display a warning for some of the malicious domains I picked randomly and thus led to believe that domain been resolved when indeed it was not :facepalm:
