### ISSUE TITLE
[feature request] Drop AAAA on IPv4-only Network

### ISSUE THREAD

**Issue by kmahyyg** [NLnetLabs/unbound#312]
There's still a lot IPv4-only network or the IPv6 connectivity is super worse than IPv4, 
So we need an option to drop all AAAA response and try to request A response if trying to get some DNS record.

Please add an options for users to drop all AAAA if user specified: `do-ipv6: no` or you might want to add a new config option.

Thanks.

**Comment by hdais** [comment]
1. Apply AAAA-filter patch in contrib/aaaa-filter-iterator.patch.

2. Try this configuration - it drops all AAAA records in response messages.

`server:`
       `private-address: ::/0`

**Comment by mmiller7** [comment]
> `server:`
> `private-address: ::/0`

Just want to say THANK YOU for this!  It seems to have worked on pfSense Unbound DNS Resolver...and seemed to result in a massive speedup web browsing on my IPv4-only ISP not having devices trying to use IPv6 responses.

**Comment by bcookatpcsd** [comment]
Sorry to necro-post.. 

it seems w/o the patch this configuration addition blocks receiving AAAA responses.. 

(in Oct 2025 even with the new iterator.patch) I couldn't get the aaaa-filter option to be respected, but this option worked even on unpatched Unbound

Alpine stock 1.23.1 unbound with: 

```
 unbound -V
Version 1.23.1

Configure line: --build=x86_64-alpine-linux-musl --host=x86_64-alpine-linux-musl , etc
```

```
private-address: ::/0
```

```
 drill -p 5353 -t aaaa www.google.com @::1
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 34141
;; flags: qr rd ra ; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 0
;; QUESTION SECTION:
;; www.google.com.	IN	AAAA

;; ANSWER SECTION:

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:

;; Query time: 43 msec
;; SERVER: ::1
;; WHEN: Sun Nov  2 11:07:37 2025
;; MSG SIZE  rcvd: 32
```
Does the patch provide something further?

**Comment by gthess** [comment]
Yes, the patch usually removes AAAA records right when receiving the upstream response (like `private-address: ::/0`). Unless the query itself was for AAAA and Unbound knows (extra A query if needed) that there is no A record next to it.

If you just want to NOT return AAAA to clients, then using:
```
server:
    module-config: "respip validator iterator"
    response-ip: ::/0 redirect
```
is the better approach, since it will correctly cache the complete answer but at the last moment remove the AAAA records before replying to clients.

**Comment by bcookatpcsd** [comment]
I was trying to be a better netizen and simply not ask for something that I'm not going to use.. (saving resources all around)

I was trying to prevent the upstream from even being asked.. because ultimately it will be discarded or removed..

**Comment by gthess** [comment]
Currently you can't block/filter AAAA incoming queries to Unbound.
If Unbound does not connect over IPv6 you can use `do-ip6: no` to prevent Unbound itself from trying to connect to IPv6 nameservers. Incoming AAAA queries will still be resolved by Unbound though.
