### ISSUE TITLE
unbound-control-setup creates TLS certificates without SANs

### ISSUE THREAD

**Issue by jprenken** [NLnetLabs/unbound#316]
The unbound-control-setup script creates TLS certificates without the subjectAlternativeName extension. Some clients (notably Golang 1.15+) complain or won't validate these certificates.

@bastelfreak created a patch here that solves this issue for me: https://github.com/kumina/unbound_exporter/issues/20

**Comment by bastelfreak** [comment]
oh that patch worked for you? nice! I need to test this again. It creates a proper SAN certifucate, but the exporter didnt want to connect to umbound. maybe that was caused by the exporter, not unbound.

**Comment by jprenken** [comment]
I think I found the problem. This additional line is needed for the server certificate (i.e. the first segment of your patch):

`-addext "basicConstraints=critical,CA:TRUE,pathlen:0" \`

Go 1.15 now expects and enforces a `basicConstraints` extension for CA certificates.

**Comment by jprenken** [comment]
Additional note: `-addext` requires OpenSSL 1.1.1.
