### ISSUE TITLE
potential memory leak on config failure

### ISSUE THREAD

**Issue by magenbluten** [NLnetLabs/unbound#319]
the region created here: https://github.com/NLnetLabs/unbound/blob/52b04806f4236c37acd10179ab465a54adc7e86a/services/rpz.c#L388

does not get free'd in the `err` handling path: https://github.com/NLnetLabs/unbound/blob/52b04806f4236c37acd10179ab465a54adc7e86a/services/rpz.c#L435

assuming the region could be created but one of the following actions fails.

**Comment by wcawijngaards** [comment]
Thanks for the review!  That is a good fix, committed in https://github.com/NLnetLabs/unbound/commit/a87f05be7b36c7c45eca249dfd9d998e31770a34 for the next release.
