### ISSUE TITLE
potential memory corruption due to size miscomputation upton custom region alloc init

### ISSUE THREAD

**Issue by magenbluten** [NLnetLabs/unbound#320]
here we allocate a fresh region with a user provided `size` value:

https://github.com/NLnetLabs/unbound/blob/52b04806f4236c37acd10179ab465a54adc7e86a/util/regional.c#L86

this `size` value gets aligned to the neccessary alignment requirements. but this happens _after_ the malloc. thus `size` 
can now be larger than what was actually allocated:

https://github.com/NLnetLabs/unbound/blob/52b04806f4236c37acd10179ab465a54adc7e86a/util/regional.c#L87
https://github.com/NLnetLabs/unbound/blob/52b04806f4236c37acd10179ab465a54adc7e86a/util/regional.c#L90

**Comment by gthess** [comment]
Seems like it indeed, thanks!
