### ISSUE TITLE
unbound testsuite fails on mock build in systemd-nspawn if systemd support is build

### ISSUE THREAD

**Issue by bleve** [NLnetLabs/unbound#323]
test suite fails in mock when using systemd-snawn continaier for build when unbound is build with --enable-systemd. testsuite works fine if unbound is build without systemd support.

I guess test suite should disable use of notify.

Version 1.12.0.

**Comment by wcawijngaards** [comment]
The fix should remove the issue, it unsets the environment variable that systemd uses to enable the notification.  I guess this variable is somehow set for the entire container, instead of just for the server startup.
