### ISSUE TITLE
Auth zone: unbound stop resolving when insecure + prefetch-key

### ISSUE THREAD

**Issue by ArnGa** [NLnetLabs/unbound#328]
Hello,
This issue is a continuation of issue 254 but I haven't figured out how to re-open.
Currently I am using version 1.11.0 and reproducing this bug again.
This time around I was able to further debug the problem and I think I found the conditions causing it.
The problem concerns "auth-zones", for example configured like this:
auth-zone:
name: "xxx.fr"
zonefile: /var/lib/unbound/zones/xxx.fr
master: A.B.C.D
allow-notify: A.B.C.D
for-downstream: no
for-upstream: yes
fallback-enabled: yes

I use certain zones only internally and I have therefore declared them in "insecure-zone":
domain-insecure: "xxx.fr"

In my configuration, I'm in prefetch for the DS keys:
prefetch-key: yes

With these conditions, starting from an empty cache, if I request in loop, I realize that after the TTL expiration of the requested record the behavior is not the same:
- for the domain which is not listed as insecure, Unbound checks the DS, caches the response and responds to the client (OK);
- for the domain which is listed as insecure, Unbound still tries to check the DS (!), does not succeed and then responds NXDOMAIN to the client (NOK).

If I disable the prefetch-key:
prefetch-key: no
For both types of domains (insecure or not), the behavior is OK.
So I have the impression that with the combination "auth-zone + prefetch-keys: yes", Unbound does not respect the "domain-insecure" directive for the concerned domain.

Hoping to have been clear enough.
Regards

**Comment by ArnGa** [comment]
I add an element.
If I disable the "fallback-enabled: yes" directive for the internal zone (insecure), then I get good operation regardless of whether the prefetch-key is enabled or not.

**Comment by gthess** [comment]
Disabling `fallback-enabled` for "internal" auth-zones is the correct solution. An enabled fallback will allow Unbound to try and resolve those "internal" zones on the internet where they most probably will get a DNSSEC verified NXDOMAIN response.
Closing this as a non issue :)
Feel free to reopen/tag.
