### ISSUE TITLE
unbound-host hangs on “mail.cpanelssltest.org”

### ISSUE THREAD

**Issue by FGasper** [NLnetLabs/unbound#33]
```
unbound-host mail.cpanelssltest.org
```
This query takes about 45 seconds before `unbound-host` prints the result—but then the command still doesn’t exit.

`dig +trace` executes the same query almost instantaneously.

Seen in v1.9.1 on macOS.

**Comment by wcawijngaards** [comment]
For me that takes 12.5 minutes, and then it exits.  With -ddd it prints debug information about what is going on.  It prints about lots of timeouts and that servers are lame for the delegation.

Dig is a different tool, and it performs a fast debug lookup with a short timeout, that you can configure from the commandline, as well as the number of retries.

The domain is sure broken and this takes a long time, but I am not sure what I can do about it.  I think your (similar) post on unbound-users is a good idea, it may elicit help from others about it.

**Comment by FGasper** [comment]
At a minimum, shouldn’t `unbound-host` exit once it has its answer?

**Comment by wcawijngaards** [comment]
Wait, and then I notice, unbound-host printed something useful, the IPv4 address.  But it was hanging on the lookups for AAAA and MX records.  You can instruct unbound-host to only perform a lookup for type 'A', the IPv4 address, with -t A as commandline argument.  That takes 35 seconds for me.

**Comment by wcawijngaards** [comment]
So what happens (a reply to your comment about exit), is that it looks up the A record in 35 seconds.  The servers for the domain won't answer for type AAAA and MX (IPv6 and mail record) and this creates timeouts.  With exponential backoff those become large, and unbound tries multiple servers multiple times.  This takes a long time.

**Comment by FGasper** [comment]
Ahh, ok; I didn’t realize it was doing an all-records lookup. That explains the hang.

**Comment by wcawijngaards** [comment]
Yes, it performs three lookups.

**Comment by FGasper** [comment]
Even so, it seems this should not take 35 seconds.

- `dig @a.root-servers.net mail.cpanelssltest.org A`
- `dig @d0.org.afilias-nst.org mail.cpanelssltest.org A`
- `dig @ssldns1.cpanel.net mail.cpanelssltest.org A`

That provides an answer; libunbound seems just to be ignoring the A record that’s given alongside the CNAME from ssldns1.cpanel.net?

**Comment by wcawijngaards** [comment]
Yes it does, it ignores the records given alongside CNAME (and also for DNAMEs). This is the anti-poison protection mechanism.  You cannot disable it, because otherwise it would be vulnerable (to the 'Kaminsky' poison attack sequence).  And what unbound does is lookup the record by itself.

Unbound thus looks up every component of a lookup chain, by itself.  That should exist.  Lookup chains (chains of aliases) should not exist only in one packet, but the components have to exist on their own lookups.

**Comment by FGasper** [comment]
Ahh, ok. I didn’t know about that.

Thank you for such prompt and helpful responses here; I’ll close this issue.
