### ISSUE TITLE
[Feature request] Add unencrypted DNS over HTTPS support

### ISSUE THREAD

**Issue by triatic** [NLnetLabs/unbound#330]
When Apache is already running on a server and owns port 443, it is common for it to forward DNS over HTTPS queries to a local unencrypted DNS over HTTPS server or reverse proxy.

For this reason, my request is for Unbound to add support for unencrypted DNS over HTTPS connections.

**Comment by wcawijngaards** [comment]
Added the option `http-notls-downstream: yesno` and if you enable that it should perform no tls http service.  The dohclient test has the `-n` commandline option to make it perform a no tls connection to the server.

**Comment by triatic** [comment]
Perfect, thanks.
