### ISSUE TITLE
unbound-anchor segfault

### ISSUE THREAD

**Issue by icebluey** [NLnetLabs/unbound#331]
Env:
Unbound 1.12.0
RHEL 7.9
Linux kernel 5.9.1

$ dmesg | grep -i unbound
[ 2070.554617] unbound-anchor[2211]: segfault at 7ffe67404a98 ip 00007f684168dc08 sp 00007ffe67404aa0 error 6 in libunbound.so.8.1.10[7f684163d000+8e000]

I do not run any unbound commands, and do not why this error is coming up.
How can I fix this?

further info
In /var/log/meaasge : 
systemd: Starting update of the root trust anchor for DNSSEC validation in unbound...
systemd: unbound-anchor.service: main process exited, code=killed, status=11/SEGV
kernel: unbound-anchor[80126]: segfault at 7ffef400de78 ip 00007f46ad5ac5b8 sp 00007ffef400de80 error 6 in libunbound.so.8.1.10[7f46ad55c000+8d000]
kernel: Code: 40 00 41 57 41 89 ff 41 56 49 89 f6 41 55 49 89 cd 41 54 49 89 d4 55 53 48 81 ec 78 28 00 00 8b 3d e5 2a 08 00 48 8d 5c 24 70 <e8> c3 05 fb ff 4c 89 e9 4c 89 e2 be 00 28 00 00 48 89 df 48 89 c5
systemd: Failed to start update of the root trust anchor for DNSSEC validation in unbound.
systemd: Unit unbound-anchor.service entered failed state.
systemd: unbound-anchor.service failed.

**Comment by gthess** [comment]
Hi,

`unbound-anchor` is a small program that checks and updates (if needed) the DNS root trust anchor.
You don't run this but systemd runs it for you before starting unbound.

If you look at `/usr/lib/systemd/system/` you should find a `unbound.service` file with a line like:
```
ExecStartPre=-/usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -c /etc/unbound/icannbundle.pem
```
That is the line that starts `unbound-anchor` before `unbound`.
_The file locations may be different in your machine._

To see what is happening with the segfault I would need you to run the same command as root under `gdb`, something like the following:
```
sudo gdb -ex=run --args /usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -c /etc/unbound/icannbundle.pem
```
_If the file locations are different in your `unbound.service` file please use them instead of the example above. Make sure to *not include* the dash ('-') at the start of the ExecStartPre command._

This should produce the same segfault as the one you are seeing in your log file. By then typing `bt` in the current running gdb you should be able to get a stacktrace. That will give me more information on what is happening.

**Comment by icebluey** [comment]
> Hi,
> 
> `unbound-anchor` is a small program that checks and updates (if needed) the DNS root trust anchor.
> You don't run this but systemd runs it for you before starting unbound.
> 
> If you look at `/usr/lib/systemd/system/` you should find a `unbound.service` file with a line like:
> 
> ```
> ExecStartPre=-/usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -c /etc/unbound/icannbundle.pem
> ```
> 
> That is the line that starts `unbound-anchor` before `unbound`.
> _The file locations may be different in your machine._
> 
> To see what is happening with the segfault I would need you to run the same command as root under `gdb`, something like the following:
> 
> ```
> sudo gdb -ex=run --args /usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -c /etc/unbound/icannbundle.pem
> ```
> 
> _If the file locations are different in your `unbound.service` file please use them instead of the example above. Make sure to _not include_ the dash ('-') at the start of the ExecStartPre command._
> 
> This should produce the same segfault as the one you are seeing in your log file. By then typing `bt` in the current running gdb you should be able to get a stacktrace. That will give me more information on what is happening.

Hi,
It is unbound-anchor.service problem.

# good unbound-anchor.service
[Service]
Type=oneshot
#User=unbound
ExecStart=/usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -c /etc/unbound/icannbundle.pem -f /etc/resolv.conf -R

# failed unbound-anchor.service
[Service]
Type=oneshot
User=unbound
ExecStart=/usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -c /etc/unbound/icannbundle.pem -f /etc/resolv.conf -R


Unbound was built with '--with-username=unbound' .
Why can not run as unbound user?

unbound user was created
$ getent passwd unbound
unbound:x:999:999:Unbound DNS resolver:/etc/unbound:/sbin/nologin

**Comment by gthess** [comment]
`unbound-anchor` needs write access to the `/var/lib/unbound/root.key` but I suspect that based on the location of the file, the `unbound` user has the correct permissions.

`--with-username=unbound` only affects unbound itself, not the accompanying programs like `unbound-anchor`.

Could you run
```
/usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -c /etc/unbound/icannbundle.pem -f /etc/resolv.conf -R -vvvv
```
as both `root` and `unbound` user and paste the output here?

**Comment by icebluey** [comment]
## run as root user in terminal:
`# /usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -c /etc/unbound/icannbundle.pem -f /etc/resolv.conf -R -vvvv`
/var/lib/unbound/root.key has content  
success: the anchor is ok

## unbound is a nologin user, so I run as unbound in systemd(set User=unbound in unbound-anchor.service), here is the error output:
polkitd\[2980\]: Registered Authentication Agent for unix-process:3120:367221 (system bus name :1.105 \[/usr/bin/pkttyagent --notify-fd 5 --fallback\], object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en\_US.UTF-8)

systemd\[1\]: Starting update of the root trust anchor for DNSSEC validation in unbound...

-- Subject: Unit unbound-anchor.service has begun start-up

-- Defined-By: systemd

-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- 

-- Unit unbound-anchor.service has begun starting up.

kernel: unbound-anchor\[3126\]: segfault at 7ffc0a81528c ip 00007fedafc84f6a sp 00007ffc0a815270 error 6 in libunbound.so.8.1.10\[7fedafc26000+106000\]

kernel: Code: 55 48 89 e5 8b 05 9e f7 11 00 85 c0 75 07 b8 00 00 00 00 eb 07 48 8d 05 94 f7 11 00 5d c3 55 48 89 e5 53 48 81 ec a8 28 00 00 <89\> bd 6c d7 ff ff 48 89 b5 60 d7 ff ff 48 89 95 58 d7 ff ff 48 89

systemd\[1\]: unbound-anchor.service: main process exited, code=killed, status=11/SEGV

systemd\[1\]: Failed to start update of the root trust anchor for DNSSEC validation in unbound.

-- Subject: Unit unbound-anchor.service has failed

-- Defined-By: systemd

-- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel

-- 

-- Unit unbound-anchor.service has failed.

-- 

-- The result is failed.

systemd\[1\]: Unit unbound-anchor.service entered failed state.

polkitd\[2980\]: Unregistered Authentication Agent for unix-process:3120:367221 (system bus name :1.105, object path /org/freedesktop/PolicyKit1/AuthenticationAgent, locale en\_US.UTF-8) (disconnected from bus)

systemd\[1\]: unbound-anchor.service failed.

**Comment by gthess** [comment]
You can use sudo to run as the unbound user.

Can you try
```
sudo -u unbound gdb -ex=run --args /usr/sbin/unbound-anchor -a /var/lib/unbound/root.key -c /etc/unbound/icannbundle.pem -f /etc/resolv.conf -R -vvvv
```
This may provide the same segfault. If that is so, you can type `bt` while in gdb to get the stack trace.

**Comment by gthess** [comment]
Closing this as inactive; feel free to reopen/ping.
