### ISSUE TITLE
the anchor is NOT ok Error and cannot allocate memory to rcvbuf/sndbuf

### ISSUE THREAD

**Issue by Gil80** [NLnetLabs/unbound#332]
Trying to resolve some errors with Unbound.

**After a system reboot**
`package-helper[512]: fail: the anchor is NOT ok and could not be fixed`
I have to run `sudo systemctl restart unbound` to get `package-helper[1148]: success: the anchor is ok` each time after a system restart.

The Unbound command lists the following issues:
`unbound[1218:0] warning: so-rcvbuf 4194304 was not granted. Got 360448. To fix: start with root permissions(linux) or sysctl bigger net.core.rmem_max(linux) or kern.ipc.maxsockbuf(bsd) values.
unbound[1218:0] warning: so-sndbuf 4194304 was not granted. Got 360448. To fix: start with root permissions(linux) or sysctl bigger net.core.wmem_max(linux) or kern.ipc.maxsockbuf(bsd) values.
unbound[1218:0] error: can't bind socket: Address already in use for 127.0.0.1 port 5335
unbound[1218:0] fatal error: could not open ports`

I am running with root permissions.

Operating system:
Distro:  Raspbian
Version: 10

**Comment by gthess** [comment]
This seems like a packaged Unbound.
- The package helper tries to run unbound-anchor before starting Unbound and it fails.
- The buf warnings are just warnings and they provide further suggestions on how to resolve.
- The bind error suggests that Unbound was not properly terminated. It either still listens on that socket or something else is listening there.

Ultimately it seems like a problem with the raspbian distro.
Closing as a non issue; feel free to reopen/tag :)
