### ISSUE TITLE
cannot resolve opensuse.org

### ISSUE THREAD

**Issue by cpslck** [NLnetLabs/unbound#334]
Hey, I'm running a raspberry with unbound & pihole without any problems for weeks now, but 2 days ago I tried to download a package from a repo on download.opensuse.org, and found out that opensuse.org couldn't be resolved by unbound for whatever reasons. The other domain that doesn't work is vodafone.pt (every other european vodafone domain can be resolved btw).

`pi@ctrlbox:~ $ dig opensuse.org @127.0.0.1 -p 5353

; <<>> DiG 9.11.5-P4-5.1+deb10u2-Raspbian <<>> opensuse.org @127.0.0.1 -p 5353
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 30815
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1472
;; QUESTION SECTION:
;opensuse.org.			IN	A

;; Query time: 12 msec
;; SERVER: 127.0.0.1#5353(127.0.0.1)
;; WHEN: Wed Oct 28 11:39:06 CET 2020
;; MSG SIZE  rcvd: 41
`
I tried almost everything I could imagine, changing the unbound config several times, deleting the cache etc. & googling for days now. I found 2 other people on the internet having the same problem with those 2 domains and this setup, on reddit and on a german msg-board, but without any solution.

This must be some kind of configuration issue with raspiOS & unbound I think, but why does this happen only on 2 out of thousands of domains I tested? I followed this guide when setting that raspberry up: https://github.com/notasausage/pi-hole-unbound-wireguard

I recorded an unbound log with verbosity 5 here, where I try to dig opensuse.org: https://termbin.com/898wl

some additional info from unbound-control:

pi@ctrlbox:~ $ sudo unbound-control lookup opensuse.org.
The following name servers are used for lookup of opensuse.org.
;rrset 80923 3 0 2 0
opensuse.org.	80923	IN	NS	ns2.opensuse.org.
opensuse.org.	80923	IN	NS	ns1.opensuse.org.
opensuse.org.	80923	IN	NS	ns3.opensuse.org.
;rrset 80923 1 0 1 0
ns3.opensuse.org.	80923	IN	A	62.146.92.204
;rrset 80923 1 0 1 0
ns3.opensuse.org.	80923	IN	AAAA	2a01:138:a004::204
;rrset 80923 1 0 1 0
ns1.opensuse.org.	80923	IN	A	195.135.221.195
;rrset 80923 1 0 1 0
ns1.opensuse.org.	80923	IN	AAAA	2001:67c:2178:8::31
;rrset 80923 1 0 1 0
ns2.opensuse.org.	80923	IN	A	195.135.221.196
;rrset 80923 1 0 1 0
ns2.opensuse.org.	80923	IN	AAAA	2001:67c:2178:8::30
Delegation with 3 names, of which 0 can be examined to query further addresses.
It provides 6 IP addresses.
2001:67c:2178:8::30	expired, rto 187184 msec, tA 0 tAAAA 0 tother 0.
195.135.221.196 	expired, rto 187184 msec, tA 3 tAAAA 3 tother 0.
2001:67c:2178:8::31	expired, rto 187184 msec, tA 0 tAAAA 0 tother 0.
195.135.221.195 	expired, rto 187184 msec, tA 3 tAAAA 1 tother 0.
2a01:138:a004::204	expired, rto 187184 msec, tA 0 tAAAA 0 tother 0.
62.146.92.204   	expired, rto 187184 msec, tA 3 tAAAA 3 tother 0.

**Comment by cpslck** [comment]
Update, now it's getting strange:

my internet provider (vodafone germany) assigns dynamic IP addresses, sometimes you get 2.x.x.x and sometimes you get 84.x.x.x

I just restarted my router and got a new IP address (84.x.x.x instead of 2.x.x.x), now everything works. So I cannot resolve those domains when I get a 2.x.x.x IP. My only explanation for this is that this ip-range is on a firewall-blocklist of those dns-servers, or could it be something else?

**Comment by gthess** [comment]
You are correct, this seems like a network issue.
As you see from the `unbound-control` output (same information also in the log file), the rto is way above the maximum of 120000msec. This means that unbound tried to communicate with those nameservers but never got a reply. They are now ignored by unbound but occasionally probed to see if they get responsive later on.
You can find more information [here](https://www.nlnetlabs.nl/documentation/unbound/info-timeout/), especially the 'blocking' section.
