### ISSUE TITLE
Fail to build --with-libnghttp2 with error: 'SSIZE_MAX' undeclared

### ISSUE THREAD

**Issue by yvoinov** [NLnetLabs/unbound#343]
When trying to build with DoH support, got an error:

./libtool --tag=CC --mode=compile gcc -I. -I/usr/local/include -I/opt/csw/include -I/usr/local/include -I/usr/local/include -I/opt/csw/include -I/opt/csw/include -DSRCDIR=. -O3 -m64 -flto -std=c99 -D_REENTRANT -pthreads  -o listen_dnsport.lo -c services/listen_dnsport.c
libtool: compile:  gcc -I. -I/usr/local/include -I/opt/csw/include -I/usr/local/include -I/usr/local/include -I/opt/csw/include -I/opt/csw/include -DSRCDIR=. -O3 -m64 -flto -std=c99 -D_REENTRANT -pthreads -c services/listen_dnsport.c  -fPIC -DPIC -o .libs/listen_dnsport.o
services/listen_dnsport.c: In function 'http2_submit_response_read_callback':
services/listen_dnsport.c:2130:15: error: 'SSIZE_MAX' undeclared (first use in this function)
  if(copylen > SSIZE_MAX)
               ^
services/listen_dnsport.c:2130:15: note: each undeclared identifier is reportedonly once for each function it appears in
gmake: *** [Makefile:308: listen_dnsport.lo] Error 1

To fix require to add #include <limits.h> to services/listen_dnsport.c.

Just this include omitted. After add, issue is gone.

**Comment by wcawijngaards** [comment]
Thanks!  Implemented the include as you suggested, that should fix the issue.

**Comment by yvoinov** [comment]
Yes, this exactly fixed on my side. 😁

10.11.2020 20:32, Wouter Wijngaards пишет:
