### ISSUE TITLE
PyParser_SimpleParseFile has been removed in Python 3.10

### ISSUE THREAD

**Issue by pemensik** [NLnetLabs/unbound#344]
[PyParser_SimpleParseFile](https://docs.python.org/3.9/c-api/veryhigh.html#c.PyParser_SimpleParseFile) is deprecated in Python 3.9 and removed in Python 3.10. It was reported as [rhbz#1889726](https://bugzilla.redhat.com/show_bug.cgi?id=1889726).

It is not clear to me, why [current code](https://github.com/NLnetLabs/unbound/blob/5385e2e09444d60df1bcbd3a173846ba933b03df/pythonmod/pythonmod.c#L371) runs first and on failure compile the code. It seems to me some flags might be used directly, maybe using [PyRun_FileExFlags](https://docs.python.org/3.9/c-api/veryhigh.html#c.PyRun_FileExFlags), so error backtrace is reported on the first run. But I lack the expertise of python internals handling, so instead of MR I offer just the report.

Would you know correct replacement for deprecated function?

**Comment by gthess** [comment]
This was addressed in https://github.com/NLnetLabs/unbound/commit/e0d426ebb10653a78bf5c4053198f6ac19bfcd3e.
