### ISSUE TITLE
can i disable dnssec?just like  bind dnssec-enable no and dnssec-validation no;

### ISSUE THREAD

**Issue by daysomeon** [NLnetLabs/unbound#348]
https://www.nlnetlabs.nl/documentation/unbound/howto-turnoff-dnssec/
I tried through the link above to disable dnssec，but not effect

**Comment by gthess** [comment]
If you want to completely turn off comment out DNSSEC any option for `trust-anchor-file` and `auto-trust-anchor-file` in the configuration file (point 2) and remove `validator` from the module-config option (point 3). You need to restart unbound after the changes.
That should work.

Did you try and it is not working?
You can verify by issuing `dig @<your-unbound-ip> bogus.nlnetlabs.nl txt`.

**Comment by daysomeon** [comment]
> If you want to completely turn off comment out DNSSEC any option for `trust-anchor-file` and `auto-trust-anchor-file` in the configuration file (point 2) and remove `validator` from the module-config option (point 3). You need to restart unbound after the changes.
> That should work.
> 
> Did you try and it is not working?
> You can verify by issuing `dig @<your-unbound-ip> bogus.nlnetlabs.nl txt`.

thanks，its right. I used to judge based on rrsig record
