### ISSUE TITLE
Possible memory leak in delegpt_add_addr_mlc

### ISSUE THREAD

**Issue by cairojack** [NLnetLabs/unbound#359]
During code inspection I found a potential memory leak.
(ver 1.12.0) iter_delegt.c:623

a malloc of a delegpt_addr* is made in delegpt_add_addr_mlc
and assigned to db->target_list and db_usable->list
however a strdup later in the code can fail, and these assignments are not cleaned up

```
diff --git a/iterator/iter_delegpt.c b/iterator/iter_delegpt.c
index 9a672b0a..8c1d88e4 100644
--- a/iterator/iter_delegpt.c
+++ b/iterator/iter_delegpt.c
@@ -624,10 +624,8 @@ int delegpt_add_addr_mlc(struct delegpt* dp, struct sockaddr_storage* addr,
        if(!a)
                return 0;
        a->next_target = dp->target_list;
-       dp->target_list = a;
        a->next_result = 0;
        a->next_usable = dp->usable_list;
-       dp->usable_list = a;
        memcpy(&a->addr, addr, addrlen);
        a->addrlen = addrlen;
        a->attempts = 0;
@@ -643,6 +641,9 @@ int delegpt_add_addr_mlc(struct delegpt* dp, struct sockaddr_storage* addr,
        } else {
                a->tls_auth_name = NULL;
        }
+    /* now it is safe to set these */
+    dp->target_list = a;
+    dp->usable_list = a;
        return 1;
 }

**Comment by gthess** [comment]
Hi, thanks for looking!

However an error in the `delegpt_add_addr_mlc()` will eventually lead to `delegpt_free_mlc()` which will also free the `delegpt_addr*` together with the delegation point altogether.

Feel free to ping me here if you think otherwise and want to reopen.
