### ISSUE TITLE
In some situation, Unbound should not try to find and query all authoritative DNS Servers。

### ISSUE THREAD

**Issue by gzzhangxinjie** [NLnetLabs/unbound#361]
According to `https://docs.menandmice.com/display/MM/Unbound+request-list+demystified`,  

```
Unbound tries very hard on every query to find an answer. It will not give up on the first sight of trouble (for example if the first authoritative DNS Server for a domain name turns out to be “lame”). Instead if will try to find and query all authoritative DNS Servers available for the domain name, as long as resources allow. In worst case scenarios, this can take some amount of time. If there are many authoritative DNS Servers for a domain, and each of these DNS Servers have multiple IP Addresses, the timeouts can accumulate.
```

In most cases, it's OK!  But in some situation, it will cause unbound cannot response to some queries。

Assumes that, 

1. `example.com` has authoritative nameservers

```
ns1.example.com
ns2.example.com
ns3.example.com
ns4.example.com
```

2. Unfortunately,  all these nameservers failed or timeout (for example, these nameservers suffer from DDOS).
3. There are more than 2k QPS of domain `example.com`，like `1.example.com`, `2.example.com`, `3.example.com` and so on.

In this situation，for each domain of `example.com`, it will tried to query all authoritative nameservers of `example.com`， but  all  authoritative are timeout。 The consequence is the request-list is full, and the other normal query will be placed into jostle-list。If the unbound is very busy, these normal queries will be drop in certain probability。

So, The questions are:
1. `In worst case scenarios, this can take some amount of time.  If there are many authoritative DNS Servers for a domain, and each of these DNS Servers have multiple IP Addresses, the timeouts can accumulate.`  Normally，the query timeout is 5 seconds，is it worth to tries to find and query all authoritative DNS servers, especially nameservers are unhealthy? 
2. when the nameservers of domain are failed, Is there any method to mark some nameservers as unusable in certain period?

**Comment by gthess** [comment]
Hi! I believe you can find answers to your questions at https://www.nlnetlabs.nl/documentation/unbound/info-timeout/.
Especially the 'probing' and 'blocking' sections.
