### ISSUE TITLE
udp connect failed: Cannot assign requested address

### ISSUE THREAD

**Issue by mibere** [NLnetLabs/unbound#364]
Just replaced Unbound 1.12.0 with 1.13.0, without changing the Unbound configurion file.
With `verbosity: 1` the Unbound log is now flooded with thousands of

`unbound[21:0] error: udp connect failed: Cannot assign requested address for <stripped IP> port 53`

It stopped after adding `udp-connect: no` to the configuration file.

Side note: all logged IP addresses are IPv6, my system is IPv4 only.

**Comment by MatthewVance** [comment]
I'm seeing a similar issue. My Docker setup is all IPv4, but I'm seeing the following errors when launching the 1.13.0 container (using the same config as before with 1.12.0):
```
[redacted] libunbound[18:0] error: udp connect failed: Cannot assign requested address for 2001:500:12::d0d port 53
[redacted] libunbound[18:0] error: udp connect failed: Cannot assign requested address for 2001:7fd::1 port 53
[redacted] libunbound[18:0] error: udp connect failed: Cannot assign requested address for 2001:500:9f::42 port 53
[redacted] libunbound[18:0] error: udp connect failed: Cannot assign requested address for 2001:500:2f::f port 53
```
All the IPv6 addresses in the error log appear to be associated with [root servers](https://www.iana.org/domains/root/servers).

**Comment by churchofnoise** [comment]
@mibere , just came across this topic which might be related to your issue: https://github.com/NLnetLabs/unbound/issues/376 
There is a solution in the latest master (added on Dec 26): https://github.com/NLnetLabs/unbound/commit/08968baec1122a58bb90d8f97ad948a75f8a5d69 
Fwiw, A.

**Comment by gthess** [comment]
Hi @mibere, @MatthewVance,
Is this issue resolved on the current 1.13.1 version?

**Comment by mibere** [comment]
In my opinion, the ticket can be closed.

**Comment by gthess** [comment]
OK.
@MatthewVance, if you disagree you can ping me here and I will be happy to reopen the issue.
