### ISSUE TITLE
unbound-control timeout when Unbound is not running

### ISSUE THREAD

**Issue by BBcan177** [NLnetLabs/unbound#371]
unbound-control timeout when Unbound is not running:

```
unbound-control -c /var/unbound/unbound.conf  status

version: 1.12.0
verbosity: 2
threads: 1
modules: 2 [ python iterator ]
uptime: 10628 seconds
options: control(ssl)
unbound (pid 98061) is running...
```

`unbound-control -c /var/unbound/unbound.conf stop`
ok

`unbound-control -c /var/unbound/unbound.conf status`
Command takes forever to time-out.

Its the same for any other **unbound-control** command when Unbound is not running.

**Comment by wcawijngaards** [comment]
I do not get this, not for using a pipe and not when I use an ssl connection.  It prints `connect: Connection refused`, immediately, and then `unbound is stopped`.

What settings do you have?  I am using 127.0.0.1 for the SSL setup and a named pipe file for the unix socket setup.

**Comment by wcawijngaards** [comment]
Fixed this in the commit referenced, that adds a timeout of a couple seconds.  When it expires, it prints that the remote server has timed out.
