### ISSUE TITLE
Not compatible with Python 3.10: PyParser_SimpleParseFile() has been removed

### ISSUE THREAD

**Issue by vstinner** [NLnetLabs/unbound#378]
Hi,

The unbound project uses the Python PyParser_SimpleParseFile() function which has been removed in Python 3.10:
https://bugs.python.org/issue40939#msg380826

PyParser_SimpleParseFile() is used to display a parsing error (SyntaxError).

I proposed a pseudo-code to reimplement something like PyParser_SimpleParseFile():
https://bugs.python.org/issue40939#msg381227

I'm not sure that I understood correctly the current unbound code. Would you mind to have a look?

Downstream Fedora issue: https://bugzilla.redhat.com/show_bug.cgi?id=1889726

Thanks,
Victor

**Comment by vstinner** [comment]
Oh, it seems like the issue was fixed by the commit e0d426ebb10653a78bf5c4053198f6ac19bfcd3e.

**Comment by gthess** [comment]
This was indeed addressed in https://github.com/NLnetLabs/unbound/commit/e0d426ebb10653a78bf5c4053198f6ac19bfcd3e; closing.
