### ISSUE TITLE
Does not work on Windows 10 x64

### ISSUE THREAD

**Issue by gjf** [NLnetLabs/unbound#381]
I have installed Unbound to use it as local DNS resolver on my system only to avoid using external DNS.

So it looks like the default config should work - but it doesn't.

The log file looks like:
```
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] error: udp connect failed: No error for 2001:503:c27::2:30 port 53
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] info: error sending query to auth server 2001:503:c27::2:30 port 53
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] error: udp connect failed: No error for 2001:500:a8::e port 53
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] info: error sending query to auth server 2001:500:a8::e port 53
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] info: response for . NS IN
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] info: reply from <.> 192.33.4.12#53
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] info: query response was THROWAWAY
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] info: response for . NS IN
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] info: reply from <.> 199.7.91.13#53
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] info: query response was THROWAWAY
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] error: udp connect failed: No error for 2001:500:a8::e port 53
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] info: error sending query to auth server 2001:500:a8::e port 53
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] info: response for . NS IN
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] info: reply from <.> 198.41.0.4#53
19.12.2020 3:34:10 C:\Program Files\Unbound\unbound.exe[15248:0] info: query response was THROWAWAY
```
What is wrong?

Detailed log is attached: [log.txt](https://github.com/NLnetLabs/unbound/files/5718697/log.txt)

**Comment by magl8** [comment]
DNS root access seems to be blocked. Try to establish a forwarding to some public dns resolvers, e.g. 8.8.8.8 and/or 1.1.1.1.
There are many step-by-step guides out there, e.g. [https://www.redhat.com/sysadmin/forwarding-dns-2](https://www.redhat.com/sysadmin/forwarding-dns-2)

**Comment by gjf** [comment]
Yeah, adding

forward-zone:
        name: "."
        forward-addr: 1.1.1.1
        forward-addr: 8.8.8.8

works for sure.

But the main idea was to use root access without using any public DNS.

Any idea why this access is blocked and how to overcome it?

Please note I have Unbound installed on Asus RT-AC68U router as an addon in the same network as all tested Windows system. And it works! So it means it is not provider's issue but Unbound itself (at least - Windows-based build).

**Comment by gjf** [comment]
It was found router had DNSFilter enabled - so that was an issue. Now everything works.
