### ISSUE TITLE
(1) A minor request to improve the log (2) A minor bug in one log message

### ISSUE THREAD

**Issue by ZjYwMj** [NLnetLabs/unbound#384]
unbound version is 1.12.0

1. **notice: init module 1: subnet**
Having a `config-module: "subnet ..."`
results in an error. The correct configuration is, probably,
`config-module: "subnetcache ..."`
Is that correct?
With `config-module: "subnetcache ..."`
the log have: 
    > unbound[3228]: [3228:0] notice: init module 1: subnet

    I think the name in the log should match exactly the name in
    `unbound -V`, and in the configuration.

2. **See the list of linked modules with unbound -h**
    Sometimes, when there is a reference to a module that is not present, the comment in the log is:
    > ... This module is not present (not compiled in), See the list of linked modules with unbound -h

    Was that meant to be `unbound -V`?

**Comment by gthess** [comment]
Thanks for reporting!
