### ISSUE TITLE
autoconf 2.70 impacts unbound build 

### ISSUE THREAD

**Issue by gene-git** [NLnetLabs/unbound#385]
autoconf 2.70 was released on december 8th and brings quite a few changes, some are not backward compatible.  The release note is here:

[https://lwn.net/Articles/839395/](url)

Building unbound now has a lot of warnings from configure.ac and as the release note points running 'autoupdate' does not fix them. May be worth looking into and updating configure.ac. 

thank you!

**Comment by wcawijngaards** [comment]
Fixed it and it now generates no warnings when autoconf-2.70 is run for unbound.

**Comment by gene-git** [comment]
Terrific thank you - confirmed all looks good.
