### ISSUE TITLE
DOH not responsing with "http2_query_read_done failure" logged

### ISSUE THREAD

**Issue by dyunwei** [NLnetLabs/unbound#386]
I am using  unbound 1.12.0.  In some situation, some queries do not get response from unbound.  Looks like unbound closes connections actively. After some tests, I find "http2_query_read_done failure" will be logged when unbound does not answer the query.

Unbound Logs:
Dec 09 18:18:52 unbound[227717:0] debug: svcd callbacks end
Dec 09 18:18:52 unbound[227717:0] debug: close of port 57230
Dec 09 18:18:52 unbound[227717:0] debug: close fd 85
Dec 09 18:18:52 unbound[227717:0] debug: comm point stop listening 84
Dec 09 18:18:52 unbound[227717:0] debug: comm point start listening 84 (120000 msec)
**Dec 09 18:18:56 unbound[227717:0] debug: http2_query_read_done failure: can't fit qbuffer in c->buffer**
Dec 09 18:18:56 unbound[227717:0] debug: close fd 84

**Comment by dyunwei** [comment]
I found the root cause of this issue. r_buffer is r->query_reply.c->buffer, used to fill the reply in the mesh_send_reply function, then call comm_point_send_reply, and then call http2_submit_dns_response to send the DOH response. However, the buffer is not cleared after use. If the query length is greater than the last response length, the next dns query in the same H2 session will encounter an error.
This is bug!!!

**Comment by dyunwei** [comment]
I've made a commit to fix this bug in dyunwai/unbound.

**Comment by dyunwei** [comment]
Is it convenient for you to fix this issue in the next version?  @gthess  @ralphdolmans

**Comment by gthess** [comment]
Hi @dyunwei, I haven't looked at this since you closed the issue. Is this bug still relevant? And does your proposed solution solve the problem for you? If so, could you reopen this issue and create a PR with your suggested fix referencing this issue? I can take it from there then.

**Comment by dyunwei** [comment]
HI, @gthess, this bug is still relevant. I have tested for several weeks with my proposed solution, and now DOH works well. I have create a PR to fix the issue. #420

**Comment by dyunwei** [comment]
reopen

**Comment by gthess** [comment]
With the PR merged, I am closing this.
Thanks for this!
