### ISSUE TITLE
client-subnet-always-forward seems to effectively bypass any caching?

### ISSUE THREAD

**Issue by mzealey** [NLnetLabs/unbound#387]
From the documentation, I assumed that `client-subnet-always-forward` was basically the same as setting `send-client-subnet: 0.0.0.0/0` - in terms of upstream functionality of sending ECS upstream it seems to be. However when deploying to a live environment I noticed that there was basically no caching going on. Reading through the code it seems to be that this is the case. From the documentation I did not expect this, but it seems to be written like this in the code comments. Is it possible to clarify in the documentation as to exactly what this option does please?

**Comment by wcawijngaards** [comment]
Yes, certainly, it already reads, in the section for subnet that `The option will
always be forwarded, regardless the allowed addresses, if
client-subnet-always-forward is set to yes. In this case the lookup in
the regular cache is skipped.`

So I added a commit that adds this text to the documentation for the client-subnet-always-forward option: `And the lookup in the regular cache is skipped.`
