### ISSUE TITLE
ECS caching issues

### ISSUE THREAD

**Issue by mzealey** [NLnetLabs/unbound#388]
So I've been experimenting with the `subnetcache` module and looking at the queries it sends over the wire.

```
    module-config: "subnetcache validator iterator"
    send-client-subnet: 0.0.0.0/0
```

With this setting (1.13.0 also tested with 1.9.0) it sends the initial upstream queries with ECS correctly, but any subsequent questions to the server are answered straight from this without any packets being sent, no matter what the source IP or `+subnet=` option is in kdig. In spite of the upstream server (eg `A google.com`) returning the ECS field. So it looks to me like for some reason the `subnetcache` module is not being consulted for future queries, even if/when the documentation says it should be caching with an additional ecs subnet in the tuple. With log level 5 and log-replies set, the subsequent queries only print:

```
[1609417985] unbound[1:6] info: 172.17.0.1 google.com. A IN
[1609417985] unbound[1:6] info: 172.17.0.1 google.com. A IN NOERROR 0.000000 1 55
[1609417986] unbound[1:0] info: 172.17.0.1 google.com. A IN
[1609417986] unbound[1:0] info: 172.17.0.1 google.com. A IN NOERROR 0.000000 1 55
```

ie i'm not sure if they are even hitting the `subnetcache` module?

With `client-subnet-always-forward: yes` it works correctly, presumably because it effectively bypasses any sort of caching.

**Comment by mzealey** [comment]
Some results from digging deeper with google.com.

If I have the setup as described above and do:

```
for i in `seq 11 14`; do kdig @... google.com +subnet=$i.50.3.4 A; done
```

it queries upstream. Each google response includes some SCOPE parameter < 8.

However, when I query something under `10.xxx`, google responds with an answer as SCOPE=0. After that point all answers from unbound (ECS or none) are served from this scope=0 entry (ie as if ECS had not been specified), even if there is a prior closer match with ECS. I guess one way to work around this would be to have a `min-scope` parameter which could be set to say 8 which would allow effectively say SCOPE=8 if SCOPE=0 returned from the server? (or a `scope-if-zero` parameter doing the same but only applying to scope 0 responses)?

**Comment by gthess** [comment]
I believe this is because the upstream nameservers are not permitted for ECS (configuration option: `send-client-subnet`, or `client-subnet-zone`).
If you want unbound to always *forward* ECS to all upstreams then you can use `client-subnet-always-forward: yes`.
Is this the case for you?

**Comment by mzealey** [comment]
See first ticket - `send-client-subnet: 0.0.0.0/0` is specified so should be sending everywhere (which it is). `client-subnet-always-forward: yes` basically bypasses any caching so is not good.

**Comment by gthess** [comment]
Small correction: `client-subnet-always-forward: yes` does not bypass *any* caching; just the regular cache. The ECS cache is still consulted.

Sorry, I missed the option setting for `send-client-subnet`; I was more focused on the " i'm not sure if they are even hitting the subnetcache module?" and "With client-subnet-always-forward: yes it works correctly,".

What I see here is that the upstream is not consistent with its replies and certain replies, as is the case with 10.x.x.x, shadow other replies. When replying with scope=0 to unbound, unbound uses that answer for all networks (as instructed by the upstream).
Maybe it would be better for the upstream reply to have a scope of 8 in this case but ultimately I don't see an issue with unbound.

Enforcing a certain scope when upstream replies with 0 does not sound good as we bypass the upstream's intention.

**Comment by gthess** [comment]
Closing this as no-issue and inactivity now; you can ping me here if you want.
