### ISSUE TITLE
Assertion nread >= 0 failed in evmap_io_del_ on CentOS 7 in version 1.13.0

### ISSUE THREAD

**Issue by jcjones** [NLnetLabs/unbound#393]
Running unbound 1.13, across several CentOS 7 hosts, I'm reliably getting random assertion failures out of libevent, similar to [debian bug 973052](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=973052), but on 1.13:
```
[err] evmap.c:381: Assertion nread >= 0 failed in evmap_io_del_
unbound.service: Main process exited, code=killed, status=6/ABRT
```

Watching #376 the last several days, I cherry-picked 08968ba onto the ` release-1.13.0` tag and tried it overnight and still hit the same assertion.

I'll cherry-pick 4d51c6b as well and try that next.

I'm afraid I currently don't have any additional debug artifacts, but if 4d51c6b doesn't resolve the issue, I'll make the suitable changes to get dumps.

**Comment by wcawijngaards** [comment]
Looks like it is likely something to do with the lifetime of a stream connection, and thus depends on timers and timeout on the tcp channel with perhaps history.  The first commit you tried fixes something else, but the second one is meant to fix it, if that happens because of double adds and removes.  Otherwise it could be an uninitialized reuse case, that we had in an older release with similar assertion failures, but I thought that was solved.

**Comment by jcjones** [comment]
12 hours or so of running on two hosts had no additional crashes; I've patched another three hosts to watch overnight, and will report back in another twelve hours or so. Given the current assertion and restart rate, I expect twelve hours of five hosts to be a good indicator.

**Comment by jcjones** [comment]
As far as I can tell, https://github.com/NLnetLabs/unbound/commit/4d51c6b86e84e0786d9cd5134fce536e5cf1980f fixes this issue.

**Comment by jcjones** [comment]
For what it's worth, a point release including that fix would be appreciated, but isn't critical.

**Comment by wcawijngaards** [comment]
Good to hear that it works!  Thank you for the test.  Release this sounds like a good idea.  I can close this issue and also #376 then, I think.

**Comment by jcjones** [comment]
Just a heads-up, I'm getting segfaults now, even with https://github.com/NLnetLabs/unbound/commit/08968baec1122a58bb90d8f97ad948a75f8a5d69 applied, but without the extra null check in 422213c1719ca324faced1b4c6210a36b4c7506a. I'll see if I can get you a core file.

**Comment by wcawijngaards** [comment]
Does it have https://github.com/NLnetLabs/unbound/commit/4d51c6b86e84e0786d9cd5134fce536e5cf1980f as well?  That is a second fix for the other stack trace quoted.

**Comment by jcjones** [comment]
Yeah. I'm working on deploying a branch of 1.13.0 with:

- https://github.com/NLnetLabs/unbound/commit/4d51c6b86e84e0786d9cd5134fce536e5cf1980f
- https://github.com/NLnetLabs/unbound/commit/08968baec1122a58bb90d8f97ad948a75f8a5d69

The next build will also add in
-  https://github.com/NLnetLabs/unbound/commit/422213c1719ca324faced1b4c6210a36b4c7506a

but I probably won't have results until the start of the week.

**Comment by jcjones** [comment]
Still seeing segfaults with those three patches cherry-picked, but they're less common. So far only seeing them on CentOS7, not on 8. I realize at this point there's not much else we can do until I strong-arm these boxes into producing core dumps with symbols, which I'll do next week.

**Comment by wcawijngaards** [comment]
There is a recent bugfix for a core in #399 and commit https://github.com/NLnetLabs/unbound/commit/7e46204bf73ecdee56e1ab1c48e1829d71cdbc0a fixes that.  It may be the issue you are facing?

**Comment by jcjones** [comment]
Thanks, @wcawijngaards, I'll let you know what I see after that rolls out in a few hours.

**Comment by jcjones** [comment]
Still seeing segfaults with:

- 4d51c6b
- 08968ba
- 422213c
- 7e46204bf73ecdee56e1ab1c48e1829d71cdbc0a

I haven't spent any time in recent days trying to figure out what's going wrong with getting core files, but I'll put the effort in shortly as I move some more things off the ol' stack.

**Comment by jcjones** [comment]
Crash rate is definitely down as an anecdotal note.
