### ISSUE TITLE
[Feature request] add new type always_null to local-zone similar to always_nxdomain

### ISSUE THREAD

**Issue by TheteSigma** [NLnetLabs/unbound#397]
DNS blacklists currently like to use nxdomain or a network null (0.0.0.0 and ::).
Unbound currently already supports a shortcut for nxdomain like:
  local-zone: "example.com" always-nxdomain

Would like to have a similar shortcut for null network like:
  local-zone: "example.com" always-null

which would replace the working form:
  local-zone: "examplel.com" redirect
  local-data: "example.com A 0.0.0.0"
  local-data: "example.com AAAA ::"

dnsmasq 2.80 added a similar ability:
address=/example.com/#

Unbound is able to better handle large DNS block lists then dnsmasq.
250k domains to block has almost no impact on Unbound, while it adds 30ms to the query time for dnsmasq.

This feature would make it easier to create large blocklists with the a third the number of configuration lines.

**Comment by wcawijngaards** [comment]
Okay implemented, the syntax is `local-zone: "example.com" always_null`

**Comment by TheteSigma** [comment]
Thank you for implementing and the quick turn around.
