### ISSUE TITLE
unbound 1.13.0 abort

### ISSUE THREAD

**Issue by bleve** [NLnetLabs/unbound#400]
unbound[22274]: [err] evmap.c:367: Assertion nread >= 0 failed in evmap_io_del

**Comment by dyunwei** [comment]
It seems you are experiencing the same issue, which has been reported as #393 .

**Comment by bleve** [comment]
This is on Foobar Linux 7 (based on rhel7).

**Comment by gthess** [comment]
Hi @bleve,
Is this issue fixed for you with version 1.13.1?

**Comment by bleve** [comment]
Indeed it looks like it is fixed in 1.13.1 which we have been running since the release.
