### ISSUE TITLE
DNS query with small edns bufsize fail

### ISSUE THREAD

**Issue by codematle** [NLnetLabs/unbound#404]
According to [https://tools.ietf.org/html/rfc6891#section-6.2.3](https://tools.ietf.org/html/rfc6891#section-6.2.3) responder _should_ round the 'UDP Payload Size' up to 512 (at least I think so). However, for values smaller than 12 Unbound returns SERVFAIL.

### How to reproduce:
`dig +bufsize=0 +edns  .`

### Expected  output:
DNS record for '.'

### Acctual output:
SERVFAIL

**Comment by wcawijngaards** [comment]
There is an option to make unbound behave like this: `harden-short-bufsize: yes` in unbound.conf.
https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/#harden-short-bufsize

But the default is 'off' for this option.  The default can be on if you think that is more compliant with the RFC.
