### ISSUE TITLE
The unbound configured tls has no edns information

### ISSUE THREAD

**Issue by liang-hiwin** [NLnetLabs/unbound#406]
The screenshots are DOT configured with adguard home and DOT configured with unbound.
DOT adguard home configuration which has edns support, unbound from the CMD terminal configuration DOT did not see support in edns.
![a](https://user-images.githubusercontent.com/17548936/104892459-2df24b00-59ad-11eb-938e-b840e2f352c1.png)
![b](https://user-images.githubusercontent.com/17548936/104892478-3480c280-59ad-11eb-98d7-3468d95185c3.png)

**Comment by wcawijngaards** [comment]
Hi,
When I test this locally, I can get EDNS in answers from Unbound.  Both over DoT and DoH.
```
$ ./streamtcp -s -f 127.0.0.1 www.example.com. A IN
[ ... ]
Next query is www.example.com. A IN

next received packet
data[231] 0F2D81A0000100020000000103777777076578616D706C6503636F6D0000010001C00C000100010001518000045DB8D822C00C002E000100015180009F00010803000151806015FCF05FFA0270F55B076578616D706C6503636F6D009406C0A77EE4B4C9FFAE6AE2A4408217A5094E9AC49852FA6AA7004F5E8F69317444CECD660338DA19F9A8E3D9700E163AC6E14D7D01335106F4E06CCE0C730ED2C6200CEF4F8732DD6BB31EEBC93D008A46C1E3AD49B01326AF94D3A2A221BEF007271DB2257F96FCB8178916548F973E3B4E6B307B0292B91E902BBC80456800002904D0000080000000
;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 3885
;; flags: qr rd ra ad ; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1 
;; QUESTION SECTION:
www.example.com.	IN	A

;; ANSWER SECTION:
www.example.com.	86400	IN	A	93.184.216.34
www.example.com.	86400	IN	RRSIG	A 8 3 86400 20210131004224 20210109192224 62811 example.com. lAbAp37ktMn/rmripECCF6UJTprEmFL6aqcAT16PaTF0RM7NZgM42hn5qOPZcA4WOsbhTX0BM1EG9OBszgxzDtLGIAzvT4cy3WuzHuvJPQCKRsHjrUmwEyavlNOioiG+8AcnHbIlf5b8uBeJFlSPlz47TmswewKSuR6QK7yARWg= ;{id = 62811}

;; AUTHORITY SECTION:

;; ADDITIONAL SECTION:
; EDNS: version: 0; flags: do ; udp: 1232
;; MSG SIZE  rcvd: 231
orderly exit
```

Unbound only includes EDNS when the querier asks for EDNS.  This is according to the EDNS protocol.  Queries without EDNS get no EDNS in the answer.  But queries that have EDNS in the question packet get an EDNS record in the response.

In the snippet above I am using `streamtcp` a test tool from unbound sources, that sets EDNS on the queries that it makes.

**Comment by liang-hiwin** [comment]
> Hi,
> When I test this locally, I can get EDNS in answers from Unbound. Both over DoT and DoH.
> 
> ```
> $ ./streamtcp -s -f 127.0.0.1 www.example.com. A IN
> [ ... ]
> Next query is www.example.com. A IN
> 
> next received packet
> data[231] 0F2D81A0000100020000000103777777076578616D706C6503636F6D0000010001C00C000100010001518000045DB8D822C00C002E000100015180009F00010803000151806015FCF05FFA0270F55B076578616D706C6503636F6D009406C0A77EE4B4C9FFAE6AE2A4408217A5094E9AC49852FA6AA7004F5E8F69317444CECD660338DA19F9A8E3D9700E163AC6E14D7D01335106F4E06CCE0C730ED2C6200CEF4F8732DD6BB31EEBC93D008A46C1E3AD49B01326AF94D3A2A221BEF007271DB2257F96FCB8178916548F973E3B4E6B307B0292B91E902BBC80456800002904D0000080000000
> ;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 3885
> ;; flags: qr rd ra ad ; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1 
> ;; QUESTION SECTION:
> www.example.com.	IN	A
> 
> ;; ANSWER SECTION:
> www.example.com.	86400	IN	A	93.184.216.34
> www.example.com.	86400	IN	RRSIG	A 8 3 86400 20210131004224 20210109192224 62811 example.com. lAbAp37ktMn/rmripECCF6UJTprEmFL6aqcAT16PaTF0RM7NZgM42hn5qOPZcA4WOsbhTX0BM1EG9OBszgxzDtLGIAzvT4cy3WuzHuvJPQCKRsHjrUmwEyavlNOioiG+8AcnHbIlf5b8uBeJFlSPlz47TmswewKSuR6QK7yARWg= ;{id = 62811}
> 
> ;; AUTHORITY SECTION:
> 
> ;; ADDITIONAL SECTION:
> ; EDNS: version: 0; flags: do ; udp: 1232
> ;; MSG SIZE  rcvd: 231
> orderly exit
> ```
> 
> Unbound only includes EDNS when the querier asks for EDNS. This is according to the EDNS protocol. Queries without EDNS get no EDNS in the answer. But queries that have EDNS in the question packet get an EDNS record in the response.
> 
> In the snippet above I am using `streamtcp` a test tool from unbound sources, that sets EDNS on the queries that it makes.

Execute dig @127.0.0.1 -p53 +subnet=x.x.x.x/24 www.google.com The resolved ip has no partition resolution. For example, if I am a telecom network, I should give me a telecom ip, but in fact, it was given by China Unicom.

**Comment by wcawijngaards** [comment]
The option `+qr` makes dig print out the query packet that it sends.  Does the query packet include EDNS?  If it does not, then that explains why there is not an EDNS in the response.

**Comment by liang-hiwin** [comment]
> The option `+qr` makes dig print out the query packet that it sends. Does the query packet include EDNS? If it does not, then that explains why there is not an EDNS in the response.

127.0.0.1:5353 is unbound
127.0.0.1:5304 is the adguard home
It can be seen from the analysis result that the edns result of adguard home is very reasonable, but the unbound result is not the edns result and does not follow edns.
![S$19O GI975S$@3W)SNW%LN](https://user-images.githubusercontent.com/17548936/105135050-52bffd00-5b2a-11eb-98a2-1a7992dde755.png)

**Comment by dyunwei** [comment]
Could you share your configuration file in use? ECS module in unbound is disabled by default.

**Comment by wcawijngaards** [comment]
Additionally, I would like to comment that in both queries you have EDNS in the answer.  Both the query and the answer for both the first and second dig command have EDNS.  The subnet option for EDNS is only present in the second answer.  Not the first.  Thus, the issue seems to be about EDNS subnet.  Perhaps in the first post here about tls, the commandline tool used to get a tls response has not included an edns subnet identifier and thus unbound does not see the subnet information, and the answer also has no EDNS?

**Comment by liang-hiwin** [comment]
> Could you share your configuration file in use? ECS module in unbound is disabled by default.


I have compiled ecs，The red part above is the code of the server root

**Comment by liang-hiwin** [comment]
> Additionally, I would like to comment that in both queries you have EDNS in the answer. Both the query and the answer for both the first and second dig command have EDNS. The subnet option for EDNS is only present in the second answer. Not the first. Thus, the issue seems to be about EDNS subnet. Perhaps in the first post here about tls, the commandline tool used to get a tls response has not included an edns subnet identifier and thus unbound does not see the subnet information, and the answer also has no EDNS?

Not only does the tool for testing tls do not have the client's subnet ip, but also does not use the client's subnet in normal use, such as the private DNS that comes with Android 9. You can see from the packet capture tool that the resolved ip is not included Client subnet information
