### ISSUE TITLE
unbound 1.13.1 segfault

### ISSUE THREAD

**Issue by bleve** [NLnetLabs/unbound#423]
unbound[5458]: segfault at 0  ip 000055cb735853b1 sp 00007ffd037fe6c8 error 4 in unbound[55cb73533000+14f000]

Sorry, no more info yet. Unfortunately crashed on a system where it can't be debugged deeper.

**Comment by mki3853** [comment]
Installed debug pkg ..

[root@badnews]# addr2line -e /sbin/unbound -fCi 0x523B1
view_cmp
/usr/src/debug/unbound-1.13.1/unbound-1.13.1/util/alloc.c:333

--8<--
struct regional*
alloc_reg_obtain(struct alloc_cache* alloc)
{
        if(alloc->num_reg_blocks > 0) {
                struct regional* r = alloc->reg_list;
                alloc->reg_list = (struct regional*)r->next;
                r->next = NULL;
                alloc->num_reg_blocks--;
                return r;
        }
        return regional_create_custom(ALLOC_REG_SIZE);
}
--8<--

Line 333 from the above is
                alloc->reg_list = (struct regional*)r->next;

**Comment by gthess** [comment]
Thanks for the info. This is a peculiar place for a segfault. Can you reliably reproduce it?
Could you also share how you configured/compiled unbound and the configuration file in use?

**Comment by bleve** [comment]
I sent you configs. This has happened only once so we don't have reproducer.

**Comment by gthess** [comment]
Still looking into that. Do you happen to have any log output from that time?

**Comment by bleve** [comment]
Only one logline before crash and that is some time before.

Feb 14 03:05:12 hostname unbound: [5458:0] error: arpa.: failed lookup, cannot probe to master iad.xfr.dns.icann.org.
Feb 14 03:32:52 hostname kernel: unbound[5458]: segfault at 0 ip 000055cb735853b1 sp 00007ffd037fe6c8 error 4 in unbound[55cb73533000+14f000]
Feb 14 03:32:52 hostname systemd: unbound.service: main process exited, code=killed, status=11/SEGV

**Comment by pawciobiel** [comment]
This seams to be happening on 1.13.2 too:

```
unbound[7304]: segfault at 0 ip 0000556828378070 sp 00007ffe5ad37860 error 6 in unbound[556828357000+8c000]
Code: d2 48 81 c3 00 01 00 00 31 c0 83 e2 03 89 53 f8 48 89 df f3 ab b8 01 00 00 00 bf 04 00 00 00 48 c1 e0 23 4d 8b ad b0 00 00 00 <49> 89 45 00 31 c0 e8 81 42 02 00 48 8b 44 24 48 64 48 2b 04 25 28
```

I can also see lots of SSL errors a few minutes before the crash:
```
DT localhost unbound: [7304:0] error: SSL_handshake syscall: Host is unreachable
DT localhost unbound: [7304:0] error: SSL_handshake syscall: Host is unreachable
DT localhost unbound: [7304:0] error: SSL_handshake syscall: Host is unreachable
```

```
unbound-libs-1.13.2-r0
unbound-1.13.2-r0
unbound-openrc-1.13.2-r0
```

**Comment by bleve** [comment]
This doesn't happen with newer versions, looks like being fixed.
