### ISSUE TITLE
unbound uses private _Py_fopen() function, removed in Python 3.10

### ISSUE THREAD

**Issue by vstinner** [NLnetLabs/unbound#426]
unbound uses the private `_Py_fopen()` function, but this function was removed in Python 3.10. I wrote a PR to replace it with `fopen()` which is always available.

With issue #378 fix, it should make unbound compatible with Python 3.10.

**Comment by vstinner** [comment]
I removed the function in Python 3.10 :-)
* https://bugs.python.org/issue32381
* https://github.com/python/cpython/commit/ca064402079f889226cb107b26b329891431c319

I wrote PR #427 to fix unbound.

**Comment by wcawijngaards** [comment]
Looks good, merged the fix into the repository.  Good to have it build on 3.10.
