### ISSUE TITLE
"interface-automatic" config option causes unbound not to bind non-53 port 

### ISSUE THREAD

**Issue by hough-ctc** [NLnetLabs/unbound#433]
server:
   interface: 0.0.0.0@53
   interface: ::0@53
   interface: 0.0.0.0@853
   interface: ::0@853
   interface-automatic: yes

causes unbound not to bind 853 port

as seen in the debug log (unbound -ddvvv):

> [1614050289] unbound[1391:0] notice: Start of unbound 1.13.0.
> 2021 Feb 23 11:18:09 unbound[1391:0] debug: creating udp6 socket :: 53
> 2021 Feb 23 11:18:09 unbound[1391:0] debug: creating tcp6 socket :: 53
> 2021 Feb 23 11:18:09 unbound[1391:0] debug: creating udp4 socket 0.0.0.0 53
> 2021 Feb 23 11:18:09 unbound[1391:0] debug: creating tcp4 socket 0.0.0.0 53
> 2021 Feb 23 11:18:09 unbound[1391:0] debug: creating tcp4 socket 127.0.0.1 8953
> 2021 Feb 23 11:18:09 unbound[1391:0] debug: setup SSL certificates
> 2021 Feb 23 11:18:09 unbound[1391:0] debug: chdir to /etc/unbound
> 2021 Feb 23 11:18:09 unbound[1391:0] debug: switching log to /var/log/unbound/unbound.log

Version is:  1.13.0
     ./configure --with-libevent --with-pthreads --enable-subnet --sysconfdir=/etc --with-ssl

OS:  CentOS Linux release 7.6.1810 (Core) 
     Linux version 3.10.0-693.el7.x86_64 (builder@kbuilder.dev.centos.org)    ( cat /proc/version)

if Setting interface-automatic to no, 853 port is bound.

>  [1614050855] unbound[1570:0] notice: Start of unbound 1.13.0.
> 2021 Feb 23 11:27:35 unbound[1570:0] debug: creating udp4 socket 0.0.0.0 53
> 2021 Feb 23 11:27:35 unbound[1570:0] debug: creating tcp4 socket 0.0.0.0 53
> 2021 Feb 23 11:27:35 unbound[1570:0] debug: creating udp6 socket :: 53
> 2021 Feb 23 11:27:35 unbound[1570:0] debug: creating tcp6 socket :: 53
> 2021 Feb 23 11:27:35 unbound[1570:0] debug: creating udp4 socket 0.0.0.0 853
> 2021 Feb 23 11:27:35 unbound[1570:0] debug: creating tcp4 socket 0.0.0.0 853
> 2021 Feb 23 11:27:35 unbound[1570:0] debug: setup TCP for SSL service
> 2021 Feb 23 11:27:35 unbound[1570:0] debug: creating udp6 socket :: 853
> 2021 Feb 23 11:27:35 unbound[1570:0] debug: creating tcp6 socket :: 853
> 2021 Feb 23 11:27:35 unbound[1570:0] debug: setup TCP for SSL service
> 2021 Feb 23 11:27:35 unbound[1570:0] debug: creating tcp4 socket 127.0.0.1 8953

**Comment by wcawijngaards** [comment]
The `interface-automatic` option causes unbound to ignore the `interface` lines.

This was made this way because the interface automatic option needs a socket address of the wildcard 0.0.0.0 or ::.

**Comment by hough-ctc** [comment]
ok! Thanks!

**Comment by wcawijngaards** [comment]
I guess this closes the issue, if you need something in particular just comment again, reopen or make a new one.
