### ISSUE TITLE
Unbound 1.13.1 ignoring ttl from python module

### ISSUE THREAD

**Issue by drachs** [NLnetLabs/unbound#437]
Our team is migrating from unbound 1.4.17 to 1.13.1.   During testing of this migration we noticed TTL's returned by our python module were all being set to 0.

To reproduce this issue, set up unbound 1.13.1 with the resgen.py example code.   Do a query such as this:
```
[root@dev-dns-1 pythonmod]# dig ttltest.localdomain @127.0.0.1

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.68.rc1.85.amzn1 <<>> ttltest.localdomain @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 13343
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ttltest.localdomain.           IN      A

;; ANSWER SECTION:
ttltest.localdomain.    0       IN      A       127.0.0.1

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Mar  2 18:40:50 2021
;; MSG SIZE  rcvd: 53
```

The same query with unbound 1.4.17  against the exact same code (resgen.py from 1.13.1) returns as follows:
```
[root@dev-dns-1 pythonmod]# dig ttltest.localdomain @127.0.0.1

; <<>> DiG 9.8.2rc1-RedHat-9.8.2-0.68.rc1.85.amzn1 <<>> ttltest.localdomain @127.0.0.1
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 42485
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;ttltest.localdomain.           IN      A

;; ANSWER SECTION:
ttltest.localdomain.    10      IN      A       127.0.0.1

;; Query time: 0 msec
;; SERVER: 127.0.0.1#53(127.0.0.1)
;; WHEN: Tue Mar  2 18:42:06 2021
;; MSG SIZE  rcvd: 53
```

**Comment by wcawijngaards** [comment]
Hi,

So if I use resgen.py from the latest code repository version and run it in a test, I get the 10 TTL answer.  Not the 0 TTL answer. So I do not see the problem at all?  Is there some sort of local-zone statement in your config that prohibits the python module from answering?  At verbosity 4 the log contains also a log message with the packet with the 10 TTL answer logged as the answer from the python module that it handed to unbound.  This is with python 3.9.

**Comment by drachs** [comment]
Thank you for looking into this, because you could not reproduce we did a deep dive into our environment looking for local issues and found that long ago someone had added `cache-max-ttl: 0` to the unbound.conf.   This appears to have been ignored by the older version of unbound we were using but not by the latest version.

Sorry for that, this issue was a configuration problem on our end.   Thank you for checking it out.
