### ISSUE TITLE
[FR] Echo back requester's IP

### ISSUE THREAD

**Issue by NightMachinery** [NLnetLabs/unbound#443]
Some DNS servers have a feature where they echo back the requester's IP:

```
❯ dig TXT +short o-o.myaddr.l.google.com @8.8.4.4
"2a00:1450:400a:1001::104"
"edns0-client-subnet 2.180.196.0/24"
```

I think this is currently not possible in Unbound?

**Comment by wcawijngaards** [comment]
No, that would be an unwanted feature.  If it was enabled by default.

If you want to have this, you could write a python script or use the dynamic library module.  The resip.py example echoes the IP in a TXT record, you could modify it to suit your need, perhaps.
https://github.com/NLnetLabs/unbound/blob/master/pythonmod/examples/resip.py

**Comment by NightMachinery** [comment]
@wcawijngaards Thanks, I think that would work. Does the docker image support python modules?

**Comment by NightMachinery** [comment]
https://github.com/NLnetLabs/pythonunbound is not up-to-date, but it should work. Thanks!

**Comment by ximon18** [comment]
@NightMachinary: I just manually built and pushed `nlnetlabs/pythonunbound:1.13.1` to Docker Hub based on Unbound 1.13.1 (still running in Ubuntu 18.04 with Python 3.6.9). I have also updated the Docker `:latest` tag to point to the new image version.
