### ISSUE TITLE
respip and cname chasing

### ISSUE THREAD

**Issue by rajeevn1** [NLnetLabs/unbound#446]
version: 1.13.1
module-config: "respip validator iterator"

Even though rpz blocks eagle.actonservice.com in direct query, it is not blocked when part of cname. 

~> dig absinfo.eagle.org
absinfo.eagle.org.      26367   CNAME   eagle.actonservice.com.
eagle.actonservice.com. 83967   CNAME   ci90.actonsoftware.com.
ci90.actonsoftware.com. 83967   A       207.189.124.20
~> dig eagle.actonservice.com
~>

**Comment by gthess** [comment]
This is indeed not part of the RPZ code yet. The current RPZ logic only applies to the initial query name.
There is *ongoing* work to implement the rest of the RPZ draft (https://github.com/NLnetLabs/unbound/pull/401) though.

**Comment by wcawijngaards** [comment]
See commit https://github.com/NLnetLabs/unbound/pull/401/commits/7f39003c04c2f663f5e1697b7be22724076b5e5b for #401.  That should solve this issue.

**Comment by gthess** [comment]
The RPZ PR was merged and this should have been addressed in 1.14.0; closing.
