### ISSUE TITLE
unbound servfails and "anchor could not be fixed" error

### ISSUE THREAD

**Issue by coldbootinitheart** [NLnetLabs/unbound#450]
Tried running unbound on raspbian os but got the error mentioned in the title, synced time, made sure to regenerate the root.key file, double checked the ownership and permission to no avail. Decided to nuke my sdcard to install the preconfigured dietpi thinking it might be a mistake on my part, still the same issue. I do not have a good grasp of networking and am pretty sure it has nothing to do with diet-pi so decided to ask help here. Here are some log files:
[dietpi.confg](http://paste.debian.net/1190404)
[systemctl status unbound](http://paste.debian.net/1190406)
[dig unbound output](http://paste.debian.net/1190407/)
[normal dig output](http://paste.debian.net/1190408/)
[unbound logs when trying to dig google.com](http://paste.debian.net/1190410/)

I am using openwrt on my router if that matters.
Any help would be greatly appreciated!

**Comment by gthess** [comment]
I suspect that this is because of `use-caps-for-id: yes`. Can you turn that to `no` and check again?

**Comment by coldbootinitheart** [comment]
~~Hi I did as you suggested, seems to not fix the issue: [unbound logs](http://paste.debian.net/1190445/)
Should I increase verbosity? Currently its at 3.
Increased verbosity to 5: [logs](http://paste.debian.net/1190446/)~~

**Comment by gthess** [comment]
Am I right that the second log (verbosity 5) ended in a correct resolution? At least this is what I see.
It seems that you don't get consistent DNS answers from your network.

I see that for the caps-for-id errors earlier, where a wrong 0x20-ID is returned and results in activating unbound's fallback for caps-for-id. This could result in query failure or timeout from the client since it will take more time to verify that spoofing is not taking place.

The same could be happening when you (re)start the service.
I suppose you restart the service between configuration changes.
This makes the package-helper run before unbound is started. Part of the helper is to run unbound-anchor which will handle (create/update) the root anchor for DNSSEC. This will be done by either DNS (RFC 5011) or HTTP and the ICANN certificate (as a fallback when the 5011 probe timer allows). Failures while quering could result in the "anchor could not be fixed" error you saw.

Which version of unbound is this?

**Comment by coldbootinitheart** [comment]
Oh god I am pretty sure I sent you the wrong logs I am extremely sorry
correct logs: 
[unbound log](http://paste.debian.net/1190476/)
[dig log](http://paste.debian.net/1190477/)

my unbound version is `1.9.0`
it seems I get the ip of google but it still returns SERVFAIL (in the dig log anyway)?

**Comment by gthess** [comment]
I don't see any RRSIGs in the responses. Is DNSSEC stripped from your upstream network?
Also unbound reports that the upstream servers are not authoritative but instead resolvers themselves (REC_LAME). Are you sure your traffic goes where it is supposed to go?

I don't see any configured forwarders in your config file, so queries should normally reach authoritative nameservers.

This doesn't look like an unbound issue for the moment btw, more like a local configuration/network one.

**Comment by coldbootinitheart** [comment]
even after completly resetting my router to defaults and updating openwrt to the lastest version I still get the same pattern of errors in the logs. Everything in openwrt is default yet dnssec is not being validated. I am a little lost on how to fix this, can you help me out?

**Comment by gthess** [comment]
You can try `harden-dnssec-stripped: no` and see if it helps.
Although you run the risk of a downgrade attack that disables security for a zone.

Alternatively you could configure unbound to forward all traffic to DNS over TLS open resolvers. That should bypass whatever seems to be happening in your network.
For configuring this, adding the following sections would work:
```
server:
    tls-cert-bunble: /path/to/your/system/cert-bundle   # in debian /etc/ssl/certs/ca-certificates.crt
forward-zone:
    name: "."
    forward-addr: <IP>@<PORT>#<HOSTNAME>
    forward-tls-upstream: yes
```
For upstreams resolvers you can look at https://dnsprivacy.org/wiki/display/DP/DNS+Privacy+Public+Resolvers#DNSPrivacyPublicResolvers-DNS-over-TLS(DoT).
Only resolvers under the DoT sections are relevant.

**Comment by coldbootinitheart** [comment]
unbound did not work even when I disabled `harden-glue`, `harden-dnssec-stripped` and `use-caps-for-id`.
Tried your second suggestion and apparantly everything works (used quad9 and activated above options)!
[unbound log](https://paste.debian.net/1190676/)
[dig log](https://paste.debian.net/1190677/)
[unbound config](https://paste.debian.net/1190678/)

pardon my ignorance but I thought the whole point of using unbound was to avoid relying on third parties for dns resolution? How is this any different from just using the quad9 dns from say pihole?

Honestly I am still a bit confused by your previous statements about local configuration/network error, am I doing something wrong? I am failing to comprehend why exactly DNSSEC gets stripped from my network. Is it my ISP? I was really hoping to use unbound for dns resolvs too.

**Comment by coldbootinitheart** [comment]
So I used my mobile data on my pi with the unbound setup (with out `forward-zone`) and everything started working again. This can only mean that my ISP is doing something to prevent dnssec from working (or a misconfiguration in openwrt which I doubt as all options are default)? I am extremely concerned and would like to know if something can be done (besides `forward-zone` option) as I won't be able to change ISPs easily.

**Comment by gthess** [comment]
>pardon my ignorance but I thought the whole point of using unbound was to avoid relying on third parties for dns resolution?

Well it is, but if unbound can't get the correct answers there is not much resolving that can be had :)

>I am extremely concerned and would like to know if something can be done (besides forward-zone option) as I won't be able to change ISPs easily.

If this is happening at your ISP level you can't do anything except tunneling your DNS traffic.

You do rely on third party resolvers that way but based on the information on the site I linked you can make an informed decision which resolvers suit your privacy concerns. Just to note that unbound still validates DNSSEC itself even if forwarding queries to other resolvers.

**Comment by coldbootinitheart** [comment]
is it possible to somehow just tunnel dns traffic on different port but use unbound's resolver? As I think dns on port 53 is being intercepted.
Also this: [nslookup log](https://paste.debian.net/1190816/) I think pretty much guarantees my ISP is doing some shady stuff.

**Comment by gthess** [comment]
It is not possible to use another port for authoritatives. 53 is what they listen on.

That nslookup output says it uses 88.88.88.88 as the resolver to ask the question to and comes back with an answer. I don't see what is wrong there. Also I don't know where 88.88.88.88 comes from in your system.

I am also tempted to close this issue as this is not a bug in unbound and purely a system/network one.

**Comment by coldbootinitheart** [comment]
@gthess 88.88.88.88 is just a bogus dns resolver. The fact that it resolvs it means dns queries are possibly being hijacked/intercepted (atleast from what I have read online). This had nothing to do with unbound in the end. I am extremely sorry for wasting your time and thank you again for being so considerate and helping me out. Hopefully this issue helps someone else with dns interception going on at the ISP level.

**Comment by coldbootinitheart** [comment]
Closed as this had nothing to do with unbound.
