### ISSUE TITLE
It seems that unbound continues to read disk.

### ISSUE THREAD

**Issue by yutayu** [NLnetLabs/unbound#455]
from iotop 

  PID  PRIO  USER    DISK READ>  DISK WRITE  SWAPIN      IO    COMMAND                    
21439 be/4 unbound    1796.00 K      0.00 B  0.00 %  0.02 % unbound -d

It seems that unbound continues to read disk.
What does it mean?

apt show unbound
Package: unbound
Version: 1.9.0-2+deb10u2

uname -a
Linux raspberrypi 5.10.17-v7+ #1403 SMP Mon Feb 22 11:29:51 GMT 2021 armv7l GNU/Linux

**Comment by yutayu** [comment]
and I don't log.

**Comment by wcawijngaards** [comment]
You are out of memory and swapping to disk, perhaps? If unbound is set to a large cache size, it grows. When then the unbound process is too big to fit in memory, it is swapped to disk and this causes disk read and write.

If it is swap activity, you can disable swap by turning off swap. Or freeing up memory, possibly by configuring smaller values for the unbound cache sizes.

**Comment by yutayu** [comment]
I didn't notice swap. Thanks.
I will tune . :)
