### ISSUE TITLE
Better set pointer to null after delete in iterator/iterator.c

### ISSUE THREAD

**Issue by XidongWang-coder** [NLnetLabs/unbound#463]
In function _iter_deinit()_ in file iterator/iterator.c, it's better to set _iter_env->priv_ and _iter_env->donotq_ to null after line 120 and line 121. A similar fix is in [https://github.com/NLnetLabs/unbound/commit/2c4be0c2012a157e0dde6e7cf7712ec146931186](url).

https://github.com/NLnetLabs/unbound/blob/13e445d50b6e2a9441d9364d4213a57781d9e6f1/iterator/iterator.c#L111-L128

**Comment by gthess** [comment]
Thanks for noting that but on second look I don't believe this would solve a similar issue as in the commit you link to.
In that commit the `val_env->kcache` and `val_env->neg_cache` pointers that were freed were also accessible from the general environment value, that is why `env->key_cache` and `env->neg_cache` needed to be set to NULL.

**Comment by gthess** [comment]
Closing this, feel free to reopen though.
