### ISSUE TITLE
Possible NAME:WRECK issue?

### ISSUE THREAD

**Issue by roeckelein** [NLnetLabs/unbound#464]
In sldns/wire2str.c's sldns_wire2str_dname_scan(), a DNS name compression target is computed, but the subsequent sanity check only verifies the target is within the packet bounds.   Shouldn't this sanity check instead (at least) insure the target occurs in the packet, AFTER the DNS header, and BEFORE the "current" location in the packet?

...around line 807:
```
		/* find out what sort of label we have */
		if((labellen&0xc0) == 0xc0) {
			/* compressed */
			uint16_t target = 0;
			if(in_buf && *dlen == 0)
				return w + sldns_str_print(s, slen,
					"ErrorPartialDname");
			else if(!in_buf && pos+1 > pkt+pktlen)
				return w + sldns_str_print(s, slen,
					"ErrorPartialDname");
			target = ((labellen&0x3f)<<8) | *pos;
			if(in_buf) { (*d)++; (*dlen)--; }
			/* move to target, if possible */
			if(!pkt || target >= pktlen)                               // <<<<<<<<< INSUFFICIENT SANITY CHECK?
				return w + sldns_str_print(s, slen,
					"ErrorComprPtrOutOfBounds");
			if(counter++ > maxcompr) {
				if(comprloop && *comprloop < 10)
					(*comprloop)++;
				return w + sldns_str_print(s, slen,
					"ErrorComprPtrLooped");
			}
			in_buf = 0;
			pos = pkt+target;
			continue;

```

Ideally, the target should be verified against a list of possible "rest-of-domain-name" targets within the packet between DNS header and "current location", but that is getting a little crazy ;)

**Comment by wcawijngaards** [comment]
That is not really the DNS specification, the domain name compression is allowed to be to anywhere. This is from the RFCs that define domain name compression.

For that reason unbound accepts a wider range of compression encodings. It allowed anywhere in the packet to work, like the specification allows for. But when unbound creates compressed packets, it only compresses to previously seen domain names. And unbound does not compress non-compressible domain names.

So, we produce what your sanity check wants. But accept the wider range of inputs that the RFC allows.

**Comment by roeckelein** [comment]
OK, thanks for taking a look!
