### ISSUE TITLE
ublocktrace.0

### ISSUE THREAD

**Issue by icebluey** [NLnetLabs/unbound#467]
unbound version: 1.13.1

Every time I run unbound-anchor command , this ublocktrace.0 file will be generated in current directory.
What is this file for and how to avoid generating it?

**Comment by gthess** [comment]
This file is generated when debugging the code (specifically lock verification).
I suspect that you compiled unbound with debugging options enabled like `--enable-debug` and `--enable-lock-checks`.
Is that the case?

**Comment by icebluey** [comment]
Yes, you are right.
It does not generate ublocktrace.0 file after I remove `--enable-lock-checks`  option.

**Comment by gthess** [comment]
Good to hear!
I would generally suggest to not enable any debug options like `--enable-lock-checks` when you want to run unbound as a service. These are meant to be used during development to make sure that certain conditions/assumptions remain valid while editing the code. They introduce more code to accomplish that and it leads to lower performance.
