### ISSUE TITLE
OpenSSL 1.0.1 can no longer build Unbound

### ISSUE THREAD

**Issue by FGasper** [NLnetLabs/unbound#468]
Fix: https://github.com/NLnetLabs/unbound/pull/466

**Comment by wcawijngaards** [comment]
Fixed that and also the dohclient test program compiles and removed a compile warning. Unbound needs OpenSSL 1.0.2 (or later) for the ALPN calls to use HTTP2 for DNS-over-HTTPS service. Thank you for the patch to fix it.
