### ISSUE TITLE
Unbound does not configure or build on Mac Catalina or Big Sur

### ISSUE THREAD

**Issue by eoinnorris** [NLnetLabs/unbound#471]
Whenever I try and configure the project I get this error:

configure: error: OpenSSL found in /usr/local, but version 0.9.7 or higher is required

Which looks like it comes from from this line in the configuration file. 

	      # see if OPENSSL 1.0.0 or later (has EVP MD and Verify independency)
	      { $as_echo "$as_me:${as_lineno-$LINENO}: checking if openssl supports SHA2 and ECDSA with EVP" >&5
$as_echo_n "checking if openssl supports SHA2 and ECDSA with EVP... " >&6; }
	      if grep OPENSSL_VERSION_TEXT $ssldir/include/openssl/opensslv.h | grep "OpenSSL" >/dev/null; then
		if grep OPENSSL_VERSION_NUMBER $ssldir/include/openssl/opensslv.h | grep 0x0 >/dev/null; then
		  { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
$as_echo "no" >&6; }

Here's what the version file looks like
<img width="763" alt="Screenshot 2021-04-22 at 14 06 11" src="https://user-images.githubusercontent.com/156072/115719415-f7ddb200-a373-11eb-8796-a6e2f381671b.png">

My scripting is weak, but I am not sure what the grep 0x0  is doing.

**Comment by eoinnorris** [comment]
See this as well

$as_echo "#define HAVE_EVP_SHA256 1" >>confdefs.h

                            { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
$as_echo "yes" >&6; }

else

                            { $as_echo "$as_me:${as_lineno-$LINENO}: result: no" >&5
$as_echo "no" >&6; }
                            as_fn_error $? "OpenSSL found in $ssldir, but version 0.9.7 or higher is required" "$LINENO" 5

fi

**Comment by Jakker** [comment]
You said at the unbound-users list that you tried to use brew, so I assume you have that still around. 
What I did was:
`
brew install openssl
`
(Lots of noise)
`brew install expat
`
(Some more noise) Then I downloaded a fresh copy op the unbound tar ball unpacked it and after
```
$ ./configure --with-ssl=/usr/local/Cellar/openssl@1.1/1.1.1k --with-libexpat=/usr/local/Cellar/expat/2.3.0
$ make
```
it was done. Most time was spend figuring out where brew was storing the libraries etc.

Enjoy!

**Comment by eoinnorris** [comment]
Thanks, Jaap!

I’ll give that a try. 

Is that on a Mac?

Eoin.

**Comment by Jakker** [comment]
Yes, it was on a Mac running Big Sur

**Comment by eoinnorris** [comment]
Thanks, that works. I tried something like that before and it failed, however it was because the openssl@1.1 path was openssl@1.1/1.1.1i for some reason. Just realised that when I tried the build. So I have the latest build building on 10.15 and 11. My own forked build is failing for some other reason on make, but you have clearly fixed that.

**Comment by eoinnorris** [comment]
So I will close.
