### ISSUE TITLE
Unbound block list , How to know from query log that if domain refused or not?

### ISSUE THREAD

**Issue by jamesarems** [NLnetLabs/unbound#482]
I have configured an Unbound server with domain block list, blocking works perfectly fine. But from the query log, i can only see that blocked domain is queried, that's it. I tired with

```
server:
local-zone: "00009483.com" always_refuse
```
and increased log level as well, but i cannot able to find any indication that this domain refused / blocked . Is there any configuration do i need to update ? or is it possible to add custom query message for blocked domains?

**Comment by bjovereinder** [comment]
Dear James,

Thank you for using Unbound.

We use GitHub Issues for bugs and feature requests only.

For questions like configuration or support, we use the Unbound community mailing list, see https://lists.nlnetlabs.nl/mailman/listinfo/unbound-users.

Can you resend your question to the mailing list?  

Thank you,

-- Benno
