### ISSUE TITLE
[FR] python binding allow to load a compiled python

### ISSUE THREAD

**Issue by dtouzeau** [NLnetLabs/unbound#483]
We use nuitka in order to compile python code for best performances.
nuitka can compile python code to binary or to module.

It seems that unbound allows only to load a pure python scripts.

Possible to load a python module or compiled python instead ?

**Comment by wcawijngaards** [comment]
Unbound uses python to run the script file. I thought that would pick up any .pyc file, but something goes wrong?

Loading .pyc files does not seem to have a robust API. Does the tool you use recommend how to use the binary?

**Comment by dtouzeau** [comment]
After thinking about it, it will be too difficult and time consuming to integrate such a solution.
On the other hand, the community will not turn to this kind of solution.
The best is to compile python modules and call them with a python script that includes unbound
I close the case
