### ISSUE TITLE
Unbound occasionally reports broken stats

### ISSUE THREAD

**Issue by jaseemabid** [NLnetLabs/unbound#485]
**Describe the bug**

Some of the time stats reported by unbound through the control socket formats floats incorrectly and this broke [unbound_exporter](https://github.com/kumina/unbound_exporter) for us. The values are unexpectedly negative and in the wrong format. 

Example stats:
```
$ sudo unbound-control -c /etc/unbound.conf stats_noreset | grep -F '0.-'

thread1.recursion.time.avg=0.-402022313
thread2.recursion.time.avg=0.-1726117941
thread3.recursion.time.avg=0.-1813043235
total.recursion.time.avg=0.-701203423
```

Prometheus exporter failed to parse these lines:
```
2021/05/06 16:47:22 Failed to scrape socket: strconv.ParseFloat: parsing "0.-1176731538": invalid syntax
```

The [exporter barfs on the first parse error](https://github.com/kumina/unbound_exporter/blob/master/unbound_exporter.go#L451-L465) and reports unbound as down. 

```
$ curl -s 127.0.0.1:10062/metrics  | grep unbound_up

# HELP unbound_up Whether scraping Unbound's metrics was successful.
# TYPE unbound_up gauge
unbound_up 0
```

It's interesting how avg is negative but median is not. That may help us reverse engineer and figure out what happened?
```
thread1.recursion.time.avg=0.-402022313
thread1.recursion.time.median=0.000276483
```

I can try to reproduce and find more information if required. Unfortunately the running binary didn't have debug symbols so I couldn't extract all local variables with gdb. 

**To reproduce**

1. Not sure yet, will try to isolate the issue and report more stats later.

**Expected behavior**

1. Report time stats in the correct format
2. Make sure time stats are always positive. 

**System:**
 - Unbound version: Version 1.7.3
 - OS: CentOS
 
I know its an old version, but it doesn't look like the metrics code changed a lot since then. I couldn't find anything related in the changelog either. 
 
 Thanks!

**Comment by wcawijngaards** [comment]
The commit fixes the issue by making sure that the values are not negative. It then turns to 0.

It also casts the size_t to long long to stop what may be an integer overflow causing the negative numbers in the division function. This likely stops the wrong statistic report, but I do not know for sure; I guess it was related to a 32bit compile. Thanks for the report!

**Comment by jaseemabid** [comment]
Whoa! That's a pretty quick fix @wcawijngaards. Thank you so much 🍻
