### ISSUE TITLE
Error Unbound Windows 10_64 20h2 and 21h1

### ISSUE THREAD

**Issue by Marcosdw** [NLnetLabs/unbound#488]
Hello,

Error logs windows

C:\Program Files\Unbound\unbound.exe:0] error: udp connect failed: No error for xxxxxx port 53

Thank you for giving me a solution

Sorry, I use a French / English online translator

unbound_setup_1.13.1.exe
OS : Windows 64 20H2 : 19042.964

**Comment by RyoKakomi** [comment]
Hello,

I think already listen UDP 53 port.

1. Please check netstat command.
`netstat -oan`

2. Checking first steps PID.
Maybe you already have a DNS client service running.

Best Regards,

**Comment by gthess** [comment]
Hi @Marcosdw,

Maybe your case is similar with https://github.com/NLnetLabs/unbound/issues/381?
Is there a firewall somewhere that blocks DNS queries over UDP ?

**Comment by Marcosdw** [comment]
I created a Firewall rule for C:\Program Files\Unbound\unbound.exe incoming and outgoing connection and the problem is still present

C:\Program Files\Unbound\unbound.exe:0] error: udp connect failed: No error for xxxxxx port 53

unbound_setup_1.13.1.exe
OS : Windows 64 21H1 : 19043.1052

**Comment by RyoKakomi** [comment]
Hi @Marcosdw,

Try to stop the DNS Client service.
`net stop dnscache`


Regards,

**Comment by Marcosdw** [comment]
@RyoKakomi 
does not work

**Comment by Marcosdw** [comment]
Test parameters
Add in: C:\Program Files\Unbound\Service.conf
```
# May be set to yes if you have ipv6 connectivity
do-ip6: no
```
in the last line.

For the moment no error in the event observer.

**Comment by gthess** [comment]
I understand that this is resolved then, IPv6 connectivity issue on the host; closing.
