### ISSUE TITLE
module-config respip missing in unbound.conf.5.in man page

### ISSUE THREAD

**Issue by he32** [NLnetLabs/unbound#492]
**Describe the bug**
The documentation of the "respip" module-config is missing in the unbound.conf(5) man page source.
I'm wondering what other parts of the documentation for the RPZ feature is missing...

**To reproduce**
1. Inspect documentation, see it missing.

**Expected behavior**
The documentation for a supported feature should not be omitted.

**System:**
 - Unbound version: 1.13.1
 - OS: NetBSD
 - `unbound -V` output:
```
Version 1.13.1

Configure line: --enable-allsymbols --with-libexpat=/usr --with-libevent=/usr --enable-event-api --with-ssl=/usr --with-pidfile=/var/run/unbound/unbound.pid --sysconfdir=/usr/pkg/etc --with-libnghttp2 --enable-gost --enable-sha2 --prefix=/usr/pkg --build=x86_64--netbsd --host=x86_64--netbsd --mandir=/usr/pkg/man --enable-option-checking=yes
Linked libs: pluggable-libevent 2.1.8-stable (it uses kqueue), OpenSSL 1.1.1k  25 Mar 2021
Linked modules: dns64 respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Additional information**
A sweep should probably be made to add any other missing documentation bits related to the RPZ feature.

**Comment by wcawijngaards** [comment]
The documentation for the respip module is contributed and is it is in the doc folder, here is the location in the code repository
https://github.com/NLnetLabs/unbound/blob/master/doc/IP-BasedActions.pdf 

That said, a note in the man page could be useful too.

**Comment by he32** [comment]
Hm, OK, thanks for the pointer -- that's useful.

However, that looks a little "half-integrated".
I guess you won't object to me drafting a pull request to integrate this in the man page properly?

**Comment by he32** [comment]
To this end, see pull request #494.

**Comment by wcawijngaards** [comment]
Yes of course, thank you. That looks nice for the documentation in the man page!

Merged it into the code repository. Removed the comment line in minimal-responses.

**Comment by he32** [comment]
Right, the comment was just to balance the single-apostrophe in the previous line, and fix the font highlighting in my emacs... :)
