### ISSUE TITLE
Unbound ignores do-ip6: no

### ISSUE THREAD

**Issue by birdie-github** [NLnetLabs/unbound#502]
**Describe the bug**
```
nslookup  www.youtube.com
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
www.youtube.com	canonical name = youtube-ui.l.google.com.
Name:	youtube-ui.l.google.com
Address: 108.177.14.93
Name:	youtube-ui.l.google.com
Address: 74.125.205.91
Name:	youtube-ui.l.google.com
Address: 64.233.164.93
Name:	youtube-ui.l.google.com
Address: 74.125.131.190
Name:	youtube-ui.l.google.com
Address: 74.125.205.190
Name:	youtube-ui.l.google.com
Address: 74.125.131.136
Name:	youtube-ui.l.google.com
Address: 74.125.131.91
Name:	youtube-ui.l.google.com
Address: 74.125.205.93
Name:	youtube-ui.l.google.com
Address: 64.233.161.91
Name:	youtube-ui.l.google.com
Address: 74.125.205.136
Name:	youtube-ui.l.google.com
Address: 64.233.161.190
Name:	youtube-ui.l.google.com
Address: 108.177.14.91
Name:	youtube-ui.l.google.com
Address: 64.233.161.93
Name:	youtube-ui.l.google.com
Address: 64.233.164.91
Name:	youtube-ui.l.google.com
Address: 64.233.164.190
Name:	youtube-ui.l.google.com
Address: 74.125.131.93
Name:	youtube-ui.l.google.com
Address: 2a00:1450:4010:c0e::5b
Name:	youtube-ui.l.google.com
Address: 2a00:1450:4010:c0f::be
Name:	youtube-ui.l.google.com
Address: 2a00:1450:4010:c0e::be
Name:	youtube-ui.l.google.com
Address: 2a00:1450:4010:c0f::5b
```

**To reproduce**
```
cat /etc/unbound/conf.d/dns-tls.conf
server:
  tls-cert-bundle: /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
  do-ip6: no
  root-hints: /etc/unbound/root.hints

forward-zone:
  name: "."
  forward-tls-upstream: yes

  forward-addr: 1.1.1.1@853#cloudflare-dns.com
  forward-addr: 9.9.9.9@853#dns.quad9.net

```

**Expected behavior**
**No** IPv6 addresses returned from upstream servers.

**System:**
 - Unbound version: unbound-1.13.1-1.fc33.x86_64
 - OS: Fedora 33
 - `unbound -V` output: 
 ```
Version 1.13.1

Configure line: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= 
--disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin 
--sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 
--libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man 
--infodir=/usr/share/info --with-pythonmodule --with-pyunbound PYTHON=/usr/bin/python3 
--enable-dnstap --with-libnghttp2 --with-libevent --with-pthreads --with-ssl --disable-rpath 
--disable-static --enable-relro-now --enable-pie --enable-subnet --enable-ipsecmod 
--with-conf-file=/etc/unbound/unbound.conf --with-pidfile=/run/unbound/unbound.pid 
--enable-sha2 --disable-gost --enable-ecdsa --with-rootkey-file=/var/lib/unbound/root.key
Linked libs: libevent 2.1.8-stable (it uses epoll), OpenSSL 1.1.1k  FIPS 25 Mar 2021
Linked modules: dns64 python ipsecmod subnetcache respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Additional information**
Add any other information that you may have gathered about the issue here.

All other configurations files are unchanged.

This is even worse for Google Chrome:

```
Host resolver cache
Capacity: 1000
Current State
Active entries: 1
Expired entries: 0
Network changes: 1
Hostname	Family	Addresses	TTL	Expires	Network Isolation Key	Network changes
www.youtube.com	?	
2a00:1450:4010:c0f::5d
2a00:1450:4010:c0e::88
2a00:1450:4010:c0e::be
2a00:1450:4010:c0f::be
-1000	2021-06-13 19:13:43.093	null null	1
```

**Comment by gthess** [comment]
Hi,

This is not what `ip6:no` is supposed to do.
From the manpage:
>Enable  or  disable  whether ip6 queries are answered or issued. [...] it does not impact the contents of the DNS traffic, which may have ip4 and ip6 addresses in it.

So this option is only about IPv6 network connections to/from Unbound. It does not involve DNS AAAA queries/records.

---

There is a *contributed* patch at `contrib/aaaa-filter-iterator.patch` that kinda does what you are looking for. From its manpage:
>aaaa-filter: <yes or no>
Activate behavior similar to BIND's AAAA-filter.
This forces the dropping of all AAAA records, unless in the case of
explicit AAAA queries, when no A records have been confirmed.
This also causes an additional A query to be sent for each AAAA query.
This breaks DNSSEC!

If this is something that would work for you, you need to patch Unbound and compile it yourself.

---

If you want to shut down IPv6 on your machine, local configuration on the system itself or the applications you would like for this to happen (e.g., browser) is the better solution.

**Comment by birdie-github** [comment]
I do understand that but could you consider an option which tells unbound not to return IPv6 AAAA addresses?

**Comment by birdie-github** [comment]
@gthess 

I do understand that but could you consider an option which tells unbound not to return IPv6 AAAA addresses?

This bug report is sort of ambiguous and almost invalid - I'm not looking to disable IPv6 support in unbound, I'm looking to stop it from returning IPv6 addresses from upstream servers.

**Comment by Jakker** [comment]
Note that this is already in the user contribute directory: `aaaa-filter-iterator.patch`

It does break DNSSEC:

```+.B aaaa\-filter: \fI<yes or no>
+Activate behavior similar to BIND's AAAA-filter.
+This forces the dropping of all AAAA records, unless in the case of
+explicit AAAA queries, when no A records have been confirmed.
+This also causes an additional A query to be sent for each AAAA query.
+This breaks DNSSEC!
+.TP
```

**Comment by Jakker** [comment]
"Artem S. Tashkinov" writes:

 > @gthess 
 >
 > I do understand that but could you consider an option which tells unbound not to return IPv6 AAAA addresses?
 >
 > This bug report is sort of ambiguous invalid - I'm not looking to disable IPv6 support in unbound, I'm looking to stop it from returning IPv6 addresses from upstream servers.

See the comment at https://github.com/NLnetLabs/unbound/issues/502#issuecomment-861482965

	jaap
