### ISSUE TITLE
Compilation against openssl 3.0.0 beta2 is failing to build unbound

### ISSUE THREAD

**Issue by satya-rajesh** [NLnetLabs/unbound#515]
Unbound when compiled against openssl beta2, it is failing to compile.
https://github.com/openssl/openssl/releases/tag/openssl-3.0.0-beta2

**To reproduce**
1. Use openssl 3.0.0 beta2 from https://github.com/openssl/openssl/releases/tag/openssl-3.0.0-beta2
2. Compile unbound

**Expected behavior**
The build should succeed

**System:**
 - Unbound version: 1.12.0
 - OS: photon

Error:
smallapp/unbound-control.c: In function 'ssl_path_err':
smallapp/unbound-control.c:490:4: warning: implicit declaration of function 'ERR_GET_FUNC'; did you mean 'ERR_GET_LIB'? [-Wimplicit-function-declaration]
  490 |   (ERR_GET_FUNC(err) == SYS_F_FOPEN ||
      |    ^~~~~~~~~~~~
      |    ERR_GET_LIB

/bin/ld: .libs/unbound-control.o: in function `ssl_path_err':
/usr/src/photon/BUILD/unbound-1.12.0/smallapp/unbound-control.c:490: undefined reference to `ERR_GET_FUNC'
/bin/ld: /usr/src/photon/BUILD/unbound-1.12.0/smallapp/unbound-control.c:491: undefined reference to `ERR_GET_FUNC'
collect2: error: ld returned 1 exit status
make: *** [Makefile:355: unbound-control] Error 1

**Comment by satya-rajesh** [comment]
As per: https://www.openssl.org/news/changelog.html

The ERR_GET_FUNC() function was removed. With the loss of meaningful function codes, this function can only cause problems for calling applications.

**Comment by wcawijngaards** [comment]
In the latest version of the code repo, this compilation problem is fixed. Also the use of deprecated functions has been replaced with the new OpenSSL 3.0.0 provider API. Thanks for the links!

**Comment by satya-rajesh** [comment]
Thanks, it works now
