### ISSUE TITLE
dohclient ssl shakehand failue

### ISSUE THREAD

**Issue by ghpass** [NLnetLabs/unbound#524]
hi,
When dot and doh are tried,   DoT is ok,  but DoH doesn't work well.  
   
_#./dohclient  -s 127.0.0.1 paypal.com A IN
   [1628843078] unbound[22642:0] error: could not allocate SSL_CTX pointer crypto error:140A90A1:lib(20):func(169):reason(161)
   [1628843078] unbound[22642:0] fatal error: cannot create ssl ctx_  

Enviroment is as follows:   
1) unbound 1.13.0   
    ./configure --with-libevent --with-pthreads --enable-subnet --sysconfdir=/etc --with-ssl -with-libnghttp2   
2) version of openssl and openssl-devel      
      #yum list openssl-devel openssl        
       _Installed Packages   
        openssl.x86_64                                                           1:1.0.2k-21.el7_9                                                                         
        openssl-devel.x86_64                                                  1:1.0.2k-21.el7_9_ 
 3) 443 and 853 port are opened 
   some of  server configures:  
    _interface: 0.0.0.0@853 			#ipv4 over TLS
    interface: ::0@853 			#ipv4 over TLS
    interface: 0.0.0.0@443
    interface: ::0@443_
    #netstat -aptn
    _tcp        0      0 0.0.0.0:853             0.0.0.0:*               LISTEN      22615/unbound       
    tcp        0      0 0.0.0.0:443              0.0.0.0:*               LISTEN      22615/unbound 
    tcp6       0      0 :::443                   :::*                    LISTEN      22615/unbound       
    tcp6       0      0 :::853                  :::*                    LISTEN      22615/unbound_
  4) The certification  is generated as follows:    
    #openssl req -newkey rsa:2048 -new -nodes -x509 -days 3650 -keyout key.pem -out cert.pem   
    in the server configure:   
    _tls-service-key: key.pem
    tls-service-pem: cert.pem_

**Comment by ghpass** [comment]
Resolved!
There is a bug in dohclient.c.
Add following line in the beginning of run() funtion, and ok!
     SSL_library_init();

**Comment by gthess** [comment]
Already fixed in 7226d2f9f24f2047357a192ebb7be9754357fe93.
