### ISSUE TITLE
unbound not doing upstream tcp connectivity

### ISSUE THREAD

**Issue by dinguz** [NLnetLabs/unbound#535]
**Describe the bug**

When running unbound with loglevel 3 or above, I see lots of these messages:

outnettcp got tcp error -1

and the occasional (but much less often):

tcp error for address 9.9.9.9 port 853

which is configured as a DoH upstream server.

When looking at the stats, the TCP usage is always 0.

**To reproduce**
1. set loglevel to 3 or above
2. restart unbound
3. do some random DNS queries

**Expected behavior**

Unbound being able to successfully use tcp transfers.

**System:**
 - Unbound version: 1.13.1
 - OS: OPNsense 21.7.1 (FreeBSD 12.1-RELEASE-p19-HBSD)
 - `unbound -V` output:

Version 1.13.1

Configure line: --with-ssl=/usr/local --with-libexpat=/usr/local --disable-dnscrypt --disable-dnstap --with-libnghttp2 --enable-ecdsa --disable-event-api --enable-gost --with-libevent --with-pyunbound=yes --with-pythonmodule=yes LDFLAGS=-L/usr/local/lib ac_cv_path_SWIG=/usr/local/bin/swig --disable-subnet --disable-tfo-client --disable-tfo-server --with-pthreads --prefix=/usr/local --localstatedir=/var --mandir=/usr/local/man --infodir=/usr/local/share/info/ --build=amd64-portbld-freebsd12.1
Linked libs: libevent 2.1.12-stable (it uses kqueue), OpenSSL 1.1.1k  25 Mar 2021
Linked modules: dns64 python respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

**Additional information**
Add any other information that you may have gathered about the issue here.

I have double-checked the firewall and NAT configuration, and nothing seems to be blocking DNS related TCP traffic, or any traffic originating from the firewall itself.

**Comment by wcawijngaards** [comment]
Can you show what the tcp error is? I thought it would also log the error description with the tcp error?

These errors are not shown a lower verbosity, and they show because you ask you see them. This is what happens to the socket connections. And it is logged for you.

**Comment by dinguz** [comment]
It doesn't log anything else unfortunately, so I'm not sure where to start
looking next. Can you give any pointers? Or should I run with a higher
loglevel?


Met vriendelijke groet,

Derkjan de Haan


Op wo 25 aug. 2021 om 09:48 schreef Wouter Wijngaards <
***@***.***>:

**Comment by wcawijngaards** [comment]
Can you give some context, preferably on verbosity 4 or more, around these log lines? For a couple examples? I think this may also get logged for like, TCP resets, host down, and maybe stuff like timeouts.

The query num tcp stat is downstream queries, not upstream ones. So I guess your clients use UDP not TCP.

**Comment by dinguz** [comment]
Loglevel 3 does give no context for these messages to occur.

Here is a log excerpt with loglevel 4, it has some of the errors at 18:49:00
[resolver_20210825.log](https://github.com/NLnetLabs/unbound/files/7048609/resolver_20210825.log)

If I understand correctly the messages occur when unbound is trying to close down a TCP connection, and then fails to do so. When checking the firewall state table, I also noticed quite a few DNS-related TCP connections in the time_wait state, so this may be related.

**Comment by wcawijngaards** [comment]
From what it looks like, the other side closed the TCP connections at that time. That is also what is reported with the tcperror -1; there is no further errno logged, so I think that means the connection closed, without further errors. Eg. that means the other server close()d the socket. This is normal if the other server restarts for example, or maybe because it wants to manage the TCP connections that it has; possibly with timeouts for how long they can be used. And that may explain why it does several at the same time. Unbound then reopens tcp connections and continues.

The time_wait state in the firewall confirms the close of the connection. So maybe there is nothing really wrong, the tcperror logged is that the connection unexpectedly closed. Does this mean there is no problem?

**Comment by dinguz** [comment]
I guess this indeed means there is no problem. Thanks for the support and the time it took you to investigate and react.

On a side note, would it make sense to change the 'tcp usage' stats in a way so it is clear from the name that only inbound connections are counted here? Or better maybe, make 2 different stats, differentiating between inbound en outbound tcp usage?

**Comment by wcawijngaards** [comment]
The values are called 'num.query.tcp' for incoming tcp and 'num.query.tcpout' for outgoing tcp. The man page for unbound-control also lists the statistics output as incoming connections for the tcp usage, which is about the number of buffers in use.
