### ISSUE TITLE
libunbound-dev package on Ubuntu 20 does not validate ed25519/ed448

### ISSUE THREAD

**Issue by pinheadmz** [NLnetLabs/unbound#542]
Ubuntu 20 ("focal") comes with [OpenSSL version 1.1.1](https://packages.ubuntu.com/search?keywords=openssl&searchon=names&suite=focal&section=all) and has available [libunbound-dev version 1.9.4](https://packages.ubuntu.com/search?keywords=libunbound&searchon=names&suite=focal&section=all)

OpenSSL version 1.1.1 [provides support for ed25519 and ed448](http://manpages.ubuntu.com/manpages/focal/en/man7/Ed448.7ssl.html)

However, I am an unable to validate these DNSSEC algorithms with this configuration.

Unbound should support those algorithms if it is built on a system where OpenSSL supports those algortihms: [(unbound release notes)](https://www.nlnetlabs.nl/news/2018/May/03/unbound-1.7.1-released/) [(related issue)](https://github.com/NLnetLabs/unbound/issues/271).

This makes me wonder if the Ubuntu package maintainer either accidentally or for-some-reason on purpose disabled those algorithms in the `libunbound-dev` package available for that version of Ubuntu?

I contribute to a [nodejs package](https://github.com/chjj/unbound) that binds to libunbound-dev and I noticed this issue testing on Ubuntu 20 both locally and on Github Actions where 20 is the latest Ubuntu version available.

I was able to fix our CI tests by [installing libunbound from source as part of the CI action](https://github.com/chjj/bns/pull/32/commits/bfa401650ca51c35c30d6e1df8d228ad05ccb875) and now our ed25519 and ed448 tests pass.

**Comment by pinheadmz** [comment]
Cross-posted: https://answers.launchpad.net/ubuntu/+source/unbound/+question/698721

**Comment by gthess** [comment]
Hi! Thanks for bringing this to our attention but this indeed seems like a package issue.
As we are not responsible for that, I am closing this issue.
