### ISSUE TITLE
Disable IPv6 query server option result in syntax error

### ISSUE THREAD

**Issue by hari-bo** [NLnetLabs/unbound#543]
According to the server option described in https://www.nlnetlabs.nl/documentation/unbound/unbound.conf/ I am trying to disable IPv6 queries.

unbound.conf contains at the bottom of these two lines
#custom
do-ip6: no

As soon as I start unbound, this immediately results in an error.
_/opt/unbound/etc/unbound/unbound.conf:318: error: syntax error
,read /opt/unbound/etc/unbound/unbound.conf failed: 1 errors in configuration file_

I am using the latest version Unbound 1.13.2

**Comment by wcawijngaards** [comment]
Likely you have the option in the wrong section. The option has to be in the 'server:' section. And often, at the end of the file there are other sections, like stub, forward, remote-control sections. You can start the server section again for server section options by putting `server:` in a line above the `do-ip6: no` option. Like this:
```
server:
    do-ip6: no
```

**Comment by hari-bo** [comment]
Wow, so simple... thanks that did the trick!

**Comment by wcawijngaards** [comment]
Good to hear that it worked! This ticket is closed, then.
