### ISSUE TITLE
"forward-host" do NOT support TLS upstream

### ISSUE THREAD

**Issue by liheng562653799** [NLnetLabs/unbound#546]
According to my viewing of code and experiments, "forward-host" config item dont support TLS.
SUPPORT:         forward-host: 1.1.1.1@853#one.one.one.one    
NOT SUPPORT:  forward-host:one.one.one.one@853#one.one.one.one

If I am right, can you please tell me are there any reasons why "forward-host" dont support TLS.
Or it is just to be done to support more features that are less important like this;  and if so, do we have any plan to support this?

**Comment by gthess** [comment]
This should now be supported, thanks for bringing it up!
Btw, when using forward-host beware of the cycle dependency of resolving the name that you use there.
