### ISSUE TITLE
[FR]How to use unbound with the feature: DNS over Https？

### ISSUE THREAD

**Issue by ShipeiXu** [NLnetLabs/unbound#568]
As in the question, how to compile, configure, and run so that unbound can support the feature of dns over https？

thaks！

I have saw that DoH have been supported in version 1.12.0

**Comment by ShipeiXu** [comment]
this is a repeated issue? uhhhh!

**Comment by wcawijngaards** [comment]
You need to compile with libnghttp2. This means `./configure --with-libnghttp2` or you can specify an exact path for the library with `./configure --with-libnghttp2=path`. Then compile and install. Or use a package that compiled with the option. `unbound -V` outputs what options are used for the compile, so you can check if the package has the option.

Then enable DoH in the configuration, in unbound.conf. It uses the option `https-port` that defaults to 443, and then bind to that interface, eg. `interface: 127.0.0.1@443`. And then you have DoH service.

With the options `tls-service-key` and `tls-service-pem` you can set the certificate files. There are more options for TLS and HTTPS and for TCP connections. The defaults work. Options like `http-endpoint`, `http-max-streams`, `http-query-buffer-size`, `http-response-buffer-size`, `http-nodelay`, and `http-notls-downstream`.

**Comment by ShipeiXu** [comment]
I'll try again today.

**Comment by ShipeiXu** [comment]
Is there a specific config.file？ When I configure the interface :0.0.0.0@443, it's still  resolv dns protocol。

**Comment by ShipeiXu** [comment]
unbound can not work!!!!!

**Comment by ShipeiXu** [comment]
[root@localhost ~]# /usr/unbound/sbin/unbound -V
Version 1.13.2

Configure line: --with-libnghttp2 --prefix=/usr/unbound/ --enable-subnet --with-pthreads --with-libevent --enable-ipset
Linked libs: libevent 2.0.21-stable (it uses epoll), OpenSSL 1.0.2k-fips  26 Jan 2017
Linked modules: dns64 subnetcache ipset respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

**Comment by ShipeiXu** [comment]
![image](https://user-images.githubusercontent.com/3360832/141730760-db5bf0d1-9e8e-4709-acbe-91459bef0f0c.png)

**Comment by ShipeiXu** [comment]
![image](https://user-images.githubusercontent.com/3360832/141731295-86e23eab-c5f4-43dd-b310-aeb49e358236.png)
