### ISSUE TITLE
unbound-checkconf reports fatal error if interface names are used as value for interfaces:

### ISSUE THREAD

**Issue by ddt-consult** [NLnetLabs/unbound#574]
For a unbound.conf containing something like this:

```
server:
         interfaces: lo
```

unbound-checkconf will report a fatal error:
`[1637242350] unbound-checkconf[25626:0] fatal error: cannot parse interface specified as 'lo'`

unbound itself does work and respects the interface config option, though.
This happens with an unbound compiled from the unbound-1.13.2.tar.gz source provided on the download section of the nlnetlabs website.

**Comment by wcawijngaards** [comment]
Fixed this, so that unbound-checkconf resolves the interface names, and checks if everything works fine, also for interface names. It also detects duplicate addresses, duplicate interface names and duplicate addresses from the resolution of the interface names. Thanks for the report!

**Comment by ddt-consult** [comment]
Thanks for fixing this so quickly!
