### ISSUE TITLE
What's the latest version of Unbound compatible with macOS10.13.6?

### ISSUE THREAD

**Issue by fgyamauti** [NLnetLabs/unbound#579]
Hi. I'm sorry if here is not the correct place to ask it. 

 What's the latest version of Unbound compatible with macOS10.13.6 (High Sierra)? The current version seems to be running in my system properly. Still, however, I'd prefer to confirm whether I can safely use all the features of the current version with my OS. The current manual mentions only macOS Big Sur, so I suppose it's a requirement.

 Thanks in advance.

**Comment by wcawijngaards** [comment]
The version to use is the latest unbound version. Where the manual mentions the version is because we tested it on that version, but unbound is fairly portable to a number of MacOS versions. So the last version of Unbound is the one to use.
