### ISSUE TITLE
Response refused from ARGUS

### ISSUE THREAD

**Issue by sand-max** [NLnetLabs/unbound#58]
Hi! I using "argus" as system monitoring. For bind check DNS work ok
But for unbound I get REFUSED, next messages:
12:46:50.881654 IP (tos 0x0, ttl 64, id 53425, offset 0, flags [DF], proto UDP (17), length 55)
    X.X.X.2.56121 >  X.X.X.60.53: [udp sum ok] 12024 A? cisco.com. (27)
12:46:50.882005 IP (tos 0x0, ttl 64, id 47423, offset 0, flags [none], proto UDP (17), length 40)
    X.X.X.60.53 >  X.X.X.2.56121: [bad udp cksum 0x98a1 -> 0xdcdd!] 12024 Refused- [0q] 0/0/0 (12)

And dig works OK
13:50:40.211764 IP (tos 0x0, ttl 64, id 33609, offset 0, flags [none], proto UDP (17), length 55)
 X.X.X.2.48985 >  X.X.X.60.53: [udp sum ok] 18953+ A? cisco.com. (27)
13:50:40.469015 IP (tos 0x0, ttl 64, id 19361, offset 0, flags [none], proto UDP (17), length 71)
    X.X.X.60.53 >  X.X.X.2.48985: [bad udp cksum 0x98c0 -> 0x15c0!] 18953 q: A? cisco.com. 1/0/0 cisco.com. [1h] A 72.163.4.185 (43)

**Comment by wcawijngaards** [comment]
Hi.  It could be that you are missing the rdflag in the lookup, unbound, by default, does not allow nonrecursive lookups.  But you can allow it by setting the allow_snoop in access-control for that IP address.
dig sets the +RD flag by default, but +norec is an option you can use to send without it.
If that is not it, I'd need more data than the tcpdump, maybe full packet, or, printout from wireshark, eg. dig-style printout would be nice.

**Comment by sand-max** [comment]
> Hi. It could be that you are missing the rdflag in the lookup, unbound, by default, does not allow nonrecursive lookups. But you can allow it by setting the allow_snoop in access-control for that IP address.
> dig sets the +RD flag by default, but +norec is an option you can use to send without it.
> If that is not it, I'd need more data than the tcpdump, maybe full packet, or, printout from wireshark, eg. dig-style printout would be nice.

Thanks ! I added in conf of argus "recurse: yes" . It's ok now!

**Comment by wcawijngaards** [comment]
Nice to know what the solution is, in case other users have it.  I can close this issue, then.
