### ISSUE TITLE
unbound 1.14.0rc1 segfault

### ISSUE THREAD

**Issue by bleve** [NLnetLabs/unbound#583]
Dec  6 09:16:11 foo-gw-01 kernel: unbound[2860272]: segfault at 28 ip 000056274c6fd9a8 sp 00007ffd200092a0 error 4 in unbound[56274c6af000+124000]

addr2line -e /usr/sbin/unbound -fCi 0x4E9A8
local_data_cmp
/usr/src/debug/unbound-1.14.0-0.1.rc1.foo8.x86_64/unbound-1.14.0rc1/services/localzone.c:126

**Comment by wcawijngaards** [comment]
Is this reproducible by having the particular set of config and a particular query? Perhaps querylog can tell what the last query is that hit local-zone or rpz? And the config is the settings for local-zone and rpz information that could be involved.

**Comment by bleve** [comment]
There is no rpz. And this is regression, this never happened with 1.13.2 with same config.

Three types of local zones configured.

local-data: configured overrides with some zones not visible in global dns.
rfc8806 config for root, ip6.arpa, in-addr.arpa and few other important zones.
auth-zone: configs for internal dns zones.

Segfault likely means d1 or d2 is NULL.

**Comment by wcawijngaards** [comment]
The auth-zone entries and rfc8806 copy of zones is not code that uses this function. But the local-data does.

The local-data settings and local-zone settings should be the ones that impact this code.

If you have the local-data configured, and then make the particular query in question, does that reproduce the failure? If so can you share the failure-producing set up?

**Comment by bleve** [comment]
No ide which query causes this - Added query and reply logging now.

**Comment by bleve** [comment]
This looks like being fixed on later versions.
