### ISSUE TITLE
unbound 1.14.0 segfault in alloc.c

### ISSUE THREAD

**Issue by bleve** [NLnetLabs/unbound#586]
Dec 11 17:41:23 foo-gw-01 kernel: unbound[494017]: segfault at 0 ip 00005617390fecb5 sp 00007ffc575b6318 error 4 in unbound[5617390a5000+127000]

$ addr2line -e /usr/sbin/unbound -fCi 0x59CB5
alloc_reg_obtain
/usr/src/debug/unbound-1.14.0-1.foo8.x86_64/unbound-1.14.0/util/alloc.c:333

Nothing in log but now I enabled coredumps to get more information next time.

**Comment by JiangHeng12138** [comment]
It is recommended that the coredump and config file be provided.
