### ISSUE TITLE
unbound-anchor cannot deal with full disk

### ISSUE THREAD

**Issue by wrohdewald** [NLnetLabs/unbound#595]
umbound 1.13.1 on debian bullseye

This morning, I found a full disk and a non-running unbound. Even after making room in the filesystem,
unbound refused to run:

[1641110455] unbound[7164:0] error: failed to read /var/lib/unbound/root.key

/var/lib/unbound# ls -lc
insgesamt 0
-rw-r--r-- 1 unbound unbound 0  2. Jan 00:00 root.key

So I assume that at midnight, unbound-anchor tried to update this by simply overwriting it. Which is of
course a recipe for disaster with a full disk.

A fix would be
1. create  root.key.new
2. mv root.key.new root.key

I fixed it by manually running unbound-anchor

**Comment by teunvink** [comment]
Sadly, we see this happen from time to time on machines part of the NLNOG RING (which NLNetLabs is part of as well!). A fix would very much be appreciated!

**Comment by gthess** [comment]
With the above commit unbound-anchor will behave like Unbound when updating the auto-trust-anchor-file. Namely write to a temp file and then replace the original (same strategy as @wrohdewald suggested above).
