### ISSUE TITLE
unset the RA bit when a query is blocked by an unbound RPZ nxdomain reply

### ISSUE THREAD

**Issue by jpgpi250** [NLnetLabs/unbound#596]
Pi-hole + unbound user here (currently v1.14.0), using RPZ zones, this to ensure 'always blocked', using, for example, the list from [urlhaus](https://urlhaus.abuse.ch/downloads/rpz).

When using pi-hole + unbound, unbound is used as the upstream resolver.
The developer of pihole-FTL has added code to allow detection of responses, blocked by the upstream resolver.
Pi-hole (dnsmasq+++) can use a variety of upstream resolvers. Apparently, when using with upstream resolver quad9, the following [code](https://github.com/pi-hole/FTL/blob/a296265896876ba8178aac4394df51f0c1e9cb66/src/dnsmasq_interface.c#L2496-L2498) allows pi-hole to indicate the query was blocked by the upstream resolver:

[FR]: is it possible to provide this information from unbound to pi-hole, e.g. unset the RA bit when a query is blocked by an unbound RPZ nxdomain reply?

**Comment by wcawijngaards** [comment]
The commit adds the option `rpz-signal-nxdomain-ra` and if it is set, then the RA flag is turned off for NXDOMAIN blocked queries by the RPZ.

**Comment by jpgpi250** [comment]
tested, compiled unbound master branch 1.14.1 and used latest pi-hole version
added **rpz-signal-nxdomain-ra: yes** to the rpz config

works perfectly, result as expected in the pihole query log. thanks @wcawijngaards 

![image](https://user-images.githubusercontent.com/24669386/148285321-5fa07b71-7d99-44a1-a825-eecf5e9b5a10.png)
