### ISSUE TITLE
unbound-checkconf fatal error: module conf 'respip dns64 validator iterator' is not known to work

### ISSUE THREAD

**Issue by mgraves00** [NLnetLabs/unbound#598]
**Describe the bug**
When running unbound-checkconf the following error is received.

[1641393252] unbound-checkconf[45905:0] fatal error: module conf 'respip dns64 validator iterator' is not known to work

However when running the server it runs just fine.  Checking similar issue #192 it appears that the process is to open and issue and report that it's working.

**To reproduce**
1. add 'module-config: "respip dns64 validator iterator"' to config
2. run 'unbound-checkconf'

**Expected behavior**
unbound-checkconf does not report any error.

**System:**
 - Unbound version: 1.13.2
 - OS: openbsd 7.0
 - `unbound -V` output:
pons# unbound -V 
Version 1.13.2

Configure line: --enable-allsymbols --with-ssl=/usr --with-libevent=/usr --with-libexpat=/usr --without-pythonmodule --with-chroot-dir=/var/unbound --with-pidfile= --with-rootkey-file=/var/unbound/db/root.key --with-conf-file=/var/unbound/etc/unbound.conf --with-username=_unbound --disable-shared --disable-explicit-port-randomisation --without-pthreads
Linked libs: pluggable-libevent 1.4.15-stable (it uses kqueue), LibreSSL 3.4.1
Linked modules: dns64 respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

**Comment by wcawijngaards** [comment]
Thanks for the report, I did not know that this combination works. It is added to the list of available combinations that unbound-checkconf allows for.
