### ISSUE TITLE
[FR] RFC 9156 (obsoletes RFC 7816)

### ISSUE THREAD

**Issue by IlariStenrothValtori** [NLnetLabs/unbound#599]
This is a request to review changes in RFC 9156 since RFC 7816 (DNS Query Name Minimisation to Improve Privacy). Separate FR issues should be created for each change needed in Unbound. After releasing a RFC 9156 conformant release the Unbound RFC compliance list on the web site and on the documentation should be updated.

**Comment by wtoorop** [comment]
I asked @ralphdolmans about this a few weeks ago and he answered:

> Yes I would say that Unbound is compliant. At least in strict minimisation mode. The RFC is basically based on the decisions made when developing qname minimization in Unbound, which are proven to work. 
> 
> Changes in the RFC that were already in Unbound include the use of the A qtype, the algorithm to limit the number of queries, and the justification to not minimise forwarded queries. 

which leaves updating the RFC compliance list I suppose

**Comment by gthess** [comment]
Website and doc also updated.
