### ISSUE TITLE
Questions about forward-zone

### ISSUE THREAD

**Issue by liang-hiwin** [NLnetLabs/unbound#608]
Forwarding to a specific domain name looks like this:
forward-zone:
         name: "google.com."
         forward-addr: 1.1.1.1
         forward-addr: 8.8.8.8

So how is the domain name that is not configured in this forwarding resolved, recursively resolved?

**Comment by wcawijngaards** [comment]
The most specific forward-zone clause is used to resolve a query. Other names use the other forward clauses and stub clauses. If you configure nothing, it uses the root hints to resolve the query.

**Comment by liang-hiwin** [comment]
> forward-zone:
> name: "google.com."
> forward-addr: 1.1.1.1
> forward-addr: 8.8.8.8

If I configure it like this, are all domain names resolved using 9.9.9.9&&208.67.222.222, and google.com using 8.8.8.8&&1.1.1.1?

forward-zone:
name: "google.com."
forward-addr: 1.1.1.1
forward-addr: 8.8.8.8

forward-zone:
name: "."
forward-addr: 9.9.9.9
forward-addr: 208.67.222.222

**Comment by wcawijngaards** [comment]
Yes, it is then resolved like that. It matches the longest suffix of the queried name.

**Comment by liang-hiwin** [comment]
> Yes, it is then resolved like that. It matches the longest suffix of the queried name.

thanks

**Comment by wcawijngaards** [comment]
Nice to hear that this resolves the issue :-) . Closing the issue for it.
