### ISSUE TITLE
Unbound 1.14.0 does not open LAN port 53 in Windows 10. Only at 127.0.0.1

### ISSUE THREAD

**Issue by JmaxxamJ** [NLnetLabs/unbound#609]
-example.conf:

verbosity: 0
interface: 192.168.1.4
port: 53
outgoing-interface: 192.168.1.5

- netstat -ab:
Show  TCP    127.0.0.1:53           MediaServer:0          LISTENING
 [unbound.exe]
But no 192.168.1.4.

- Windows 10 pro, default install. Only Windows Firewall, Unbound - enable all.

Configure line: --host=x86_64-w64-mingw32 --build=x86_64-redhat-linux-gnu --target=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --exec-prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --bindir=/usr/x86_64-w64-mingw32/sys-root/mingw/bin --sbindir=/usr/x86_64-w64-mingw32/sys-root/mingw/sbin --sysconfdir=/usr/x86_64-w64-mingw32/sys-root/mingw/etc --datadir=/usr/x86_64-w64-mingw32/sys-root/mingw/share --includedir=/usr/x86_64-w64-mingw32/sys-root/mingw/include --libdir=/usr/x86_64-w64-mingw32/sys-root/mingw/lib --libexecdir=/usr/x86_64-w64-mingw32/sys-root/mingw/libexec --localstatedir=/usr/x86_64-w64-mingw32/sys-root/mingw/var --sharedstatedir=/usr/x86_64-w64-mingw32/sys-root/mingw/com --mandir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/man --infodir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/info --enable-debug --enable-static-exe --disable-flto --disable-gost --with-ssl=/home/wouter/src/unbound/unbound-dist-UZ29la/sslinstall --with-libexpat=/home/wouter/src/unbound/unbound-dist-UZ29la/wxpinstall
Linked libs: event winsock (it uses WSAWaitForMultipleEvents), OpenSSL 3.0.0 7 sep 2021
Linked modules: dns64 respip validator iterator

**Comment by gthess** [comment]
You could be using the wrong configuration file. In Windows the default configuration file is `service.conf`; try and edit that file instead. Furthermore, Unbound would complain and not start if it can't listen on the configured IP(s).

**Comment by gthess** [comment]
Closing this as inactive non-issue.
