### ISSUE TITLE
Redis and prefetching

### ISSUE THREAD

**Issue by ol-iver** [NLnetLabs/unbound#614]
There are a couple of points unclear to me how redis (cachedb) is working in combination with the prefetch functionality
- Are records stored in redis only prefetched?
- When an unbound instance prefetches a record of its own cache, does it update the record in redis accordingly?
- When an unbounds instaces prefetches a record of its own cache, does it query redis for an updated record before resolving it by itself?

Could someone please clarify that?

**Comment by wcawijngaards** [comment]
The first question is not the case, the records are prefetched based on the internal cache.
The second question, yes they are also stored in the cachedb redis storage after a prefetch of the record.
Yes unbound attempts to query the cachedb storage for the record before resolving it itself. It does that for all queries, and also prefetch queries walk through this code path.

**Comment by ol-iver** [comment]
That helps a lot. Thank you 😄
