### ISSUE TITLE
Unable to stop Unbound in Windows console (does not respond to CTRL+C command)

### ISSUE THREAD

**Issue by NativeDevMan** [NLnetLabs/unbound#624]
Unable to stop Unbound in Windows console (does not respond to CTRL+C command).
I have not met another application that does not know how to stop on CTRL + C. Fix this glaring bug please.

**To reproduce**
unbound.exe -d -p -c unbound.conf
then 
CTRL+C

**System:**
 - Unbound version: 1.15.0
 - OS: Windows
 - `unbound -V` output:  Version 1.15.0

Configure line: --host=x86_64-w64-mingw32 --build=x86_64-redhat-linux-gnu --target=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --exec-prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --bindir=/usr/x86_64-w64-mingw32/sys-root/mingw/bin --sbindir=/usr/x86_64-w64-mingw32/sys-root/mingw/sbin --sysconfdir=/usr/x86_64-w64-mingw32/sys-root/mingw/etc --datadir=/usr/x86_64-w64-mingw32/sys-root/mingw/share --includedir=/usr/x86_64-w64-mingw32/sys-root/mingw/include --libdir=/usr/x86_64-w64-mingw32/sys-root/mingw/lib --libexecdir=/usr/x86_64-w64-mingw32/sys-root/mingw/libexec --localstatedir=/usr/x86_64-w64-mingw32/sys-root/mingw/var --sharedstatedir=/usr/x86_64-w64-mingw32/sys-root/mingw/com --mandir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/man --infodir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/info --enable-debug --enable-static-exe --disable-flto --disable-gost --with-ssl=/home/wouter/src/unbound/unbound-dist-slSyV9/sslinstall --with-libexpat=/home/wouter/src/unbound/unbound-dist-slSyV9/wxpinstall
Linked libs: event winsock (it uses WSAWaitForMultipleEvents), OpenSSL 3.0.0 7 sep 2021
Linked modules: dns64 respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

**Comment by wcawijngaards** [comment]
Thanks for the report! The issue is likely that there was no `SIGBREAK` handling in some parts of the code. The commit patches this to add the `SIGBREAK` handler to the list of signals that causes unbound to stop, much like `SIGINT` on Linux and FreeBSD.

This adds the code to the repository, and it is an improvement. I do not know if it actually works now for you, but it seems very likely.
