### ISSUE TITLE
letsencrypt Domain name won't resolve

### ISSUE THREAD

**Issue by dsm1212** [NLnetLabs/unbound#627]
**Describe the bug**
The name acme-v02.api.letsencrypt.org won't resolve. It seems like the servers unbound is using are just never available. I had been watching this fail for a while assuming it was just some server not reachable, but it doesn't seem to ever clear and I need it to renew a web certificate. I temporarily defined the domain to the ip I got from 8.8.8.8 in my pihole so I could do the cert update and it worked. So I'm good for the time being, but I'd like to know how to diagnose this further. I'm overwhelmed with logging. I can gather more logging if you tell me what to enable.

**To reproduce**
From a client run "dig acme-v02.api.letsencrypt.org" with request going to unbound.

After some time I get back:

; <<>> DiG 9.10.6 <<>> acme-v02.api.letsencrypt.org
;; global options: +cmd
;; connection timed out; no servers could be reached

Log attached with verbosity 2 and SERVFAIL logging enabled. 
[fail.log](https://github.com/NLnetLabs/unbound/files/8057605/fail.log)

**Expected behavior**
Response with IP 172.65.32.248 should return

**System:**
 - Unbound version: 1.14.0 (docker latest tag from a few weeks ago)
image is sha256:009d59258ba3096b5222667c86fb77563c08a2f3beaa7dd86ee134021114a766
 
 - OS: debian
 - `unbound -V` output:
 Version 1.14.0

Configure line: --with-deprecate-rsa-1024 --disable-dependency-tracking --prefix=/opt/unbound --with-pthreads --with-username=_unbound --with-ssl=/opt/openssl --with-libevent --with-libnghttp2 --enable-tfo-server --enable-tfo-client --enable-event-api
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 3.0.1 14 Dec 2021
Linked modules: dns64 respip validator iterator
TCP Fastopen feature available

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

**Comment by dsm1212** [comment]
Gah, I think I truncated the log at the wrong SERVFAIL. The error is the same as the one shown though for s3.amazonaws.com: "could not fetch nameservers for 0x20 fallback". Seems to be an example of the same thing.

**Comment by dsm1212** [comment]
I disabled use-caps-for-id and reran. I still get no servers found for this letsencrypt address. I do have both ipv4 and ipv6 fully enabled. Maybe that is causing this? Log with verb 4 attached.
[failedsearch.log](https://github.com/NLnetLabs/unbound/files/8062136/failedsearch.log)

**Comment by dsm1212** [comment]
I re-enabled use-caps-for-id and set do-ip6 to no and now when I dig this lets encrypt address or ping it, I get a result! However it's always the ipv6 address. Dig never returns the ipv4 address for that domain name. In fact ping4 to this address gives "ping4: acme-v02.api.letsencrypt.org: Address family for hostname not supported". I'm a little confused what do-ip6 really does.

**Comment by dsm1212** [comment]
After thinking about my configuration I realized that do-ipv6:no is fine for me. I have pihole in front of unbound and that supports both ipv4 and ipv6 with unbound in the backend over only ipv4. I think there is just some quirk using unbound with both ip4 and ip6 enabled. Could be a bug or could be something I don't understand. But is ok with me to drop this if you want.

**Comment by JiangHeng12138** [comment]
I had a similar problem, I disable do-ipv6 and prefer-ip6, but I still see IPv6 queries being issued to my forwarding server.
set local-zone: ip6.arpa. refuse may be fixed this.


From the man page of unbound.conf:

do-ip6: (yes or no)

Enable or disable whether ip6 queries are answered or issued. Default is yes. If disabled, queries are not answered on IPv6, and queries are not sent on IPv6 to the internet nameservers. With this option you can disable the ipv6 transport for sending DNS traffic, **it does not impact the contents of the DNS traffic, which may have ip4 and ip6 addresses in it.**

**Comment by gthess** [comment]
Hi,
This is what happens:
```
debug: sanitize: removing public name with private address <ca80a1adb12a4fbdac5ffcbc944e9a61.pacloudflare.com.> 172.65.32.248#53
```
Unbound removes that IPv4 address because it thinks it belongs to private space.
Do you have `private-address: ` in your config and maybe also a typo in the IPv4 there?

**Comment by dsm1212** [comment]
Doh! Thank you. I found a 172.0.0.0/8 entry, but I have no idea how it got there. Originally I did not have an unbound.conf so I copied the default one out of the container, I guess I must have done that but I'm surprised because I also had the specific entries for the docker subnets I've got. It makes no sense that I added this class A. Anyhow that explains it so closing.
