### ISSUE TITLE
Unbound does not remove pid file outside chroot directory when terminated

### ISSUE THREAD

**Issue by gctwnl** [NLnetLabs/unbound#63]
If I run `unbound` chrooted in `/opt/local/etc/unbound/` and the pidfile is `/opt/local/var/run/unbound/unbound.pid` then unbound can write the pidfile, but not remove it.

`nsd` does this.

When the pidfile is inside the chroot hirearchy, unbound behaves properly

Version 1.9.2

**Comment by ralphdolmans** [comment]
Thanks for your report. Removing the pidfile is not possible as privileges are dropped after the creation of this file.

NSD does not allow a pidfile outside of the chroot directory. Adding this requirement to Unbound is not desirable as this will break current installations. Note that Unbound should not have a problem on startup with an old pidfile present. If no process is running with the PID from the file Unbound will only log the "did not exit gracefully last time" message when the pidfile is in chroot, for exactly this reason.

If have added text to the ubound.conf man page to reflect this limitation.
