### ISSUE TITLE
Unify the RPZ log messages

### ISSUE THREAD

**Issue by pettai** [NLnetLabs/unbound#630]
**Describe the bug**
Very remotely related is a nit to https://github.com/NLnetLabs/unbound/issues/628

First hit on the QNAME log says "rpz: applied ..."
https://github.com/NLnetLabs/unbound/blob/master/services/rpz.c#L1405
While the response IP hit log says "RPZ applied ..." 
https://github.com/NLnetLabs/unbound/blob/master/respip/respip.c#L1304

**To reproduce**
Compare QNAME and Response IP RPZ hit logs (example here)
https://github.com/NLnetLabs/unbound/issues/628

**Expected behavior**
Log uniformly "rpz: ..." 

**System:**
 - Unbound version: 1.15.0
 - OS: Ubuntu
 - `unbound -V` output:

**Comment by gthess** [comment]
"rpz:" was chosen for solving this.
