### ISSUE TITLE
RPZ Logging irregularity

### ISSUE THREAD

**Issue by deteque** [NLnetLabs/unbound#635]
This isn't a big issue, but RPZ logging for hosts and domains produces this label in the log file:
i**nfo: rpz: applied**

However, it appears that rpz-ip triggers result in this label:
**info: RPZ applied** 

The "rpz" is capitalized and doesn't have a trailing colon after it.

While mostly cosmetic, it would make regexes simpler if the RPZ logging was more consistent.

**Comment by gthess** [comment]
Closing as a duplicate of #630 (which is now fixed).
"rpz:" was chosen.
