### ISSUE TITLE
Does Unbound support master-slave configuration?

### ISSUE THREAD

**Issue by JiangHeng12138** [NLnetLabs/unbound#638]
Hi
Does Unbound support master-slave configuration? One as the primary authority name server and another as the secondary authority name server.

**Comment by gthess** [comment]
Hi,
No Unbound only supports XFR-in from a primary server in the `auth-zone:` and `rpz:` configuration sections.
Unbound does not work as a primary nameserver providing NOTIFY and XFR-out to secondary nameservers.
