### ISSUE TITLE
Inquiry related to oss-fuzz fuzzers for unbound.

### ISSUE THREAD

**Issue by hyyi** [NLnetLabs/unbound#639]
Hello, I was recently looking into recreating and analyzing the scenarios where fuzzers helped find bugs in oss projects and was trying out the oss-fuzz fuzzers that had found bugs for unbound in the past. Unfortunately, I have found that the initial seed corpora for the fuzzers that had found bugs for unbound have gone missing around 2 weeks ago as the account hosting them seems to have been deleted. So I was hoping if by chance you might have a backup of the missing corpora?

I had asked the oss-fuzz maintainers but they also seem to be out of luck and got a suggestion to make an inquiry here.

Thank you in advance!

**Comment by wcawijngaards** [comment]
No, I do not have copies of that stuff. In unbound's repository, there is a contrib directory for contributed files, where a couple fuzz programs are located.

It is contrib/unbound-fuzzme.patch. The unbound-fuzzme program parses a packet. It is replaced by unbound-fuzzers.tar.bz2. It adds three programs that process their input.

**Comment by hyyi** [comment]
Thank you for the clarification :)

**Comment by infogulch** [comment]
@hyyi I found the missing fuzz files here: https://archive.softwareheritage.org/browse/origin/directory/?origin_url=https://github.com/luisx41/fuzzing-corpus&path=projects/unbound I have downloaded them locally in case they disappear again. The tip revision that has the files is 0026a4660ddc895fc46565d0920a3227646c3684.

I hope you can use these to continue your fuzzing research, I would be interested to read your results.

Perhaps these files could be merged directly in the unbound repo (under /testdata/, presumably). The `fuzz_n_fuzzer_seed_corpus.zip` files from `luisx41/fuzzing-corpus` repo total about 400kB, and `parse_packet_fuzzer_seed_corpus.zip` from the `jsha/unbound` repo is about 8MB. I think it would be worth it for these corpora to be preserved in the main repo to reduce the impact of url rotting. 



Note the corresponding issue on the oss-fuzz repo: https://github.com/google/oss-fuzz/issues/7348.

**Comment by hyyi** [comment]
@infogulch Thank you very much! These will definitely help me in my current research :) I hope I'll be able to share the results soon.
