### ISSUE TITLE
configuring `--with-libunbound-only` causes .pc file not to be installed

### ISSUE THREAD

**Issue by FGasper** [NLnetLabs/unbound#643]
**Describe the bug**
When you build and install _just_ libunbound, the .pc file isn’t installed. This makes it unduly complex to link against libunbound.

**To reproduce**
1. Unpack Unbound 1.15.0
2. `./configure --with-libunbound-only --prefix=$(pwd)/mybuild && make install`
3. `find mybuild | grep pc`

**Expected behavior**
The above should show `mybuild/lib/pkgconfig/libunbound.pc`.

**System:**
 - Unbound version: 1.15.0
 - OS: Ubuntu 20
 - `unbound -V` output: n/a

**Additional information**
The pkg-config file does install if you omit `--with-libunbound-only`.

**Comment by wcawijngaards** [comment]
The merged fix should fix the problem. The issue is closed.
