### ISSUE TITLE
Suspicious (?) delay in resolution

### ISSUE THREAD

**Issue by FGasper** [NLnetLabs/unbound#65]
```
#include <stdio.h>
#include <unbound.h>

#define MX 15
#define TXT 16

int main() {
    struct ub_ctx* ub = ub_ctx_create();
    struct ub_result* result;

    // Comment the following line out to see the MX query go much faster:
    ub_resolve(ub, "onlysslcertificates.cpanelssltest.org", TXT, 1, &result);
    printf("after TXT\n");

    // The following takes a very long time, but only if the TXT query
    // precedes it:
    ub_resolve(ub, "onlysslcertificates.cpanelssltest.org", MX, 1, &result);
    printf("after MX\n");

    ub_resolve_free(result);
    ub_ctx_delete(ub);

    return 0;
}
```
The above demonstrates a strangely long delay in resolving the MX query—but, as the comment notes, _only_ when there’s a TXT query before it. (An A query in lieu of the TXT does not produce the same delay.)

Strangely, when I try the same thing using Net::DNS::Resolver::Recurse, the delay isn’t there:
```
> perl -MNet::DNS::Resolver::Recurse -e'my $dns = Net::DNS::Resolver::Recurse->new(); $dns->query("onlysslcertificates.cpanelssltest.org", "TXT"); print "after TXT\n"; $dns->query("onlysslcertificates.cpanelssltest.org", "MX"); print "after MX\n"'
```

The DNS configuration for this domain is admittedly a bit wonky, but the long delay from libunbound still seems suspicious, particularly given that the Perl resolver doesn’t have the delay.

Thank you!

**Comment by wcawijngaards** [comment]
The TXT reply contains the NS set from the child side for the zone.  Thus the second lookup uses that information.  And those servers do not respond.  All timeouts.  After a while it falls back to using the nameservers received from the parentside of the delegation.
The child side of the zone cut is authoritative for the data.  The data should be the same, with potentially the parent not synchronized yet.  Unbound prefers the child side of the zone cut, but if that does not work, it uses the parent delegation information.  I think that answers the question about the delay, so I'll close.

```;; ->>HEADER<<- opcode: QUERY, rcode: NOERROR, id: 52176
;; flags: qr aa cd ; QUERY: 1, ANSWER: 1, AUTHORITY: 2, ADDITIONAL: 0 
;; QUESTION SECTION:
;; onlysslcertificates.cpanelssltest.org.	IN	TXT

;; ANSWER SECTION:
onlysslcertificates.cpanelssltest.org.	14400	IN	TXT	"v=spf1 +a +mx +ip4:10.215.218.116 ~all"

;; AUTHORITY SECTION:
cpanelssltest.org.	86400	IN	NS	ns2.cpanel.net.
cpanelssltest.org.	86400	IN	NS	ns1.cpanel.net.

;; ADDITIONAL SECTION:

;; EDNS: version 0; flags: do ; udp: 4096
```

**Comment by wcawijngaards** [comment]
Fixed the debug printout for this, it failed to print the cpanelssltest.org. NS record to the logs if minimal responses was turned on.  In commit https://github.com/NLnetLabs/unbound/commit/80c2c69fa75bbf0d4ed27da53883e9e53cdc595b .
