### ISSUE TITLE
Debian needs a package maintainer

### ISSUE THREAD

**Issue by triatic** [NLnetLabs/unbound#652]
The Debian package for Unbound seems to be going through a period of neglect: https://packages.debian.org/sid/unbound

As a great many people access Unbound via the Debian repository (and by extension the Ubuntu repository) I feel this neglect harms the Unbound project as a whole. 

Is there any scope for one of the Unbound developers to maintain the Debian package?

**Comment by eilandert** [comment]
I'm not a debian maintainer, nor am I an Unbound developer, but I have some packages wrapped up on https://deb.myguard.nl/pool/main/u/unbound/  (or https://deb.myguard.nl/openssl3/pool/main/u/unbound/ for openssl3 builds).

**Comment by gthess** [comment]
Hi @triatic, did you raise your concerns with the Debian maintainers?
We are not offering packages for Unbound and it is not in our immediate plans.
But maintaining Debian's own package is something completely different which is best left to the Debian community.

**Comment by triatic** [comment]
Hi @gthess ,

I am unsure of the best way of the best way to contact the Debian maintainers directly, perhaps it would be best coming from an Unbound developer?

My concerns were first raised when attempts were made to get Debian to compile dns-over-https support into the Unbound package. A bug report was filed in November 2020 and remains unresolved.

The latest package release is 1.13.1 and is over a year old.

I note that the ISC releases a PPA for bind: https://launchpad.net/~isc/+archive/ubuntu/bind

Although you say it is not in your plans, I do think it would be a useful service.

**Comment by gthess** [comment]
>I am unsure of the best way of the best way to contact the Debian maintainers directly, perhaps it would be best coming from an Unbound developer?

The page you linked has some email addresses you can contact on the side.
I believe users of the package have more influence than software developers; packagers are already informed by us when a new version is out.

>I note that the ISC releases a PPA for bind: https://launchpad.net/~isc/+archive/ubuntu/bind
Although you say it is not in your plans, I do think it would be a useful service.

This is something different than maintaining Debian's package (as you also point out :).
We had discussions about publishing compiled packages in the past but apart from the compilation configuration question itself (i.e., how to compile Unbound for generic usage, like in your DoH example) we also reached operational concerns for our side.
It's good to know that you would find the service useful; will keep in mind when we revisit the subject.

**Comment by florianernst** [comment]
JFTR, as I was just stumbling over this issue here:

In the meantime the unbound package in Debian has found a new uploader, and the 1.15.0 release found its way in Debian Sid, as requested in several issues in the Debian Bug Tracking system. See https://tracker.debian.org/pkg/unbound for the current state of the package.

As such I believe this issue here could just be closed.

**Comment by triatic** [comment]
Yes, it does appear Debian has a long-awaited new maintainer, so I will close this now.
