### ISSUE TITLE
ECS not working properly in version 1.15.0

### ISSUE THREAD

**Issue by jfb8856606** [NLnetLabs/unbound#654]
**Describe the bug**
Refer #605, this PR will cause ECS not to work properly while retry a query or restart the CNAME.

**To reproduce**
1. Set forward upstream and set `send-client-subnet=0.0.0.0/0` and `client-subnet-always-forward: yes`
2. Query a domain that has a NAME RR(such as www.baidu.com) from unbound.
3. The first query to upstream will add ECS opt, but the second(restart CNAME rr) will not add ECS opt;
4. Or while the upstream did not reply in time, the retry query will not add ECS opt also.

**Expected behavior**
Every request forwarded to upstream should carry the ECS option。

**System:**
 - Unbound version:1.15.0
 - OS:CentOS 8.0
 - `unbound -V` output:
```
Version 1.15.0

Configure line: --enable-subnet --with-libevent --with-pthreads --with-ssl --enable-dnscrypt
Linked libs: libevent 2.1.8-stable (it uses epoll), OpenSSL 1.1.1k  FIPS 25 Mar 2021
Linked modules: dns64 subnetcache respip validator iterator
DNSCrypt feature available

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Additional information**
I tried to modify it as below and it works fine, but I am not sure if the modification is correct.
```
diff --git a/services/outside_network.c b/services/outside_network.c
index a7e5fa3..59f7076 100644
--- a/services/outside_network.c
+++ b/services/outside_network.c
@@ -3373,7 +3373,8 @@ outnet_serviced_query(struct outside_network* outnet,
        /* Restore the option list; we can explicitly use the copied one from
         * now on. */
        per_upstream_opt_list = qstate->edns_opts_back_out;
-       qstate->edns_opts_back_out = backed_up_opt_list;
+       if (backed_up_opt_list)
+               qstate->edns_opts_back_out = backed_up_opt_list;

        if((client_string_addr = edns_string_addr_lookup(
                &env->edns_strings->client_strings, addr, addrlen))) {
```

**Comment by gthess** [comment]
Hi, this seems to work correctly for me. However there have been some changes for ECS since 1.15.0 namely (8e8ccfe3c3c5889a43d2a73e1cef7ebaced59d47, 7749d98a14359200d6d37028f27f07fd823623a1). Can you try with those fixes or just the latest from the master branch?

**Comment by jfb8856606** [comment]
thank you for your reply, I will try with these fixes and the latest from the master branch?

**Comment by jfb8856606** [comment]
They work correctly.
