### ISSUE TITLE
[Unbound 1.13.1] NXDOMAIN for queries to a stub-zone unless "stub-no-cache: yes" is used

### ISSUE THREAD

**Issue by callum-key** [NLnetLabs/unbound#667]
**Describe the bug**
Clients are receiving NXDOMAIN responses to queries for a stub-zone unless the `stub-no-cache: yes` directive is set.

Previously, all resolution for a stub zone was working correctly using the following unbound.conf lines:

stub-zone:
name: example.cso
stub-addr: 127.0.0.1@10053

Then, one day, resolution for this zone began failing, and Unbound would respond with "NXDOMAIN". 
This only happens for the specific stub-zone listed above, and a restart of Unbound and the device itself results in 5-10 minutes of correct "NOERROR" response, before then going back to responding with "NXDOMAIN".

I found another user who also had this issue on the Unbound-Users mailing list:
https://lists.nlnetlabs.nl/pipermail/unbound-users/2022-February/007656.html

I added `stub-no-cache: yes` to the stub-zone declaration, and DNS resolution has been consistent since.

**To reproduce**
Unfortunately, I do not understand how to reproduce this behaviour.
We have three Unbound servers in total (1.13.1), all running the same stub-zone configuration, but this only occurred recently on one of the devices. The other two are running well as expected, and no changes had to be made to their configuration.

**Expected behavior**
I would expect that "stub-no-cache: yes" does not need to be used.
This has not needed to be added to the other two Unbound servers that we host, so I would not expect it to be required on this one, either, for stub zone resolution to work.

**System:**
 - Unbound version: 1.13.1
 - `unbound -V` output: `[1650373683] unbound[3573:0] notice: Start of unbound 1.13.1.`

**Comment by wcawijngaards** [comment]
You need to upgrade. Version 1.13.2 has the following fix for it: https://github.com/NLnetLabs/unbound/commit/55ba863440dc5b1266b79f26ed92bbbdde5a2ebb . So upgrade to the latest version, or a later version that has the fix.

This is the fix you need, there is a higher nxdomain that gets into the cache, and this makes it synthesize nxdomain answers. The fix fixes the problem by using the stub definition to stop nxdomain synthesis. As a workaround you could disable the nxdomain synthesis with `harden-below-nxdomain: no`. But it is better to leave that enabled and upgrade to a fixed version. RFC standards want the nxdomain synthesis enabled, because it is better for cohesion of the DNS.

**Comment by callum-key** [comment]
Hi Wouter,

I very much appreciate your quick response.
I did check the unbound version patch notes for various newer releases, but I must have missed this or not looked hard enough!

Thank you for your time and confirming that, I'll ensure that we upgrade our unbound versions.

**Comment by sobcz** [comment]
I see same/similar problem with latest 1.15.0 (official Windows x64 binaries) and enabled DNSSEC validation.

With this (complete for testing) config it works as expected:
```
server:
	directory: "%EXECUTABLE%"
stub-zone:
	name: "domain.faketld"
	stub-addr: 192.168.80.2
	stub-first: no
	stub-tls-upstream: no
	stub-no-cache: no
```
Queries for "host1.domain.faketld", "faketld", "host2.domain.faketld"  (in this order) return \<address1\>, NXDOMAIN, \<address2\>. But when I add:
```
	auto-trust-anchor-file: "root.key"
	domain-insecure: "faketld"
```
Then result is \<address1\>, NXDOMAIN, NXDOMAIN. Using:
```
	stub-no-cache: yes
```
brings back expected \<address1\>, NXDOMAIN, \<address2\>.
