### ISSUE TITLE
Unbound DoH setup with Cloudflare

### ISSUE THREAD

**Issue by privacyguy123** [NLnetLabs/unbound#675]
Can't find any documentation on how to set this up?

**Comment by jo20201** [comment]
https://github.com/trinib/AdGuard-WireGuard-Unbound-Cloudflare#setup-cloudflare-with-dohodoh

**Comment by gthess** [comment]
Hello,
Unbound does not support DoH to upstream. However you can use DoT with Cloudflare as described in the previous link or https://dnsprivacy.org/public_resolvers/#dns-over-tls-dot.
