### ISSUE TITLE
When a domain has ns record but has no glue record, unbound may has no idea to recursive.

### ISSUE THREAD

**Issue by IIvyPy** [NLnetLabs/unbound#682]
**Describe the bug**
When a domain has ns record but has no glue record, unbound may has no idea to recursive.
eg: sina.j.baishangeek.cn

**To reproduce**
1.  unbound query A record of sina.j.baishangeek.cn;  
2. unbound has cached NS record of j.baishangeek.cn(116.196.126.20), so he tried to find A record of sina.j.baishangeek.cn toward 116.196.126.20 ;
3. 116.196.126.20 response NS record of sina.j.baishangeek.cn(ns3.sina.j.baishangeek.cn, ns2.sina.j.baishangeek.cn, ns1.sina.j.baishangeek.cn) but it has no glue record response;
4. unbound tried to find A record of ns3.sina.j.baishangeek.cn so it has to recursive sina.j.baishangeek.cn again.
5. so the steps above will be a loop.

**Expected behavior**

**System:**
 - Unbound version:  Version 1.10.1
 - OS: CentOS release 6.2 (Final)

**Comment by IIvyPy** [comment]
![image](https://user-images.githubusercontent.com/24852675/169971062-c5bb49f7-cdc3-49be-a771-795dc9a331e1.png)

**Comment by Philip-NLnetLabs** [comment]
This seems to me a configuration error in the j.baishangeek.cn zone on 116.196.126.20. What do you think that should happen in this case?

**Comment by IIvyPy** [comment]
> This seems to me a configuration error in the j.baishangeek.cn zone on 116.196.126.20. What do you think that should happen in this case?
![image](https://user-images.githubusercontent.com/24852675/170608008-06ed30fe-7850-4a59-be6a-a32d8ff31a35.png)
The NS record of  j.baishangeek.cn is 116.196.126.20, so Unbound go to ask record of sina.j.baishangeek.cn towards 116.196.126.20, which seems to be reasonable.

**Comment by IIvyPy** [comment]
> This seems to me a configuration error in the j.baishangeek.cn zone on 116.196.126.20. What do you think that should happen in this case?

Did you means the record in the j.baishangeek.cn zone on 116.196.126.20 which lack glue record for ns1.sina.j.baishangeek.cn ?

**Comment by IIvyPy** [comment]
> This seems to me a configuration error in the j.baishangeek.cn zone on 116.196.126.20. What do you think that should happen in this case?

But I mean if unbound recursives sina.j.baishangeek.cn from root, which can avoid this error.

**Comment by dyunwei** [comment]
I think the loop won't be avoided in your case, even doing the recursion process from root. The case you mentioned is like the case below.

.com has NS records of google.com but doesn't have the ip info for nsx.google.com. How to resolve www.google.com in this case?

**Comment by Philip-NLnetLabs** [comment]
I don't think we can fix this in unbound
