### ISSUE TITLE
[FTBS] configure script error with libmnl on openSUSE 15.3 (and possibly other distributions)

### ISSUE THREAD

**Issue by Corin-EU** [NLnetLabs/unbound#684]
openSUSE 15.3 liibmnl-revel package puts the llibmnl header file ibmnl.h in /usr/include/libmnl/libmnl .  I suspect the reason for the double sub-directory is because in previous  incarnations, the upper sub-directory was versioned eg /usr/include/libnml-0.1

The issue #223 addressed the generic case of libmnl.h detection with the appropriate solution of using pkg-config to find the header file eg  pkg-config --cflags   libmnl but for unknown reasons that issue was closed without any comment or resolution.

The configure option "--with-libmnl=path   specify explicit path for libmnl" to specify a path does not actually not do anything in respect of a path.  The variable is only used to test if it has been set, not whether it has any value.  One would expect ta variable to be something like --with-libmnl-includes and --with-libmlnl-libdir to specify paths to override pkg-config path searches.

This issue is present in the newest release 0.15.0, and on checking the very latest Github version of configure.ac, there is no change to the hard coded path searching with the use of pkg-config.  In fact the configure.ac comments say ipkg-config is only used for the options enable_systemd, with_pyunbound, and with_pythonmod", and not to require it otherwise.

**Comment by wcawijngaards** [comment]
The commit fixes it by testing for the particular header location. That should fix the issue for that choice. It then also sets an include flag for the interior include directory.

**Comment by Corin-EU** [comment]
opensuse 15.3

           git reflog  | head -n 1
          edc1d077 HEAD@{0}: clone: from https://github.com/NLnetLabs/unbound

          ./configure --enable-ipset

          grep mnl config.log
          configure:21717: checking for libmnl
          CPPFLAGS=' -I/usr/include/libmnl'
         LIBS='-lcrypto -lmnl'

Thank you for the very rapid fix.   All is now working.

Presumably you have your reasons why you do not want to use pkg-config (maybe a transition from autotools to cmake is planned) to solve the issue in the general case.
