### ISSUE TITLE
unbound service can't start on windows XP (not bug. maybe libssp-0.dll version?)

### ISSUE THREAD

**Issue by tec1987** [NLnetLabs/unbound#689]
I install unbound 1.15.0 on winXP SP3 32-bit. folder: C:\Unbound\ (Confirmed **path unrelated**)

"Unbound DNS validator" service can't start In the control panel - services.msc.
**(Error 1053: The service did not respond to the start or control request in a timely fashion)**
but start "unbound.exe" in Explorer or cmd.exe, is work normal.

I copy libunbound\\\*.\* to windows\system32\ folder. The service still can't start.
but run "unbound.exe" in Explorer, prompt message: system32\\**libssp-0.dll is not a valid windows image**.

Stud_PE check this dll:
![amd64_libssp-0 dll](https://user-images.githubusercontent.com/23297763/171857784-815521de-9a3c-4d39-a1cb-22d2ef097209.png)

and I find some code here:
https://github.com/NLnetLabs/unbound/blob/2cee189e536d9da0fc07c027b00a4a9578692b2f/makedist.sh#L442

and here:
https://github.com/NLnetLabs/unbound/commit/808a3cb16daf2d7238aa24fccecaaa0398fe13fa#diff-81659df66b1bb16e1c1a07593253aa956e1405044923bfaa761a48e182bc03a0R432

So I try to replace it:
https://github.com/brechtsanders/winlibs_mingw/releases
\mingw32\bin\libssp-0.dll from winlibs-i686-posix-dwarf-gcc-12.1.0-mingw-w64msvcrt-10.0.0-r1.7z
**Can't work...   Too new???**

Find some early versions: working well

https://github.com/brechtsanders/winlibs_mingw/releases?page=10
libssp-0.dll in mingw-w64-i686-9.2.0-7.0.0-r4.7z

There are some other can work versions:

	winlibs-i686-posix-sjlj-gcc-10.2.0-mingw-w64-7.0.0-r1.7z

	https://sourceforge.net/projects/mingw-w64/files/
	i686-win32-dwarf: i686-8.1.0-release-win32-dwarf-rt_v6-rev0.7z

	https://sourceforge.net/projects/orwelldevcpp/
	libssp-0.dll in "Dev-Cpp 5.11 TDM-GCC 4.9.2 Setup.exe"

The last working version:
https://packages.msys2.org/package/mingw-w64-i686-gcc-libs	**recommend**
Files: /mingw32/bin/libssp-0.dll in mingw-w64-i686-gcc-libs-12.1.0-2-any.pkg.tar.zst

Looks similar to:
https://github.com/NLnetLabs/unbound/issues/659

**Comment by tec1987** [comment]
I move libssp-0.dll from windows\sysrem32 to libunbound folder, it's can't work...
Only copy libssp-0.dll file to sysrem32, it can work.

**Comment by gthess** [comment]
We made a change to also copy the 32-bit ssp library to the executable. I made a binary available at https://nlnetlabs.nl/~george/unbound_setup_1.16.1-w32.exe. The Unbound version is reported as 1.16.1 since this is built from the master branch.
Could you try and see if that solves your issue?

**Comment by tec1987** [comment]
Thanks.
This version works well.

**Comment by tec1987** [comment]
Closed

**Comment by CNMan** [comment]
![2022-11-18_190249](https://user-images.githubusercontent.com/8692234/202691687-bf2e92d2-2182-448d-9bca-140646b3e613.png)
1.17.0 can't work again:(
