### ISSUE TITLE
Getting "error: syntax error" after using files to restrict access to certain domains

### ISSUE THREAD

**Issue by alvosec** [NLnetLabs/unbound#696]
After a while we turned Unbound back, upgraded Debian 10 to 11, and Unbound to 1.13.1. If we create file to define all restrictive domains inside /etc/unbound/unbound.conf.d/* we get this error:

```
/etc/unbound/unbound.conf.d/block.conf:1: error: syntax error
read /etc/unbound/unbound.conf failed: 1 errors in configuration file
```
Syntax of the content looks like this:

```
local-zone: "malware.com" redirect
local-data: "malware.com A 0.0.0.0"
```
Do we need to upgrade to 1.16.0 or is this a bug or our approach is wrong? Thank you

**Comment by gthess** [comment]
Hi, newer Debian versions use the newer `include-toplevel:` directive to include files. Files included with that directive must explicitly start a clause. So in your case the content needs to be:
```
server:
    local-zone: "malware.com" redirect
    local-data: "malware.com A 0.0.0.0"
```
This is all guesswork so please let me know if that helped.

**Comment by alvosec** [comment]
Hi @gthess that was a solution. Thank you very much for responding.
