### ISSUE TITLE
[FR] Statistics counter for number of outgoing UDP queries sent

### ISSUE THREAD

**Issue by edmonds** [NLnetLabs/unbound#704]
Hi,

There are a number of statistics counters that relate to the inbound queries sent to Unbound and how they're processed or responded to:

* `{threadX,total}.num.queries` - number of queries received
* `{threadX,total}.num.cachehits` - number of queries that were successfully answered using a cache lookup
* `{threadX,total}.num.cachemiss` - number of queries that needed recursive processing
* `{threadX,total}.num.recursivereplies` - The number of replies sent to queries that needed recursive processing. Could be smaller than threadX.num.cachemiss if due to timeouts no replies were sent for some queries.

What I would really like and that doesn't seem to be tracked by Unbound is the number of outgoing UDP queries sent by the server. There is an existing counter for TCP queries:

* `num.query.tcpout` - Number of queries that the Unbound server made using TCP outgoing towards other servers.

But there does not seem to be a UDP equivalent that counts the number of queries made using UDP outgoing towards other servers.

The number of outgoing queries sent by the server can vary due to timeouts/retries or various config options (`qname-minimisation`, `target-fetch-policy`, `harden-referral-path`, whether DNSSEC validation is enabled or not, etc.) and the client-facing counters (`num.queries`, `num.cachemiss`, etc.) won't really reflect any variations.

I think what I'm looking for would be a counter that gets incremented after a successful UDP send in the `randomize_and_send_udp()` function: https://github.com/NLnetLabs/unbound/blob/3bade62c8a4b5f4ecc2ba69de67a752891ae77ee/services/outside_network.c#L2116-L2172

Thanks!

**Comment by gthess** [comment]
The above commit adds 'num.query.udpout' to the statistics.
