### ISSUE TITLE
Can Unbound compile normally with openssl-3.0.0+quic?

### ISSUE THREAD

**Issue by liang-hiwin** [NLnetLabs/unbound#708]
Can Unbound compile normally with openssl-3.0.0+quic? This open source project: https://github.com/quictls/openssl/tree/OpenSSL_1_1_1p+quic

**Comment by gthess** [comment]
Not sure I understand the question but currently there is no need to compile Unbound with openssl-3.0.0+quic.
There is however ongoing work for DNS over Quic support in a separate branch (https://github.com/NLnetLabs/unbound/tree/dnsoverquic). That branch does require compilation with the forked openssl.
Does that answer your question?

**Comment by liang-hiwin** [comment]
> Not sure I understand the question but currently there is no need to compile Unbound with openssl-3.0.0+quic. There is however ongoing work for DNS over Quic support in a separate branch (https://github.com/NLnetLabs/unbound/tree/dnsoverquic). That branch does require compilation with the forked openssl. Does that answer your question?

Thank you for your answer, because I want to configure http3.0, and worry that after compiling with openssl3.0, it will affect the compilation environment of Unbound
