### ISSUE TITLE
Sept 3, 2019 commit compilation error

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#71]
error log:
In file included from util/netevent.c:58:
util/netevent.c: In function ‘squelch_err_ssl_handshake’:
util/netevent.c:1068:32: error: ‘SSL_F_TLS_POST_PROCESS_CLIENT_HELLO’ undeclared (first use in this function)
 1068 |   err == ERR_PACK(ERR_LIB_SSL, SSL_F_TLS_POST_PROCESS_CLIENT_HELLO, SSL_R_NO_SHARED_CIPHER) ||
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/wang-zhikuan/System_D/Debian-Stretch/myscript/ipkg/unbound/opt/include/openssl/err.h:243:51: note: in definition of macro ‘ERR_PACK’
  243 |                                 ((((unsigned long)f)&0xfffL)*0x1000)| \
      |                                                   ^
util/netevent.c:1068:32: note: each undeclared identifier is reported only once for each function it appears in
 1068 |   err == ERR_PACK(ERR_LIB_SSL, SSL_F_TLS_POST_PROCESS_CLIENT_HELLO, SSL_R_NO_SHARED_CIPHER) ||
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/wang-zhikuan/System_D/Debian-Stretch/myscript/ipkg/unbound/opt/include/openssl/err.h:243:51: note: in definition of macro ‘ERR_PACK’
  243 |                                 ((((unsigned long)f)&0xfffL)*0x1000)| \
      |                                                   ^
util/netevent.c:1069:32: error: ‘SSL_F_TLS_EARLY_POST_PROCESS_CLIENT_HELLO’ undeclared (first use in this function)
 1069 |   err == ERR_PACK(ERR_LIB_SSL, SSL_F_TLS_EARLY_POST_PROCESS_CLIENT_HELLO, SSL_R_UNKNOWN_PROTOCOL) ||
      |                                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/media/wang-zhikuan/System_D/Debian-Stretch/myscript/ipkg/unbound/opt/include/openssl/err.h:243:51: note: in definition of macro ‘ERR_PACK’
  243 |                                 ((((unsigned long)f)&0xfffL)*0x1000)| \
      |                                                   ^
util/netevent.c:1071:75: error: ‘SSL_R_VERSION_TOO_LOW’ undeclared (first use in this function); did you mean ‘SSL_R_MESSAGE_TOO_LONG’?
 1071 |   err == ERR_PACK(ERR_LIB_SSL, SSL_F_TLS_EARLY_POST_PROCESS_CLIENT_HELLO, SSL_R_VERSION_TOO_LOW))
      |                                                                           ^~~~~~~~~~~~~~~~~~~~~
/media/wang-zhikuan/System_D/Debian-Stretch/myscript/ipkg/unbound/opt/include/openssl/err.h:244:51: note: in definition of macro ‘ERR_PACK’
  244 |                                 ((((unsigned long)r)&0xfffL)))
      |                                                   ^
make: *** [Makefile:288: netevent.lo] Error 1
make: *** Waiting for unfinished jobs....

**Comment by wcawijngaards** [comment]
Thanks for the check!  These symbols do not exist in openssl 1.0.2, but they do in 1.1.1.  There are ifdefs now to stop the compile problem.
