### ISSUE TITLE
Does the sequence of parts of unbound.conf matter?

### ISSUE THREAD

**Issue by churchofnoise** [NLnetLabs/unbound#710]
Hi,

I've got a question on the sequence of entries in unbound.conf.

Unbound has been used at my home for a couple of years now (together with Pi-Hole), and over time I had perfected my unbound.conf to my own liking (including a.o. hyper local functionality and long TTLs). Initially this all ran on dedicated Raspberry Pi devices in a 'bare metal' setup

Recently, I installed a Firewall (a Firewalla Purple) that allows me to run functionality on it in Docker containers.
I've decided to use Kyle Harding's Unbound Docker image ( https://github.com/klutchell/unbound-docker ) and that has worked well, together with the 'official' Pi-Hole docker.

The yaml file that runs this can be found below:

> version: "3"
> 
> services:
>   pihole:
>     hostname: firewalla
>     container_name: pihole
>     image: pihole/pihole:nightly
>     networks:
>       default:
>         ipv4_address: 172.16.0.2
>     environment:
>       TZ: 'Europe/Brussels'
>       DNS1: '172.16.0.4'
>       DNS2: '172.16.0.4'
>       WEBPASSWORD: [EDITED OUT]
>     volumes:
>       - '/data/pi-hole/etc-pihole:/etc/pihole'
>       - './etc-dnsmasq:/etc/dnsmasq.d'
>       - '/etc/localtime:/etc/localtime:ro'
>     restart: unless-stopped
>     links:
>       - unbound
> 
>   unbound:
>     image: klutchell/unbound:latest
>     networks:
>       default:
>         ipv4_address: 172.16.0.4
>     ports:
>       - 5335:5335/tcp
>       - 5335:5335/udp
>     restart: unless-stopped
>     volumes:
>       - './unbound-conf:/etc/unbound/custom.conf.d'
> 
> networks:
>   default:
>     driver: bridge
>     ipam:
>       config:
>       - subnet: 172.16.0.0/24

Recently, I'd asked https://github.com/klutchell to add some more support for custom configs, which he did.
Initially, this was added in the 'server:' section of his base config: `include: /etc/unbound/custom.conf.d/*.conf`
This worked well, for additional configuration of parameters that are supposed to be part of the server: section.
if you wanted to add config that needed to be, that seemed ot possible

I'd asked Kyle to move it to the base level, outside of the server section, as I wanted to include other sections (namely the hyper local config, to name one). He was so kind to oblige.
However, since this happened - the `include: /etc/unbound/custom.conf.d/*.conf` line was moved out of the server:  section and put before it, my custom config seems not to be taken into account anymore: TTLs have gone down significantly again, making me quite sure that my TTL parameters are not being taken into account.

**Hence my question: is there a certain sequence that needs to be followed in unbound.conf or did something else happen that stopped Unbound from considering my custom config file.**

For reference, the unbound.conf that is used by the Docker container can be found here: [https://github.com/klutchell/unbound-docker/blob/main/rootfs_overlay/etc/unbound/unbound.conf](url), and this is my custom conf in the unbound-conf subdir:

> server:
>     cache-min-ttl: 86400
>     cache-max-negative-ttl: 86400
>     infra-host-ttl: 86400
> 
>     serve-expired: yes
> 
>     harden-referral-path: yes
>     harden-algo-downgrade: yes
>     harden-below-nxdomain: yes
>     harden-short-bufsize: yes
> 
>     use-caps-for-id: yes
> 
>     minimal-responses: yes
> 
>     hide-version: yes
> 
>     prefetch-key: yes
> 
>     private-domain: plex.direct

**Comment by wcawijngaards** [comment]
A new feature was added for moving the include to the base level, the toplevel include, `include-toplevel: "/etc/unbound/custom.conf.d/*.conf"` that starts a new toplevel for every include file. Otherwise the order matters and statements from previous conf files can change the section that the next one is parsed in.

Other than that, the order of statements and includes makes a difference. In some cases, as some statements override previous statements.

Distros have changed their include to have the include-toplevel used. That is to make the .conf files more separate from each other. Perhaps you should as well, and this is what causes the issue? Or your configuration options have been superseded in other config files that are loaded later?

**Comment by churchofnoise** [comment]
Thank you for the very swift response @wcawijngaards . Heel sterk geapprecieerd :)
Will take this up further and report back in case any useful info for this community might become available.

for my clarification: do you mean that starting an 'include-toplevel' statement is always required if you want to include on the toplevel, so not part of a section such as 'server' or 'auth-zone' or ...?

On today, the include statement is at the very start of the file, this is a snippet:

> include: /etc/unbound/custom.conf.d/*.conf
> 
> server: ................................

(excluded the actual content after the ':')

**Comment by wcawijngaards** [comment]
You do not always have to do so, but it is a good idea to make the conf files more independent. The older include statement continues to work.

If you include with that include at the start, you have to set the section in the config files and their section influences the next config file that is read. But I guess it is better to use the include-toplevel.

**Comment by churchofnoise** [comment]
The changes were made (include to include-toplevel and the change in sequence) and all is well now - thanks a lot for the swift support!
