### ISSUE TITLE
infra-keep-probing is causing problems to fast server selection

### ISSUE THREAD

**Issue by hunts** [NLnetLabs/unbound#713]
**Describe the bug**
Recently we are tuning our Unbound fleet's performance. To reduce latency for resolving a domain not in the cache, we started serving root zone locally via auth_zone. But we still see large latency, and then we started monitoring performance of TLD's nameservers.

We are seeing, even with fast server selection(num = 3), Unbound does not pick the fast servers. Note, if we do a reload, it is picking the expected servers, but when the infra-host-ttl is reached, Unbound starts behaving like it does not know which one is faster any more.

After doing some experience, I've identified the root cause, a bug in the infra-keep-probing logic, at https://github.com/NLnetLabs/unbound/blob/055f5e68a3b200a40a9572edd1c5b28a2ae29a9c/services/cache/infra.c#L721-L736

When the infra cache entry expired, the host get huge penalty because it will be treated as unresponsive server (USEFUL_SERVER_TOP_TIMEOUT-1000) even it is the fastest one, and thus won't be selected as an upstream candidate because of the logic at
https://github.com/NLnetLabs/unbound/blob/055f5e68a3b200a40a9572edd1c5b28a2ae29a9c/iterator/iter_utils.c#L407-L415
and at
https://github.com/NLnetLabs/unbound/blob/055f5e68a3b200a40a9572edd1c5b28a2ae29a9c/iterator/iter_utils.c#L590-L596

While if the entry does not exist at all, it's rtt is default to 376 (int UNKNOWN_SERVER_NICENESS = 376). Effectively, it means a host with an expired latency data is much worst then an unknown host.
 

**To reproduce**
1. Update server config: `infra-keep-probing: yes`, `fast-server-permil: 500`, `fast-server-num: 3`, `infra-cache-numhosts: 10000`, and `infra-host-ttl: 600`.
2. Restart the service (`sudo systemctl restart unbound.service`0 to get into a clean state.
3. Check `sudo /usr/sbin//unbound-control -c /etc/unbound/unbound.conf stats`, and dump_infra for later reference.
4. Run `for x in {1..200}; do dig @you_ip -p you_port $x.com \+short; done` to fill infra cache
5. Check stats again `sudo /usr/sbin/unbound-control -c /etc/unbound/unbound.conf stats`, and dump_infra to find infra cache of .com's nameserver hosts
6. Double confirm by doing a lookup for example.com `sudo /usr/sbin/unbound-control -c /etc/unbound/unbound.conf lookup example.com`. we should see .com TLD nameserver hosts are mostly (if not all) present in the infra cache.
7. Wait for 11 mins (longer than the infra-host-ttl)
8. Redo step 6, you'l see .com TLD nameserver hosts are all "not in infra cache"
9. Flush message/rrset cache, `for x in {1..200}; do sudo /usr/sbin/unbound-control -c /etc/unbound/unbound.conf flush_zone $x.com; done`
10. Redo step 4-6. This time you'll only one .com nameserver host is in the infra cache.
11. Think the queries is not enough, let's send more queries: `for x in {201..400}; do dig @you_ip -p you_port $x.com \+short; done`
12. Redo step 5-6. You'll see it is same result as you saw in step 10.

**Expected behavior**
When host entry expires, their TTL is reset and present in infra cache again

**System:**
 - Unbound version: 1.16
 - OS: Debian Bullseye
 - `unbound -V` output: 
```
  Version 1.16.0
  
  Configure line: --enable-dnstap --disable-rpath --with-libevent --with-pidfile=/var/run/unbound.pid --prefix=/usr --sysconfdir=/etc
  Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 1.1.1n  15 Mar 2022
  Linked modules: dns64 respip validator iterator
```

**Additional information**
One thing I'm not quite sure is that if infra-keep-probing is not working at all. Because even with this bug, we expect the probing result will eventually reset the expired entry, it looks like this does not happen. So whether there is another bug or just a result of this bug as well.

**Comment by hunts** [comment]
Before we settle down a proper fix, I'm looking for a work around. If we believe infra-keep-probing is not working at all, we can turn if off. Or, we can use a very large infra-host-ttl, which effectively allow hosts in the cache to be evicted based on LRU rather
than expired by themselves even when there are room for them.

For the later one, I'm not sure if that will cause other problems, since I see EDNS-support indicator is also in the entry. E.g. issue #686

**Comment by hunts** [comment]
Fwiw, I've patched our package using this change: https://github.com/NLnetLabs/unbound/pull/714, and the result looks quite good. In certain locations, the P90 latency talking to the *.gtld-servers.net is 2ms (which was 80ms+) when the fast server selection start working.

**Comment by gthess** [comment]
Hi @hunts, with #714 merged this now seems resolved to me.
