### ISSUE TITLE
Random udp read timeout errors , Freebsd unbound server 

### ISSUE THREAD

**Issue by pencil404** [NLnetLabs/unbound#715]
Hello I need to resolve around 50k domain names repeatedly , No Cache & almost all queries are send to upstream , cuz i want latest record data, I have setup an unbound server for that , But I am getting Random udp Timeout errors with zdns or custom dns clients. but when check again resolve individually/randomly with dig or zdns/any client  it works fine .

Even when testing with 5k queries

```console
root@saq34:~# time cat 50k_subs.txt | head -n 5000 | zdns A --name-servers <Resolver_IP> -retries 1 -timeout 20 -threads 1000 | jq -r '[.name ,.status ] | @tsv' | grep "TIMEOUT"
admin1868.cloud.com     TIMEOUT
bundesdruckerei.cloud.com       TIMEOUT
admin3378.cloud.com     TIMEOUT
admin2429.cloud.com     TIMEOUT

real    0m20.618s
user    0m1.681s
sys     0m0.576s
```

OR

```console
root@saq34:~# time cat 50k_subs.txt | head -n 5000 | zdns A --name-servers <Resolver_IP> -retries 1 -nx -timeout 20 -threads 1000 | jq -r '[.name ,.status ] | @tsv' | grep "TIMEOUT"
ashteadtechn.cloud.com  TIMEOUT
bizworx.cloud.com       TIMEOUT
autodis.cloud.com       TIMEOUT
demoabinbev.cloud.com   TIMEOUT
admin2752.cloud.com     TIMEOUT
admin7318.cloud.com     TIMEOUT

real    0m20.682s
user    0m1.513s
sys     0m0.574s
```
everytime 
or by a custom go dns client I get timeout errors like

`read udp <CLIENT_IP>:53794-><Resolver_IP>:53: i/o timeout`

but Individially they all resolve fine .
So, I am on the conclusion that it's the problem isn't with client or domain names  but with how i setup/configured unbound , cuz memory is enough to handle that much i think , 
8gb ram - 4 CPUs vps , & It's

FreeBSD 12.2-RELEASE amd64
Unbound Version 1.15.0 with libevent enabled , ig (i did pkg install unbound & updated buffers)
Linked libs: libevent 2.1.12-stable (it uses kqueue), OpenSSL 1.1.1h-freebsd  22 Sep 2020
Linked modules: dns64 respip validator iterator

Config file :

```bash
server:
    port: 53
    verbosity: 0
    num-threads: 4
    #extended-statistics: yes
    qname-minimisation: yes
    auto-trust-anchor-file: "/usr/local/etc/unbound/root.key"
    infra-cache-min-rtt: 500
    so-reuseport: yes
    #msg-cache-slabs: 8
    #rrset-cache-slabs: 8
    #infra-cache-slabs: 8
    #key-cache-slabs: 8
    #rrset-cache-size: 256m
    #msg-cache-size: 256m
    #prefetch: yes
    minimal-responses: yes
    outgoing-range: 22768
    num-queries-per-thread: 8192
    interface: 0.0.0.0
    cache-max-ttl: 1
    #cache-min-ttl: 3
    #infra-host-ttl: 30
    #infra-lame-ttl: 120
    access-control: 127.0.0.1 allow
    access-control: 0.0.0.0/0 deny
    access-control: <CLIENT_IP> allow
    #infra-cache-numhosts: 30000
    username: unbound
    #jostle-timeout: 300
    rrset-roundrobin: yes
    directory: "/usr/local/etc/unbound"
    use-syslog: no
    hide-version: yes
    hide-identity: yes
    so-rcvbuf: 56m
    so-sndbuf: 56m
    do-ip4: yes
    do-ip6: no
    do-udp: yes
    do-tcp: yes

remote-control:
    control-enable: yes
    control-port: 953
    control-interface: 0.0.0.0
```
I don't want cached data so i set cache-max-ttl to 1 sec , idk if that's the way , So where am i going wrong here exactly ? 
Please do help :))) thx

**Comment by gthess** [comment]
Hi,
Setting `cache-max-ttl: 1` is a little bit overly aggressive :).
That means that Unbound will have to resolve (and validate) *everything* (all the way from the root) constantly.
Unbound would then either take more time to resolve the query, which by that time the client may have given up; or Unbound will be overloaded with queries (your queries and all the related generated queries e.g., looking up delegations and gathering DNSSEC information) in which case it drops slow queries (all of your queries because of 1 TTL) so that they are replaced with new incoming queries.

I would suggest to test with normal cache settings to see how much time Unbound needs for you script to run and configure that value-ish as max. It would make sense to me to use the same cache for one measurement. If that makes sense then just reloading unbound with `unbound-control reload` before a measurement would be even easier.

You could also bump the `num-queries-per-thread:` option. Half of that number of queries are eligible for being dropped by Unbound if they are slow to resolve (as mentioned above).

**Comment by pencil404** [comment]
Hi , I got timeout error kind of solved , idk what did that but this configuration did .

```conf
server:
port: 53
verbosity: 0
num-threads: 4
outgoing-range: 55048
minimal-responses: yes
so-reuseport: yes
jostle-timeout: 50
num-queries-per-thread: 8192
interface: 0.0.0.0
cache-max-ttl: 1
access-control: 127.0.0.0/8 allow
access-control: <ip> allow
access-control: <ip> allow
username: unbound
directory: "/usr/local/etc/unbound"
use-syslog: no
access-control: 0.0.0.0/0 deny
hide-version: yes
hide-identity: yes
infra-cache-numhosts: 10000
infra-host-ttl: 180
infra-cache-min-rtt: 50
infra-cache-slabs: 4
so-rcvbuf: 56m
so-sndbuf: 56m
do-ip4: yes
do-ip6: no
do-udp: yes
do-tcp: no
remote-control:
control-enable: yes
control-port: 953
control-interface: 0.0.0.0
```

But now i have another problem , that I am getting stale dns records .
I tested it few times with ,
- Add new CNAME record to a subdomain ---> got correct dns records as soon as i entered it .
- Remove the dns record --- > still shows the old CNAME .
- Update it with New CNAME ---> still shows old CNAME .

This happens randomly , one time correct  , query again then I get old records , sometimes NO cname record .
Are these still in some cache , somewhere ??

tried with `8.8.8.8` , there I understand due to load balancing & caching , I could also see ttl decreasing with dig & sometimes it will show correct dns record , if it hits a server that didn't cached .
But I have only 1 vps server with cache ttl : 1 , then how's it happening ?? Or if they are cached with root servers ?? or this infra-cache/host is the culprit ??? maybe i should try log & check  or time the ttl duration ?? idk

**Comment by gthess** [comment]
Were you able to figure out this issue?
You could try and query the authoritative directly and see if the new record is already published there.
If yes you can see which servers Unbound uses for those zones with `unbound-control lookup <domain_name>`.
`unbound-control dump_cache` will dump whatever Unbound has in its cache.

**Comment by gthess** [comment]
Closing this as inactive non-issue.
