### ISSUE TITLE
[FR] Support for NEW TOKEN for DNS over QUIC

### ISSUE THREAD

**Issue by msoxzw** [NLnetLabs/unbound#719]
@wcawijngaards, I really appreciate your current work on [DNS over QUIC](https://github.com/NLnetLabs/unbound/tree/dnsoverquic).

**Current behavior**
It seems that the DNS over QUIC under development has not supported NEW TOKEN: [`recv_new_token`](https://nghttp2.org/ngtcp2/types.html#c.ngtcp2_callbacks.recv_new_token) has not set for DoQ client and [`ngtcp2_conn_submit_new_token`](https://nghttp2.org/ngtcp2/ngtcp2_conn_submit_new_token.html) has not set for DoQ server.  As far as I know, many public DoQ servers send NEW_TOKEN frames, e.g. quic://dns.adguard.com, quic://dns.nextdns.io

**Describe the desired feature**
Quote from [ngtcp2 README](https://github.com/ngtcp2/ngtcp2#token-not-something-included-in-retry-packet)
> Token (Not something included in Retry packet)
> ----------------------------------------------
> QUIC server might send a token to client after connection has been
> established.  Client can send this token in subsequent connection to
> the server.  Server verifies the token and if it succeeds, the address
> validation completes and lifts some restrictions on server which might
> speed up transfer.  In order to save and/or load a token,
> use --token-file option of examples/client.  The given file is
> overwritten if it already exists when storing a token.

**Potential use-case**
Quote from [RFC 9250](https://datatracker.ietf.org/doc/rfc9250/)
>    DoQ implementations that configure Address Validation using Retry
>    Packets SHOULD implement the Address Validation for Future
>    Connections procedure defined in Section 8.1.3 of [RFC9000], the QUIC
>    transport specification.  This defines how servers can send NEW_TOKEN
>    frames to clients after the client address is validated in order to
>    avoid the 1-RTT penalty during subsequent connections by the client
>    from the same address.

**Comment by wcawijngaards** [comment]
Avoiding the 1RTT during subsequent connections sounds like a useful feature to me. It would be good to support that.

**Comment by wcawijngaards** [comment]
The code now has `ngtcp2_conn_submit_new_token` set for the server. I do not know if it solves the issue that is desired. The code can be used and tried out, it can be found in pullrequest #871 .
