### ISSUE TITLE
rpz entries for IPv6

### ISSUE THREAD

**Issue by jpgpi250** [NLnetLabs/unbound#725]
I have a working rpz file, content (partial):

```
family.puredns.org CNAME .
fdns1.dismail.de CNAME .
fdns2.dismail.de CNAME .
```
works perfect, unbound log:
```
Jul 28 19:56:30 unbound[31710:2] info: rpz: applied [doh] family.puredns.org. rpz-nxdomain 127.0.0.1@36105 family.puredns.org. A IN
```

now I'm adding the IP's, first entry only as example (a different domain name may be used)

```
family.puredns.org CNAME .
32.4.35.137.108.rpz-ip CNAME .
32.33.44.137.108.rpz-ip CNAME .
fdns1.dismail.de CNAME .
fdns2.dismail.de CNAME .
```

again, works perfect, unbound log:
```
Jul 28 19:56:09 unbound[31710:1] info: rpz: applied [doh] 108.137.35.4/32 rpz-nxdomain 127.0.0.1@45571 108.137.35.4.aws.puredns.org. A IN
```

**the question** (I've been reading the [documentation](https://unbound.docs.nlnetlabs.nl/en/latest/topics/filtering/rpz.html), but can't find an answer):

the domain family.puredns.org has 4 IP addresses (2 IPv4 - see above, 2 IPv6):
```
2406:da19:66f:e800:e62b:6932:38d5:9409
2406:da19:66f:e810:63fc:4173:1c08:a00d
```
how do I add entries (.rpz-ip) for IPv6 addresses

appologies for my ignorence, thank you for your time and effort.

**Comment by gthess** [comment]
Hi Peter,
You can find the answer in https://datatracker.ietf.org/doc/html/draft-vixie-dnsop-dns-rpz#section-4.1.1

**Comment by jpgpi250** [comment]
Thanks, applied as per documentation, works perfectly.
