### ISSUE TITLE
running unbound-control: unexpected verbosity results.

### ISSUE THREAD

**Issue by jpgpi250** [NLnetLabs/unbound#727]
Version 1.16.2

Configure line: --prefix=/usr --sysconfdir=/etc --disable-static --enable-tfo-client --enable-tfo-server --with-libevent --with-libhiredis --enable-cachedb --with-pidfile=/run/unbound.pid
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 1.1.1n  15 Mar 2022
Linked modules: dns64 cachedb respip validator iterator
TCP Fastopen feature available

My unbound config has verbosity 1 (gives operational information.)

In order to test a specific rpz zone for false positives (run a lot of digs from [this](https://s3.amazonaws.com/alexa-static/top-1m.csv.zip) list), I issue the following command, this to reduce logging (rpz applied still shows up with verbosity 0  - please don't change this):

sudo /usr/sbin/unbound-control verbosity 0 (**works fine**, log level is reduced)

after my test is completen, I than enter

sudo /usr/sbin/unbound-control verbosity 1 (**doesn't work**)

however, normal logging (verbosity 1) does NOT resume, the loglevel remains at 0, even though unbound-control says "ok". I need to restart unbound in order to resume normal logging.

**Comment by wcawijngaards** [comment]
This works fine for me. The `status` command can be used to print the current verbosity level. After the verbosity command, the status command shows that the correct verbosity level is used by the server. Also I can see verbosity level 1 output, on exit of the server it then prints the statistic values that are not printed at verbosity level 0. Something else must be going on for you, what output is of interest? There is not a lot of verbosity 1 log printout. Or is the verbosity level reset by performing a reload from config?

**Comment by jpgpi250** [comment]
following commands:

sudo /usr/sbin/unbound-control verbosity 0
sudo /usr/sbin/unbound-control rpz_disable "pihole"
sudo /usr/sbin/unbound-control rpz_disable "whotracks"

run some tests (dig, source list [here](https://s3.amazonaws.com/alexa-static/top-1m.csv.zip), partial of course...
log entries seen (with verbosity 0 (required, please don't change))
```
Jul 31 17:53:19 unbound[26654:0] info: rpz: applied [doh] doh.opendns.com. rpz-nxdomain 192.168.2.228@59290 doh.opendns.com. A IN
Jul 31 18:01:44 unbound[26654:2] info: rpz: applied [doh] mask.apple-dns.net. rpz-nxdomain 192.168.2.228@59866 mask.apple-dns.net. A IN
Jul 31 18:14:39 unbound[26654:0] info: rpz: applied [doh] dns.google. rpz-nxdomain 192.168.2.228@64170 dns.google. A IN
Jul 31 18:26:48 unbound[26654:1] info: rpz: applied [doh] doh.dns.apple.com. rpz-nxdomain 192.168.2.228@49506 doh.dns.apple.com. A IN
Jul 31 18:41:10 unbound[26654:3] info: rpz: applied [doh] dns.google.com. rpz-nxdomain 192.168.2.228@52204 dns.google.com. A IN
Jul 31 19:54:13 unbound[26654:2] info: rpz: applied [doh] mask-t.apple-dns.net. rpz-nxdomain 192.168.2.228@56050 mask-t.apple-dns.net. A IN
```

sudo /usr/sbin/unbound-control rpz_enable "pihole"
sudo /usr/sbin/unbound-control rpz_enable "whotracks"
sudo /usr/sbin/unbound-control verbosity 1

normal (verbosity 1) logging doesn't resume, unbound restart required.

demo:
gif (edited, removed obsolete frames) attached
rpz alert is triggered from another rpz (doh), not disabled...
![unbound-control](https://user-images.githubusercontent.com/24669386/182127879-f747f080-b022-4c54-a38e-0859d2dc8a88.gif)

**Comment by wcawijngaards** [comment]
From your animated gif, very nice by the way, it looks like you are using at the start verbosity level 2. That is what prints short messages about query responses and lookup replies. So if you want those messages printed, you should set verbosity 2 at the end.

Perhaps you have verbosity 1 in config file, but then -v on the command line, and they add up. The `-v`s and verbosity from the config file add up to the log level. This could be why there is verbosity 2 but it is not visible in the conf file.

**Comment by jpgpi250** [comment]
I have indeed -v in the service file
```
ExecStartPre=-/usr/sbin/unbound-anchor -a /etc/unbound/root.key -v
ExecStart=/usr/sbin/unbound -d -v
````

retried the test, switching to verbosity 2 as the last step

WORKS // SOLVED

sorry for the inconvenience, thanks for your time and effort

**Comment by jpgpi250** [comment]
since you liked the gif... https://www.screentogif.com/
