### ISSUE TITLE
./configure ... checking whether we need -> failed (3)

### ISSUE THREAD

**Issue by jpgpi250** [NLnetLabs/unbound#731]
compiling unbound from github repository (git clone https://github.com/NLnetLabs/unbound)
Linux raspberrypi 5.15.32-v7+ #1538 SMP Thu Mar 31 19:38:48 BST 2022 armv7l GNU/Linux

sudo ./configure --prefix=/usr --sysconfdir=/etc --disable-static --enable-tfo-client --enable-tfo-server --with-libevent --with-libhiredis --enable-cachedb --with-pidfile=/run/unbound.pid

```
checking whether we need -std=c99 -D__EXTENSIONS__ -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -D_XOPEN_SOURCE_EXTENDED=1 -D_ALL_SOURCE as a flag for gcc... failed
checking whether we need -std=c99 -D__EXTENSIONS__ -D_BSD_SOURCE -D_DEFAULT_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -D_ALL_SOURCE as a flag for gcc... failed
...
checking whether we need -D__EXTENSIONS__ as a flag for gcc... failed
```

sudo make && sudo make install -> OK

unbound -V
```
Version 1.16.3

Configure line: --prefix=/usr --sysconfdir=/etc --disable-static --enable-tfo-client --enable-tfo-server --with-libevent --with-libhiredis --enable-cachedb --with-pidfile=/run/unbound.pid
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 1.1.1n  15 Mar 2022
Linked modules: dns64 cachedb respip validator iterator
TCP Fastopen feature available
```

Don't know if this requires action (mine or yours).
apologies for my ignorance, thanks for your time and effort.

**Comment by JiangHeng12138** [comment]
"checking whether we need -> failed" is not an error, we can ignore it.

**Comment by gthess** [comment]
Indeed, not an error; closing.
