### ISSUE TITLE
Failed execution of 1.16.2 on windows

### ISSUE THREAD

**Issue by nexusds** [NLnetLabs/unbound#732]
Log File;
[1659453883] C:\Program Files\Unbound\unbound.exe[6680:0] error: setsockopt(..., IPV6_USER_MTU, ...) failed: Bad protocol option.
[C:\Program Files\Unbound\unbound.exe:0] info:    8.000000   16.000000 1

config;
interface: x.x.x.x
interface: xxxx:xxxx:xxxx:xxxx::xxxx
access-control: 0.0.0.0/0 allow
access-control: ::/0 allow
num-threads: 12

works fine using 1.16.1

**Comment by jpgpi250** [comment]
duplicate? same as [this](https://github.com/NLnetLabs/unbound/issues/729) one (solved)?

**Comment by nexusds** [comment]
> duplicate? same as [this](https://github.com/NLnetLabs/unbound/issues/729) one (solved)?

Looks like it is, however this is windows server 2019.

**Comment by nexusds** [comment]
will there be a version increment and/or the office binary download be updated with the OS ipv6_mtu check code?

**Comment by jpgpi250** [comment]
only a user here, not a member of the team.
I would... options (pick one):
- compile unbound from github source (will give you version 1.16.3). the fix has already been merged. To get the github source: git clone https://github.com/NLnetLabs/unbound
- download the 1.16.2 tar.gz, extract, and replace services/listen_dnsport.c with [this](https://raw.githubusercontent.com/NLnetLabs/unbound/master/services/listen_dnsport.c) one
- edit the file in your extracted tar.gz, small change required, see [here](https://github.com/NLnetLabs/unbound/pull/730/files), replace red with green
- wait for the next release...

**Comment by nexusds** [comment]
This is still an issue in 1.16.3

**Comment by gthess** [comment]
1.16.3 is a security release only. This means that it is basically 1.16.2 + security patch. The upcoming 1.17.0 release will include the windows fixes among other features/bugfixes.

**Comment by Philip-NLnetLabs** [comment]
Let's assume it is fixed in 1.17.0.

**Comment by nexusds** [comment]
Yes it is.

***@***.***

Richard Hunt
Nexusds.com

• phone:

1.888.266.7620
416.640.6070 Ext:225

• fax:

416.640.6072

• email:

***@***.******@***.***>

• web:

www.nexusds.com<http://www.nexusds.com/>

Instagram:

nexusds<https://www.instagram.com/nexusds/>

Twitter:

nexusdsc<http://www.twitter.com/nexusdsc>

facebook:

www.facebook.com<http://www.facebook.com/pages/Scarborough-ON/NEXUSDS/112876155413924>




________________________________


This communication is concerning the business of Nexusds.com, and it’s Authorized Representative, and is intended to be confidential to the person to whom it is addressed. If you are not the intended recipient(s), please do not read, copy or use this communication or share it to any other parties, but notify the sender immediately by e-mail at ***@***.***, or by telephone at (416) 640-6070 x 225.
