### ISSUE TITLE
Logging resolved IP addresses

### ISSUE THREAD

**Issue by gitd8b** [NLnetLabs/unbound#733]
Hi,

I have been searching high and low for an answer to this, and can't seem to find anything... Starting to think it's not possible, so here's my last place to ask.

Is there a way to log resolved IP addresses in unbound logs? Ideally, I'd like the resolved IP to be a part of the request log, but even if it's separate, that'd be okay as well. Basically, I have alerting in place to look for key words in some requests that I want to validate whether it's coming back as an IP or 0.0.0.0.

For example:
Computer A (192.168.5.2) makes request to telemetry.example.com
Unbound logs: 
"query: 192.168.5.2 telemetry.example.com. A IN"

My alert system would see 'telemetry' in this query, but has no way to know whether unbound returned 0.0.0.0 or a valid IP address. This means my alert system now has to put in _another_ DNS request to see what it would resolve as, and then from that response, determine whether it should alert me or not.

Ideal log:
Computer A (192.168.5.2) makes request to telemetry.example.com
Unbound logs: 
"query: 192.168.5.2 telemetry.example.com. A IN : Resolves to 0.0.0.0"

Acceptable log:
Computer A (192.168.5.2) makes request to telemetry.example.com
Unbound logs: 
    "query: 192.168.5.2 telemetry.example.com. A IN"
    "reply: 192.168.5.2 telemetry.example.com. A IN NOERROR 0.000000 1 41 0.0.0.0"

Or something like that. If this isn't something that unbound can already do, then feel free to convert this to a feature request. Otherwise, any guidance would be well appreciated.

Thank you!

**Comment by dyunwei** [comment]
DNSTAP Logging Options can satisfy your requirement.

Reference:  https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#dnstap-logging-options

**Comment by gitd8b** [comment]
Yesss, looks like this is what I was looking for. Going to play with this and if I have any issues or it doesn't work the way I need it to, I'll re-open this. Looks like it's not built by default with unbound for my firewall software, so I may have to get that working first, but this is exactly what I was looking for. Thank you dyunwei!
