### ISSUE TITLE
Unbound dynlib/python mod : Not able to add discovered IPs to ipset

### ISSUE THREAD

**Issue by sharonenoch** [NLnetLabs/unbound#737]
I am using the below version of Unbound

Ubuntu 18.04
Unbound version 1.13.1-1.1 built with dynlib support using the command  dpkg-buildpackage -rfakeroot -b
Source was taken from debian repository :  https://anonscm.debian.org/git/pkg-dns/unbound.git
git checkout debian/1.13.1-1.1

root@CPE2:/home/router# unbound -V
Version 1.13.1

Configure line: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --disable-rpath --with-pidfile=/run/unbound.pid --with-rootkey-file=/var/lib/unbound/root.key --with-libevent --with-dynlibmodule --with-pythonmodule --enable-subnet --enable-dnstap --enable-systemd --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --libdir=/usr/lib
Linked libs: libevent 2.1.8-stable (it uses epoll), OpenSSL 1.1.1  11 Sep 2018
Linked modules: dns64 python dynlib subnetcache respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

We wrote a pythonmod program initially which will add the resolved DNS ips to an IPSET and also to REDIS DB. We are using the pyroute2 and redis libraries in python3 for the same.

The Redis DB update works perfectly.. but when adding the ipset it always returns "Operation not permitted". The same python program works fine when executed as a standalone from the bash command line in root user mode

The same is true when we wrote the functionality using the shared C library approach.. We are able to open the netfilter socket successfully but the ips never get added to the ipset when sending the netlink message to add the same.. The standalone C program works fine.

When looking at the capsh output of unbound service we see the following

CapInh: 0000000000000000
CapPrm: 0000000000000000
CapEff: 0000000000000000
CapBnd: 000001ffffffffff
CapAmb: 0000000000000000

I am not able to change this capabilities using either

1) setcap commands..  

2) including the capabilities in the apparmor file for unbound but still no luck..

  capability net_bind_service,
  capability net_raw,
  capability net_admin,
  network,

3) Added the above capabilities for the unbound user in /etc/security/capabilities

4) Tried modifying the systemd file of unbound to start with User=root.. but always we get "Operation not permitted"
 
Not sure if I am looking at it wrong or missing something..  Hoping anyone can shed some thoughts on the same

**Comment by wcawijngaards** [comment]
There is another user name configured in unbound.conf `username: "unbound"` and that defaults to the 'unbound' user. So if  you set systemd to start it as root, then unbound drops the root permissions because of that, and that could explain the permission issues with ipset. Set the value of the username in unbound.conf to "root" as well.

Also, there is a setting for chroot and this is enabled by default as well. If the ipset routines use something like opening a file from /proc to do their procedure, then this is not available inside the chroot. The chroot can be disabled with `chroot: ""` in unbound.conf. But it could be that the ipset works with netlink sockets that do not need directories mounted in the chroot.

**Comment by sharonenoch** [comment]
@wcawijngaards Thankyou so much.. I completely overlooked that.. By adding the above changes the shared library can now add to ipsets.. 

Now that anyways I am running it in root, I feel I should also change the /var/lib/unbound folder to be owned as root?. Since /etc/unbound owner is root. The reason being I got the error related to the below.. 

`fatal error: could not open autotrust file for writing, /var/lib/unbound/root.key.28988-0-564015a7dd00: Permission denied
`
I ran the aa-logprof and it added dac_override to the capability which I felt may not be needed if the permissions were root for the same.

**Comment by wcawijngaards** [comment]
Unbound wants to write the root key probe update to file, and so it wants to create a file there. This depends on the directory permissions. After writing to this file, it renames the file to replace the root.key file with it.

**Comment by sharonenoch** [comment]
Thankyou @wcawijngaards
