### ISSUE TITLE
rfc:rpz (draft) for having full support of rpz zones and always_nxdomain

### ISSUE THREAD

**Issue by spirillen** [NLnetLabs/unbound#74]
# intro:
I'm building a [project](https://gitlab.com/my-privacy-dns) to hosts public owned RPZ zones.

The issue is the way unbound handles `always_nxdomain` as demonstrated in this [thread](https://github.com/ScriptTiger/Hosts-Conversions/issues/1#issuecomment-530804904)

unbound is not only adding nxdomain from second level domains and down the latter, it also doing so in the opposed direction from fourth or fifth level domains to the second level

# Now the question/feature request:
Is there currently a work around for this issue to use the `always_nxdomain` or actually full support for real RPZ zones, rather than having to build very very big files with 
```
local-zone: "%%b" redirect
local-data: "%%b A !TO_BLACKHOLE!"
```

# Outtro
The main idea with my project is to fully implant the NXDOMAIN as they smarter and faster as you have a straight-up answer and wildcard is fully supporter, any DNS queries don't have to wait up for any redirection timeouts ex. 127.0.0.1 or 0.0.0.0

I'm asking you here as (personal linux) Unbound is the only reliable recursor I have found that could be easily installed on Windows 10.Home.xxxxxxxxxxxxxxx.what.ever.hosts.reset.version.tracking.optimization.version

### Ping for inclusion
@ScriptTiger

**Comment by ralphdolmans** [comment]
Hi,
To be clear: you are talking about nxdomain answers generated using Unbound's local-zone configuration, right? Local-zones should only be applied for matching domains and subdomains. Please check your configuration to make sure you don't have a local-zone matching the parent domain.

**Comment by spirillen** [comment]
> Hi,
> To be clear: you are talking about nxdomain answers generated using Unbound's local-zone configuration, right?

Yes :+1: 

> Local-zones should only be applied for matching domains and subdomains. Please check your configuration to make sure you don't have a local-zone matching the parent domain.

Will do this later, as unbound is on a diff PC

**Comment by spirillen** [comment]
Found the line in a local file added to the config :+1: now I have to figure out why... but that not your headache

By the way... I can see you are working on integrating full support for RPZ zones in this [PR](https://github.com/NLnetLabs/unbound/pull/73) Do you have any idea for the release date :question:  and do you have docs on the layouts for the RPZ zone files?.

I would hate to make a lot of code just to remake it in 2 weeks :unamused:

**Comment by gthess** [comment]
Closing this as RPZ is fully supported since 1.14.0
