### ISSUE TITLE
Add non-recursive option

### ISSUE THREAD

**Issue by danielguevara** [NLnetLabs/unbound#75]
We would like to add a non-recursive option and are wondering if such a pull request would be accepted.
 
Our use case requires us to use unbound as a resolver for local domains with no need for recursion. This would allow us to disable the recursive root server lookups. We would make this an option that has to be enabled and let the default behavior be the same as it is today.
 
Currently even if you disable DNSSEC with:
module-config: "iterator"
              (Setting this to "iterator" will result in  a non-validating server.)
domain-insecure: "."
              (Sets  domain  name  to  be  insecure,  DNSSEC  chain of trust is ignored towards the domain name.)
 
The root server lookups still happen.

**Comment by chantra** [comment]
You can solve this with a config similar to:

local-zone: "." refuse
local-zone: "mydomain1" transparent
local-zone: "mydomain2" transparent
stub-zone:
  name: "mydomain1."
  stub-addr: ip1
  stub-addr: ip2

stub-zone:
  name: "mydomain2."
  stub-addr: ip3
  stub-addr: ip4

Hope that helps.

**Comment by danielguevara** [comment]
To add a bit more clarity, we also need to be able to lookup any public domain. We are actually also including two conf files with domain specific forwarding. In the unbound.conf we forward to OpenDNS by default, and the other two configuration files either forward to our internal DNS or AmazonDNS based on domain matching. In all we have roughly 65 domains defined. We have made the business decision to trust the forwarders response.


**Unbound.conf:**
include: /etc/unbound/conf.d/trusted.conf
include: /etc/unbound/conf.d/private.conf

server:
  directory: "/etc/unbound"
  username: "unbound"
  pidfile: "/var/run/unbound.pid"
  verbosity: 2
  interface: 127.0.0.1
  do-ip6: no
  access-control: 127.0.0.0/8 allow
  domain-insecure: "."
  module-config: "iterator"
  prefetch: yes
  num-threads: 2

forward-zone:
  name: "."
  forward-addr: 208.67.222.222
  forward-addr: 208.67.222.220

Sample of the include files with our data stripped out...
**private.conf:**
forward-zone:
  name: "mydomain1"
  forward-addr: ip1
  forward-addr: ip2

**trusted.conf:**
forward-zone:
  name: "pubdomain1"
  forward-addr: amazonDNSip
forward-zone:
  name: "pubdomain2"
  forward-addr: amazonDNSip
(60+ more...)

**Comment by wcawijngaards** [comment]
Hi,
Is this still with that old (1.6.x?) version that I saw emails on unbound-users about?  It has been fixed in the meantime, that no root lookups happen if you have a forward zone declared, I believe.
Best regards, Wouter

**Comment by danielguevara** [comment]
Yes, it is with 1.6.6, That is the latest for Centos 7 according to:
https://repology.org/project/unbound/versions

is the link out of date?

**Comment by wcawijngaards** [comment]
I believe the problem you have is fixed in the last release 1.9.3 on https://nlnetlabs.nl/projects/unbound/download .

**Comment by wcawijngaards** [comment]
Just tested, and yes for me with 1.9.3 and a forward-zone for "." there is no root prime query at the start.

**Comment by wcawijngaards** [comment]
Hmpf, I cannot find the Changelog entry in the long lists between 1.6.x and today, that is the fix for it.  So it could exist, if it still happens for you with the last release, then something else must be going wrong.

**Comment by danielguevara** [comment]
I cannot find an rpm for CentOS via a package manager. Currently working on compiling myself to test.

**Comment by danielguevara** [comment]
I confirmed this resolved my issue. Would it be possible to get a newer rpm package published for RHEL/CentOS?

**Comment by wcawijngaards** [comment]
Hi Daniel,
We do not make the rpm packages, the policy of most packager systems is that they want to do that themselves.  There is an rpm .spec example file in contrib/.
That said, the unbound-users list or some other way to contact the rpm makers could be a way to ask for newer rpms.
I think I can close this issue since it is fixed, but feel free to keep posting or reopen or make a new issue if that is needed.
Best regards, Wouter

**Comment by danielguevara** [comment]
Thanks!
