### ISSUE TITLE
[Q] Is there a way to resolve a list of domains on launch?

### ISSUE THREAD

**Issue by txtsd** [NLnetLabs/unbound#750]
I'm looking to have unbound automatically resolve (and therefore cache) a list of domains (preferably via a file) whenever it launches. This way a list of frequently accessed {sub,}domains can be built and prefetched which would be great for whenever the server (or device hosting the server) restarts.

Is this possible to do at the moment?

**Comment by wcawijngaards** [comment]
There is the script, in the source tarball and code repository, `contrib/warmup.sh` that performs this task. There is also `warmup.cmd` for use on Windows.

**Comment by txtsd** [comment]
Excellent! Just what I needed.
