### ISSUE TITLE
There is a problem with prefetches 

### ISSUE THREAD

**Issue by liang-hiwin** [NLnetLabs/unbound#766]
The prefetch function is configured, and the unbound_exporter program checks that all values of prefetch are empty

https://github.com/letsencrypt/unbound_exporter/issues/47

```
root@debian:~# unbound -V
Version 1.16.2

Configure line: --enable-subnet --with-libevent --with-pthreads --with-ssl --enable-dnscrypt --with-libhiredis --enable-cachedb --enable-tfo-client --enable-tfo-server --enable-ipset
Linked libs: libevent 2.1.8-stable (it uses epoll), OpenSSL 1.1.1m  14 Dec 2021
Linked modules: dns64 cachedb subnetcache ipset respip validator iterator
DNSCrypt feature available
TCP Fastopen feature available

```

```
	prefetch: yes
	prefetch-key: yes
	serve-expired-ttl: 86400
	serve-expired-client-timeout: 1800
```

**Comment by saint-lascivious** [comment]
![IMG_20221009_210427.jpg](https://user-images.githubusercontent.com/1484933/194745410-4b242eb1-0282-44e1-b9b5-c1a6e705ed51.jpg)

It's not a lot (personal servers with a caching proxy in front of Unbound), but, my Munin graphs disagree with you somewhat regarding cache prefetch not working. You can see there little spurts of 0.5~1.5 qps in cache prefetch activity over time.

Perhaps you're expecting prefetch to fetch _every_ record before cache ttl expiration?

**Comment by liang-hiwin** [comment]
> ![IMG_20221009_210427.jpg](https://user-images.githubusercontent.com/1484933/194745410-4b242eb1-0282-44e1-b9b5-c1a6e705ed51.jpg)
> 
> It's not a lot (personal servers with a caching proxy in front of Unbound), but, my Munin graphs disagree with you somewhat regarding cache prefetch not working. You can see there little spurts of 0.5~1.5 qps in cache prefetch activity over time.
> 
> Perhaps you're expecting prefetch to fetch _every_ record before cache ttl expiration?

Mine are all zeros, how did you open this panel?

**Comment by saint-lascivious** [comment]
>Mine are all zeros, how did you open this panel?

It's part of a personal distributed monitoring server/platform deployed within my network.

https://munin-monitoring.org/

Edited to add: It's possible, and probable in my opinion, you're assuming the statistics are cumulative. They're not, at least by default.

It's also probable you're not aware that viewing stats with unbound-control will clear those stats after the fact. You'd need to explicitly pass `stats no-reset` to `unbound-control` should you not want that to happen.

This appears to be a string of misunderstandings around assumed function.

**Comment by liang-hiwin** [comment]
> > Mine are all zeros, how did you open this panel?
> 
> It's part of a personal distributed monitoring server/platform deployed within my network.
> 
> https://munin-monitoring.org/
> 
> Edited to add: It's possible, and probable in my opinion, you're assuming the statistics are cumulative. They're not, at least by default.
> 
> It's also probable you're not aware that viewing stats with unbound-control will clear those stats after the fact. You'd need to explicitly pass `stats no-reset` to `unbound-control` should you not want that to happen.
> 
> This appears to be a string of misunderstandings around assumed function.

thanks
