### ISSUE TITLE
Unbound 1.17.0 - error: pythonmod

### ISSUE THREAD

**Issue by UnveilTech** [NLnetLabs/unbound#769]
**Describe the bug**
[1665757055] unbound[10031:0] notice: init module 0: respip
[1665757055] unbound[10031:0] notice: init module 1: validator
[1665757055] unbound[10031:0] notice: init module 2: python
[1665757055] unbound[10031:0] error: pythonmod: cannot initialize core module: unboundmodule.py
[1665757055] unbound[10031:0] error: module init for module python failed
[1665757055] unbound[10031:0] fatal error: failed to setup modules

we've compiled with python 2.7 and 3 (3.7), same error.
files unbound.py and unboundmodule.py exist in both "/usr/lib/python2.7/dist-packages" and "/usr/lib/python3/dist-packages"

**To reproduce**
compile Unbound 1.17.0, enable "python" in the module-config

**Expected behavior**
we expect it works with no error ;)

**System:**
 - Unbound version: 1.17.0
 - OS: Debian 10
 - `unbound -V` output:
Version 1.17.0
Configure line: --prefix=/usr/local/unbound --sysconfdir=/etc --with-pidfile=/var/run/unbound.pid --with-rootkey-file=/usr/local/unbound/key/root.key --with-username=unbound --with-libevent --with-pythonmodule --with-libnghttp2 --enable-cachedb --with-libhiredis=/usr PYTHON=3 PYTHON_LDFLAGS=-L/usr/lib/python3.7/config-3.7m-x86_64-linux-gnu -L/usr/lib -lpython3.7m -lcrypt -lpthread -ldl -lutil -lm -Xlinker -export-dynamic -Wl,-O1 -Wl,-Bsymbolic-functions PYTHON_CPPFLAGS=-I/usr/include/python3.7m -I/usr/include/python3.7m
Linked libs: libevent 2.1.8-stable (it uses epoll), OpenSSL 1.1.1n  15 Mar 2022
Linked modules: dns64 python cachedb respip validator iterator

**Additional information**
unbound -dv -c /etc/unbound/unbound.conf
[1665757867] unbound[11430:0] notice: Start of unbound 1.17.0.
[1665757867] unbound[11430:0] warning: did not exit gracefully last time (11371)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/unboundmodule.py", line 831, in <module>
    class module_env(_object):
  File "/usr/lib/python3/dist-packages/unboundmodule.py", line 901, in module_env
    __swig_setmethods__["now"] = _unboundmodule.module_env_now_set
AttributeError: module '_unboundmodule' has no attribute 'module_env_now_set'

**Comment by UnveilTech** [comment]
hi,
a day, maybe someone from the Unbound team will take 5 minutes to answer that bug...

**Comment by trinv** [comment]
I got the same errors but no one can help. Hope to hear from Unbound soon.

**Comment by trinv** [comment]
```
checking consistency of all components of python development environment... no
configure: error:
  Could not link test program to Python. Maybe the main Python library has been
  installed in some non-standard library path. If so, pass it to configure,
  via the LDFLAGS environment variable.
  Example: ./configure LDFLAGS="-L/usr/non-standard-path/python/lib"
  ============================================================================
   ERROR!
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================
```

**Comment by gthess** [comment]
@trinv
When I am trying here on Debian 10 (I assume you use the same and that you have already installed the *-dev packages of python) running something like:
```
$ python
>>> import sysconfig
>>> sysconfig.get_path('include')
'/usr/local/include/python2.7'
```
(which is what the configure script is doing), I get a non existent include directory.
Not sure why that is but manually checking python's CFLAGs I get the following:
```
$ python2-config --cflags
-I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7  -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fdebug-prefix-map=/build/python2.7-2.7.16=. -fstack-protector-strong -Wformat -Werror=format-security  -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes
```
Then I can configure with something like:
```
./configure PYTHON_CPPFLAGS="-I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu/python2.7" --with-pythonmodule
```
and it works; hope that helps (I assume you are building with Python2.7 because 3 does not yield configure problems for me below).

---

@UnveilTech
I see no problems here on a fresh Debian 10 machine. The error line maybe is correct as locally I have `_unboundmodule.module_env__now_set` (notice the extra `_`) as an available method. Maybe something with a previous built version? Or swig?
You can start by checking if the file in the dist-packages is the same as the one currently built in pythonmod/unboundmodule.py.

Also `PYTHON=3` is probably wrong and you need `PYTHON_VERSION=3` instead.

I would do a `make uninstall` and a `make clean` and then try again with just:
```
./configure PYTHON_VERSION=3 --prefix=/usr/local/unbound --sysconfdir=/etc --with-pidfile=/var/run/unbound.pid --with-rootkey-file=/usr/local/unbound/key/root.key --with-username=unbound --with-libevent --with-pythonmodule --with-libnghttp2 --enable-cachedb --with-libhiredis=/usr
```
which leaves all the explicit Python things except the version out of the configure line. If you build with Python 2 check my answer above.

**Comment by gthess** [comment]
(the description seems like a duplicate of #534)

**Comment by UnveilTech** [comment]
2 months later and still no answer/fix from the NLnetLabs team... :(

**Comment by gthess** [comment]
@trinv, @UnveilTech are your issues resolved with the above suggestions? I am inclined to close this issue.

**Comment by UnveilTech** [comment]
Hello Yorgos,

Wout provided us a patch that should be added to a next build of Unbound.
That patch fixes the problem…

Best regards,
UnveilTech Support Team
www.unveiltech.com<http://www.unveiltech.com>
Skype: unveiltechsupportteam

De : Yorgos Thessalonikefs ***@***.***
Envoyé : vendredi 17 mars 2023 14:58
À : NLnetLabs/unbound ***@***.***>
Cc : UnveilTech - Support ***@***.***>; Mention ***@***.***>
Objet : Re: [NLnetLabs/unbound] Unbound 1.17.0 - error: pythonmod (Issue #769)


@trinv<https://github.com/trinv>, @UnveilTech<https://github.com/UnveilTech> are your issues resolved with the above suggestions? I am inclined to close this issue.

**Comment by gthess** [comment]
Ah, so it was the issue with Python installation paths then as observed above, good to know :)
For future reference the relevant commits were 4517dcd439562cb1df07e77738153c0c906bb069 and 0fed35a4b713eb7474394a8562b896f45cf74115.

**Comment by UnveilTech** [comment]
Hello,

That’s correct…

Best regards,
UnveilTech Support Team
www.unveiltech.com<http://www.unveiltech.com>
Skype: unveiltechsupportteam

De : Yorgos Thessalonikefs ***@***.***
Envoyé : vendredi 17 mars 2023 16:07
À : NLnetLabs/unbound ***@***.***>
Cc : UnveilTech - Support ***@***.***>; Mention ***@***.***>
Objet : Re: [NLnetLabs/unbound] Unbound 1.17.0 - error: pythonmod (Issue #769)


Ah, so it was the issue with Python installation paths then as observed above, good to know :)
For future reference the relevant commits were 4517dcd<https://github.com/NLnetLabs/unbound/commit/4517dcd439562cb1df07e77738153c0c906bb069> and 0fed35a<https://github.com/NLnetLabs/unbound/commit/0fed35a4b713eb7474394a8562b896f45cf74115>.

**Comment by socketpair** [comment]
So, what is the quick fix for that ? In Fedora36 pythonmodule is broken.

The fix IS NOT included in 1.17.1. Probably will be release in 1.17.2

@gthess how I can quick-fix that if 1.17.1 is already installed ? Possibly define PYTHONPATH for the whole unbound or so ?

**Comment by socketpair** [comment]
strace unbound:

```
openat(AT_FDCWD, "<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Нет такого файла или каталога)
openat(AT_FDCWD, "/usr/lib64/python310.zip/<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Нет такого файла или каталога)
openat(AT_FDCWD, "/usr/lib64/python3.10/<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Нет такого файла или каталога)
openat(AT_FDCWD, "/usr/lib64/python3.10/lib-dynload/<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Нет такого файла или каталога)
openat(AT_FDCWD, "./<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Нет такого файла или каталога)
openat(AT_FDCWD, "/etc/unbound/<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Нет такого файла или каталога)
openat(AT_FDCWD, "/etc/unbound/<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Нет такого файла или каталога)
openat(AT_FDCWD, "/run/ideco-dns-backend/<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Нет такого файла или каталога)
openat(AT_FDCWD, "/usr/local/lib64/python3.10/site-packages/<string>", O_RDONLY|O_CLOEXEC) = -1 ENOENT (Нет такого файла или каталога)
```

`<string>` WHAT ?

**Comment by jimdigriz** [comment]
For others that come this way...I am using Debian 'bookworm' 12 and it is worth also checking any apparmour rules that come with the packaging which are not set up to look in `/usr/local/...`:
```
Nov 21 10:27:02 dnsproxy systemd[1]: Starting unbound.service - Unbound DNS server...
Nov 21 10:27:02 dnsproxy unbound[9584]: [9584:0] notice: init module 0: validator
Nov 21 10:27:02 dnsproxy unbound[9584]: [9584:0] notice: init module 1: python
Nov 21 10:27:02 dnsproxy unbound[9584]: Traceback (most recent call last):
Nov 21 10:27:02 dnsproxy unbound[9584]:   File "<string>", line 1, in <module>
Nov 21 10:27:02 dnsproxy unbound[9584]: ModuleNotFoundError: No module named 'unboundmodule'
Nov 21 10:27:02 dnsproxy unbound[9584]: [9584:0] error: pythonmod: cannot initialize core module: unboundmodule.py
Nov 21 10:27:02 dnsproxy unbound[9584]: [9584:0] error: module init for module python failed
Nov 21 10:27:02 dnsproxy unbound[9584]: [9584:0] fatal error: failed to setup modules
Nov 21 10:27:02 dnsproxy systemd[1]: unbound.service: Main process exited, code=exited, status=1/FAILURE
Nov 21 10:27:02 dnsproxy systemd[1]: unbound.service: Failed with result 'exit-code'.
Nov 21 10:27:02 dnsproxy systemd[1]: Failed to start unbound.service - Unbound DNS server.
Nov 21 10:27:02 dnsproxy systemd[1]: unbound.service: Scheduled restart job, restart counter is at 5.
Nov 21 10:27:02 dnsproxy systemd[1]: Stopped unbound.service - Unbound DNS server.
Nov 21 10:27:02 dnsproxy systemd[1]: unbound.service: Start request repeated too quickly.
Nov 21 10:27:02 dnsproxy systemd[1]: unbound.service: Failed with result 'exit-code'.
Nov 21 10:27:02 dnsproxy systemd[1]: Failed to start unbound.service - Unbound DNS server.
```

The hints of the reasoning behind the pain are visible in:
```
azureuser@dnsproxy:~$ sudo dmesg | tail
...
[80877.805556] audit: type=1400 audit(1700562421.563:280): apparmor="DENIED" operation="open" profile="unbound" name="/usr/local/lib/python3.11/dist-packages/" pid=9542 comm="unbound" requested_mask="r" denied_mask="r" fsuid=105 ouid=0
[80878.030363] audit: type=1400 audit(1700562421.815:281): apparmor="DENIED" operation="open" profile="unbound" name="/etc/unbound/" pid=9556 comm="unbound" requested_mask="r" denied_mask="r" fsuid=105 ouid=0
```

`strace` shows corresponding `EPERM`s.

Fixed for me with:
```
azureuser@dnsproxy:~$ sudo ln -s -t /usr/local/lib/python3.11/dist-packages /usr/lib/python3/dist-packages/unboundmodule.py 
azureuser@dnsproxy:~$ cat <<'EOF' | sudo tee /etc/apparmor.d/local/usr.sbin.unbound >/dev/null
/usr/local/lib/python3.11/dist-packages/ r,
/usr/local/lib/python3.11/dist-packages/** r,
/opt/vendor/product/script.py r,
EOF
azureuser@dnsproxy:~$ sudo aa-enforce /etc/apparmor.d/usr.sbin.unbound
azureuser@dnsproxy:~$ sudo systemctl restart unbound
```

If you wish to import modules, remember to slip into the top of your script something like:
```
sys.path.insert(0, '/usr/lib/python3/dist-packages/')
```
