### ISSUE TITLE
RPZ exception for a domain when blocking TLD. possible?

### ISSUE THREAD

**Issue by jpgpi250** [NLnetLabs/unbound#771]
my RPZ definition (config):

```
rpz:
	name: tld
	zonefile: zonefiles/tld.zone
	url: http://127.0.0.1/tld.rpz
	rpz-action-override: nxdomain
	rpz-signal-nxdomain-ra: yes
	rpz-log: yes
	rpz-log-name: tld
```

the rpz file (partial), data from [this site](https://www.spamhaus.org/statistics/tlds/) (daily updated)
```
; Most Abused Top Level Domains
; data source: https://www.spamhaus.org/statistics/tlds/
; Last updated: 2022-10-24 14:09:01 (UTC) (UTC)
;
*.surf CNAME .
*.link CNAME .
*.cricket CNAME .
*.associates CNAME .
*.financial CNAME .
*.ml CNAME .
*.discount CNAME .
*.top CNAME .
*.icu CNAME .
*.fit CNAME .
```

question: Apparently, I need to make an exception for gitcdn.link, required for raw github transactions?
I was hoping adding a line to the rpz would do the trick, something like:
```
gitcdn.link CNAME rpz-passthru.
```
accepted by /usr/local/sbin/nsd-checkzone rpz /var/www/html/tld.rpz (result is 'zone rpz is ok')

but it doesn't work, I still get NXDOMAIN (dig)

is this even possible, if yes, what is the proper syntax to achieve this.

thanks for your time and effort.

**Comment by gthess** [comment]
I believe it is because of `rpz-action-override: nxdomain`. Can you try without that option?

**Comment by jpgpi250** [comment]
rpz definition (config) changed into:
```
rpz:
	name: tld
	zonefile: zonefiles/tld.zone
	url: http://127.0.0.1/tld.rpz
	# no rpz-action-override here (exceptions - rpz-passthru)
	# rpz-action-override: nxdomain
	rpz-signal-nxdomain-ra: yes
	rpz-log: yes
	rpz-log-name: tld
```

WORKS as hoped / expected

Thanks for the obvious (stupid me) tip!
