### ISSUE TITLE
[doc] Missing documention in ub_resolve_event() for callback parameter was_ratelimited

### ISSUE THREAD

**Issue by jelu** [NLnetLabs/unbound#779]
As subject, doc says

> void callback(void* mydata, int rcode, void* packet, int packet_len, int sec, char* why_bogus)

but code says

> typedef void (*ub_event_callback_type)(void*, int, void*, int, int, char*, int);

missing the last `int`

**Comment by wcawijngaards** [comment]
The commit adds the documentation to the header file, in the comment for `ub_resolve_event`. It is was_ratelimited. This is the same `was_ratelimited` that is also returned in the `struct ub_result` for queries.

Thank you for the detailed report!

**Comment by jelu** [comment]
Np Wouter! And thank you for the quick commit! :smile:
