### ISSUE TITLE
Memory leak in outside_network.c

### ISSUE THREAD

**Issue by rdrozhdzh** [NLnetLabs/unbound#78]
In function `outnet_serviced_query()`, first `serviced_query` object is created at
https://github.com/NLnetLabs/unbound/blob/13d96540de32c7c3016146496b3be0b9619528bb/services/outside_network.c#L2124-L2128
which potentially allocates memory for the fields `qbuf`, `zone`, `tls_auth_name` and `opt_list`.

And later under some conditions, this object can be destroyed, but only `qbuf` and `zone` fields are released at
https://github.com/NLnetLabs/unbound/blob/13d96540de32c7c3016146496b3be0b9619528bb/services/outside_network.c#L2135-L2139
and
https://github.com/NLnetLabs/unbound/blob/13d96540de32c7c3016146496b3be0b9619528bb/services/outside_network.c#L2144-L2148

Probably, the function `serviced_delete()` or `serviced_node_del()` should be used instead for destroying the `serviced_query` object.

**Comment by wcawijngaards** [comment]
Yes `serviced_node_del` is the function we can use here.  Thank you for the report!

**Comment by rdrozhdzh** [comment]
You must not remove lines
```
  free(cb);
```
in both cases. The variable `cb` is not related to the `serviced_query` object being destroyed

**Comment by wcawijngaards** [comment]
You are correct, and I fixed it in https://github.com/NLnetLabs/unbound/commit/554e4a939c81b6669b457de573a37070c0e4b531 after the code analyzer (clang) found it!

**Comment by rdrozhdzh** [comment]
ok, I see it now, thank you!
