### ISSUE TITLE
RFC 1035 not support, 0x20 requirement provides no security benefit

### ISSUE THREAD

**Issue by andrewhodel** [NLnetLabs/unbound#801]
Requiring 0x20 support does nothing, requests can be modified in transit regardless of the number of requests requiring a massive server load increase.

**Comment by andrewhodel** [comment]
It also means that RFC 1035 is not supported by unbound.

**Comment by gthess** [comment]
Closing this as per #800. 0x20 is a configurable option and can be kept disabled.

**Comment by andrewhodel** [comment]
I opened https://github.com/jsha/unboundtest/issues/9 to make it easier to understand.

The unbound client never requires 0x20, but it does send it's request with non all lower letter case.

Fixed for me by converting incoming queries to lowercase - https://unboundtest.com/m/A/ispapp.co/5RVJUM7V

@gthess thanks
