### ISSUE TITLE
Raspian OS 64bit Unbound 1.13.1 Timeout´s DNSSEC on specific Adresses

### ISSUE THREAD

**Issue by Starfoxfs** [NLnetLabs/unbound#803]
**Describe the bug**
I get Timeouts with enabled DNSSEC on Pihole, on this Sites:

```
dig fail01.dnssec.works @127.0.0.1 -p5335
dig good-A.test.dnssec-tools.org @127.0.0.1 -p5335
dig good-AAAA.test.dnssec-tools.org @127.0.0.1 -p5335
```
or without Localhost and Port

It works directly if we set a timeout for the "Dig" Command like:
`dig fail01.dnssec.works @127.0.0.1 -p5335 +timeout=15`
but with a higher Response Time about 2700ms

See also this Thread on Pihole Forums:
[https://discourse.pi-hole.net/t/unbound-pihole-latest-version-timeout-nur-beim-servfail-test/](https://discourse.pi-hole.net/t/unbound-pihole-latest-version-timeout-nur-beim-servfail-test/)
Me and a other User have this Problems

Other Sites works without Problems:
```
dig www.dnssec-failed.org
dig www.brokendnssec.net +dnssec
```

On fail01.dnssec.works Unbound status says:

> unbound[7099:0] info: validation failure <fail01.dnssec.works. A IN>: no signatures from 5.45.109.212

Where is the Problem here ? before on my 32Bit Raspian OS this worked like a charm.

If you need more configuration Information just ask.

**To reproduce**
1. Hardware Raspberry Pi 4B 2GB
2. Fresh install of Unbound with Pihole on a Raspian OS 64bit (LITE Version)
3. The first use of "dig fail01.dnssec.works @127.0.0.1 -p5335" or only "dig fail01.dnssec.works" leads to "connection timeout no servers coud be reached.
4. Same for "dig good-A.test.dnssec-tools.org" and "dig good-AAAA.test.dnssec-tools.org"

**Expected behavior**

**System:**
 - Unbound version: 1.13.1
 - OS: Raspian OS 64bit (LITE) Bullseye 11 latest
 - `unbound -V` output:
Version 1.13.1

Configure line: --build=aarch64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/aarch64-linux-gnu --libexecdir=${prefix}/lib/aarch64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --disable-rpath --with-pidfile=/run/unbound.pid --with-rootkey-file=/var/lib/unbound/root.key --with-libevent --with-pythonmodule --enable-subnet --enable-dnstap --enable-systemd --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --libdir=/usr/lib --disable-flto
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 1.1.1n  15 Mar 2022
Linked modules: dns64 python subnetcache respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

**Additional information**
Add any other information that you may have gathered about the issue here.

**Comment by alexnt85** [comment]
Same for me:
"connection timeout; no servers could be reached".

Unbound version: 1.13.1
OS: Raspian OS 32bit (`uname -m` output `armv6l`)

**Comment by janaxhell** [comment]
Just to add that this same exact behavior happens on Orange Pi Zero 2 with Armbian_22.11.1_Orangepizero2_bullseye_edge_6.0.10 and latest unbound.

**Comment by gthess** [comment]
I see two different broken domains here.
- dnssec.works
  One of the nameservers (ns2.myinfrastructure.org) is not responding. This coupled with the DNSSEC error from the other nameservers makes Unbound try to find a correct answer that will eventually hang on the timeouts of the unresponsive nameserver. Eventually a SERVFAIL response will be generated by Unbound but not because of the DNSSEC error, rather the timeout errors that did not let Unbound finish the fallback logic of trying to find an answer that makes sense.
- test.dnssec-tools.org
  This domain seems broken even for tests that should not be, based on their name (https://dnsviz.net/d/good-a.test.dnssec-tools.org/dnssec/).

I am closing this; feel free to reopen/ping if I missed something :)
