### ISSUE TITLE
Issues of EDNS buffer size

### ISSUE THREAD

**Issue by idealeer** [NLnetLabs/unbound#832]
Although the `edns buffer size` is set to 1232 for a query, Unbound still receives a response with a size larger than 1232, even than 4096.

As suggested here https://www.dnsflagday.net/2020/:

```
It is important for DNS software vendors to comply with DNS standards, 
and to use a default EDNS buffer size (1232 bytes) that will not cause 
fragmentation on typical network links.
```

We recommend following current practices by only accepting responses less than 1,232 by default, which are implemented by PowerDNS Recursor.

We also wonder why Unbound does this.

**Comment by wcawijngaards** [comment]
The size of the response is selected by the server that sends it. Unbound has lenient acceptance. This is limited by the way, by the actual buffer size that unbound has behind it. But Unbound selects an EDNS query size in the query that is the appropriate value. So we are sending strictly and accepting leniently.

Compliance with flagday 2020 happened for us in a release at that time, when we changed the values suggested by the flagday; the advertised EDNS size. In version 1.12.0, 8 oct 2020.

**Comment by idealeer** [comment]
Got it. Thanks for the explanation. Maybe the large response has issues like fragmentation, but they are another topic.
