### ISSUE TITLE
[FR] Ability to clean expired DNS records when using cachedb module and Redis databases

### ISSUE THREAD

**Issue by alpominth** [NLnetLabs/unbound#836]
In [a documentation of Unbound](https://nlnetlabs.nl/documentation/unbound/unbound.conf/) there is this citation:

`"It should be  noted  that  Unbound  never  removes  data  stored in the Redis server, even if some data have expired in terms of DNS TTL or the Redis  server  has  cached too  much  data;  if  necessary  the Redis server must be configured to limit the cache size, preferably with some kind of  least-recently-used eviction  policy."`

I don't know if this behavior is intended or not, but when using Unbound with high-loads the Redis database would be huge.

My suggestion is to implement a mechanism of cleaning the expired data from the Redis database.

Maybe an option like this would be interesting:

`redis-prune-expired: yes`

I know that implementing such a feature would impact the performance and would increase disk/memory I/O, that's why this feature should be optional.

**Comment by saint-lascivious** [comment]
Keeping expired records around is kind of the point, and they'll always be expired from the perspective of the client (always served with TTL 0).

The database max memory footprint can be limited, and several different methods of eviction style are configurable in Redis.

I set a max memory value of 16MB, and evict on a least frequently used basis personally. Which is, without coincidence, pretty much exactly as the documentation describes (investigate eviction policies that suit your requirements).

Looking at my Munin monitoring, with my network's use case this ends up in around ~32k database entries persisted at any given time.

**Comment by alpominth** [comment]
@saint-lascivious

If I want to limit the Redis memory to 300MB only for Unbound not letting the DB bigger and have more applications that need more than 300MB, it would be a problem.

IMHO, Unbound should deal the Redis cleaning, as setting a maximum memory usage just for Unbound instance can conflicts with other program in the host that also use the same Redis DB.

**Comment by saint-lascivious** [comment]
The simpler solution would appear to be just not mixing your database instances up.

As an aside, 300MB would be approximately an order of magnitude greater than it would need to be, even in a relatively high volume server.

Somewhat off topic to this issue but I noticed in another issue you'd commented in that you were pretty aggressively messing about with client facing TTL. Throwing larger numbers at things isn't always the best solution, but that's said in the context of not knowing what exactly it was you are trying to address there.

**Comment by alpominth** [comment]
@saint-lascivious 

Do you mean run more than one instance of Redis? If it is that, I don't think it's a good idea.

What I use here is a permanent caching of DNS queries, that's why that 60 days of TLL, this big cache serves 50 different computers in the firm I work.

**Comment by saint-lascivious** [comment]
Yes, I do. Slap it in a container, there's low overhead on multiple instances. It's reasonably unlikely a single database configuration is going to be able to meet the needs of all your projects in an efficient manner. Start small, and see how long it's taking until you start seeing evictions under your desired profile. 8M, 16M, 32M etc. even 16M is a giant shittone (tens of thousands) of DNS cache entries.

There's absolutely no need to alter _client facing_ TTL to that extent. You can keep your cache indefinitely behind the scenes, and reset cache TTL on client query. I can't think of any possible need to alter client facing TTL to such an  extent.

There is some irony involved with being worried about Redis cache eviction (have you investigated cache eviction policies?), while deliberately ensuring your clients get 60 day TTLs (really 59.9something, not sure what happened there).

Edit: This seemed harsher than I intended, upon review. Written language tone is not my strongest suit.

**Comment by alpominth** [comment]
@saint-lascivious 

I got.

> have you investigated cache eviction policies?

/\ Yes, I read a lot about it and I configured correctly. I changed `maxmemory-policy` in Redis to `allkeys-lru`  as some guys was recommending in a pi-hole forum.

==============

Well, I don't know if NLnetLabs team will think my idea reasonable but if they implement it, better.

**Comment by gthess** [comment]
Cleaning expired Redis records from Unbound is almost impossible. Unbound would have to keep its own bookkeeping of what is cached in Redis and issue deletion commands for each expired record.

There is already the option [redis-expire-records](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-cachedb-redis-expire-records) for Unbound that sets the record expiration for Redis. Then it is up to Redis on how to handle the key eviction/free space.

As I understand, if you want fine-grained configuration of the Redis cache the best approach (by reading [this](https://redis.com/blog/outgrowing-logical-databases/) and [this](https://redis.com/blog/benchmark-shared-vs-dedicated-redis-instances/) sparked by #850) is to use dedicated Redis instances for better configuration/performance/monitoring.
