### ISSUE TITLE
systemctl reload fails

### ISSUE THREAD

**Issue by sam-lunt** [NLnetLabs/unbound#84]
I'm running version 1.9.3-2 of unbound on Arch Linux.

The `CapabilityBoundingSet` value in `/usr/lib/systemd/system/unbound.service` causes the call `# systemctl reload unbound` to fail with the below error:

    kill[57844]: kill: sending signal to 57760 failed: Operation not permitted

If the line `CapabilityBoundingSet` is commented out in the service file, the call to reload works without issue. Also, if the value `CAP_KILL` is added to the `CapabilityBoundingSet`, the reload command is able to complete without error.

My guess is that the `ExecReload` command `/bin/kill -HUP $MAINPID` is executed as root. The combination of the fact that the unbound process is owned by the unbound user and that root does not have the `CAP_KILL` capability means that there is insufficient permissions for root to send the HUP signal to the unbound process.

**Comment by wcawijngaards** [comment]
Fixed by merging #85.  Thanks for the fix.
