### ISSUE TITLE
Unbound won't build with aaaa-filter-iterator.patch

### ISSUE THREAD

**Issue by Jakker** [NLnetLabs/unbound#841]
Applying the `aaaa-filter-iterator.patch` will break compiling unbound. It can be fixed with patchin the patch:

```
--- aaaa-filter-iterator.patch	2023-02-08 11:19:38.869425000 +0100
+++ aaaa-filter-iterator.patch.orig	2023-01-12 09:18:31.000000000 +0100
@@ -108,8 +108,6 @@
  	iter_env->supports_ipv6 = cfg->do_ip6;
  	iter_env->supports_ipv4 = cfg->do_ip4;
  	iter_env->outbound_msg_retry = cfg->outbound_msg_retry;
- 	iter_env->max_sent_count = cfg->max_sent_count;
- 	iter_env->max_query_restarts = cfg->max_query_restarts;
 +	iter_env->aaaa_filter = cfg->aaaa_filter;
  	return 1;
  }
```

See also https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=269337

**Comment by wcawijngaards** [comment]
Yes that patch works, if it is applied in reverse. I also adjusted it so that the context lines are three lines instead of five. With that change the patch applies and unbound compiles.
