### ISSUE TITLE
systemd resolver as DNS over TLS (DoT) client

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#847]
Hello,

I was just giving systemd-resolved a try to connect as TLS client to Unbound. But it failed. Is someone using this combination without trouble?

I have a second (openwrt) router to separate my networks which runs stubby and flawlessly gets the data over TLS from my local Unbound. So my configuration seems to be correct.

My desktop client is a Ubuntu 22.04 LTS with systemd 249. If I change the resolver configuration (resolved.conf) to "DNSOverTLS=yes", it doesn’t work. So I dumped the packets with wireshark. systemd-resolved opens a TLS 1.3 connection with a "client hello". Unbound answers with a "server hello" and "change cipher spec". After a "change cipher spec" response from my client the connection ends with a "TCP RST". I can provide the pcap file if required.

I am a little surprised by this. TLS 1.3 has just a few ciphers which were defined right from the beginning. So I expect every TLS 1.3 client not to stumble upon cipher negotiation. And this is **before** the certificate validity is checked? Or am I in an error?

**Comment by ghost** [comment]
Interesting. If I set DNSoverTLS to "opportunistic" it works.

**Comment by simondeziel** [comment]
I also use `systemd-resolved` as DoT client to unbound and it works well. To make `resolved` verify the certificate, you need to have the certificate cover the hostname you provide in the `DNS=` config, i.e: `DNS=192.0.2.1#dot.example.com`. Alternatively, if you can get a TLS cert covering an IP, you then don't need to specify the `#dot.example.com` name in `resolved.conf` and you will still be able to validate the server's cert.

This is covered in https://www.freedesktop.org/software/systemd/man/resolved.conf.html#DNSOverTLS=

**Comment by ghost** [comment]
Thanks for the hints. Well, my first certificate was self-signed. Stubby liked it, systemd not. Now I have a new one issued from my local CA. The names (different from the real hostname) are set in "Common Name" and "Subject Alternative Name". OpenSSL can verify it when connecting as "s_client" to Unbound. Stubby still likes it, systemd not :)

For me it’s not that important. In my local network I can live with opportunistic mode. But it’s strange anyway.

**Comment by simondeziel** [comment]
@AnanasPfirsichSaft I'm glad you've found a workaround. At this point, I think the remaining issue is probably not with Unbound itself.
