### ISSUE TITLE
[Question] Does the cache size applies to Redis cache?

### ISSUE THREAD

**Issue by alpominth** [NLnetLabs/unbound#848]
There is this information in [unbound.conf manual](https://nlnetlabs.nl/documentation/unbound/unbound.conf/):

```
       It should be  noted  that 
       Unbound  never  removes  data  stored in the Redis server, even if some
       data have expired in terms of DNS TTL or the Redis  server  has  cached
       too  much  data;  if  necessary  the Redis server must be configured to
       limit the cache size, preferably with some kind of  least-recently-used
       eviction  policy.
```

And there are these options for setting the cache size:

```
       msg-cache-size: <number>
       rrset-cache-size: <number>
       key-cache-size: <number>
       neg-cache-size: <number>
```

My question is:

If I set a limit of size with these option to the Unbound cache, will it apply to Redis cache too? If the maximum cache size was reached, will Unbound overwrite old keys in the Redis cache to allocate space to new keys?

**Comment by saint-lascivious** [comment]
No.

**Comment by alpominth** [comment]
@saint-lascivious 

Got.

**Comment by saint-lascivious** [comment]
Note that this is covered in the cachedb documentation:


> Unbound never removes data stored in the Redis server, even if some data have expired in terms of DNS TTL or the Redis  server has cached too much data
>

**Comment by alpominth** [comment]
I thought that Unbound would read only the data inside cache size range.
