### ISSUE TITLE
[FR] Ability to use specific database in Redis

### ISSUE THREAD

**Issue by alpominth** [NLnetLabs/unbound#850]
Redis uses 16 databases in default Debian version.

This feature would be useful for avoiding mess up different kinds of data if the user use Redis for other than DNS caching.

**Comment by GieltjE** [comment]
This would be really helpfull, there are too many applications about which cannot set the DB and thus all collide in DB 0.

**Comment by gthess** [comment]
This seems trivial to do but I don't understand the usage of different DBs in redis. Is the concern only about key collisions or could you also have different configurations per DB?

**Comment by gthess** [comment]
It seems logical databases do not have their own configuration but they share the same options as the redis instance.
By reading [this](https://redis.com/blog/outgrowing-logical-databases/) and [this](https://redis.com/blog/benchmark-shared-vs-dedicated-redis-instances/) it seems that having dedicated instances is the better approach.
So if configuration/performance/monitoring is not a concern, as it is not solved by logical databases, the only think left is key collisions I guess?
What is a current problem that this feature would solve? :)

**Comment by GieltjE** [comment]
For lots of smaller instances using multiple databases is just fine (we have a few servers that use it just for some unbound caching and some other small applications), running multi redis instances just add extra complexity without bringing much to the table.
For these cases it is very usefull if the databases are separated (no collisions and easier debugging/maintaince if something goes wrong with one of the applications).
As adding a database identifier shouldn't be very difficult (connection string addition if I'm correct), that would be much appreciated.
