### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [NLnetLabs/unbound#851]
I would like to point out that an identifier like “[`_UB_UNBOUND_EVENT_H`](https://github.com/NLnetLabs/unbound/blob/f72116883b923608ab2e6d134cc770f988ede82a/libunbound/unbound-event.h#L55 "Update candidate")” [does eventually not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by Philip-NLnetLabs** [comment]
Fixed in master

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/NLnetLabs/unbound/commit/2a100ee9ee02e42e6581b09dabc8289583347350 "Renaming of two include guards").
