### ISSUE TITLE
Unbound forward-zones query esponse was CNAME Stops resolving

### ISSUE THREAD

**Issue by cyz452** [NLnetLabs/unbound#862]
When using Unbound with forward-zones, Let's say there is a domain:

nlnetlabs.nl

with subdomains:

unbound.docs.nlnetlabs.nl

following configuration doesn't seem to work:
forward-zones
    name: "nlnetlabs.nl"
    forward-addr: 8.8.8.8

client: ping unbound.docs.nlnetlabs.nl
    ping: unbound.docs.nlnetlabs.nl: Name or service not known

Service:
Mar 13 16:35:57 localhost.localdomain unbound[1513]: [1513:0] info: start of service (unbound 1.16.2).
Mar 13 16:35:59 localhost.localdomain unbound[1513]: [1513:0] info: resolving unbound.docs.nlnetlabs.nl. A IN
Mar 13 16:35:59 localhost.localdomain unbound[1513]: [1513:0] info: resolving unbound.docs.nlnetlabs.nl. AAAA IN
Mar 13 16:35:59 localhost.localdomain unbound[1513]: [1513:0] info: response for unbound.docs.nlnetlabs.nl. A IN
Mar 13 16:35:59 localhost.localdomain unbound[1513]: [1513:0] info: reply from <nlnetlabs.nl.> 8.8.8.8#53
Mar 13 16:35:59 localhost.localdomain unbound[1513]: [1513:0] info: query response was CNAME
Mar 13 16:35:59 localhost.localdomain unbound[1513]: [1513:0] info: resolving unbound.docs.nlnetlabs.nl. A IN
Mar 13 16:35:59 localhost.localdomain unbound[1513]: [1513:0] info: response for unbound.docs.nlnetlabs.nl. AAAA IN
Mar 13 16:35:59 localhost.localdomain unbound[1513]: [1513:0] info: reply from <nlnetlabs.nl.> 8.8.8.8#53
Mar 13 16:35:59 localhost.localdomain unbound[1513]: [1513:0] info: query response was CNAME
Mar 13 16:35:59 localhost.localdomain unbound[1513]: [1513:0] info: resolving unbound.docs.nlnetlabs.nl. AAAA IN
Mar 13 16:35:59 localhost.localdomain unbound[1513]: [1513:0] info: resolving unbound.docs.nlnetlabs.nl.localdomain. A IN
Mar 13 16:35:59 localhost.localdomain unbound[1513]: [1513:0] info: resolving unbound.docs.nlnetlabs.nl.localdomain. AAAA IN

Stops resolving will not resolving to an A record.

; <<>> DiG 9.16.23-RH <<>> unbound.docs.nlnetlabs.nl
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 33838
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;unbound.docs.nlnetlabs.nl. IN  A

;; ANSWER SECTION:
unbound.docs.nlnetlabs.nl. 5    IN  CNAME   readthedocs.io.
readthedocs.io.     5   IN  A   104.17.33.82
readthedocs.io.     5   IN  A   104.17.32.82

;; Query time: 22 msec
;; SERVER: 192.168.92.2#53(192.168.92.2)
;; WHEN: Mon Mar 13 16:37:47 CST 2023
;; MSG SIZE  rcvd: 103

Version 1.16.2

Configure line: --build=x86_64-redhat-linux-gnu --host=x86_64-redhat-linux-gnu --program-prefix= --disable-dependency-tracking --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --sysconfdir=/etc --datadir=/usr/share --includedir=/usr/include --libdir=/usr/lib64 --libexecdir=/usr/libexec --localstatedir=/var --sharedstatedir=/var/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-pythonmodule --with-pyunbound PYTHON=/usr/libexec/platform-python --with-libevent --with-pthreads --with-ssl --disable-rpath --disable-static --enable-relro-now --enable-pie --enable-subnet --enable-ipsecmod --with-conf-file=/etc/unbound/unbound.conf --with-pidfile=/var/run/unbound/unbound.pid --enable-sha2 --disable-gost --enable-ecdsa --with-rootkey-file=/var/lib/unbound/root.key --enable-linux-ip-local-port-range
Linked libs: libevent 2.1.8-stable (it uses epoll), OpenSSL 1.1.1k  FIPS 25 Mar 2021
Linked modules: dns64 python ipsecmod subnetcache respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

I have searched unbound.net, this site, and elsewhere without finding an answer. Thanks for help.

**Comment by gthess** [comment]
Hi, it seems to work here on both the 1.16.2 version and the latest code.
It also seems to work on your example since I see the IP addresses in the ANSWER SECTION.
Maybe it is a system error? As in the system is not configured to talk to Unbound for DNS? And that is why ping in this example cannot resolve the name?

**Comment by cyz452** [comment]
Yes, dig unbound.docs.nlnetlabs.nl can see the IP addresses in the ANSWER SECTION.
run ping is on the unbound host .

ping www.nlnetlabs.nl
ping unbound.docs.nlnetlabs.nl
the two results are different，See the picture：

![20230314084312](https://user-images.githubusercontent.com/64049343/224863475-ac718a06-0c8e-415d-8e1f-1abe5adb633a.jpg)
![20230314084339](https://user-images.githubusercontent.com/64049343/224863479-d45eb0c9-7a6c-4288-92c7-699392966a69.jpg)
Thanks for help.

**Comment by gthess** [comment]
Still works for me here; also ping with the resolv.conf entry.
In this particular example unbound.docs.nlnetlabs.nl is a CNAME to readthedocs.io.
Can you try:
```
dig readthedocs.io.
ping readthedocs.io.
```
and see how that is resolved?

**Comment by cyz452** [comment]
Thanks, the parsed CNAME also needs to be configured in forward-zone.

The following configuration solved my problem：

/etc/unbound/conf.d/forward-nlnetlabs.nl.conf
forward-zone:
            name: "nlnetlabs.nl" 
            forward-addr: 8.8.8.8
forward-zone:
            name: "readthedocs.io" 
            forward-addr: 8.8.8.8

I thought forward-zone would go all the way to resolving to an A record，Is it possible to add such a function.

For example, www.apple.com has multiple CNAMEs, and there are many domain names like this. 

The domain name configuration uses the specified DNS resolution in the forward-zone,Changing the A record resolution of the website to CNAME will invalidate the domain name resolution configured in the forward-zone, and it will not be resolved from the DNS of the specified forward-zone.

thank you very much for your help.

**Comment by gthess** [comment]
I am then closing this as a non-issue :).
What forward-zone does is forwarding the queries for that zone and below to the designated target resolvers.
readthedocs.io is another zone altogether and Unbound will try to resolve that with other configuration options.
I guess in your example, readthedocs.io is not resolvable.

Are you trying to allow only a subset of domains/zones to be resolvable?
In that case it would be easier to use [local-zone](https://unbound.docs.nlnetlabs.nl/en/latest/manpages/unbound.conf.html#unbound-conf-local-zone) instead:
```
local-zone: "." always_refuse
local-zone: "nlnetlabs.nl." type_transparent
```
local-zone "filtering" is done on client queries.
The root zone `.` will REFUSE all queries that do not match more specific local-zone configurations. In this example client queries for the nlnetlabs.nl zone will be allowed full recursion including the CNAME to another zone.
