### ISSUE TITLE
unbound-control hanging

### ISSUE THREAD

**Issue by maxso-216** [NLnetLabs/unbound#879]
I find out unbound-control have been hanging and displaying nothing on my router.
In `unbound.log`, the sentence
`unbound[3163:0] error: accept failed: Function not implemented for (inet_ntop error) port 0` is spammed.
What does above sentence mean?

**Comment by gthess** [comment]
I can only guess that `accept4()` is probably not available on your system and Unbound fails to discover that.
Is this still an issue? If so, could you share the Unbound version and the system you are on? From a quick look I guess it is linux on ARM?

**Comment by maxso-216** [comment]
Well,as the unbound is poorly compiled by me, so the unbound is pretty buggy on the router. So, I switch to another router which has entware support, and the installed unbound is started with no issue. My only guess is that I am compiling unbound wrongly.
