### ISSUE TITLE
Unbound returns SERVFAIL for some domains

### ISSUE THREAD

**Issue by ckotte** [NLnetLabs/unbound#88]
I cannot resolve certain domains when I use DNSSEC. Looks like it's similar to this issue described here https://github.com/getdnsapi/stubby/issues/204. 

```
dig coder.show                     

; <<>> DiG 9.14.6 <<>> coder.show
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: SERVFAIL, id: 58735
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;coder.show.			IN	A

;; Query time: 1980 msec
;; SERVER: ::1#53(::1)
;; WHEN: Fri Sep 27 16:12:05 CEST 2019
;; MSG SIZE  rcvd: 39
```

```
dig +cdflag coder.show                                       

; <<>> DiG 9.14.6 <<>> +cdflag coder.show
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 35499
;; flags: qr rd ra cd; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;coder.show.			IN	A

;; ANSWER SECTION:
coder.show.		525	IN	CNAME	hosted.fireside.fm.
hosted.fireside.fm.	231	IN	A	45.33.51.100
```

I get this error in the logs:
```
unbound[187882]: [187882:0] info: validation failure <coder.show. A IN>: DS got unsigned CNAME answer from 1.1.1.1 and 1.1.1.1 for DS coder.show. while building chain of trust
unbound[187882]: [187882:0] info: validation failure <coder.show. A IN>: DS got unsigned CNAME answer from 1.1.1.1 and 1.1.1.1 for DS coder.show. while building chain of trust
```

Is there a way to enable the resolution of such "illegal" DNS configurations. I really would like to use DNSSEC, but it's not usable if certain domains don't work...

**Comment by spirillen** [comment]
You should try one of the following, as I don't recall which one was the right one...

**NOTE**: I'm not a hardcore unbound user, It just a test tool for me to check my scripts

```python
harden-dnssec-stripped: no
disable-dnssec-lame-check: yes
```

### harden-dnssec-stripped: <yes or no>
              Require DNSSEC data for trust-anchored zones, if  such  data  is
              absent,  the  zone  becomes  bogus. If turned off, and no DNSSEC
              data is received (or the DNSKEY data fails  to  validate),  then
              the  zone  is made insecure, this behaves like there is no trust
              anchor. You could turn this off if you are sometimes  behind  an
              intrusive  firewall (of some sort) that removes DNSSEC data from
              packets, or a zone changes from  signed  to  unsigned  to  badly
              signed  often.  If  turned  off  you run the risk of a downgrade
              attack that disables security for a zone. Default is on.

### disable-dnssec-lame-check: <yes or no>
              If true, disables the DNSSEC lameness  check  in  the  iterator.
              This check sees if RRSIGs are present in the answer, when dnssec
              is expected, and retries another authority if RRSIGs  are  unex-
              pectedly  missing.   The  validator  will  insist  in RRSIGs for
              DNSSEC signed domains regardless of this  setting,  if  a  trust
              anchor is loaded.

Source:

https://nlnetlabs.nl/documentation/unbound/unbound.conf/

You can also always use `man unbound` from the terminal

**Comment by ckotte** [comment]
@spirillen Thanks for the hint, but it still doesn't work with those options set.

**Comment by gthess** [comment]
This seems like a problem with the domain and not unbound (or stubby for the relevant issue).
Unbound saw an unsigned record in a supposedly signed domain and rightfully fails validation.

Unbound and DNSSEC were doing their job in regards to this misconfigured domain; you are supposed to get a SERVFAIL when validation fails.

The problem now seems resolved btw; coder.show went unsigned. Can you verify that from your end?
Although they seem to still have DNS issues (like CNAME next to other records; http://dnsviz.net/d/coder.show/dnssec/).

**Comment by ckotte** [comment]
I know that this is not an issue with unbound (or stubby). However, they are useless to me with DNSSEC enabled since several domains don't work. coder.show is just an example. There are other domains with dynamic DNS I need to access every day.

Some kind of workaround would be nice to be able to resolve such domains with DNSSEC enabled and still use proper DNSSEC validation for everything else.

**Comment by gthess** [comment]
If you know those domains in advance and you are confident with receiving bogus answers from them then you can define them under the option `domain-insecure:`.

However there is no proper option to legitimately retry without DNSSEC if validation fails because that defeats the purpose of validation.

**Comment by ckotte** [comment]
@gthess Ok. Thx. This works.
