### ISSUE TITLE
ignored interface-view option

### ISSUE THREAD

**Issue by AlexDF2017** [NLnetLabs/unbound#897]
It seems that interface-view option isn't functional (it is ignored).

Relevant rows from config to reproduce the issue:

server:
interface: 0.0.0.0
interface-view: 0.0.0.0 myview
view:
name: myview
local-data: "www.test.com A 10.160.10.90"

Using linux dig tool, pointing to unbound ip and asking for www.test.com, I receive the public ip address instead of 10.160.10.90 using unbound configured forwarder.

But if I add the following to config (range includes all ip involved):
    access-control-view: 192.168.0.0/16 myview

the dig tool correctly receive 10.160.10.90 as answer, so it seems the view itself is ok.
In interface & interface-view, instead of 0.0.0.0 I tried to use private unbound ip or interface name, same results; tried even using different ports adding @port, same results again.

Checked on unbound v.1.17.0 & v.1.17.1 on fresh debian 11 vm.

Whats wrong?

Alex

_______________________________________________
root@debiantest11:~/unbound-master# unbound -V
Version 1.17.1

Configure line: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --runstatedir=/run --disable-maintainer-mode --disable-dependency-tracking --with-pythonmodule --with-pyunbound --enable-subnet --enable-dnstap --enable-systemd --with-libnghttp2 --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --disable-rpath --with-pidfile=/run/unbound.pid --with-libevent --enable-tfo-client --with-rootkey-file=/usr/share/dns/root.key --enable-tfo-server
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 1.1.1n  15 Mar 2022
Linked modules: dns64 python subnetcache respip validator iterator
TCP Fastopen feature available

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues

**Comment by gthess** [comment]
Hi, I can't reproduce here.
I am using the following configuration:
```
server:
        interface: 0.0.0.0
        interface-action: 0.0.0.0 allow
        interface-view: 0.0.0.0 myview
        port: 5353

view:
        name: myview
        local-data: "www.test.com A 10.160.10.90"
```
and I get the following result:
```
$ dig @192.168.1.23 -p 5353 www.test.com

; <<>> DiG 9.10.3-P4-Ubuntu <<>> @192.168.1.23 -p 5353 www.test.com
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 2848
;; flags: qr aa rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;www.test.com.                  IN      A

;; ANSWER SECTION:
www.test.com.           3600    IN      A       10.160.10.90

;; Query time: 0 msec
;; SERVER: 192.168.1.23#5353(192.168.1.23)
;; WHEN: Mon Jun 12 15:09:37 CEST 2023
;; MSG SIZE  rcvd: 57
```
Another note for something that could be unnecessary complicating your setup is using ACL for the 0.0.0.0 interface. Is there a specific need for such configuration? You are essentially configuring a view (local-data) _for everything_; you can just configure local-data without a view. If incoming traffic is not routed to a view, the globally configured local-data will be used.

Do you maybe have other conflicting configuration? Can you try with just the configuration above?

**Comment by AlexDF2017** [comment]
Hi, thanks for the reply.

The problem was related to the following option:

    access-control: 192.168.0.0/16 allow

which at first sight wasn't related to the view, instead not only the access-control-view overrides the interface-view but even the "simple" access-control (in fact the documentation reports access-control* , without the trailing minus, sorry...).

Omitting it and substituting with

    interface-action: 0.0.0.0 allow

resolved the issue; we loose the granular ACL to limit access per source ip address, no problem, we will transfer this role to a firewall.

About the question about the view usage: my first reported configuration was just a very simple config used to reproduce the problem, our intention is to use views applying to different interface ports, as per following:

    interface: 0.0.0.0@15001
    interface-action: 0.0.0.0@15001 allow
    interface-view: 0.0.0.0@15001 my-view-1
    
    interface: 0.0.0.0@15002
    interface-action: 0.0.0.0@15002 allow
    interface-view: 0.0.0.0@15002 my-view-2
    
    interface: 0.0.0.0@15003
    interface-action: 0.0.0.0@15003 allow
    interface-view: 0.0.0.0@15003 my-view-3

Thanks for the suggestion about interface-action.
Alex

**Comment by AlexDF2017** [comment]
Issue closed
