### ISSUE TITLE
warning: ‘Py_SetProgramName’ is deprecated

### ISSUE THREAD

**Issue by saint-lascivious** [NLnetLabs/unbound#906]
Miscellaneous build noise in python module:

`libtool: compile:  gcc -I. -Wdate-time -D_FORTIFY_SOURCE=2 -I./../unbound -I/usr/include/python3.11 -DSRCDIR=./../unbound -g -O2 -ffile-prefix-map=/home/saint/source/unbound-out=. -fstack-protector-strong -Wformat -Werror=format-security -I/usr/include/google -c util/configlexer.c -o configlexer.o >/dev/null 2>&1
../unbound/pythonmod/pythonmod.c: In function ‘pythonmod_init’:
../unbound/pythonmod/pythonmod.c:312:7: warning: ‘Py_SetProgramName’ is deprecated [-Wdeprecated-declarations]
  312 |       Py_SetProgramName(progname);
      |       ^~~~~~~~~~~~~~~~~
In file included from /usr/include/python3.11/Python.h:94,
                 from ../unbound/pythonmod/pythonmod.c:54:
/usr/include/python3.11/pylifecycle.h:37:38: note: declared here
   37 | Py_DEPRECATED(3.11) PyAPI_FUNC(void) Py_SetProgramName(const wchar_t *);
      |                                      ^~~~~~~~~~~~~~~~~
`

Unbound version and configure string (Debian-ish, with a side of everything):

$ unbound -V
Version 1.17.2

Configure line: --build=aarch64-linux-gnu --prefix=/usr --includedir=/include --mandir=/share/man --infodir=/share/info --sysconfdir=/etc --localstatedir=/var --disable-option-checking --disable-silent-rules --libdir=/lib/aarch64-linux-gnu --libexecdir=/lib/aarch64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --disable-rpath --with-pidfile=/run/unbound.pid --with-rootkey-file=/var/lib/unbound/root.key --with-libevent --with-pythonmodule --enable-subnet --enable-dnstap --enable-systemd --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --libdir=/usr/lib --disable-flto --enable-cachedb --enable-dnscrypt --enable-ipsecmod --enable-ipset --enable-tfo-client --enable-tfo-server --with-libhiredis --with-libnghttp2
Linked libs: libevent 2.1.12-stable (it uses epoll), OpenSSL 3.0.8 7 Feb 2023
Linked modules: dns64 python cachedb ipsecmod subnetcache ipset respip validator iterator
DNSCrypt feature available
TCP Fastopen feature available

**Comment by wcawijngaards** [comment]
Thank you for the report! Python added new python initialization configuration that uses `PyInitializeFromConfig`. The fix commit adds that and also preinitializes python for the AppendInittab call, for swig. The `Py_NoSiteFlag` does not seem to be deprecated, but `config.site_import` is set as well by the commit.
