### ISSUE TITLE
1.17.1 contrib/Dockerfile.tests E: Package 'netcat' has no installation candidate

### ISSUE THREAD

**Issue by jeffwesthead** [NLnetLabs/unbound#912]
Should Dockerfile.tests be changed to install netcat-openbsd?

jeff@jeff0607:~/repos/unbound-1.17.1$ uname -a
Linux jeff0607 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

jeff@jeff0607:~/repos/unbound-1.17.1$ git branch
* branch-1.17.1

jeff@jeff0607:~/repos/unbound-1.17.1$ sudo docker build -t unbound-tester -f contrib/Dockerfile.tests .
Sending build context to Docker daemon  196.4MB
Step 1/7 : FROM gcc:latest
 ---> ce4bf977c328
Step 2/7 : WORKDIR /usr/src/unbound
 ---> Using cache
 ---> 61a3e604399e
Step 3/7 : RUN apt-get update
 ---> Using cache
 ---> 78208568785e
Step 4/7 : RUN apt-get install -y bison flex
 ---> Using cache
 ---> e359aa591ee0
Step 5/7 : RUN apt-get install -y ldnsutils dnsutils xxd splint doxygen netcat
 ---> Running in 97fae8402ca2
Reading package lists...
Building dependency tree...
Reading state information...
Package netcat is a virtual package provided by:
  netcat-openbsd 1.219-1
  netcat-traditional 1.10-47

**Comment by gthess** [comment]
Closing this now as the change from `netcat` to `netcat-openbsd` was commited as part of the changes for #889.
