### ISSUE TITLE
1.17.1 make test in Dockerfile.tests container fails: lto1: fatal error: bytecode stream in file '.libs/as112.o' generated with LTO version 11.3 instead of the expected 13.0

### ISSUE THREAD

**Issue by jeffwesthead** [NLnetLabs/unbound#913]
I modified contrib/Dockerfile.tests to install netcat-openbsd to get around my other issue.

Once inside the container, I ran ./configure with no arguments and then make test. This fails. Please advise!

root@0e76cfd17b46:/usr/src/unbound# uname -a
Linux 0e76cfd17b46 5.15.0-1041-azure #48-Ubuntu SMP Tue Jun 20 20:34:08 UTC 2023 x86_64 GNU/Linux

./libtool --tag=CC --mode=link gcc   -I.  -DSRCDIR=. -g -O2 -flto  -o unittest unitanchor.lo unitdname.lo unitlruhash.lo unitmain.lo unitmsgparse.lo unitneg.lo unitregional.lo unitslabhash.lo unitverify.lo readhex.lo testpkts.lo unitldns.lo unitecs.lo unitauth.lo unitzonemd.lo unittcpreuse.lo worker_cb.lo dns.lo infra.lo rrset.lo dname.lo msgencode.lo as112.lo msgparse.lo msgreply.lo packed_rrset.lo iterator.lo iter_delegpt.lo iter_donotq.lo iter_fwd.lo iter_hints.lo iter_priv.lo iter_resptype.lo iter_scrub.lo iter_utils.lo localzone.lo mesh.lo modstack.lo view.lo outbound_list.lo alloc.lo config_file.lo configlexer.lo configparser.lo fptr_wlist.lo edns.lo locks.lo log.lo mini_event.lo module.lo net_help.lo random.lo rbtree.lo regional.lo rtt.lo dnstree.lo lookup3.lo lruhash.lo slabhash.lo tcp_conn_limit.lo timehist.lo tube.lo winsock_event.lo autotrust.lo val_anchor.lo rpz.lo proxy_protocol.lo validator.lo val_kcache.lo val_kentry.lo val_neg.lo val_nsec3.lo val_nsec.lo val_secalgo.lo val_sigcrypt.lo val_utils.lo dns64.lo  authzone.lo         respip.lo netevent.lo listen_dnsport.lo outside_network.lo ub_event.lo keyraw.lo sbuffer.lo wire2str.lo parse.lo parseutil.lo rrdef.lo str2wire.lo strlcat.lo strlcpy.lo -lssl -lcrypto
libtool: link: gcc -I. -DSRCDIR=. -g -O2 -flto -o unittest .libs/unitanchor.o .libs/unitdname.o .libs/unitlruhash.o .libs/unitmain.o .libs/unitmsgparse.o .libs/unitneg.o .libs/unitregional.o .libs/unitslabhash.o .libs/unitverify.o .libs/readhex.o .libs/testpkts.o .libs/unitldns.o .libs/unitecs.o .libs/unitauth.o .libs/unitzonemd.o .libs/unittcpreuse.o .libs/worker_cb.o .libs/dns.o .libs/infra.o .libs/rrset.o .libs/dname.o .libs/msgencode.o .libs/as112.o .libs/msgparse.o .libs/msgreply.o .libs/packed_rrset.o .libs/iterator.o .libs/iter_delegpt.o .libs/iter_donotq.o .libs/iter_fwd.o .libs/iter_hints.o .libs/iter_priv.o .libs/iter_resptype.o .libs/iter_scrub.o .libs/iter_utils.o .libs/localzone.o .libs/mesh.o .libs/modstack.o .libs/view.o .libs/outbound_list.o .libs/alloc.o .libs/config_file.o .libs/configlexer.o .libs/configparser.o .libs/fptr_wlist.o .libs/edns.o .libs/locks.o .libs/log.o .libs/mini_event.o .libs/module.o .libs/net_help.o .libs/random.o .libs/rbtree.o .libs/regional.o .libs/rtt.o .libs/dnstree.o .libs/lookup3.o .libs/lruhash.o .libs/slabhash.o .libs/tcp_conn_limit.o .libs/timehist.o .libs/tube.o .libs/winsock_event.o .libs/autotrust.o .libs/val_anchor.o .libs/rpz.o .libs/proxy_protocol.o .libs/validator.o .libs/val_kcache.o .libs/val_kentry.o .libs/val_neg.o .libs/val_nsec3.o .libs/val_nsec.o .libs/val_secalgo.o .libs/val_sigcrypt.o .libs/val_utils.o .libs/dns64.o .libs/authzone.o .libs/respip.o .libs/netevent.o .libs/listen_dnsport.o .libs/outside_network.o .libs/ub_event.o .libs/keyraw.o .libs/sbuffer.o .libs/wire2str.o .libs/parse.o .libs/parseutil.o .libs/rrdef.o .libs/str2wire.o .libs/strlcat.o .libs/strlcpy.o  -lssl -lcrypto
lto1: fatal error: bytecode stream in file '.libs/as112.o' generated with LTO version 11.3 instead of the expected 13.0
compilation terminated.

**Comment by wcawijngaards** [comment]
It looks like the code is compiled with two different versions of gcc, and the link stage complains about the version difference. The LTO optimizations can be turned off with `./configure --disable-flto` and then that flag should be removed from the commandline.

The option `--enable-checking` could be useful for running tests, by the way, but is not really required, I think. It is the same as `--enable-debug`.

**Comment by jeffwesthead** [comment]
You're exactly right - I had built outside the container and then inside. Doing make clean resolved the issue without requiring --disable-flto. Thanks!
