### ISSUE TITLE
How to forward auth_zone's cname entry result to outside network ?

### ISSUE THREAD

**Issue by BITljn** [NLnetLabs/unbound#914]
I use unbound to be my local dns, I configured my auth_zone with a CNAME entry like this
    www.example.com IN CNAME www.baidu.com

when I query www.example.com, it just give a answer with a CNAME result, and never do recursive lookups for www.baidu.com. which is what I really need. Is there a way to implement it?  
I have only thought about implementing a merge module to instantiate a cname sub_query to achieve this. Is it possible to directly initialize an iterator mesh to implement this logic?

**Comment by gthess** [comment]
The solution is to use
```
auth-zone:
    for-downstream: no
    for-upstream: yes
```
Then the zone will only be used while resolving, instead of replying authoritatively to clients.

[I have updated the manpage](https://github.com/NLnetLabs/unbound/commit/299f55b0d1e1db5fe19ec5ffc5334fa0796daf71) to make it more clear since we often get that question.

**Comment by BITljn** [comment]
thanks, this solves my problem

**Comment by BITljn** [comment]
> The solution is to use
> 
> ```
> auth-zone:
>     for-downstream: no
>     for-upstream: yes
> ```
> 
> Then the zone will only be used while resolving, instead of replying authoritatively to clients.
> 
> [I have updated the manpage](https://github.com/NLnetLabs/unbound/commit/299f55b0d1e1db5fe19ec5ffc5334fa0796daf71) to make it more clear since we often get that question.

I have a further question on this issue, I would like to ensure that my private zone (authzone or localzone) is resolved before the msg-cache and iterator. In cases where the authzone contains only a CNAME entry, I would like it to forward this CNAME to the network without providing an authoritative response to the client. I am wondering if Unbound is capable of achieving this functionality. Could you please provide me with some guidance or advice on this matter?

**Comment by gthess** [comment]
> I have a further question on this issue, I would like to ensure that my private zone (authzone or localzone) is resolved before the msg-cache and iterator.

With `for-downstream: no` and `for-upstream: yes`, the data of the authzone is used only while resolving, not as authoritative answers to client queries. If there is an auth-zone for a domain, Unbound will use the local zone data instead of contacting any nameservers. These responses will then be cached for later use.
The main cache lookup for client queries happens before resolution and the data from the auth-zone will eventually be cached there with this configuration.

> In cases where the authzone contains only a CNAME entry, I would like it to forward this CNAME to the network without providing an authoritative response to the client. I am wondering if Unbound is capable of achieving this functionality. Could you please provide me with some guidance or advice on this matter?

I believe this is what I described in the manpage changes linked above. Is the text not clear enough?

**Comment by BITljn** [comment]
Yes it is clear enough, I understand in the manpage that how to use auth_zone (upstream=yes, downstream=no) as a local copy of auth servers, and it really solve the cname problem. My case is that I want to have my private zones which it's records is different from auth_zone's, the private zone must put ahead of the unbound msg-cache and before resolving. 

At first, I use authzone `for-downstream: yes` and `for-upstream: yes` , the authzone is like a authoritative server that never do cname resolving, so it failed. And next I config unbound by using `for-downstream: no` and `for-upstream: yes`, unbound will first lookup from cache then do lookup in the authzone and do the cname resolving as mentioned in the manpage. But this behavior can lead to cache pollution of my private records.  I need to resolve private zone in the first place (here is my authzone) and then the cache and public. At last I tried config local-zone and local-data for private zones, it is resolve before cache and public, but it can not do cname resolving.  

In the code, I found an object called local_alias in query_info. Can this be used to redirect the resolution of local data and achieve my desired functionality？

**Comment by gthess** [comment]
Have you experience such cache pollution? Unbound only knows the configured auth-zone for a specific zone. All the queries will need to get answers from your zone. So the cache will be populated with data from your auth-zone.

Maybe in your case having the following configuration would also work:
```
local-zone: www.example.com. redirect
local-data: "www.example.com. CNAME www.baidu.com."
```
This will use the local_alias you refer to by keeping the CNAME record, resolving the target and constructing an answer based on the local CNAME record + the resolution result.

**Comment by BITljn** [comment]
> Have you experience such cache pollution? Unbound only knows the configured auth-zone for a specific zone. All the queries will need to get answers from your zone. So the cache will be populated with data from your auth-zone.
> 
> Maybe in your case having the following configuration would also work:
> 
> ```
> local-zone: www.example.com. redirect
> local-data: "www.example.com. CNAME www.baidu.com."
> ```
> 
> This will use the local_alias you refer to by keeping the CNAME record, resolving the target and constructing an answer based on the local CNAME record + the resolution result.

Thanks a lot, this redirect local-zone really help me and solve my problem. 
The cache pollution is my own problem, I develop my own module instead of using authzone, so no problem with unbound anyway.
