### ISSUE TITLE
Unbound 1.17.1 prefetch warning Dietpi Bookworm

### ISSUE THREAD

**Issue by ghost** [NLnetLabs/unbound#926]
Hello unbound team.

Is this normal behaviour with Dietpi and unbound 1.17.1 ?

https://dietpi.com/forum/t/unbound-error-prefetch/17696/13

**Comment by whyisthisbroken** [comment]
You have the answer right here:
https://dietpi.com/forum/t/unbound-error-prefetch/17696/3

**Comment by gthess** [comment]
Indeed these are just warnings that certain features (in this case serve-expired and prefetch) do not work together with the subnetcache module; they do work for main cache content.

If the features are not needed you can disable them in the configuration. If the subnetcache module is not needed, it can also be disabled in the configuration.

To add to the linked thread, subnetcache is enabled by default if compiled in Unbound. To remove it you need to explicitly define a module configuration like:
```
server:
    module-config: "validator iterator"
```
