### ISSUE TITLE
RFE: is it possible to start making github releases?🤔

### ISSUE THREAD

**Issue by kloczek** [NLnetLabs/unbound#929]
Is it possible next time on release new version make the github release to have entry on https://github.com/NLnetLabs/unbound/releases? 🤔

I'm only asking because on the creation of a new GH release a notification is spread to all those whom have set in the web UI Watch->Releases.

My automation process uses those notifications by trying to make preliminary automated upgrades of building packages, which allows saving some time on maintaining packaging procedures.

More about gh releases is possible to find on
https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository
https://github.com/marketplace/actions/github-release
https://pgjones.dev/blog/trusted-plublishing-2023/
https://github.com/ESSS/pytest-regressions/commit/bcd06142
https://github.com/jbms/sphinx-immaterial/issues/281#issuecomment-1700933026

**Comment by wcawijngaards** [comment]
Here is 1.19.0, https://github.com/NLnetLabs/unbound/releases/tag/release-1.19.0 .

**Comment by kloczek** [comment]
Just noticed that my automation processed new gh release email automatically upgrading my rpm spec file with build procedure and building successfully updated package.
```console
Wrote: /home/builder/rpmbuild/SRPMS/unbound-1.19.0-2.1g2v.src.rpm
Wrote: /home/builder/rpmbuild/RPMS/unbound-devel-1.19.0-2.1g2v.x86_64.rpm
Wrote: /home/builder/rpmbuild/RPMS/python-unbound-1.19.0-2.1g2v.x86_64.rpm
Wrote: /home/builder/rpmbuild/RPMS/python-unbound-debuginfo-1.19.0-2.1g2v.x86_64.rpm
Wrote: /home/builder/rpmbuild/RPMS/unbound-libs-1.19.0-2.1g2v.x86_64.rpm
Wrote: /home/builder/rpmbuild/RPMS/unbound-1.19.0-2.1g2v.x86_64.rpm
Wrote: /home/builder/rpmbuild/RPMS/unbound-libs-debuginfo-1.19.0-2.1g2v.x86_64.rpm
Wrote: /home/builder/rpmbuild/RPMS/unbound-debugsource-1.19.0-2.1g2v.x86_64.rpm
Wrote: /home/builder/rpmbuild/RPMS/unbound-debuginfo-1.19.0-2.1g2v.x86_64.rpm
```
Thank you very much 👍 😄
