### ISSUE TITLE
stub-zone stub-tcp-upstream

### ISSUE THREAD

**Issue by chantra** [NLnetLabs/unbound#94]
Hi,

Looking at stub-zone config, it is possible to force TLS upstream with  `stub-tls-upstream`.

Would it make sense to also be able to configure `stub-tcp-upstream`?

Context, destination may block UDP (because they are battling reflection attack). They could rely on TCP to make sure the request they are getting are legitimate. Being able to force unbound to use TCP for specific stubs would help as currently, unbound seems to only fallback to TCP when receiving a response with TC set.

**Comment by chantra** [comment]
So, unbound used to fallback to TCP if UDP timed-out, but not anymore since https://github.com/NLnetLabs/unbound/commit/9b6caf5a5bb8891fd519ef66316e23543c818a78#diff-77b05250cff60f79383feccc802b15fd

**Comment by chantra** [comment]
a "working" implementation. Slightly tested.

**Comment by gthess** [comment]
This should be fixed by #519 now; closing.
