### ISSUE TITLE
1.18.0 libunbound DNS regression when built without OpenSSL

### ISSUE THREAD

**Issue by alyssais** [NLnetLabs/unbound#942]
**Describe the bug**

My Prosody XMPP server, which uses libunbound, can't do outgoing DNS since updating to 1.18.0.

**To reproduce**
1. Build libunbound with nettle
2. Run prosody

**Expected behavior**
Prosody could make DNS requests, and send outgoing messages.

**System:**
 - Unbound version: 1.18.0
 - OS: NixOS
 - `unbound -V` output: n/a; built with --with-libunbound-only

**Additional information**

Bisected to https://github.com/NLnetLabs/unbound/commit/7e6a7f310de20fe00cfcb3a40086c5a3bbbf7e0f.

From inspection, it appears that, since `connect_sslctx_create` returns null if built without OpenSSL, setup will now always fail.

**Comment by wcawijngaards** [comment]
The issue is fixed with removal of the OpenSSL specific code for the nettle build. With that unbound-host works with a nettle libunbound only build. The bisect result and inspection are very nice! Thanks for the report, the fix is committed to the code repository.
