### ISSUE TITLE
unknown keyword 'interface-tag'

### ISSUE THREAD

**Issue by bigtrumpet** [NLnetLabs/unbound#963]
**Describe the bug**
When I try to configure the interface-tag statement, as explained on the manual page,:
https://unbound.docs.nlnetlabs.nl/en/latest/topics/filtering/tags-views.html
and try to validate the configuration, I always get a syntax error like this:
root@linuxtest2:/etc/unbound# unbound-checkconf
/etc/unbound/unbound.conf:93: error: unknown keyword 'interface-tag'

**To reproduce**
1. Define on unbound.conf these parameters:
2.      define-tag: "mycategory"
     interface-tag: 10.98.98.1 "mycategory"
3. run unbound-checkconf

**Expected behavior**
I followed the example on this page https://unbound.docs.nlnetlabs.nl/en/latest/topics/filtering/tags-views.html

**System:**
 - Unbound version: 1.9.4
 - OS: Ubuntu 20.04 LTS
 - `unbound -V` output:

Version 1.9.4

Configure line: --build=x86_64-linux-gnu --prefix=/usr --includedir=${prefix}/include --mandir=${prefix}/share/man --infodir=${prefix}/share/info --sysconfdir=/etc --localstatedir=/var --disable-silent-rules --libdir=${prefix}/lib/x86_64-linux-gnu --libexecdir=${prefix}/lib/x86_64-linux-gnu --disable-maintainer-mode --disable-dependency-tracking --disable-rpath --with-pidfile=/run/unbound.pid --with-rootkey-file=/var/lib/unbound/root.key --with-libevent --with-pythonmodule --enable-subnet --enable-dnstap --enable-systemd --with-chroot-dir= --with-dnstap-socket-path=/run/dnstap.sock --libdir=/usr/lib
Linked libs: libevent 2.1.11-stable (it uses epoll), OpenSSL 1.1.1f  31 Mar 2020
Linked modules: dns64 python subnetcache respip validator iterator

**Additional information**
Please note that the following parameter passes syntax checking:
access-control-tag:

**Comment by gthess** [comment]
The `interface-*` ACL options were introduced in 1.17.0. The online documentation is always for the latest version which is currently 1.19.0. I'll see if I can convince readthedocs to show the "latest" version though.
