### ISSUE TITLE
config.h.in~ backup file in release tar balls

### ISSUE THREAD

**Issue by igalic** [NLnetLabs/unbound#964]
**Describe the bug**
The last two release tar balls contained a file `config.h.in~`, a backup file of `config.h.in`

**To reproduce**
1. download latest tar ball
2. extract
3. find `config.h.in~`

**Expected behavior**
that file should not exist.

**System:**
 - Unbound version: 1.19.0
 
**Additional information**
noticed on FreeBSD vendor import of unbound: https://github.com/freebsd/freebsd-src/commit/103ba509e72e3949d22485666949e9705d4af8cd (subsequently fixed: https://github.com/freebsd/freebsd-src/commit/5aab39b24ce7437265b94461ffdd9b12c0723658 )

**Comment by wcawijngaards** [comment]
The `config.h.in~` backup file is likely created due to the change in the distribution generation script to use autoreconf, that then runs the additional script and creates the backup file. The fix removes the file if present from release tarballs. Thanks for noticing the superfluous file!
