### ISSUE TITLE
doc: default number of outgoing ports without libevent

### ISSUE THREAD

**Issue by jsha** [NLnetLabs/unbound#974]
I was just noticing these lines in the README: https://github.com/NLnetLabs/unbound/blob/6c76b4e2f87d1bf68fd8908d0ddf3851ad92d644/doc/README#L23-L26

It seems like the statement that 16 ports cannot still be the default, so perhaps that part should be removed. It also makes me wonder: if the default (non-libevent) implementation is used with thousands of ports, how is the performance?

Edit: perhaps I misunderstand, and the number of ports mentioned is not the range of possibly selected ports, but how many ports can have be waiting on a response at any given time?

**Comment by wcawijngaards** [comment]
Yes that 16 port statement is not the default, and also the `--with-libevent=no` is not the default, today. The commit fixes the text to improve accuracy. Thanks for finding the text inaccuracy!

For the number of ports and outgoing queries, the default is increased to a couple thousand when libevent is used, and that is by default. The builtin alternative is based on select, that has a limit of 1024, and it then tries to give every thread about 1000/num_threads number of queries, minus a number of file descriptors used for other stuff, by default. This can be configured with `num-queries-per-thread` and `outgoing-range`.
