### ISSUE TITLE
Provided binaries for Windows are built with EoL OpenSSL 1.1.1

### ISSUE THREAD

**Issue by HS1542** [NLnetLabs/unbound#991]
**Describe the bug**
Provided binaries for Windows are built with OpenSSL 1.1.1 which is EoL.

**To reproduce**
1. Check versions of library files within libunbound

**Expected behavior**
Binaries built with the next LTS version of OpenSSL, 3.0

**System:**
 - Unbound version: 1.19 - binaries for Windows
 - OS: Windows x64
 - `unbound -V` output:
 ```
 C:\Program Files\Unbound>unbound.exe -V
Version 1.19.0

Configure line: --host=x86_64-w64-mingw32 --build=x86_64-redhat-linux-gnu --target=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --exec-prefix=/usr/x86_64-w64-mingw32/sys-root/mingw --bindir=/usr/x86_64-w64-mingw32/sys-root/mingw/bin --sbindir=/usr/x86_64-w64-mingw32/sys-root/mingw/sbin --sysconfdir=/usr/x86_64-w64-mingw32/sys-root/mingw/etc --datadir=/usr/x86_64-w64-mingw32/sys-root/mingw/share --includedir=/usr/x86_64-w64-mingw32/sys-root/mingw/include --libdir=/usr/x86_64-w64-mingw32/sys-root/mingw/lib --libexecdir=/usr/x86_64-w64-mingw32/sys-root/mingw/libexec --localstatedir=/usr/x86_64-w64-mingw32/sys-root/mingw/var --sharedstatedir=/usr/x86_64-w64-mingw32/sys-root/mingw/com --mandir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/man --infodir=/usr/x86_64-w64-mingw32/sys-root/mingw/share/info --enable-debug --enable-static-exe --disable-flto --disable-gost --with-ssl=/home/wouter/src/unbound/unbound-dist-mhn73E/sslinstall --with-libexpat=/home/wouter/src/unbound/unbound-dist-mhn73E/wxpinstall
Linked libs: event winsock (it uses WSAWaitForMultipleEvents), OpenSSL 1.1.1l  24 Aug 2021
Linked modules: dns64 respip validator iterator

BSD licensed, see LICENSE in source package for details.
Report bugs to unbound-bugs@nlnetlabs.nl or https://github.com/NLnetLabs/unbound/issues
```

**Additional information**
https://www.openssl.org/blog/blog/2023/09/11/eol-111/

**Comment by wcawijngaards** [comment]
The commit https://github.com/NLnetLabs/unbound/commit/c8554ff48c6fea3ec3922e73985d89bb62ce438b is there to help with compiling the latest version. It links `crypt32` when needed by OpenSSL 3.2.0.

**Comment by wcawijngaards** [comment]
The issue has had a number of commits to the code repository. That should make a compile with OpenSSL 3.2.0 possible.

For the code repository version 585d73bf7c6ebac04afdc99be378c6e60cd61378 there is a compile of the snapshot with OpenSSL 3.2.0. It can be found here, https://www.nlnetlabs.nl/~wouter/unbound-1.19.1_20240119.zip and https://www.nlnetlabs.nl/~wouter/unbound_setup_1.19.1_20240119.exe . The 32bit version is https://www.nlnetlabs.nl/~wouter/unbound-1.19.1_20240119-w32.zip and https://www.nlnetlabs.nl/~wouter/unbound_setup_1.19.1_20240119-w32.exe .

**Comment by HS1542** [comment]
Thank you !
